EdgeApp/edge-react-gui

src/lib/configureStore.js

Add display name for use in react/redux rebugger

Add ui display name to redux debugging

---

src/modules/Core/Context/callbacks.js
src/modules/Main.ui.js
src/modules/MainConnector.js

Requires corresponding core changes. Pull requests for those are still pending.

Wire up the core's `onExchangeUpdate` callback

---

src/modules/UI/components/ControlPanel/Component/Main.android.js
src/modules/UI/components/ControlPanel/Component/Main.ios.js
src/modules/UI/scenes/Login/Login.ui.js
src/reducers/CryptoExchangeReducer.js

This does allow us to logout without crashing, for the most part. It's probably not the best approach long-term, since it has a nasty "flash to white" scene in the middle of the logout.

Enable logout

---

src/modules/UI/components/Buttons/TextAndIconButton.ui.js
src/modules/UI/components/WalletListModal/components/WalletListModalHeader.ui.js
src/styles/components/ButtonStyles.js

this pull request fixed the incorrect header when selecting a wallet in the exchange scene. Also, some styling work was done in order to have the drop down button down carrot align properly.
https://app.asana.com/0/361770107085503/317312547827506

Wallet modal text fix

---

src/modules/UI/components/HelpModal/HelpModal.ui.js
src/modules/UI/components/HelpModal/style.js

The purpose of this task is to make certain that the contact info for the helpModal gets loaded correctly on Android (without causing regression bugs on iOS).
Asana Task: https://app.asana.com/0/361770107085503/459362679590644/f

Ensure proper content loading and display for helpModal

---

package-lock.json
package.json
postinstall.sh
src/modules/Main.ui.js
src/modules/UI/scenes/Settings/SettingsOverview.ui.js

Also re-enable minification which was only disabled due to incompatibilities with bcoin

Disable bitcoin plugin

---

src/modules/UI/scenes/WalletList/WalletList.ui.js
src/modules/UI/scenes/WalletList/components/WalletListRow/SortableWalletListRow.ui.js
src/modules/UI/scenes/WalletList/style.js

Can confirm that sorting **is** working on Android.
The purpose of this task is to fix walletList sorting on Android. Happy to say that we did not have to change the module that we were using!
Asana task: https://app.asana.com/0/361770107085503/459375388568093/f

Enable WalletList Sorting on Android

---

src/modules/UI/components/HelpModal/HelpModal.ui.js

The purpose of this task is to ensure the proper loading of the Help Modal and its content.
Asana Task: https://app.asana.com/0/361770107085503/459362679590644/f

Fix HelpModal Issues on Android

---

src/modules/UI/components/FlipInput/styles.js
src/modules/UI/scenes/TransactionDetails/AmountArea.ui.js
src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js
src/modules/UI/scenes/TransactionDetails/style.js
src/modules/utils.js

The purpose of this task is to fix the textInput cutoff issues in FlipInput and txDetails (scene) areas.
Asana Task: https://app.asana.com/0/361770107085503/479270660285757/f

Fix Android TextInput Cutoff Issues

---

src/modules/UI/scenes/WalletList/components/WalletListRow/FullWalletListRow.ui.js
src/modules/UI/scenes/WalletList/style.js

The purpose of this task is to make the walletList images visible and appropriate size on Android.
Asana Task: https://app.asana.com/0/361770107085503/478356537359297/f

Make walletList logos visible on Android

---

src/modules/UI/components/FlipInput/styles.js

* Descreased symbol / currency code area
* Decreased symbol / currency code size

Fix amount displayed in FlipInput

---

src/modules/Login/action.js
src/modules/UI/scenes/CreateWallet/action.js

This reverts commit 17e2c944763c98e05039980e0b0d23d4ac3df671.

Revert "Revert "Fix request spinner on new account creation""

---

src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js
src/modules/UI/scenes/TransactionDetails/style.js

The purpose of this task is to make the Payee and Subcategory search results pop-up show properly on both iOS and Android.
Asana Task: https://app.asana.com/0/361770107085503/483200335868537/f

Get Payee and Subcategory search results displaying correctly (Android)

---

src/modules/UI/scenes/CryptoExchange/CryptoExchangeConfirmTransactionModalComponent.js

See the ticket. https://app.asana.com/0/361770107085503/481501639034021 for new screen shot of how it looks now.

Fix styling on modal for ShapeShift Confirmation

---

src/connectors/scene/CryptoExchangeSceneConnector.js
src/constants/IconConstants.js
src/locales/en_US.js
src/modules/Main.ui.js
src/modules/UI/components/Icon/Icon.ui.js
src/modules/UI/components/Modal/Modal.ui.js
src/modules/UI/components/Modal/style.js
src/modules/UI/components/Slider/Slider.ui.js
src/modules/UI/scenes/CryptoExchange/CryptoExchangeConfirmTransactionModalComponent.js
src/reducers/CryptoExchangeReducer.js
src/styles/scenes/CryptoExchangeSceneStyles.js

* Add new exchange icon
* Fix typo in strings
* Add stylability to exchange confirmation modal
* Add type checking to modal styles
* Remove confirm button from exchange confirmation modal
* Add confirm slider to exchange confirmation modal

Improve styles on Exchange confirmation modal

---

package.json
src/app.js
src/modules/Core/Wallets/Tokens.js

Bump ethereum version
Set `global.OS` to plugins can check OS platform.

Disable Wings in iOS builds

---

package-lock.json
package.json
src/modules/Main.ui.js
src/modules/UI/Settings/selectors.js
src/modules/UI/scenes/Settings/SettingsOverview.ui.js

Allow creation of non-segwit BTC wallets

Re-enable BTC BCH and LTC

---

src/modules/UI/Wallets/action.js
src/modules/UI/Wallets/reducer.js

- Combine selectWalletId and selectCurrencyCode into one action
- Throttle calls to upsertWallet to max once per 3s

Optimize selectwallet and upsertWallet

---

android/app/build.gradle
android/keystores/BUCK
android/keystores/debug.keystore.properties

This reverts commit 1f6f41b892ad31d47544b92d84716811a592ca59.

Revert "Enable production keystore on android"

---

src/styles/scenes/CryptoExchangeSceneStyles.js

tweak styles for error message adjustment.

Adjust styles for error message on crypto exchange rate

---

package-lock.json
src/locales/en_US.js
src/modules/UI/components/HelpModal/HelpModal.ui.js
src/modules/UI/components/Modal/Modal.ui.js
src/modules/UI/scenes/CryptoExchange/CryptoExchangeConfirmTransactionModalComponent.js
src/modules/UI/scenes/Scan/components/AddressModal.js
src/modules/UI/scenes/Settings/components/SendLogsModal.ui.js
src/modules/UI/scenes/WalletList/WalletList.ui.js

The purpose of this commit is to allow sprintf functionality on the headerText strings. This specifically was necessary for the editTokens scene, where the text will inject the token name and currencyCode.
Asana Task: this is a small "side-task" of the editTokens task
https://app.asana.com/0/361770107085503/491385731813992/f

Adjust Modal headerText to Allow Sprintf

---

package-lock.json
package.json
src/modules/UI/scenes/Settings/SettingsOverview.ui.js
src/modules/UI/scenes/Settings/SettingsOverviewConnector.js
src/modules/UI/scenes/Settings/action.js

These changes are mostly a cleanup and changes needed for API changes to core-js-ui for enabling and disabling touchID.
This requires approval and merge of the react-gui PR below in order to not break the build
https://github.com/Airbitz/airbitz-core-js-ui/pull/13

Fix touchId enable/disable logic

---

src/locales/en_US.js
src/locales/en_US.unused.js

String was incorrectly removed from en_US.js

Fix missing Advanced button in txdetails

---

package-lock.json
src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js
src/modules/UI/scenes/TransactionList/TransactionList.ui.js

URGENT fix: This fixes the bulk of crash reports which are due to accessing phone contacts without permission.

URGENT: Fix crashes due to Contacts permission

---

src/modules/UI/scenes/Settings/SettingsOverview.ui.js

Fix error when device does not supports touchID

Harden settings

---

.travis.yml

Makes sure we run tests on every build/PR

Add `npm t` to Travis build

---

src/locales/en_US.js
src/modules/UI/components/FlipInput/CryptoExchangeFlipInputWrapperComponent.js

Change to "Select Receiving Wallet"

Change text for "Select Dest Wallet"

---

package-lock.json
src/modules/UI/scenes/AddToken/AddToken.ui.js
src/modules/UI/scenes/CreateWallet/CreateWallet.ui.js
src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js
src/modules/UI/scenes/WalletList/components/WalletNameInput.ui.js

Some of it are already autocapitalize, just check it.

Auto capitalize forms/Text input on various places

---

src/locales/en_US.js
src/modules/Core/Account/settings.js
src/modules/UI/Wallets/action.js
src/modules/UI/scenes/AddToken/AddToken.ui.js
src/modules/UI/scenes/AddToken/AddTokenConnector.js
src/modules/UI/scenes/AddToken/action.js
src/modules/UI/scenes/EditToken/EditToken.ui.js
src/modules/UI/scenes/EditToken/EditTokenConnector.js
src/modules/UI/scenes/EditToken/reducer.js
src/modules/utils.js
src/types.js

The purpose of this commit is to add flow type-checking to the Add Token actions file. Naturally, some related files needed modifications since many of the variables are shared among scenes / actions.
Asana Task: https://app.asana.com/0/361770107085503/511473289504673/f

Flow AddToken Actions & Related Files

---

android/.project
android/.settings/org.eclipse.buildship.core.prefs
android/app/.classpath
android/app/.project
android/app/.settings/org.eclipse.buildship.core.prefs
android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/co/edgesecure/wallet/MainApplication.java
android/settings.gradle
ios/edge.xcodeproj/project.pbxproj
ios/edge/AppDelegate.m
ios/edge/Info.plist
ios/edge/edge.entitlements
package-lock.json
package.json
src/app.js
src/locales/en_US.js
src/modules/Login/action.js

This gets background task working and adds the ability to do local notification for when a user has had their password 2FA reset on a different device.

added android and ios local notifications from background task for OTP.

---

package-lock.json
src/modules/Login/action.js
src/modules/UI/Wallets/action.js
src/modules/UI/scenes/CreateWallet/action.js
src/modules/UI/scenes/CreateWallet/reducer.js

* Decouple creating a wallet on account creation from creating a wallet
after login
* Move shared simple actions outside of create wallet scene

Fix account creation navigation

---

src/modules/Main.ui.js
src/modules/UI/scenes/EdgeLogin/EdgeLoginSceneComponent.js
src/styles/scenes/EdgeLoginSceneStyle.js

Fixes bug 
https://app.asana.com/0/361770107085503/525889361334395

Add gradient header to Edge Login Screen

---

src/modules/UI/scenes/Scan/Scan.ui.js

Move the permission request from render to componentDidMount to prevent
repeated permission requests

Fix camera permission on ios

---

.travis.yml

Upgrade travis to xcode 9.2, simulator 11.2

---

src/constants/ActionConstants.js
src/modules/Core/Account/action.js
src/modules/Core/Account/api.js
src/modules/Core/Account/reducer.js
src/modules/Core/Wallets/reducer.js
src/modules/Login/action.js
src/modules/UI/Settings/action.js
src/modules/UI/Settings/reducer.js
src/modules/UI/Wallets/reducer.js
src/modules/UI/scenes/WalletList/WalletListConnector.js
src/reducers/core/DeepLinkingReducer.js

• removed over 13 dispatches into one single dispatch to initialize the account

refactor login action initialization.

---

src/modules/Login/action.js
src/modules/UI/scenes/EdgeLogin/EdgeLoginSceneComponent.js

• Added space between logo and title on Edge Login Screen

Fix crash when using deep link and account is not logged in

---

src/locales/en_US.js
src/modules/UI/dimensions/reducer.js
src/modules/UI/scenes/CreateWallet/CreateWalletName.ui.js
src/modules/UI/scenes/CreateWallet/CreateWalletReview.ui.js
src/modules/UI/scenes/CreateWallet/CreateWalletSelectCrypto.ui.js
src/modules/UI/scenes/CreateWallet/CreateWalletSelectFiat.ui.js
src/modules/UI/scenes/CreateWallet/style.js
src/modules/UI/scenes/WalletList/WalletList.ui.js

The purpose of this task is to improve the user experience of the CreateWallet process in multiple ways:
- Changing the order of the scenes to SelectCrypto -> SelectFiat -> SelectName -> Review
- Pressing on a search result not takes you immediately to the next scene
- Keyboard no longer covers up the lower search results
- Keyboard "Done" button now says "Search" or "Next" (for Create Wallet Name) scene
Asana Tasks, respectively:
https://app.asana.com/0/361770107085503/498144750192711/f
https://app.asana.com/0/361770107085503/498144750192710/f
https://app.asana.com/0/361770107085503/544877831734650/f
https://app.asana.com/0/361770107085503/498144750192709/f

Improvements to CreateWallet Process

---

src/locales/en_US.js
src/modules/Main.ui.js
src/modules/UI/scenes/WalletList/components/HwBackButtonHandler/HwBackButtonHandler.android.js
src/modules/UI/scenes/WalletList/components/HwBackButtonHandler/HwBackButtonHandler.ios.js
src/modules/UI/scenes/WalletList/components/HwBackButtonHandler/index.js

Back button doesn't work on the login screen (to get back to the previous screen or possibly leave the app)  (https://app.asana.com/0/361770107085503/482586483170717/f)

Android: handleBackButton to exit app

---

src/modules/UI/components/Slider/Slider.ui.js
src/modules/UI/scenes/SendConfirmation/SendConfirmation.ui.js
src/modules/UI/scenes/SendConfirmation/SendConfirmationConnector.js
src/modules/UI/scenes/SendConfirmation/action.js
src/modules/UI/scenes/SendConfirmation/reducer.js

After doing a Slide to Confirm if no internet connection or the amount is invalid (0), reset the Slider button to the right side.

Reset the Slider button to the right side after any broadcast error

---

src/modules/UI/scenes/Settings/DefaultFiatSetting.ui.js
src/modules/UI/scenes/Settings/DefaultFiatSettingConnector.js
src/modules/UI/scenes/Settings/style.js

The purpose of this task is to re-style the default fiat settings scene to prevent keyboard covering lower search results.
Asana Task: https://app.asana.com/0/361770107085503/544877831734648/f

Re-style default fiat settings scene

---

src/modules/UI/scenes/WalletList/components/WalletListRow/SortableWalletListRow.ui.js

This commit fixes the currency symbol on SortableRow
This commit does not pass jest
Merge at your own peril

Fix symbol on sort row

---

src/modules/UI/components/FlipInput/CryptoExchangeFlipInputWrapperComponent.js

Asana task https://app.asana.com/0/361770107085503/498144750192728/f

Fix display denomination in exchange dropdown

---

src/components/modals/StaticModalComponent.js
src/styles/components/StaticModalStyle.js

This fixes https://app.asana.com/0/361770107085503/548710133686877

Fix centering of text in Static modals

---

android/app/src/main/AndroidManifest.xml

fixes asana https://app.asana.com/0/361770107085503/545777721916520

Changed title to show up as Edge instead of filter_react_native

---

src/modules/UI/scenes/CryptoExchange/CryptoExchangeSceneComponent.js

fixes https://app.asana.com/0/361770107085503/549547415517476

Remove Next button until we are able to click on it for transactions

---

src/modules/UI/scenes/WalletList/components/GetSeedModal/GetSeedModal.ui.js
src/modules/UI/scenes/WalletList/style.js

The purpose of this task is to align the actual seed text to the middle of the modal once it has been revealed.
Asana Task: https://app.asana.com/0/361770107085503/536391604706284/f

Center getSeedModal text

---

src/modules/UI/scenes/AddToken/AddToken.ui.js
src/modules/UI/scenes/EditToken/EditToken.ui.js

Some android devices are not responding to autocapitalize
this eliminates the problem
Asana task : https://app.asana.com/0/361770107085503/545202805762044

forced the input for the currency code to be uppercase

---

src/actions/CryptoExchangeActions.js
src/locales/en_US.js

* ShapeShift as payee
* From and To wallet
* Amounts and currency codes
Remove invalid return value from saveTransaction

Add metadata to ShapeShift spend transactions

---

src/constants/ActionConstants.js
src/modules/UI/Settings/reducer.js
src/modules/UI/Settings/selectors.js
src/modules/UI/scenes/Settings/SettingsOverview.ui.js
src/modules/UI/scenes/Settings/SettingsOverviewConnector.js
src/modules/UI/scenes/Settings/action.js
src/modules/UI/scenes/Settings/components/ConfirmPasswordModal.ui.js
src/modules/UI/scenes/Settings/components/ModalButtons.ui.js
src/styles/components/ConfirmPasswordModalStyle.js

• Added a spinner for when app is confirming
• removed the setTimout native pop up which was causing the lock up
fixes bug https://app.asana.com/0/361770107085503/547873109062338

Integrated error on confirm password into the ui.

---

src/modules/UI/components/WalletListModal/WalletListModal.ui.js

The purpose of this task is to adjust the height of the WalletListModal (Request, Scan, Exchange scenes) to take the iPhoneX dimensions into account.
Asana Task: https://app.asana.com/0/361770107085503/555052131752109/f

Adjust walletListModal height for iPhoneX case

---

src/modules/UI/scenes/ChangeMiningFee/components/CustomFees/CustomFeesModal.ui.js
src/modules/UI/scenes/ChangeMiningFee/components/CustomFees/CustomFeesModalConnector.js

https://app.asana.com/0/361770107085503/512549488379036

Persist custom fees

---

src/modules/UI/scenes/TransactionDetails/style.js

The purpose of this task is to slightly increase the area containing the "Save" and Advanced Transaction Details link (block explorer) so that the bottom link is accessible on small phones.
Asana Task: https://app.asana.com/0/361770107085503/548522228022858/f

Slightly increase txDetails advanced link area

---

package.json
src/locales/intl.js
src/locales/intl.test.js
yarn.lock

Asana task: https://app.asana.com/0/361770107085503/556665598069896/f

Add usage grouping separator from user locale in internationalization

---

src/modules/UI/components/HelpModal/style.js
src/modules/UI/components/MenuDropDown/MenuDropDown.ui.js

The purpose of this task is to adjust the styling for the exit button on the helpModal **on Android**.
Asana Task: https://app.asana.com/0/361770107085503/556700969374368/f

Make OS-specific styling for helpModal exit button

---

src/locales/en_US.js
src/modules/UI/components/FlipInput/CryptoExchangeFlipInputWrapperComponent.js
src/modules/UI/components/Header/Component/WalletNameHeader.ui.js
src/modules/UI/components/MenuDropDown/MenuDropDown.ui.js
src/modules/UI/scenes/CryptoExchange/CryptoExchangeSceneComponent.js
src/styles/scenes/CryptoExchangeSceneStyles.js

The purpose of this task is to make some adjustments to the styling of the Exchange scene, as per Reina's designs.
Design: https://projects.invisionapp.com/share/XABK6PH9Y#/screens/271932608_Exchange_UPDATED_COLORS
Asana Tasks:
https://app.asana.com/0/361770107085503/475629743533053/f
https://app.asana.com/0/361770107085503/475629743533054/f
https://app.asana.com/0/361770107085503/476579778474573/f

Fix some visual styling bugs for exchange scene

---

package.json
src/modules/Main.ui.js
src/modules/UI/components/Buttons/Buttons.ui.js
src/modules/UI/components/MenuDropDown/MenuDropDown.ui.js
src/modules/UI/components/Modal/Modal.ui.js
src/modules/UI/components/WalletListModal/components/WalletListModalHeader.ui.js
src/modules/UI/scenes/SendConfirmation/SendConfirmationOptions.js
src/modules/UI/scenes/SendConfirmation/styles.js
src/modules/UI/scenes/Settings/components/RowModal.ui.js
src/modules/UI/scenes/WalletList/components/WalletListRow/WalletListTokenRow.ui.js
src/modules/UI/scenes/WalletList/style.js
src/styles/components/HeaderMenuDropDownStyles.js
yarn.lock

This PR is dependent to the migration of the new dropdown menu. Please merge after merging with this PR first. https://github.com/Airbitz/edge-react-gui/pull/506
https://app.asana.com/0/281171002982981/498144750192744
- On the send confirmation screen. Keyboard will be closed when the right side menu is opened.

Send Confirmation - close keyboard when right side menu is opened.

---

src/modules/UI/scenes/SendConfirmation/SendConfirmationOptions.js

As per asana.
https://app.asana.com/0/361770107085503/567669255725073

Remove change currency button from Send Confirmation menu

---

package.json
src/app.js
src/modules/Logs/action.js
src/util/logger.js
yarn.lock

Asana task: https://app.asana.com/0/361770107085503/559464521227450/f
Fix logs rotation flow. Add size limit for log file to 1 MB.

Fix upload logs crash. Set log file size limit

---

src/modules/UI/scenes/TransactionList/action.js

Rename edge-login -> edge-core-js

Rename edge-login -> edge-core-js

---

src/app.js
src/modules/UI/components/FormattedText/FormattedText.ui.js

https://app.asana.com/0/361770107085503/582124331605345
As per Paul, the tab bar labels are the only one scaling and it is fine.

Disable font scaling on app's text.

---

src/locales/en_US.js

The purpose of this task is to modify the syntax / text on the Scan scene.
Asana Task: https://app.asana.com/0/361770107085503/524359325261542/f

Adjust wording on Scan scene

---

src/modules/Login/action.js

Put try/catch around fetchLoginMessages() as this will throw if the network is down and cause the app to hang.

Fix offline login

---

package.json

Bump Version 1.1.0

---

src/modules/UI/components/DropdownAlert/components/AlertBody.ui.js
src/modules/UI/components/DropdownAlert/components/AlertContainer.ui.js
src/modules/UI/components/DropdownAlert/components/AlertFooter.ui.js
src/modules/UI/components/DropdownAlert/components/AlertHeader.ui.js
src/modules/UI/components/Gradient/Gradient.ui.js
src/modules/UI/components/Modal/Modal.ui.js
src/modules/UI/components/SafeAreaView/SafeAreaViewDrawer.ui.js
src/modules/UI/components/Slider/Slider.ui.js
src/modules/UI/scenes/Scan/Scan.ui.js
src/modules/UI/scenes/SendConfirmation/SendConfirmation.ui.js
src/modules/UI/scenes/Settings/components/Row.ui.js
src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js
src/modules/UI/scenes/TransactionList/components/SearchBar.ui.js
src/modules/UI/scenes/WalletList/WalletList.ui.js
src/modules/UI/scenes/WalletList/components/GetSeedModal/GetSeedModal.ui.js
yarn.lock

Remove unneeded border util, update style type

Remove unused style util, update style type

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/co/edgesecure/app/MainActivity.java
android/app/src/main/res/values-sw600dp/bools.xml
android/app/src/main/res/values-xlarge/bools.xml
android/app/src/main/res/values/bools.xml

https://app.asana.com/0/361770107085503/498144750192772

Enable landscape on Android Tablets

---

src/modules/UI/components/Slider/styles.js

Asana Task: https://app.asana.com/0/361770107085503/632659147920251/f

Fix missing slider text

---

src/actions/CryptoExchangeActions.js
src/reducers/CryptoExchangeReducer.js

Fixes Asana issue 
https://app.asana.com/0/361770107085503/573069546835246

Fixed Problem where resetting destination wallet returns wrong numbers

---

src/components/FormField.js
src/components/materialWrappers/Input.js
src/modules/UI/scenes/AddToken/AddToken.ui.js
src/modules/UI/scenes/EditToken/EditToken.ui.js

The purpose of this task is to fix the duplication of entry in the token code field on Android (Galaxy S8), as well as use native `maxLength` to limit the number of characters to 5, rather than through Javascript.
Asana Task: https://app.asana.com/0/361770107085503/607959558678981/f

Fix Token Code Text Field Bugs

---

src/modules/UI/components/Gradient/Gradient.ui.js

Optimize Gradient rendering performance
* Make options constants

Optimize Gradient rendering performance

---

src/lib/configureStore.js
src/lib/errorAlert.js
src/modules/UI/Wallets/action.js
src/modules/UI/components/ContactsLoader/contactsLoaderConnector.js
src/modules/UI/scenes/AddToken/action.js
src/modules/UI/scenes/CreateWallet/action.js
src/modules/UI/scenes/Settings/action.js
src/modules/UI/scenes/WalletList/components/SplitModal/SplitWalletButtonsConnector.js

Add global redux error alert
Simple action / Thunks that throw errors/ reject, and are not caught, 
will automatically get logged, and display global error alert

Add global redux error alert

---

src/modules/Login/action.js

Add login debug logging

---

package.json

update version to 1.1.4

---

src/modules/Core/Account/settings.js
src/reducers/passwordReminder/passwordReminderReducer.js
src/reducers/passwordReminder/passwordReminderReducer.test.js
src/types.js

Fix postpone password reminder

Fix postpone password reminder

---

src/locales/en_US.js
src/modules/UI/scenes/Scan/action.js

Fix scan scene, parse blank address
Update error text

Fix scan scene, parse blank address

---

README.md

The purpose of this task is to help identify some of the details to make the Android build correctly for people initially getting the app set up on their computers.
Asana Task: https://app.asana.com/0/361770107085503/670208494113323/f

Add more details to Android configuration in readme / installation guide

---

src/locales/en_US.js
src/modules/Core/Account/api.js
src/modules/UI/scenes/Settings/SettingsOverview.ui.js
src/modules/UI/scenes/Settings/SettingsOverviewConnector.js
src/modules/UI/scenes/Settings/action.js
src/modules/UI/scenes/Settings/components/RestoreWalletsModal.ui.js

Enable users to restore archived / deleted wallets from the settings in gui
No specific task for this feature, but many user requests

Add RestoreWalletsModal

---

package.json
yarn.lock

Re-order bitcoin wallet types to put segwit up top

Update bitcoin version

---

src/modules/UI/scenes/WalletList/components/GetSeedModal/GetSeedModal.ui.js
src/modules/UI/scenes/WalletList/style.js

The purpose of this task is to remove the 'Share' button from the 'View Master Private Key' modal since it is an apparently vulnerability.
Asana Task: https://app.asana.com/0/361770107085503/711646399708942

Remove 'Share' button from View Master Private Key

---

package.json
yarn.lock

This fixes the 2fa issues we are seeing.

Upgrade to edge-login-ui-rn v0.3.3

---

src/modules/UI/components/Header/Component/BackButton.ui.js

https://app.asana.com/0/361770107085503/688456857713441

Fix Back Arrow for Android got smaller

---

package.json
yarn.lock

This upgrade switches the code to use the production servers rather than
the sandbox.

Upgrade simplex plugin to 0.0.2

---

src/modules/UI/components/ControlPanel/Component/Main.js

@wolverineks accidentally un-did the fix.

Re-fix the logout to PIN bug

---

android/app/src/main/AndroidManifest.xml

The purpose of this task is to prevent the tab bar / footer from appearing above the keyboard on the Request and Transaction Details scenes.
Asana Task: https://app.asana.com/0/361770107085503/715065187712956

Fix Android footer / tab bar issue

---

src/modules/UI/scenes/SendConfirmation/SendConfirmationConnector.js
src/modules/UI/scenes/SendConfirmation/action.js
src/modules/UI/scenes/SendConfirmation/selectors.js

https://app.asana.com/0/239353283679855/498144750192806

Fix unique identifier

---

src/locales/en_US.js

Asana Task : https://app.asana.com/0/361770107085503/705752231471098

FIx Export Transactions capitalization problem

---

src/modules/UI/components/ProgressBar/styles.js
src/modules/UI/scenes/WalletList/WalletList.ui.js

Please include a link to an asana task in the description of the pull request

Loading bar: move the loading bar up to the blue background

---

src/modules/Core/Account/settings.js
src/modules/Login/action.js
src/modules/ReduxTypes.js
src/modules/UI/Settings/action.js
src/modules/UI/Settings/reducer.js
src/modules/UI/scenes/WalletList/WalletList.ui.js
src/modules/UI/scenes/WalletList/WalletListConnector.js
src/modules/UI/scenes/WalletList/action.js

The purpose of this task is to give persistence to the 'Show Balance' setting toggle for the Wallet List (account level)
Task: https://app.asana.com/0/361770107085503/498144750192820

Implement 'Show Balance' Persistence for *Account*

---

src/lib/configureStore.js
src/lib/perfLogger.js
src/modules/ReduxTypes.js

If enabled, this will create a csv file
The filepath to this file is logged to the console
This will record the type, start time, end time, and duration of each 
action that updates redux (simple actions only, no thunks)
This can be used to create charts and graphs to inform performance 
optimization decisions

Add redux performance logging

---

src/locales/en_US.js

This updates the button on the settings screen but leaves the title bar alone on the recovery screen. 
Asana task https://app.asana.com/0/361770107085503/498144750192813

Update settings page button to be consistent for set up

---

e2e/app.test.js
e2e/config.json
e2e/createAccount/createAccount.test.js
e2e/init.js
e2e/loginLogout/passwordLogin.test.js
e2e/loginLogout/pinLogin.test.js
e2e/utils.js
package.json
src/modules/UI/scenes/Login/Login.ui.js
src/modules/UI/scenes/WalletList/WalletList.ui.js
yarn.lock

Add automated e2e testing with detox

---

src/modules/UI/scenes/Settings/settingsOverview.test.js

The purpose of this task is to fix a string capitalization issue that is causing the build to break on certain operating systems.
There is currently no Asana task for this.

settingsOverview.ui.js Filename Reference Capitalization Issue

---

src/modules/UI/components/FlipInput/FlipInput2.ui.js

Fix crash due to null `this.textInputFront`

---

src/app.js

• add delay in schedule background task until 1st background for Android
• added logging to grep to see if there is a weird pattern of going in and out of background

added logging

---

src/modules/UI/scenes/TransactionDetails/AmountArea.ui.js
src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js

The purpose of this task is to fix the issue of immediate persistency for the subcategories field in txDetails.
Asana Task: https://app.asana.com/0/361770107085503/648048568819691/f

Fix persistence issue with txDetails category

---

src/modules/UI/scenes/TransactionDetails/style.js

The purpose of this task is to make a small adjustment to the TextInput fields on the txDetails scene for Android.
Asana Task: https://app.asana.com/0/361770107085503/765472527049027/f

Fix issue with txDetail TextInput being cut off on Android devices

---

src/locales/strings/enUS.json
src/modules/Core/Account/settings.js
src/modules/UI/Settings/spendingLimits/SpendingLimitsReducer.js
src/modules/UI/Settings/spendingLimits/__snapshots__/spendingLimits.test.js.snap
src/modules/UI/Settings/spendingLimits/spendingLimits.test.js
src/modules/UI/components/PinInput/PinInput.ui.js
src/modules/UI/scenes/Scan/action.js
src/modules/UI/scenes/SendConfirmation/SendConfirmation.ui.js
src/modules/UI/scenes/SendConfirmation/SendConfirmationConnector.js
src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmation.test.js.snap
src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmationReducer.test.js.snap
src/modules/UI/scenes/SendConfirmation/action.js
src/modules/UI/scenes/SendConfirmation/reducer.js
src/modules/UI/scenes/SendConfirmation/selectors.js
src/modules/UI/scenes/SendConfirmation/sendConfirmation.test.js
src/modules/UI/scenes/SendConfirmation/sendConfirmationReducer.test.js

Update spending limits ux

---

package.json
yarn.lock

This version includes:
- LTC support
- Bug fixes when entering 0 for buy amounts
- Connectivity error handling

Bump the simplex plugin version

---

src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmationReducer.test.js.snap
src/modules/UI/scenes/SendConfirmation/reducer.js
src/modules/UI/scenes/SendConfirmation/sendConfirmationReducer.test.js

Enable displaying legacy address / metadata.name
https://app.asana.com/0/239353283679855/761868028519456

Enable displaying legacy address / metadata.name

---

src/locales/strings/enUS.json
src/modules/UI/components/Buttons/style.js
src/modules/UI/scenes/OnBoarding/OnBoardingComponent.js
src/styles/scenes/OnBoardingSceneStyles.js

The purpose of this task is to fix the onboarding regression that modified the CreateWallet button styling. Additionally, I have fixed some minor typos within the onboarding "cards".
Edit: apparently this also fixes a second Asana task as well...
Asana Task #1: https://app.asana.com/0/361770107085503/768634831505674/f
Asana Task #2: https://app.asana.com/0/361770107085503/768634831505675/f

Fix CreateWallet buttons and fix onboarding typos

---

src/locales/strings/enUS.json

• Fix Typo on Onboard Screen screen 1
- https://app.asana.com/0/361770107085503/768631552103200
• changed text for Onboard Screen 3
- https://app.asana.com/0/361770107085503/768631552103202

content adjustment for onboarding text

---

src/locales/strings/enUS.json
src/modules/UI/components/PinInput/PinInput.ui.js
src/modules/UI/scenes/SendConfirmation/SendConfirmation.ui.js
src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmation.test.js.snap
src/modules/UI/scenes/SendConfirmation/styles.js

https://app.asana.com/0/239353283679855/759658666093567

Update send confirmation styles

---

package.json
src/modules/UI/scenes/Login/Login.ui.js
src/modules/UI/scenes/Settings/action.js
yarn.lock

• fix code from breaking change in 0.4.0
ASANA: https://app.asana.com/0/361770107085503/693269684549043

Bump login-rn-ui to 0.4.0

---

src/locales/strings/enUS.json
src/modules/UI/scenes/OnBoarding/OnBoardingComponent.js
src/styles/components/OnBoardingSlideStyles.js
src/styles/scenes/OnBoardingSceneStyles.js

• tweak styles so text looks good on iPhone 5 as well.
Asana Tasks https://app.asana.com/0/361770107085503/769345771792918
https://app.asana.com/0/361770107085503/769345771792919

Onboarding make skip button solid

---

src/modules/UI/scenes/SendConfirmation/SendConfirmation.ui.js
src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmation.test.js.snap

https://app.asana.com/0/239353283679855/771092048976852

Fix item component style

---

src/modules/UI/components/Slider/styles.js
src/modules/UI/scenes/SendConfirmation/SendConfirmation.ui.js
src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmation.test.js.snap
src/modules/UI/scenes/SendConfirmation/styles.js

https://app.asana.com/0/239353283679855/772104413713246

Center slider on send conf

---

src/modules/UI/scenes/SendConfirmation/reducer.js

https://app.asana.com/0/361770107085503/772201122851952/

Fix max spend with custom fee

---

src/modules/Main.ui.js

Make it roughly sorted by marketcap and by shapeshift availability

Change sort order of currencies

---

src/components/FormField.js
src/components/materialWrappers/InputWithAutoFocus.js
src/components/materialWrappers/indexMaterial.js
src/modules/UI/scenes/Settings/SettingsOverview.ui.js
src/modules/UI/scenes/Settings/__snapshots__/settingsOverview.test.js.snap
src/modules/UI/scenes/Settings/components/SendLogsModal.ui.js

The purpose of this task is to get the keyboard to show for autoFocus modal inputs on Android.
Asana Task: https://app.asana.com/0/361770107085503/755725093339247/f

Fix Android autofocus issue for modals

---

package.json
yarn.lock

Fixes issue with sending money to litcoin and UFO

bitcoin version bump

---

src/modules/UI/components/QRCode/QRCode.test.js
src/modules/UI/components/QRCode/__snapshots__/QRCode.test.js.snap
src/modules/UI/scenes/Request/Request.test.js
src/modules/UI/scenes/Request/Request.ui.js
src/modules/UI/scenes/Request/RequestConnector.js
src/modules/UI/scenes/Request/__snapshots__/Request.test.js.snap
testSetup.js

https://app.asana.com/0/239353283679855/761868028519457

Remove save/refresh receiveAddres on share

---

.flowconfig
package.json
src/modules/UI/components/ContactsLoader/ContactsLoader.ui.js
src/modules/UI/scenes/WalletList/WalletList.ui.js
src/modules/utils.js
yarn.lock

We are still many versions behind, but this version has much more readable error messages.

Upgrade to Flow v0.66.0

---

src/locales/strings/enUS.json
src/modules/UI/scenes/Request/Request.ui.js

https://app.asana.com/0/239353283679855/762229470375455

Make share message currency code dynamic

---

src/modules/UI/components/Buttons/style.js
src/modules/UI/components/OptionButtons/OptionButtons.ui.js
src/modules/UI/scenes/Scan/components/AddressInput.js
src/modules/UI/scenes/Scan/components/AddressInputButtons.js

https://app.asana.com/0/239353283679855/781564217904941

Fix button style

---

src/modules/Main.ui.js
src/modules/UI/components/Loading/LoadingScene.test.js
src/modules/UI/components/Loading/LoadingScene.ui.js
src/modules/UI/components/Loading/__snapshots__/LoadingScene.test.js.snap
src/modules/UI/components/LoginStatus/LoginStatus.js

https://app.asana.com/0/239353283679855/776427948299396

Fix autologout crash

---

package.json
yarn.lock

This fixes Jenkins build failure on Android

Use forked react-native-camera with bumped gradle tools version

---

src/modules/UI/components/ControlPanel/style.js

The purpose of this task is to fix the cut-off text of the Exchange Rate in the Control Panel (sidebar)
Asana Task: https://app.asana.com/0/361770107085503/799828850647960/f

Fix padding of exchange rate area in Control Panel (sidebar)

---

.travis.yml
deploy-config.sample.json
deploy.js
execKeepAlive.js

* Use the workspace to build instead of the project. This makes sure all projects in the workspace get built as well
* Add execKeepAlive.js. This is a wrapper around exec() that will output "Waiting..." to the console every minute if no output is detected from the executing command. This prevents Travis from timing out after 10 minutes of inactivity

Fix ios build under Jenkins and Travis

---

src/modules/UI/Settings/selectors.js
src/modules/UI/components/PasswordRecoveryReminderModal/PasswordRecoveryReminderModalActions.js
src/modules/UI/scenes/WalletList/WalletList.ui.js
src/modules/UI/scenes/WalletList/WalletListConnector.js
src/modules/UI/scenes/WalletList/components/WiredBalanceBox/WiredBalanceBox.ui.js
src/modules/UI/scenes/WalletList/components/WiredBalanceBox/WiredBalanceBoxStyle.js
src/modules/UI/scenes/WalletList/style.js
src/modules/UI/selectors.js
src/modules/utils.js

This slightly optimizes WalletList.ui.js by separating the top Balance Box into a wired component.
* Get all state for WiredBalanceBox from selectors
* Get total fiat amount from thick selector that does the old `tallyUpTotalCrypto` routine. This needs to be optimized to not always re-calc all wallet fiat values if only one has changed
* Remove unnecessary props from WalletListConnector

Implement WiredBalanceBox

---

src/constants/SceneKeys.js
src/modules/Core/Account/settings.js
src/modules/UI/scenes/Settings/CurrencySettings.ui.js
src/modules/UI/scenes/Settings/CurrencySettings.ui.test.js
src/modules/UI/scenes/Settings/__snapshots__/CurrencySettings.ui.test.js.snap
src/modules/UI/scenes/Settings/__snapshots__/settingsOverview.test.js.snap

https://app.asana.com/0/239353283679855/778221740723901
Add BitcoinGold currency settings scene, update default denomination

Add BitcoinGold currency settings, update default denomination

---

src/modules/UI/scenes/CryptoExchange/CryptoExchangeSceneComponent.js

Fixes Asana Task
Exchange: Spinner is missing when app is communicating with Shapeshift
https://app.asana.com/0/361770107085503/787215130195216.
restored old conditional that was changed when button types were changed.

fixed crypto exchange spinner not showing up

---

src/actions/CryptoExchangeActions.js

Fixes Asana task 
Exchange: Min/max amount error isn't denominated
https://app.asana.com/0/361770107085503/778253360015982

error message denomiation matches what is in settings.

---

src/modules/Login/action.js

https://app.asana.com/0/239353283679855/813766231290014

Change login to navigte sooner

---

src/lib/errorAlert.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/components/ErrorAlert/actions.js

This pr fixes the issue of out of sync OTP error message. 
It also removes the error from the drop down and we handle it with a native modal. 
https://app.asana.com/0/361770107085503/762181283727968

Added error message alert for detailed message on OTP out of sync.

---

src/modules/UI/scenes/Otp/OtpSettingsSceneComponent.js
src/styles/components/ExpandableBoxStyle.js

The purpose of this task is to fix the cut off text for the 2FA key and to fix the "Enable" vs. "Disable" syntax on the button.
Asana Task: https://app.asana.com/0/361770107085503/815097986820637/f
Asana Task: https://app.asana.com/0/361770107085503/814581022784612/f

Fix 2FA Key Cut Off and Enable vs. Disable Button Syntax

---

package.json
yarn.lock

Fixes ipad horizontal issues
Reviewed by @swansontec

Use new edge-login-ui-rn

---

ios/edge.xcodeproj/project.pbxproj

Fixes crash when launching email app for password recovery

Add RNMail to linker

---

src/modules/Login/action.js

This is done in login-ui now. Speeds up logins

Remove OTP check from login

---

src/modules/Action.js
src/modules/ReduxTypes.js
src/modules/UI/scenes/WalletList/components/GetSeedModal/GetSeedModalConnector.js
src/modules/UI/scenes/WalletList/components/GetSeedModal/reducer.js
src/modules/UI/scenes/WalletList/components/RenameModal/WalletNameInputConnector.js
src/modules/UI/scenes/WalletList/components/RenameModal/reducer.js
src/modules/UI/scenes/WalletList/components/WalletOptions/__snapshots__/reducer.test.js.snap
src/modules/UI/scenes/WalletList/components/WalletOptions/reducer.js
src/modules/UI/scenes/WalletList/components/WalletOptions/reducer.test.js
src/modules/UI/scenes/WalletList/components/XPubModal/reducer.js
src/reducers/passwordReminder/passwordReminderReducer.js

Convert dynamic reducers/actions to static

Convert dynamic reducers to static

---

src/modules/UI/scenes/Scan/Scan.ui.js

The purpose of this task is to fix the torch capability of the camera on the Scan scene.
Asana Task: https://app.asana.com/0/361770107085503/817477239568533/f

Fix Camera Torch

---

src/modules/Action.js
src/modules/Core/Account/reducer.js
src/modules/Core/Wallets/reducer.js
src/modules/ExchangeRates/reducer.js
src/modules/UI/components/ABAlert/reducer.js
src/modules/UI/components/ControlPanel/reducer.js
src/modules/UI/components/WalletListModal/reducer.js
src/modules/UI/reducer.js
src/modules/UI/scenes/TransactionList/reducer.js
src/reducers/CryptoExchangeReducer.js

https://app.asana.com/0/239353283679855/829552574659288

Add remaining action types

---

src/modules/UI/scenes/SendConfirmation/SendConfirmationOptions.js
src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmationOptions.test.js.snap

https://app.asana.com/0/239353283679855/835460315857656

Remove change fee option when BIP70

---

src/modules/UI/scenes/ChangePinPassword/ChangePasswordComponent.ui.js

https://app.asana.com/0/239353283679855/804580670230013

Enable button tap passthrough on change  password

---

src/modules/Main.ui.js

The purpose of this task is to center the header title (name of wallet) on the Send Confirmation scene.
Asana Task: https://app.asana.com/0/361770107085503/819348312876768/f

Center SendConf header title

---

src/modules/UI/components/ControlPanel/Component/Main.js

The purpose of this task is to allow the sidebar to scroll if its height is greater than the height of the device's usable height.
Asana Task: https://app.asana.com/0/361770107085503/834464646242034/f

Allow scrolling within the sidebar / control panel

---

package.json
yarn.lock

The purpose of this task is to *actually* fix the need for text-wrapping for receive addresses within the Simplex plugin. This is to update the simplex plugin dependency with that fix.
Asana Task: https://app.asana.com/0/361770107085503/716460273877812/f

Update simplex plugin to allow receive addresss wrapping

---

android/app/build.gradle
android/app/src/main/java/co/edgesecure/app/MainApplication.java
android/settings.gradle
package.json
src/modules/UI/scenes/TransactionList/TransactionList.ui.js
src/modules/UI/scenes/TransactionList/style.js
yarn.lock

The purpose of this task it to ensure that the Transaction List stretches all of the way down to the footer **on devices with a soft menu (eg S8)**
Asana Task: https://app.asana.com/0/361770107085503/564784833522401/f

Implement fix for Android soft menu txList issue

---

src/modules/Main.ui.js
src/modules/ModalManager.js
src/modules/UI/components/Modals/InteractiveModal/InteractiveModal.ui.js
src/modules/UI/components/PasswordRecoveryReminderModal/PasswordRecoveryReminderModal.ui.js
src/modules/UI/components/PasswordReminderModal/PasswordReminderModal.ui.js
src/modules/UI/scenes/Request/components/XRPMinimumModal/XRPMinimumModal.ui.js
src/modules/UI/scenes/Scan/LegacyAddressModal/LegacyAddressModal.ui.js
src/modules/UI/scenes/Scan/PrivateKeyModal/PrimaryModal/PrimaryModal.ui.js
src/modules/UI/scenes/SendConfirmation/components/UniqueIdentifierModal/UniqueIdentifierModal.ui.js
src/modules/UI/scenes/Settings/SettingsOverview.ui.js
src/modules/UI/scenes/Settings/__snapshots__/settingsOverview.test.js.snap
src/modules/UI/scenes/Settings/components/RestoreWalletsModal.ui.js
src/modules/UI/scenes/Settings/components/SendLogsModal.ui.js
src/modules/UI/scenes/TransactionDetails/components/AdvancedDetailsModal/AdvancedTransactionDetailsModal.ui.js
src/modules/UI/scenes/WalletList/components/XPubModal/XPubModal.ui.js

* Restore Wallets Modal
https://app.asana.com/0/239353283679855/664407057252028

Add modal manager

---

src/modules/UI/components/TransactionAlert/TransactionAlert.ui.js
src/modules/UI/components/TransactionAlert/TransactionAlertConnector.js

https://app.asana.com/0/361770107085503/832663630999705

Postpone loading TransactionAlert until after login

---

src/modules/UI/scenes/CreateWallet/CreateWalletReview.ui.js

https://app.asana.com/0/239353283679855/807967234616332

Prevent multitap when creating a wallet

---

package.json
yarn.lock

upgrade edge-login-ui-rn to 0.5.1

upgrade edge-login-ui-rn to 0.5.1

---

src/lib/errorAlert.js

Without going into detail on the problem, this seems like a safe-ish solution.

Hack around infinite logout recursion

---

src/actions/EdgeLoginActions.js
src/reducers/core/EdgeLoginReducer.js

Fixes asana task https://app.asana.com/0/361770107085503/852452779944527
Edge Login: blank screen when trying to scan 2FA token

Fix edge Login Action types to be consistent.

---

src/modules/UI/scenes/Plugins/PluginView.ui.js
src/modules/UI/scenes/Plugins/style.js

The purpose of this task is to make the Simplex headers consistent with the rest of the app.
Asana Task: https://app.asana.com/0/361770107085503/808912757893087/f

Fix header styles for Simplex plugin

---

package.json
yarn.lock

Adds XRP buys to the simplex plugin.

Bump simplex plugin to include XRP

---

src/modules/UI/scenes/OnBoarding/OnBoardingComponent.test.js
src/modules/UI/scenes/OnBoarding/__snapshots__/OnBoardingComponent.test.js.snap
src/styles/scenes/OnBoardingSceneStyles.js

The purpose fo this task is to prevent the 'Skip' button text from getting cut off in the onboarding slides (top-right).
Asana Task: https://app.asana.com/0/361770107085503/867580585829917/f

Fix cut-off 'Skip' button text for onboarding

---

src/modules/Main.ui.js

The purpose of this task is to center the currency settings title on Android.
Asana Task: https://app.asana.com/0/361770107085503/868855858279049/f

Center currencySettings title for Android

---

src/modules/UI/components/PasswordReminderModal/PasswordReminderModal.ui.js

The purpose of this task is to center the text on the password reminder modal.
Asana Task: https://app.asana.com/0/361770107085503/876225155516440/f

Center password reminder modal text

---

src/modules/UI/components/MenuDropDown/__snapshots__/MenuDropDown.test.js.snap
src/modules/UI/scenes/WalletList/components/WalletListRow/WalletListRowOptions.ui.js
src/styles/components/HeaderMenuDropDownStyles.js

Asana Task: https://app.asana.com/0/361770107085503/878803181943370/f
Asana Task: https://app.asana.com/0/361770107085503/876225155516443/f

Use common width for dropdown trigger

---

src/modules/UI/scenes/ManageTokens/ManageTokens.ui.js
src/modules/UI/scenes/ManageTokens/style.js

Task: Save button is cut off in Manage Tokens scene

Fix Save Button text from being cut off

---

package.json
yarn.lock

bump core version

---

src/modules/UI/scenes/WalletList/style.js

Task: Visual - Wallet Balance REP - Last digit is cut off

Fix wallet list rows, add more space on the amount of currency.

---

src/modules/UI/components/MenuDropDown/__snapshots__/MenuDropDown.test.js.snap
src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmationOptions.test.js.snap
src/styles/components/HeaderMenuDropDownStyles.js

Wallet options modal vertical paddings

---

src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js

Transaction Details - Payee have no more gaps when contact results is being shown

---

src/modules/UI/components/Slider/styles.js

Task: Slide to confirm not centered on Exchange scene

Slider text scaling is remove

---

src/components/common/TransactionRow.js

Task: Don't allow negative confirmations in transaction list scene

Transaction List: Negative confirmations will be changed to 0

---

android/app/src/main/AndroidManifest.xml

Asana: https://app.asana.com/0/361770107085503/892150404107297

Bump minimum SDK version to Android 6.0

---

src/modules/UI/components/ExchangeQuote/ExchangeQuoteComponent.js
src/styles/scenes/CryptoExchangeQuoteSceneStyles.js

Task: Exchange - Receiving Fiat amount too touching outer box

Exchange: Make crypto amount box larger. Ellipsis on wallet name. Amount text alignment to right

---

src/components/modals/SwapKYCModal.js
src/locales/en_US.js
src/locales/strings/enUS.json

•  Base64 to properly encode header
Asana Task 
Exchange Settings - "avilable" is spelled incorrectly
https://app.asana.com/0/361770107085503/897070675791154
Asana Task 
Capitalize 'back' in ShapeShift KYC WebView
https://app.asana.com/0/361770107085503/890004623665033

FIxed Two Typo's

---

src/constants/DropDownValueConstants.js

Add all bitcoin related currencies to allowing viewing of xpub

Add currencies to xpub view list

---

package.json
yarn.lock

bump login version

---

src/modules/UI/components/Slider/styles.js

Task: Slide to confirm not centered on Exchange scene

Center text on slider

---

src/actions/ScenesActions.js
src/components/Main.ui.js
src/connectors/MainConnector.js

defense against multiple hits on open drawer

---

src/components/scenes/ExchangeSettingsScene.js

fix 
Swap - Settings -> Exchange wrong icon for Changelly
https://app.asana.com/0/361770107085503/905628674371516

fix changelly logo

---

src/actions/SendConfirmationActions.js

https://app.asana.com/0/361770107085503/895615229150883/f

Display correct fiat amount on 'max spend' transactions

---

src/app.js

* Move all enable booleans to top of file
* Make all enable booleans all caps
* Disable all ptimers by default
* Add perfTotals to get total time spent with a labeled counter

Clean up perf logging code

---

package.json
src/__tests__/__snapshots__/sendConfirmation.test.js.snap
src/components/scenes/SendConfirmationScene.js
src/styles/scenes/SendConfirmationStyle.js
yarn.lock

Asana Task: https://app.asana.com/0/361770107085503/905703241527159/f

Fix to SendConfirmation slider covered by keyboard

---

android/build.gradle

Bump Android minimum SDK requirement in build.gradle

---

src/components/scenes/RequestScene.js

Asana: iOS Share XLM Address Tries to Send Wrong File
https://app.asana.com/0/361770107085503/894149862410278
This now creates a text file that can be shared so that the share button doesnt share the actual app over airdrop and in emails etc. The problem was actually with all shares not just specifically the single currency 

fix share to have a file for airdrop

---

src/__tests__/__snapshots__/sendConfirmation.test.js.snap
src/components/scenes/SendConfirmationScene.js
src/styles/scenes/SendConfirmationStyle.js

Asana Task: https://app.asana.com/0/361770107085503/905703241527159/f

Put ActivityIndicator (Spinner) into Slider and Remove ScrollView

---

.gitignore

Add IDEWorkspaceChecks.plist to gitignore

---

src/__tests__/__snapshots__/TransactionDetails.ui.test.js.snap
src/components/common/TransactionDetailAmountArea.js
src/components/scenes/TransactionDetailsScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/locales/strings/es.json
src/locales/strings/pt.json
src/locales/strings/ru.json
src/styles/scenes/TransactionDetailsStyle.js

https://app.asana.com/0/361770107085503/838231819659006/f
- You can now tap the colored category box multiple times to switch categories (bug fix)
- When the picker shows, it now defaults to the current category
- Code handling categories has been refactored to remove the confusing "type" references

Fix issue with changing categoires on Tx detail and refactor category handling 

---

package.json
yarn.lock

bump version login-rn to 0.5.10

---

src/app.js

Use high performance timers for perf timers

---

src/util/logger.js

Catch errors when using logToServer

---

src/actions/SendConfirmationActions.js

https://app.asana.com/0/361770107085503/914615291304189/f

Route to transaction details instead of simply popping back after send

---

src/components/scenes/CryptoExchangeScene.js

Asana task: 
Exchange - Send Max results in amount error if amount isn't edited
https://app.asana.com/0/361770107085503/871189298630011

fix no amount problem with selecting exchange max

---

src/__tests__/__snapshots__/cryptoExchangeReducer.test.js.snap
src/actions/CryptoExchangeActions.js
src/reducers/CryptoExchangeReducer.js

Clean up swap stuff

---

src/actions/SendConfirmationActions.js

https://app.asana.com/0/361770107085503/921371462333868/f

Add metadata with fiat amount to transaction before routing to details

---

src/components/scenes/CryptoExchangeQuoteScene.js
src/styles/scenes/CryptoExchangeQuoteSceneStyles.js

re PR
Task: Exchange - Push text up "Confirm to complete your exchange through ShapeShift"

Exhchange quote: re style scene, remove all flex on the rows. Style logo to scale but not use percentage

---

src/app.js

Fix perf logger to work in debugger/browser

---

package.json
yarn.lock

Update react-native-share to fix build issue

---

package.json
src/__tests__/__snapshots__/settingsOverview.test.js.snap
src/components/Main.ui.js
src/constants/DropDownValueConstants.js
src/constants/SceneKeys.js
src/constants/WalletAndCurrencyConstants.js
yarn.lock

Add smartcash and groestl coins

---

src/components/common/FullWalletListRow.js
src/components/common/SortableWalletListRow.js
src/styles/scenes/WalletListStyle.js

Task: Sort wallet: looks to be excessive padding on the right hand side

Wallet List Sort: Fix sorting currency text and symbol, seperate currency logo to text

---

src/lib/configureStore.js

Disable RN debugger logging by default (via comment-out)

---

src/locales/strings.js

Enable Japanese and Portuguese translations

---

src/__tests__/__snapshots__/settingsOverview.test.js.snap
src/components/Main.ui.js
src/constants/SceneKeys.js
src/constants/WalletAndCurrencyConstants.js
src/modules/Settings/selectors.js

* Add plugins
* Add settings page
* Add currency code to plugin map
* Enable BSV wallet creation

Add eboost, smartcash, and groestlecoin

---

src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/components/ControlPanel/Component/UserList.js

Asana Task : Delete Username Popup - Add a period at the end of the text
https://app.asana.com/0/361770107085503/874227037418037

fix string punctualtion and localize

---

src/components/scenes/CreateWalletSelectCryptoScene.js
src/components/scenes/CreateWalletSelectFiatScene.js
src/styles/scenes/CreateWalletStyle.js

Fix height of crypto search results (type and fiat)

---

src/constants/WalletAndCurrencyConstants.js

Asana Task: https://app.asana.com/0/361770107085503/944587615243524/f

Remove IRR (Iranian Currency) from list of supported fiats

---

package.json
yarn.lock

bump core version to 13.5

---

package.json
yarn.lock

Bump edge-components version

---

android/app/build.gradle
android/app/src/main/java/co/edgesecure/app/MainApplication.java
android/settings.gradle
ios/edge.xcodeproj/project.pbxproj
package.json
src/components/modals/SwapKYCModal.js
src/components/scenes/PluginViewScene.js
src/components/scenes/TermsOfServiceScene.js
src/modules/UI/components/HelpModal/HelpModal.ui.js
yarn.lock

This is the new & improved WebView component. I would like to merge this into develop *after* the current release.

Switch to react-native-webview

---

package.json
yarn.lock

update login ui

---

src/components/scenes/TransactionsExportScene.js
src/util/utils.js

Asana: https://app.asana.com/0/361770107085503/850416333799172/f

Correct naming for transaction export files

---

localization/ReleaseNotes.txt

update release notes

---

src/locales/strings.js

Enable Korean, French, Vietnamese translations

---

package.json
yarn.lock

Bump to latest git version of edge-currency-accountbased

---

src/util/makeContext.js

Disable the core bridge

---

package.json
yarn.lock

Update account-based repo to fix duplicate transactions

---

src/actions/WalletActions.js
src/components/common/FullWalletListRow.js

The purpose of this task is to fix the routing that occurs while selecting a wallet.
Asana Task: https://app.asana.com/0/361770107085503/964114007506414/f
Asana Task: https://app.asana.com/0/361770107085503/963878263102209/f

Fix wallet selection routing

---

src/locales/en_US.js
src/locales/strings/enUS.json

Task: Update Buy button in empty wallets

Fix locale text on transaction list for buy crypto

---

package.json
yarn.lock

Bump Wyre version to fix typos

---

package.json
yarn.lock

Bump Wyre to put into production (not 'test')

---

src/modules/Settings/selectors.js
src/reducers/scenes/SettingsReducer.js

Attempt to fix the EOS popdown error

---

package.json
yarn.lock

updated login

---

android/app/src/main/AndroidManifest.xml

Asana: https://app.asana.com/0/361770107085503/959612867405646/f

Show 'Open with Edge' instead of currency names on Android when linking

---

src/modules/Login/action.js
src/reducers/scenes/WalletsReducer.js

ASana: https://app.asana.com/0/361770107085503/958253396923265/f

Do not autoselect wallet upon account init if there is a deep link pending

---

package.json
src/components/scenes/PluginViewScene.js
yarn.lock

The purpose of this task is to prevent the plugins crashing, and bump the Wyre version
Asana Task: https://app.asana.com/0/361770107085503/968867613128360/f
Asana Task: https://app.asana.com/0/361770107085503/967276756299680/f

Fix Plugin Crash and Bump Wyre Version

---

src/actions/ScanActions.js
src/actions/SettingsActions.js
src/actions/WalletOptionsActions.js
src/components/common/FullWalletListRow.js
src/constants/IconConstants.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/components/Icon/Icon.ui.js

The purpose of this task is to fix bugs in the modals that showed up after migrating to the ModalManager.
Asana Tasks:
https://app.asana.com/0/361770107085503/954569950638912/f
https://app.asana.com/0/361770107085503/954569950638918/f
https://app.asana.com/0/361770107085503/954569950638919/f
https://app.asana.com/0/361770107085503/954569950638924/f
https://app.asana.com/0/361770107085503/954569950638925/f

Modifications to modals

---

package.json
src/__tests__/__snapshots__/settingsOverview.test.js.snap
src/locales/strings.js
yarn.lock

Update snapshots changed due to prior PR

Update translations and add Chinese

---

src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/DeepLinkingManager.js

Asana: https://app.asana.com/0/361770107085503/958253396923267/f

Show alert when user taps a currency link for which no wallet exists

---

src/locales/en_US.js
src/locales/strings/enUS.json

Just realized we don't have sell yet(?) and I didn't expect the original PR to change the title within the sidebar.

Undo scene name change

---

src/components/scenes/PluginViewScene.js
src/modules/UI/components/ContactsLoader/ContactsLoader.ui.js

* Check for label, category, and notes in URI params or in x-source of plugin callback and add to GuiMakeSpendInfo metadata
* Add Bitrefill to contacts so icon will appear

Add metadata to plugin transactions

---

src/components/scenes/CreateWalletAccountSetupScene.js

P0 crash when selecting fiat currency. 

fix yoga bug caused by syntax. moved to separate function

---

src/components/modals/AddressModal.js
src/styles/scenes/ScaneStyle.js

Task: EOS - Send confirmation paste address isn’t full size box

Scan Scene: Fix the address modal button to full width and center text

---

src/components/scenes/TransactionListScene.js
src/modules/UI/selectors.js

Task: Add green loading bar to Tx list

Transaction List: Transaction List Loading Bar

---

package.json
yarn.lock

update bitrefill plugin

---

package.json
yarn.lock

Bump bitcoin version

---

src/styles/scenes/EdgeLoginSceneStyle.js

Fixes Asana 
Edge Login - Buttons are partially hidden
https://app.asana.com/0/361770107085503/960134838069890

fix buttons

---

package.json
yarn.lock

Asana Task: https://app.asana.com/0/361770107085503/981584994968702/f

Update package.json for wyre logo

---

package.json

bump to 1.6.1

---

.flowconfig
package.json
yarn.lock

Remove detox to fix Xcode 10 builds

---

localization/PlayStoreDescription.txt

edited line 9 added Digibyte, Bitcoin SV, and EOS

---

localization/ReleaseNotes.txt

update release notes to include 1.6.1

---

src/components/Main.ui.js
src/components/scenes/PluginViewScene.js
src/constants/SceneKeys.js

Fix Asana 
BItRefill fix the headers so that send crypto instead of Buy Crypto 
https://app.asana.com/0/361770107085503/1000787519105653

fix title on Send crypto

---

localization/AppStoreDescription.txt

update bsv,digibyte,eos description (no qtum)

---

src/components/scenes/CreateWalletAccountSelectScene.js
src/components/scenes/CryptoExchangeScene.js
src/connectors/scenes/CryptoExchangeSceneConnector.js
src/modules/UI/components/WalletListModal/WalletListModal.ui.js

The purpose of this task is to remove unactivated EOS wallets from the wallet list dropdown modal on the crypto exchange scene.
Asana Task: https://app.asana.com/0/361770107085503/983013711838589/f

Remove Unactivated EOS Wallets from Crypto Exchange Scene

---

src/components/scenes/PluginViewScene.js
src/styles/scenes/PluginsStyle.js

Asana Task\: https://app.asana.com/0/361770107085503/984184285131991/f

Enlarge plugin rows

---

src/actions/TransactionDetailsActions.js
src/components/scenes/TransactionDetailsScene.js
src/connectors/scenes/TransactionDetailsConnector.js

Asana: https://app.asana.com/0/361770107085503/935904815490143/f

Update transactions when metadata is updated to refresh list

---

package.json
src/components/core/EdgeCoreManager.js
src/constants/WalletAndCurrencyConstants.js
src/modules/Core/Account/settings.js
src/reducers/scenes/SettingsReducer.js
yarn.lock

The purpose of this task is to add HERC to the list of default ERC20 tokens.
Asana Task: https://app.asana.com/0/361770107085503/1107263192978693/f

Add HERC as one of the default ERC20 tokens

---

src/connectors/scenes/TransactionListConnector.js

Fix issue with incorrect EOS denomination on wallet causing crash (couldn't find multiplier).
Asana Task: https://app.asana.com/0/361770107085503/1108083253570319/f

Fix broken EOS wallet issue (denominations-related

---

src/components/scenes/CreateWalletAccountSelectScene.js
src/components/scenes/CreateWalletAccountSetupScene.js
src/styles/scenes/CreateWalletStyle.js

The purpose of this task is to fix the bottom cutoff that is occurring on the EOS select-wallet scene on small Android screens. While I was at it, I also made the EOS account handle / username scrollable so that it would be easier to find the "Next" button.
Asana Task: https://app.asana.com/0/361770107085503/996564257689999/f

Fix EOS Wallet Select Scene Bottom Cutoff and Other UI Fixes

---

src/actions/EdgeLoginActions.js
src/locales/en_US.js
src/locales/strings/enUS.json

Add modal after successful Edge Login

---

src/actions/CryptoExchangeActions.js
src/locales/en_US.js
src/locales/strings/enUS.json

Add payinAddress and uniqueIdentifier. Requires updated edge-core-js to fully work

Add more metadata to swap notes

---

src/components/scenes/WalletListScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/styles/components/AddWalletStyle.js
src/styles/components/BuyCryptoStyle.js

The purpose of this task is to implement an "Add Wallet" button to the bottom of the Wallet List.
Asana Task: https://app.asana.com/0/361770107085503/1109601070247926/f

Provisional completion of AddWallet button on WalletList

---

src/components/modals/CryptoExchangeWalletSelectorModal.js
src/components/scenes/CryptoExchangeScene.js

Fixes Asana Wallet selector header name wrong
https://app.asana.com/0/361770107085503/838232040088937

fix modal header

---

src/actions/TransactionListActions.js
src/types.js

The purpose of this task is to fix the issue of missing transactions on the transaction list.
Asana Task: https://app.asana.com/0/361770107085503/1110186891351600/f

Fix Transactions List missing transactions

---

src/__tests__/__snapshots__/sendConfirmation.test.js.snap
src/actions/SendConfirmationActions.js
src/components/scenes/SendConfirmationScene.js
src/connectors/scenes/SendConfirmationConnector.js

Asana XMR sends an incorrect amount if the amounts are modified multiple times and sent quickly
https://app.asana.com/0/361770107085503/1111016622465599

fix monero race condition bug

---

package.json
src/components/core/EdgeCoreManager.js
src/components/scenes/CreateWalletAccountSelectScene.js
yarn.lock

The purpose of this task is to fix the `invalidParams` error and CORS-related issues for the EOS activation process
Asana Task: https://app.asana.com/0/361770107085503/1109177147841615/f
Asana Task: https://app.asana.com/0/361770107085503/1109183476243106/f

Fix "Invalid Params" Issue During EOS Activation (of Inactive Wallet)

---

package.json

update version 1.7.0

---

src/__tests__/__snapshots__/settingsOverview.test.js.snap
src/components/scenes/PluginViewScene.js
src/components/scenes/SettingsOverviewScene.js
src/connectors/scenes/SettingsOverviewConnector.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/Action.js
src/modules/UI/scenes/Plugins/plugins.js
src/reducers/scenes/SettingsReducer.js

This turns on a developer mode. Button toggles on and off in Settings. If button is on, then custom plugins are enabled. 

wired up developer button

---

src/components/scenes/ManageTokensScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/styles/scenes/ManageTokensStyle.js

* Sort token list with preferred tokens at top. Since we have dozens of tokens now, sorting is key
* Swap the Add and Save buttons at bottom and rename "Add" to "Add Custom"

Manage Token fixes

---

src/components/scenes/CreateWalletSelectCryptoScene.js

Rough sort by user demand and market cap. Order was random prior after changes to enable core bridge

Sort create wallet list

---

src/components/common/CryptoExchangeWalletListRow.js
src/components/modals/CryptoExchangeWalletSelectorModal.js
src/components/scenes/CryptoExchangeScene.js

Fixes Asana URGENT: Cannot select ETH and token for exchange
https://app.asana.com/0/361770107085503/1111190578194900

fix issue of ETH subtokens when ETH is selected

---

README.md

Update readme with latest build instructions

---

src/modules/UI/scenes/Plugins/plugins.js

Asana: Bug where developer mode has more than one custom plugin. 
https://app.asana.com/0/361770107085503/1111830329206097

fix duplicate custom list for plugins

---

src/modules/Core/Account/settings.js

included USDT and DAI as well as new list for 1.7

added new erc20 tokens

---

ios/edge.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings

Enforce build system type to Original

---

package.json
yarn.lock

update edge login rn

---

src/modules/UI/components/FlipInput/FlipInput2.ui.js

* Check if ref to TextInput components is null before using
* Fix inline function props to be static for performance

Protect use of textInput ref

---

package.json
yarn.lock

update to v.0.1.5

---

src/__tests__/__snapshots__/TransactionRow.test.js.snap
src/components/common/TransactionRow.js
src/locales/en_US.js
src/locales/strings/enUS.json

Show droppedTxs in tx list with different color and status text

---

package.json

bump version 1.7.2

---

package.json
src/__tests__/account.test.js
src/components/core/EdgeCoreManager.js
src/constants/WalletAndCurrencyConstants.js
src/fake-user.js
src/modules/Login/action.js
yarn.lock

The purpose of this task is to repair any invalid currency denominations in the user's settings area.
Asana Task: https://app.asana.com/0/361770107085503/1113481040564768/f

Fix invalid synced setting denomination during account initialization

---

src/components/scenes/PluginViewLegacyScene.js

This pr fixes a bugsnag crash in PluginViewLegacy.
Asana: Crash: PluginView IfLoggedIn
https://app.asana.com/0/361770107085503/1113481040564770

defend against ifLogin crash in PluginViewLegacy

---

ios/edge.xcodeproj/project.pbxproj
src/__tests__/__snapshots__/Request.test.js.snap
src/__tests__/__snapshots__/sendConfirmation.test.js.snap
src/components/common/AddressTextWithBlockExplorerModal.js
src/components/scenes/RequestScene.js
src/components/scenes/SendConfirmationScene.js
src/connectors/scenes/RequestConnector.js
src/connectors/scenes/SendConfirmationConnector.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/components/RequestStatus/RequestStatus.ui.js

Task: Tap address to launch blockexplorer

Added a address explorer modal that will be shown when the address of request screen and send confirmation screen is clicked

---

src/constants/WalletAndCurrencyConstants.js

[Do Not Merge] Disable Ethereum import

---

src/util/utils.js

The purpose of this task is to prevent crashes when a currency (Stellar) has a malformed denomination setting.

Prevent crash when denomination structure is incorrect

---

src/constants/WalletAndCurrencyConstants.js

Re-enable Ethereum wallet import

---

package.json
yarn.lock

update Simplex to have buy and sell

---

src/styles/scenes/SendConfirmationStyle.js

Fix regression
Asana Task: https://app.asana.com/0/361770107085503/1117403288099580/f

Fix fee warning style regression

---

src/actions/ScanActions.js
src/components/scenes/RequestScene.js
src/modules/Core/Wallets/api.js

Asana Task: https://app.asana.com/0/361770107085503/1118536468069439/f

[Do Not Merge] Fix parseUri and encodeUri Issue for Tokens

---

src/components/core/EdgeCoreManager.js

Include Nomics API for exchange rates

---

ios/Podfile
ios/Podfile.lock

Asana Task: https://app.asana.com/0/361770107085503/1119662553042397/f

Fix Share Button (Request Scene)

---

src/actions/ScanActions.js

Fix multiplier flow error

---

package.json
yarn.lock

This pr updates the Simplex plugin for the beta release and is also ready for production with sell

upgraded simplex sell final plugin

---

package.json
yarn.lock

restore simplex to pre-sell integration

---

src/actions/SendConfirmationActions.js

Asana Task: https://app.asana.com/0/361770107085503/1120749480292295/f

Allow editing of customFee after high fee warning cancel

---

src/styles/scenes/WalletListStyle.js

Keep uniform WalletListRow height

---

src/components/scenes/CreateWalletNameScene.js

Change width of wallet name input

---

.travis.yml
src/components/Main.ui.js
src/components/scenes/PluginViewYAOBScene.js

TASK: https://app.asana.com/0/361770107085503/1121496030581487
Best way to test
1. open up gui
2. settings -> enable developer mode
3. custom url for buy https://libertyx.com/a/
4. search zip code 
5. click on a result. 
6. click back -> should go back to search result page
before it kicked you out of the plugin. 

fix hard back button on android

---

copy-plugin.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/scenes/Plugins/plugins.js
src/types.js

added libertyX and Bitaccess

---

package.json
yarn.lock

update simplex version for beta

---

package.json
src/components/Main.ui.js
src/modules/UI/components/ControlPanel/ControlPanel.ui.js
src/modules/UI/components/ControlPanel/style.js
src/theme/variables/airbitz.js
testSetup.js
yarn.lock

The purpose of this task is to update the react-native-router-flux package to the latest in preparation for React Native 59
Asana Task: https://app.asana.com/0/361770107085503/1115589855006934/f

Implement RNRF version 4.0.6 in preparation for RN59

---

package.json
src/__tests__/__snapshots__/Request.test.js.snap
src/components/scenes/RequestScene.js
src/modules/UI/components/QRCode/QRCode.ui.js
src/modules/UI/components/QRCode/__snapshots__/QRCode.test.js.snap
yarn.lock

The purpose of this task is to prepare the repo for RN59 by upgrading the QR code library to one that will work correctly with RN59
Asana Task: https://app.asana.com/0/361770107085503/1115589855006934/f

Upgrade QRCode generator in preparation for RN59

---

android/app/src/main/AndroidManifest.xml
copy-plugin.js
src/components/scenes/PluginViewListScene.js
src/components/scenes/PluginViewYAOBScene.js
src/modules/UI/scenes/Plugins/plugins.js
src/types.js

Solves Asana task LibertyX needs location permission
https://app.asana.com/0/361770107085503/1122302122275018

fix libertyx location permissions

---

package.json
src/components/modals/CryptoExchangeWalletSelectorModal.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/scenes/Plugins/bridgeApi.js
yarn.lock

For wallets that do not exist. 
If there is a random currency code or a wallet does not exist for a legit code this displays the error so there will be no confusion. as to what was requested by partners. 

adjusted for case sensitivity and created error messaging 

---

package.json
src/components/core/EdgeCoreManager.js
yarn.lock

Upgrade Bitcoin to include Dogecoin

Enable Dogecoin

---

package.json
src/components/scenes/LoginScene.js
yarn.lock

Bump login-ui and add small style change

---

src/styles/scenes/SettingsStyle.js

Task: Redmi 4x the text is cut off (too wide)

Fix the rows text and width to accomodate long text

---

src/components/common/CurrencySettingsTitle.js

Asana Task: https://app.asana.com/0/361770107085503/1124047294904727/f

Fix Image resizeMode 'contain' issue

---

src/components/scenes/PluginViewLegacyScene.js

Fix the legacy plugin bridge

---

package.json
yarn.lock

simplex buy only

---

src/constants/DropDownValueConstants.js

Add DOGE xpub option

---

src/components/scenes/PluginViewScene.js

two different user-agents

---

ios/Podfile
ios/Podfile.lock
package.json
src/modules/UI/scenes/Plugins/EdgeProvider.js
yarn.lock

Add react-native-safari-view

---

copy-plugin.js

We received new moonpay address for launching them live. 

change moonpay address for live

---

src/components/common/RowSwitch.js
src/components/common/RowWithButton.js
src/styles/scenes/SettingsStyle.js

Task: 
Reduce row height
Redmi 4x the text is cut off (too wide)

Fix the Exchange Settings Screen

---

src/actions/CryptoExchangeActions.js
src/locales/en_US.js
src/locales/strings/enUS.json

Asana Task : https://app.asana.com/0/361770107085503/1124421080624366

add estimate to notes

---

src/modules/UI/components/ControlPanel/Component/Main.js

Asana Task: https://app.asana.com/0/361770107085503/1124610822916578/f

Fix sidebar wallet routing issue (RNRF-related)

---

package.json
src/components/core/EdgeCoreManager.js
src/components/scenes/CreateWalletSelectCryptoScene.js
src/constants/WalletAndCurrencyConstants.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/Core/Account/settings.js
yarn.lock

Asana Task: https://app.asana.com/0/361770107085503/1125056507097546

Integration of Ravencoin

---

package.json
yarn.lock

bump version of exchange plugins

---

src/constants/DropDownValueConstants.js

Add RVN xpub option

---

package.json
yarn.lock

bump edge-exchange-plugins v0.6.5

---

copy-plugin.js
src/locales/en_US.js
src/locales/strings/enUS.json

Asana Task: https://app.asana.com/0/361770107085503/1126627318452266

remove libertyX and moonpay temporarily.

---

src/components/scenes/PluginViewScene.js

Fix the plugin back-button logic

---

src/components/modals/CountrySelectionModal.js
src/locales/en_US.js
src/locales/strings/enUS.json

Asana Tasks:
https://app.asana.com/0/361770107085503/1127227629661657/f
https://app.asana.com/0/361770107085503/1127227629661658/f

Adjust country selection prompt syntax and remove initial input text

---

src/components/scenes/EditTokenScene.js
src/styles/scenes/EditTokenStyle.js

Apply `SceneWrapper` to the token editor

---

src/modules/Login/action.js

Asana Task: https://app.asana.com/0/361770107085503/1127362746156126/f

Enable tokens upon account init

---

src/constants/CountryConstants.js

added safello

---

copy-plugin.js
src/constants/CountryConstants.js

Asana: https://app.asana.com/0/search/1128003279707767/1125609581920563

add safello

---

src/actions/WalletActions.js

Asana Task: https://app.asana.com/0/361770107085503/1128015382357110/f

Fix missing wallet disklet error

---

package.json
yarn.lock

updated simplex for review

---

src/actions/CreateWalletActions.js
src/components/modals/CryptoExchangeWalletSelectorModal.js
src/components/scenes/CryptoExchangeScene.js
src/connectors/scenes/CryptoExchangeSceneConnector.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/scenes/Plugins/EdgeProvider.js
src/styles/components/CryptoExchangeWalletSelectorModalStyles.js

Fixes Asana tasks 
Plugins Wallet Selector - Add ability that when user taps outside the window, the window will close.
https://app.asana.com/0/361770107085503/1128216423913281
MoonPay - Choose Your Wallet Screen - Tokens that are not supported by MoonPay will still appear in the list to choose from
https://app.asana.com/0/361770107085503/1128104739220755
MoonPay - Choose Your Wallet screen - Remove the list of coins shown ADA,BAT,BNB,NEO etc.
https://app.asana.com/0/361770107085503/1128104739220756

fix modal for edge provider

---

package.json
yarn.lock

bump simplex

---

src/components/modals/CryptoExchangeWalletSelectorModal.js

Fixes Asana 
MoonPay - Create wallet failed
https://app.asana.com/0/361770107085503/1128836647572769

fix incorrect error modal

---

src/locales/en_US.js
src/locales/strings/enUS.json

Update top syntax on Scan scene

---

src/components/common/WiredBalanceBox.js
src/components/scenes/WalletListScene.js
src/connectors/scenes/WalletListConnector.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/styles/components/WiredBalanceBoxStyle.js

Asana Task: https://app.asana.com/0/361770107085503/1129102831376324/f

Implement 'Exchange Rates Loading...' syntax in wireBalanceBox

---

package.json
yarn.lock

bump simplex fix for minimum purchase

---

package.json
src/constants/PluginKeys.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/scenes/Plugins/EdgeProvider.js
yarn.lock

revert simplex to buy only

---

src/modules/Login/action.js

Asana Task: https://app.asana.com/0/361770107085503/1128407158471926/f

Fix new account wallet creation Firebase event

---

src/components/common/WiredBalanceBox.js

Asana Task: https://app.asana.com/0/361770107085503/1129765564868130/f

Fix bug to handle 'null' exchange rates gracefully

---

src/components/scenes/PluginViewScene.js
src/lib/bridge/bridge.js

Guard against `injectedJavaScript` running twice

---

src/components/scenes/PluginViewLegacyScene.js

fix whitelist in legacyPlugin

---

package.json
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/scenes/Plugins/plugins.js
yarn.lock

update simplex and buy/sell text

---

src/__tests__/__snapshots__/settingsOverview.test.js.snap
src/components/core/EdgeCoreManager.js
src/components/scenes/CreateWalletSelectCryptoScene.js
src/constants/SceneKeys.js
src/constants/WalletAndCurrencyConstants.js
src/modules/Core/Account/settings.js
src/reducers/scenes/SettingsReducer.js

Re-Enable Ravencoin

---

android/app/build.gradle
ios/Podfile.lock
package.json
yarn.lock

Re-enable 64-bit support

---

src/constants/CountryConstants.js

Updated Moonpay

---

src/actions/CryptoExchangeActions.js

Related to: https://app.asana.com/0/361770107085503/1130331036367390/f

Enforce Totle same wallet as destination of swap

---

package.json
src/actions/CryptoExchangeActions.js
yarn.lock

Move Totle error to exchange plugin (and update)

---

src/modules/UI/scenes/Plugins/plugins.js

fixes Asana LibertyX - add debit card to description
https://app.asana.com/0/361770107085503/1130714915272995

modify text for Liberty X description

---

package.json
yarn.lock

update simplex plugin

---

src/constants/CountryConstants.js

Moonpay - add MX, RU, and ZA

---

src/modules/DeepLinkingManager.js

fixDeepLink

---

src/components/Main.ui.js
src/constants/SceneKeys.js
src/modules/DeepLinkingManager.js

added new stack for deeplink

---

localization/ReleaseNotes.txt

update release notes 1.8.5
* Wyre Sell - Sell crypo with your bank account
* New and improved visuals at login screen
* Prevent FaceID from automatically lauching on login

update release notes 1.8.5

---

src/__tests__/__snapshots__/settingsOverview.test.js.snap
src/components/core/EdgeCoreManager.js
src/constants/SceneKeys.js
src/constants/WalletAndCurrencyConstants.js

Enable eboost (once more)

---

ios/Podfile.lock
package.json
src/components/scenes/ScanScene.js
src/styles/scenes/ScaneStyle.js
yarn.lock

Fix the camera layout issues on old androids

---

package.json
yarn.lock

update simplex fix margin on button

---

package.json
yarn.lock

update remove hardcoded approve

---

package.json

bump to 1.8.5
Wyre Sell
eBoost
New PIN/Fingerprint Login UI

bump to 1.8.5

---

src/modules/UI/components/ContactsLoader/ContactsLoader.ui.js

added simplex and wyre to contact thumnails

---

package.json
yarn.lock

update wyre for meta and text

---

src/__tests__/__snapshots__/ChangeMiningFee.test.js.snap
src/styles/scenes/ChangeMiningFeeStyle.js

This will fail Travis because develop has Flow errors.

Fix mining fee scene layout

---

package.json
yarn.lock

update style tweaks and meta data

---

package.json
yarn.lock

update wyre plugin

---

package.json
src/constants/WalletAndCurrencyConstants.js
yarn.lock

Implement XLM XRP privKey import (and upgrade accountbased)

---

env.example.json
package.json
src/components/core/EdgeCoreManager.js
yarn.lock

This passes an API key with every request to the MyMonero server.

Update the Monero plugin

---

localization/ReleaseNotes.txt

update release notes 1.8.7
v1.8.7
* Safello - European exchange to buy or sell crypto with your credit card!
* FoxExchange and Godex, 2 new exchange partners that allow you to convert your coins into other coins!
* Import XRP and XLM private keys
* WebSockets- Improved connectivity and syncing even when using VPN

update release notes 1.8.7

---

localization/ReleaseNotes.txt
src/modules/UI/scenes/Plugins/plugins.js

Removes Safello from the release 

remove safello

---

package.json
src/modules/UI/components/ContactsLoader/ContactsLoader.ui.js
yarn.lock

Do Not Approve until uploading logo. 

added fox logo

---

package.json
yarn.lock

wyre auto focus fix

---

package.json
yarn.lock

fix highlight and kerning per iOS

---

src/components/modals/AdvancedTransactionDetailsModal.js
src/styles/scenes/TransactionDetailsStyle.js

Conditionally Show TxDetails Raw Hex Data

---

src/modules/UI/scenes/Plugins/plugins.js

Enable sorting via CountryConstants 'priority' property

---

package.json
yarn.lock

update simplex focus issue

---

package.json
yarn.lock

update wyre sell page for formatting

---

package.json
yarn.lock

update wyre default address for sign up

---

src/components/scenes/PluginViewListScene.js
src/styles/scenes/PluginsStyle.js

Fix pluginList text overflow

---

package.json
yarn.lock

update wyre for default detection fix

---

localization/ReleaseNotes.txt

update potential release notes for translations:
v1.9.0
* Improved stability when coming in and out of background
* Integrate Safello for buying and selling in Europe
* Integrate Bits of Gold for selling to Israeli and European bank account
* Integrate CoinSwitch as an exchange provider

update 1.9.0 release notes.txt

---

src/components/services/EdgeCoreManager.js

Implement background mode

---

src/components/services/ContactsLoader.js
src/constants/CountryConstants.js
src/modules/UI/scenes/Plugins/plugins.js

Also using some changes from #1546, thanks to @ahujsak.

Implement Bits of Gold

---

src/modules/UI/scenes/Plugins/plugins.js

add Bits of Gold

---

package.json
yarn.lock

update wire sell scene to fix autofocus

---

src/modules/UI/scenes/Plugins/plugins.js

change safello description text

---

package.json
yarn.lock

re-introduce button on sell page for wyre

---

package.json
yarn.lock

https://www.screencast.com/t/5Fs0Lc3bHMas
https://www.screencast.com/t/K13lSFnvA

remove auto focus from android

---

package.json
yarn.lock

fix origin error handling wyre

---

src/components/scenes/PluginViewListScene.js

Fix the buy/sell modal clashing

---

package.json
src/components/scenes/ManageTokensScene.js
src/modules/Core/Account/settings.js
src/reducers/scenes/SettingsReducer.js
src/util/corePlugins.js
yarn.lock

Add AGLD token info

---

src/util/corePlugins.js

Enable Xagau (AGLD + HERC) exchange rates

---

src/constants/WalletAndCurrencyConstants.js

Remove ability to adjust XTZ fees (for now)

---

src/components/scenes/LoginScene.js

Display Edge Version # on main login screen suggestion

---

src/components/scenes/OtpSettingsScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/styles/scenes/OtpSettingsScreenStyles.js

Make 2fa auth code clickable and add modal confirmation

---

package.json
src/components/scenes/PluginViewListScene.js
src/modules/UI/scenes/Plugins/plugins.js
yarn.lock

add camera permissions for wyre

---

src/modules/UI/scenes/Plugins/plugins.js

Fix Banxa info syntax

---

package.json
src/constants/DropDownValueConstants.js
src/constants/WalletAndCurrencyConstants.js
src/modules/Core/Account/settings.js
src/modules/Login/action.js
src/modules/UI/selectors.js
src/util/utils.js
yarn.lock

WIP remove extra (old) BNB denomination for ERC-20 version
Provisional completion of wallet denom precedence over token
Overwrite missing denomination for currencies with a plugin
Prioritize parent currencies over tokens for getCurrencyInfo

Enable BNB

---

src/constants/DropDownValueConstants.js

Remove BNB from xPub currencies

---

package.json

update version 1.9.3

---

src/actions/EdgeLoginActions.js

Fix QR code and other url protocol links

---

package.json

update version 1.9.4

---

src/locales/en_US.js
src/locales/strings/enUS.json
src/locales/strings/es.json
src/util/corePlugins.js

More RSK adjustments

---

src/components/services/ContactsLoader.js

Add Totle as a contact for swap transactions

---

src/constants/WalletAndCurrencyConstants.js
src/locales/en_US.js
src/locales/strings.js
src/locales/strings/enUS.json

Use Flow to catch string typos

---

src/constants/WalletAndCurrencyConstants.js

Fix RBTC currency information

---

src/modules/Core/Account/settings.js

Make Chainlink non-editable

---

src/__tests__/__snapshots__/settingsOverview.test.js.snap
src/constants/SceneKeys.js

Remove currency settings for XTZ, EOS, RBTC

---

src/constants/WalletAndCurrencyConstants.js

Allow import of Tezos mnemonic

---

package.json

update version to 1.9.6

---

src/constants/plugins/buyPluginFilter.js
src/constants/plugins/sellPluginFilter.js

This reverts commit f4f284351e6a2920ac98c03bd40b424fe35ae731.

Fix Bity Buy + Sell Presence and Country Codes

---

src/components/scenes/PluginViewListScene.js
src/constants/plugins/buyPlugins.json

Add paymentTypeLogoKey for apple and swish

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

Remove excess `try` statements in `EdgeProvider`

---

src/modules/Core/Account/settings.js

Change default denomination to BTC (B)

---

src/__tests__/__snapshots__/settingsOverview.test.js.snap
src/constants/DropDownValueConstants.js
src/constants/SceneKeys.js
src/constants/WalletAndCurrencyConstants.js

Add XPub Option to TBTC and Add TBTC Settings Scene

---

src/constants/plugins/buySellPlugins.js

Change Bits of Gold URL

---

src/actions/CreateWalletActions.js
src/components/scenes/CreateWalletChoiceScene.js
src/components/scenes/CreateWalletImportScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/styles/scenes/CreateWalletStyle.js

Validate Imported Private Key on Input Scene

---

src/components/scenes/CryptoExchangeQuoteScene.js
src/components/scenes/CryptoExchangeScene.js
src/modules/UI/components/FlipInput/CryptoExchangeFlipInputWrapperComponent.js
src/modules/UI/components/FlipInput/ExchangedFlipInput2.js
src/modules/UI/components/FlipInput/FlipInput2.ui.js
src/styles/scenes/CryptoExchangeQuoteSceneStyles.js
src/styles/scenes/CryptoExchangeSceneStyles.js

Crypto Exchange Scene UX

---

src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/components/ControlPanel/ControlPanel.ui.js
src/modules/UI/components/ControlPanel/ControlPanelConnector.js
src/modules/UI/components/ControlPanel/style.js

Implement 'Exchange Rate Loading' on sidebar

---

package.json
postinstall.sh
prepare-assets.sh
yarn.lock

Unify asset preparation under the `prepare` script

---

src/components/scenes/ExchangeSettingsScene.js

Make Exchange Settings scene scrollable

---

src/components/scenes/PluginViewScene.js

Report corrupted YAOB messages to bugsnag

---

src/__tests__/__snapshots__/settingsOverview.test.js.snap
src/components/scenes/SettingsOverviewScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

Task: https://app.asana.com/0/361770107085503/1135306975343600 (Send Logs button inside Settings (have its own button like Airbitz easier to find) / Revamp of Settings)

Swap send log button and enable developer button

---

package.json

bump version 1.10.0

---

env.example.json
package.json
yarn.lock

Bump exchange plugins for WBTC and Totle apiKey

---

src/constants/plugins/buySellPlugins.js

Add a camera permission to the Banxa plugin

---

CHANGELOG.md

update changelog 1.10.0

---

src/components/scenes/CryptoExchangeQuoteScene.js

Add Fox & CoinSwitch KYC modals

---

src/components/scenes/PluginViewScene.js
src/types/types.js

Include addOnUrl with plugin URI

---

android/app/build.gradle
android/app/src/main/java/co/edgesecure/app/MainApplication.java
android/settings.gradle
ios/Podfile
ios/Podfile.lock
package.json
src/components/common/FullWalletListRow.js
src/styles/scenes/WalletListStyle.js
yarn.lock

Task: Show Wallet Loading Progress Indicator (https://app.asana.com/0/361770107085503/1146358056022529)

Wallet List Icon have their own loader using a pie overlay

---

README.md

Update README to correct method of obtaining API key

---

package.json
src/components/common/FullWalletListRow.js
src/components/common/ProgressPie.js
src/styles/scenes/WalletListStyle.js
yarn.lock

Replace react-native-progress with our own component

---

src/constants/plugins/buyPlugins.json

Add Australia to Moonpay

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

Absolute value fix for sell amounts

---

src/locales/strings/enUS.json

update json language translation

---

src/actions/FioActions.js

Update FIO URL

---

CHANGELOG.md

update changelog  1.10.3  - FIO Registration URL

update changelog  1.10.3  - FIO Registration URL

---

package.json

update version 1.10.3 fio url

---

src/actions/WalletListActions.js
src/components/common/FullWalletListRow.js
src/components/common/SortableWalletListRow.js
src/components/common/WalletListRowOptions.js
src/components/common/WalletListTokenRow.js
src/components/scenes/WalletListScene.js
src/connectors/WalletListTokenRowConnector.js
src/connectors/scenes/WalletListConnector.js
src/modules/Core/Account/settings.js
src/modules/Settings/SettingsActions.js
src/modules/UI/components/MenuDropDown/__snapshots__/MenuDropDown.test.js.snap
src/reducers/scenes/SettingsReducer.js
src/styles/components/HeaderMenuDropDownStyles.js
src/styles/scenes/WalletListStyle.js

Task: Redesign Wallet List - https://app.asana.com/0/361770107085503/1148627901147577

Redesign Wallet List

---

src/__tests__/__snapshots__/TransactionRow.test.js.snap
src/components/common/TransactionRow.js
src/styles/scenes/TransactionListStyle.js

Task: Redesing Transaction List - https://app.asana.com/0/361770107085503/1148627901147579

Redesign Transaction List

---

src/components/scenes/PluginViewListScene.js

Fix pluginId which is causing problems with the currency lists

---

ios/Podfile.lock
src/modules/UI/components/MenuDropDown/__snapshots__/MenuDropDown.test.js.snap
src/styles/components/HeaderMenuDropDownStyles.js

font weight fix and update podfile

---

src/actions/WalletActions.js

Fix crash when deleting custom token

---

src/styles/scenes/CryptoExchangeQuoteSceneStyles.js

Fix row height of top exchange row.

---

src/components/common/FullWalletListRow.js
src/components/common/WalletListRowOptions.js
src/modules/UI/components/MenuDropDown/__snapshots__/MenuDropDown.test.js.snap
src/styles/components/HeaderMenuDropDownStyles.js
src/styles/scenes/WalletListStyle.js

Task: Wallet List - Fix top bottom margins, fix wallet options - https://app.asana.com/0/361770107085503/1150389748028435

Fix row height of wallet list. Custom styles on Row Options

---

src/__tests__/__snapshots__/TransactionRow.test.js.snap
src/components/common/TransactionRow.js
src/styles/scenes/TransactionListStyle.js

Task: Transaction List - Fix category display - https://app.asana.com/0/361770107085503/1150389748028433

Localized category and remove blank sub categories. Style time when status is pending or partial

---

localization/PlayStoreDescription.txt

update line 9 coins 
Binance Chain (BNB), RSK (RBTC), Stellar (XLM), Tezos (XTZ), Ravencoin (RVN), SmartCash (SMART), Zcoin (XZC), Dogecoin (DOGE),

update line 9 coins

---

src/modules/Core/Account/settings.js

update SAI and DAI info

---

src/styles/scenes/CryptoExchangeQuoteSceneStyles.js

Task: Exchange Screen - Fix exchange box margins - https://app.asana.com/0/361770107085503/1150389748028437

Fix line on exchange quote scene row

---

env.example.json

Add blockchairApiKey to env.example.json

---

src/components/scenes/PluginViewListScene.js
src/constants/plugins/buyPlugins.json
src/constants/plugins/buySellPlugins.js
src/constants/plugins/sellPlugins.json

Updates to Safello, Banxa, and text formatting

---

src/components/common/FullWalletListRow.js
src/components/common/WalletListTokenRow.js

Task: ETH Tokens need to have a spinner. Have spinner progress match that of parent ETH. - https://app.asana.com/0/361770107085503/1151162564712745

Add Loader on Wallet Tokens

---

src/modules/Core/Wallets/EnabledTokens.js

Use changeEnabledTokens

---

src/constants/plugins/buyPlugins.json
src/constants/plugins/sellPlugins.json

Update Safello titles

---

src/components/scenes/PluginViewListScene.js
src/constants/plugins/buyPlugins.json
src/constants/plugins/buySellPlugins.js

update safello and GB payment methods

---

package.json

update version 1.11.0

---

env.example.json

Add alethioApiKey to env.example.json

---

src/components/common/FullWalletListRow.js
src/components/common/WalletListTokenRow.js
src/modules/Core/selectors.js
src/styles/scenes/WalletListStyle.js
src/util/utils.js

Note: Price change is yesterdays value. Also fix the wallet list fiat balance and exchange rate to have the wallet list fiat not the default fiat.
Task: Add historical price change for wallet - https://app.asana.com/0/361770107085503/1151607706066281

Added price changes history on Wallet List Scene.

---

src/components/common/FullWalletListRow.js
src/components/common/SortableWalletListRow.js
src/components/common/WalletListTokenRow.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/styles/scenes/WalletListStyle.js

Fixed comments on PR

---

src/components/common/FullWalletListRow.js
src/components/common/WalletListTokenRow.js
src/styles/scenes/WalletListStyle.js

Wallet list fixes

---

src/__tests__/__snapshots__/sendConfirmation.test.js.snap
src/__tests__/__snapshots__/sendConfirmationOptions.test.js.snap
src/constants/WalletAndCurrencyConstants.js
src/locales/en_US.js
src/locales/strings/enUS.json

Remove XMR payment ID

---

src/modules/Core/Wallets/action.js

Update enableTokens to changeEnabledTokens

---

src/modules/Core/Wallets/action.js
src/modules/Login/action.js

Task: Exchange Rate / ETH Tokens do not show balance or price if Default Currency is MXN - https://app.asana.com/0/361770107085503/1152920147995305
Note:Factor out logic to determine enabled tokens and to call change enabled tokens.

Fix account initialization to properly enable tokens

---

CHANGELOG.md
package.json

update to 1.11.1

---

src/constants/plugins/buyPlugins.json

Update Banxa GB description

---

env.example.json

amberdataApiKey

---

package.json
yarn.lock

Bump Bitcoin plugin for BCH and BSV changes

---

src/components/common/CryptoExchangeCreateWalletRow.js
src/components/common/CryptoExchangeWalletListRow.js
src/components/common/CryptoExchangeWalletListTokenRow.js
src/components/modals/WalletListModal.js
src/styles/components/CryptoExchangeWalletListRowStyle.js

Task: Change style of exchange scene wallet selector to 1.1 design - https://app.asana.com/0/361770107085503/1151835422327121

Exchange scene wallet selector redesign and improve filter

---

src/components/common/FullWalletListRow.js
src/components/common/SortableWalletListRow.js
src/components/common/WalletListTokenRow.js
src/styles/scenes/WalletListStyle.js

Task: Wallet list - AED and SAR forces exchange rate to switch sides - https://app.asana.com/0/361770107085503/1152299401363441

Fix wallet list text Righ to Left when arabic characters are introduced

---

package.json

bump up version 1.11.2

---

ios/edge/AppDelegate.m

fixed missing semicolons

---

src/components/common/CryptoExchangeWalletListRow.js
src/components/common/CryptoExchangeWalletListTokenRow.js

Required also removing requirement positive parent balance to select a token.

Fix display balance of tokens on the exchange scene wallet picker.

---

src/components/common/CryptoExchangeWalletListRow.js
src/components/common/FullWalletListRow.js
src/components/common/SortableWalletListRow.js
src/components/common/WalletListTokenRow.js
src/modules/UI/components/WalletListRow/WalletListRowConnector.js
src/modules/UI/selectors.js
src/util/utils.js

Task: https://app.asana.com/0/361770107085503/1153857373665121

Fix wallets fiats balance not showing correct fiat amounts.

---

src/constants/plugins/buyPlugins.json

Adjust iOS priority

---

src/constants/plugins/buyPlugins.json
src/constants/plugins/sellPlugins.json

Update limit descriptions

---

src/components/scenes/SettingsOverviewScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
testSetup.js

Task: Rename rows on settings. Use TouchId, Use FaceId, Use Biometric. - https://app.asana.com/0/361770107085503/1126000976007328

Change the text of the biometry row to what biometry type is supported

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

Write Bity data to logs for QA

---

src/locales/en_US.js

update FaceID text

---

src/actions/ScanActions.js
src/styles/scenes/ScaneStyle.js

Legacy Address Modal Icon style to red

---

src/components/common/CryptoExchangeWalletListRow.js
src/components/common/HeaderWalletSelector.js
src/components/modals/WalletListModal.js
src/components/scenes/CreateWalletAccountSelectScene.js
src/components/scenes/CryptoExchangeScene.js
src/connectors/components/CryptoExchangeWalletListRowConnector.js
src/connectors/components/HeaderWalletSelectorConnector.js
src/connectors/components/WalletListModalConnector.js
src/connectors/scenes/CreateWalletAccountSelectConnector.js
src/connectors/scenes/CryptoExchangeSceneConnector.js
src/modules/UI/components/WalletListRow/WalletListRowConnector.js
src/modules/UI/scenes/Plugins/EdgeProvider.js
src/modules/UI/selectors.js

Task: Wallet List scene order of wallets is not the same as the wallet selector list. (https://app.asana.com/0/361770107085503/1154597586670346)

Functions to secure sorting of wallet list on wallet selectors

---

src/modules/Core/Account/settings.js

add ETHBNT

---

src/components/common/CryptoExchangeWalletListRow.js
src/components/modals/WalletListModal.js

Task: Wallet List - Tokens to appear as standalone wallets (https://app.asana.com/0/361770107085503/1155557910296414)
Added token filters and hiding of ethereum parent wallet on the Wallet Selector Modal

Wallet List Modal Filter Tokens

---

src/__tests__/__snapshots__/Request.test.js.snap
src/__tests__/__snapshots__/sendConfirmation.test.js.snap
src/__tests__/sendConfirmation.test.js
src/components/scenes/CryptoExchangeScene.js
src/components/scenes/RequestScene.js
src/components/scenes/SendConfirmationScene.js
src/connectors/scenes/SendConfirmationConnector.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/components/FlipInput/CryptoExchangeFlipInputWrapperComponent.js
src/modules/UI/components/FlipInput/ExchangedFlipInput2.js
src/modules/UI/components/FlipInput/FlipInput2.ui.js
src/modules/UI/components/FlipInput/styles.js
src/styles/scenes/CryptoExchangeSceneStyles.js
src/styles/scenes/RequestStyle.js
src/theme/variables/airbitz.js

Added on Request, Send Confirmation and Exchange scenes
Refactor some designs on exchange scene dropdowns
Remove some unused codes and style on the flip input
Added new color on theme

New Flip Input Design

---

src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/components/FlipInput/FlipInput2.ui.js

Make whole flip input top focus the input. Fix some typo

---

package.json

update version 1.11.4

---

src/constants/plugins/buyPlugins.json

Add US to Moonpay

---

src/components/common/CryptoExchangeWalletListRow.js

Add wallet name filter to token

---

src/actions/SendConfirmationActions.js
src/locales/en_US.js
src/locales/strings/enUS.json

Add recipient address to notes

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

Add exchangeAmount

---

src/modules/DeepLinkingManager.js

Task: Simplex Deep link broken white screen - https://app.asana.com/0/361770107085503/1157295062578034

Fix bug on deep link page and simplex deep linking

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

Add URL logging

---

src/modules/Core/selectors.js
src/util/installReason.js
src/util/tracking.js

Remove embedded async functions from loadInstallReason
Handle fetch error in fetchExchangeRateHistory
Add LoadInstallReasonFail

Clean fetch error handling

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

Add edgeProvider readData and writeData logging

---

src/modules/Logs/action.js

Add wallet summary to logs

---

src/actions/CreateWalletActions.js
src/connectors/scenes/CryptoExchangeSceneConnector.js

Updates most recent used wallets on exchange scene

---

src/modules/UI/components/FlipInput/CryptoExchangeFlipInputWrapperComponent.js
src/modules/UI/components/FlipInput/FlipInput2.ui.js

Fix crash on custom token in exchange scene

---

src/components/common/CryptoExchangeWalletListRow.js
src/components/modals/WalletListModal.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/styles/components/CryptoExchangeWalletListRowStyle.js

Task: MRU Wallets - Add headers to separate most recently used and the rest of the wallets - https://app.asana.com/0/361770107085503/1161264151944035

Label headers added on most recent wallet list section to indicate most recent or all wallet section

---

src/util/corePlugins.js

Disable Shapeshift exchange plugin

---

src/app.js

Add bugsnag breadcrumb to failed fetch calls

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

Add dispatch to trackConversion

---

src/components/Main.ui.js

Restore the scan & request scene headers

---

src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/scenes/Plugins/EdgeProvider.js

Adds getTransactions to EdgeProvider

---

src/constants/plugins/buySellPlugins.js

Add camera and location permission to dev plugin

---

src/constants/WalletAndCurrencyConstants.js

Increase max token code length to 7

---

package.json
src/actions/CryptoExchangeActions.js
src/types/TweakTypes.js
src/util/ReferralHelpers.js
yarn.lock

Pass promo codes to swap partners

---

src/components/scenes/SettingsOverviewScene.js

Task: Auto Logout Whitescreen - https://app.asana.com/0/361770107085503/1161264151944039

Fix white screen on auto logout when on settings screen

---

android/app/src/main/AndroidManifest.xml
ios/edge/edge.entitlements
src/__tests__/DeepLink.test.js
src/types/DeepLink.js

Create new deep linking patterns

---

src/actions/SettingsActions.js

Task: Put a spinner that appears until Logs are sent - https://app.asana.com/0/361770107085503/1163612456708747

Added loader when sending logs

---

src/types/DeepLink.js

Add currency deep links.  Extract parse functions for reuse

---

src/styles/scenes/WalletListStyle.js

Fix a visual glitch with the promo card text

---

DEV_CHANGELOG.md
devCHANGELOG.md

Initial devCHANGELOG commit

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

- Make `lockInputs` actually do something (setting it to false did nothing before).
- Handle the case where both `nativeAmount` and `exchangeAmount` are missing in a spend target.
- Remove Flow hack.
- Consolidate redundant code.
This needs testing!

Refactor the EdgeProvider send methods

---

package.json
src/constants/plugins/buyPlugins.json
src/constants/plugins/sellPlugins.json
yarn.lock

Update Bity fee

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/__tests__/scenesReducer.test.js
src/modules/FioAddress/reducer.js

Make fio address expiration date GMT for initial state and testing

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json

Bits of Gold fee and limit updates

---

src/modules/Login/action.js

Task: Support creation of default token wallets for referral partners - https://app.asana.com/0/361770107085503/1167229874819809

Added parsing and creation of tokens for referral partners

---

src/modules/UI/components/ControlPanel/Component/Main.js

Move Exchange higher in side menu

---

src/components/scenes/FioAddressRegisterScene.js

Keeps wallet picker visible if more than one FIO wallet is available

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/constants/plugins/buyPluginList.json

Update Moonpay limit

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/constants/plugins/buyPluginList.json

Added new supported countries for Moonpay

---

src/components/scenes/FioAddressRegisterScene.js

Disable next button if loading is false (still validating text entry)

---

src/components/scenes/CryptoExchangeQuoteScene.js

Add Switchain kyc links

---

src/constants/plugins/GuiPlugins.js

Change query name

---

src/components/navigation/TransactionDetailsTitle.js
src/components/scenes/TransactionDetailsScene.js

Fix currency name on crypto amount. Fix bug on header time not showing in android

---

src/styles/scenes/WalletListStyle.js

Add flex property to promoIcon

---

src/styles/scenes/WalletListStyle.js

Increase icon size

---

src/actions/AccountReferralActions.js

Fix disk errors that were preventing promo activations

---

src/components/modals/AddressModal.js

This should allow .kred .luxe and .xyz domains to be resolved as well as .crypto .zil .eth

added support for .kred .luxe .xyz

---

src/styles/scenes/WalletListStyle.js

Reduce promoIcon size

---

src/components/scenes/CreateWalletReviewScene.js

Always pop to the wallet list scene on key import

---

src/modules/UI/components/ShareButtons/ShareButtons.ui.js

Change Fio Address to Fio Request

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json

Update Banxa fees and remove tildas

---

src/components/scenes/RequestScene.js

Only render InputAccessoryView on iOS devices

---

src/components/Main.ui.js
src/modules/UI/components/LoginStatus/LoginStatus.js

Protect all scenes from logout

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/modules/Core/Account/settings.js

Add Orchid OXT

---

src/actions/CryptoExchangeActions.js

Add Transfer metadata

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/constants/WalletAndCurrencyConstants.js
src/modules/Core/Account/settings.js
src/modules/UI/components/ExchangeRate/action.js
src/reducers/scenes/SettingsReducer.js
src/util/corePlugins.js

Add Ethereum Clasic support.

---

src/__tests__/__snapshots__/TransactionDetails.ui.test.js.snap
src/components/scenes/TransactionDetailsScene.js

Task: TX details - current amount doesn't match localization setting - https://app.asana.com/0/361770107085503/1171463534022417

Fix RTL fiat currency on curreny price amount

---

Jenkinsfile
deploy-config.sample.json
deploy.js
env.example.json
src/components/scenes/LoginScene.js

Putting `YOLO_USERNAME` & `YOLO_PASSWORD` into ENV.json will trigger auto-login after half a second.

Implement an autologin feature

---

src/components/common/HeaderWalletSelector.js
src/components/modals/WalletListModal.js
src/components/scenes/CreateWalletAccountSelectScene.js
src/components/scenes/CryptoExchangeScene.js
src/components/scenes/FioAddressRegisterSelectWalletScene.js
src/components/scenes/FioPendingRequestDetailsScene.js
src/connectors/scenes/FioPendingRequestConnector.js
src/locales/en_US.js
src/modules/UI/scenes/Plugins/EdgeProvider.js

Supplement to the PR https://github.com/EdgeApp/edge-react-gui/pull/1946

Added refactors for the WalletListModal

---

src/util/corePlugins.js

Add WazirX rate plugin.

---

src/components/common/CryptoExchangeWalletListRow.js

Prevent excluded currency codes from appearing in search

---

src/actions/DeleteWalletModalActions.js
src/locales/en_US.js
src/locales/strings/enUS.json

Task: Deleting FIO wallets will remove access to the fio address issue - Add a warning - https://app.asana.com/0/361770107085503/1175254846648769

Reword text for deleting FIO wallet that is linked. Added newlines for format

---

src/actions/CryptoExchangeActions.js
src/assets/images/exchange/index.js
src/components/scenes/SwapSettingsScene.js

Filter transfer plugin from settings.

---

src/components/scenes/CryptoExchangeScene.js

Exclude Tezos - cherry pick from master

---

src/components/scenes/CryptoExchangeScene.js

Remove tezos exclusion from swaps.

---

src/types/DeepLink.js

Add 'http' to deeplinks

---

src/constants/WalletAndCurrencyConstants.js

Disable EOS import.

---

src/modules/UI/components/FlipInput/FlipInput2.ui.js

Add selection for each primary and secondary currencies

---

src/util/corePlugins.js

Enable ETC

---

src/constants/plugins/buyPluginList.json

Remove BCH from Safello

---

src/components/common/AirshipModal.js
src/components/common/IconCircle.js
src/components/modals/AddressModal.js

Task: Paste/Address screen icon slightly cut off at top on iPhone 8 - https://app.asana.com/0/361770107085503/1176771937664939

Fix address modal icon cut off

---

src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/components/ControlPanel/Component/Main.js
src/theme/variables/airbitz.js

Add Share App button to side menu

---

src/actions/AccountReferralActions.js

Set default installerId and creationDate if not present on account

---

src/components/scenes/FioRequestConfirmationScene.js

FIO. Send fio request using slider

---

src/constants/plugins/buyPluginList.json

Add LTC to Banxa payment methods

---

src/util/corePlugins.js

Disable ETC

---

src/modules/Login/action.js

Skip plugin settings if plugin unavailable.

---

ios/edge/edge.entitlements

Add aps environment to entitlements file.

---

src/modules/ExchangeRates/action.js

Change exchangeRate query to rates1.edge.app

---

src/components/common/WalletListEmptyRow.js
src/components/common/WalletListMenu.js

Yarn fixes on Wallet List

---

src/components/common/Tile.js
src/components/scenes/TransactionDetailsScene.js

Add Tiles to have copy functions and have TransactionDetails recipientAddresses be string

---

src/components/scenes/RequestScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

Simplify share button to avoid writing local file

---

src/components/scenes/RequestScene.js

Use deep link instead of edge://

---

src/components/scenes/RequestScene.js

Remove empty string url to prevent file share in iOS

---

src/components/scenes/RequestScene.js
src/modules/UI/components/ControlPanel/Component/Main.js

Create platform specific shareOptions for address and app share buttons

---

src/components/scenes/CurrencyNotificationScene.js

Call settings with correct user account id.

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/constants/plugins/buyPluginList.json

Disable Transak in US

---

src/actions/FioActions.js

Adding to FIO address cache when receiving FIO transaction

---

src/actions/WalletListMenuActions.js
src/components/common/WalletListMenu.js
src/components/common/WalletListRow.js
src/components/common/WalletListTokenRow.js
src/components/scenes/TransactionsExportScene.js
src/components/scenes/WalletListScene.js
src/connectors/scenes/TransactionsExportSceneConnector.js

Export transactions of tokens on Wallet List using option buttons

---

src/actions/CryptoExchangeActions.js
src/locales/en_US.js
src/locales/strings/enUS.json

Show transaction fee fiat amount on swap quote scene

---

src/actions/CreateWalletActions.js
src/components/common/HeaderWalletSelector.js
src/components/common/WalletListModalCreateRow.js
src/components/modals/WalletListModal.js
src/components/scenes/CreateWalletAccountSelectScene.js
src/components/scenes/CryptoExchangeScene.js
src/components/scenes/FioAddressRegisterScene.js
src/components/scenes/FioAddressRegisterSelectWalletScene.js
src/components/scenes/FioRequestListScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/scenes/Plugins/EdgeProvider.js

New Wallet List Modal creation of wallets and tokens

---

src/actions/WalletActions.js
src/actions/WalletListActions.js
src/components/modals/WalletListModal.js
src/components/scenes/CreateWalletAccountSelectScene.js
src/components/scenes/CreateWalletAccountSetupScene.js
src/components/scenes/CreateWalletChoiceScene.js
src/components/scenes/CreateWalletImportScene.js
src/components/scenes/CreateWalletNameScene.js
src/components/scenes/CreateWalletReviewScene.js
src/components/scenes/CreateWalletSelectCryptoScene.js
src/components/scenes/CreateWalletSelectFiatScene.js
src/components/scenes/WalletListScene.js
src/types/types.js
src/util/CurrencyInfoHelpers.js

Refactor GuiWalletType type

---

src/actions/WalletListMenuActions.js
src/components/scenes/WalletListScene.js

Make currencyCode optional for menu list options

---

src/constants/WalletAndCurrencyConstants.js

Add ETC import key support

---

src/components/scenes/TransactionDetailsScene.js

Fix estimate/fixed rate string

---

src/actions/CryptoExchangeActions.js

Swaps - calculate BTC max spendable amount using high fee 

---

src/constants/plugins/buyPluginList.json

Fix currency symbol

---

src/components/modals/UpdateModal.js

Fix update modal icon background

---

src/components/scenes/NotificationScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

Toggling of all notifications

---

src/actions/ScanActions.js
src/locales/en_US.js
src/locales/strings/enUS.json

Add sweep private key mining fee popup text

---

android/app/build.gradle
android/app/src/main/java/co/edgesecure/app/MainApplication.java
android/settings.gradle
ios/Podfile
ios/Podfile.lock
package.json
src/components/scenes/TransactionsExportScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
yarn.lock

Refactor Export Transaction

---

src/actions/CryptoExchangeActions.js

Fix parent currency fee amount on exchange quote scene

---

src/components/modals/TransactionAdvanceDetails.js
src/components/scenes/TransactionDetailsScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

Show txSecret in advanced details modal

---

src/components/modals/TransactionAdvanceDetails.js
src/components/scenes/TransactionDetailsScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

Show explorer link to prove XMR transactions

---

src/actions/AccountReferralActions.js
src/actions/DeviceReferralActions.js
src/util/tracking.js
src/util/utils.js

Create multicastUtilServers function

---

src/__tests__/__snapshots__/ChangeMiningFee.test.js.snap
src/components/scenes/ChangeMiningFeeScene.js

Save button on change mining fee scene

---

src/components/scenes/SettingsOverviewScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/theme/variables/edgeDark.js
src/theme/variables/edgeLight.js
src/types/Theme.js

Light theme on developer mode

---

src/components/scenes/SettingsOverviewScene.js
src/components/scenes/TransactionsExportScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/theme/variables/edgeDark.js
src/theme/variables/edgeLight.js
src/types/Theme.js

- Put other themes on light mode that is not on the dark mode
- Add comments on not used themes
- Fix on themes like keyboardTopViewBackgroundDefault to keyboardTopViewBackgroundLight

Theme comments and fixes

---

src/util/tracking.js

Only log events to util2

---

src/__tests__/utils.test.js
src/locales/en_US.js
src/locales/intl.js
src/locales/intl.test.js
src/locales/strings/enUS.json
src/modules/UI/components/FlipInput/FlipInput2.ui.js
src/modules/UI/components/FlipInput/styles.js

- Hide text input with styles
- Replace with only text component
- Sanitize decimalAmounts before applying it to displayAmount
- Refactor some utils and intl functions
- Added new test for newer functions
- Remove selection states and functions on the input
- Added and fix some styles and spaces

Refactor top flip input

---

src/modules/UI/components/FlipInput/FlipInput2.ui.js
src/modules/UI/components/FlipInput/styles.js

- Enter amount text is greyed out
- Put adjustsFontSizeToFit into the text fields
- Reput back selections props to the text inputs so every changes will
shift the cursor to the right

Flip input fixes

---

src/components/common/SettingsHeaderRow.js
src/components/common/SettingsRow.js
src/components/scenes/FioAddressDetailsScene.js
src/components/scenes/FioAddressListScene.js
src/components/scenes/FioRequestListScene.js

Re-add the old Settings Rows components to be used by Fio scenes

---

env.example.json
src/components/services/DeepLinkingManager.js

Add optional deep link to launch the app with

---

src/modules/UI/components/FlipInput/FlipInput2.ui.js

Fix input selection on android

---

src/components/services/DeepLinkingManager.js

Fix ENV import

---

src/actions/WalletListMenuActions.js
src/components/modals/RawTextModal.js

Have the copy button remove on raw private keys modal

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

Add edgeProvider requestSpend logging

---

src/locales/en_US.js
src/locales/strings/enUS.json

Sweep Private Key message add comma on 2nd sentence

---

src/components/common/CryptoExchangeWalletListRow.js
src/components/modals/WalletListModal.js

Wallet List Modal filter of custom tokens

---

src/modules/UI/components/FlipInput/FlipInput2.ui.js
src/modules/UI/components/FlipInput/styles.js

Task: Enter Amount text too big - https://app.asana.com/0/281171002982981/1187916501869049

Fix flip input top text being cut off

---

src/components/Main.ui.js
src/components/navigation/CurrencySettingsTitle.js
src/locales/en_US.js
src/locales/strings/enUS.json

Fix Currency Notifications Settings scene header being cut off

---

src/actions/CryptoExchangeActions.js
src/actions/TrackingActions.js
src/modules/UI/scenes/Plugins/EdgeProvider.js
src/util/tracking.js

Save orderId to util server

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/constants/plugins/GuiPlugins.js
src/constants/plugins/sellPluginList.json

Add BitaccessBTM

---

src/modules/UI/components/FlipInput/FlipInput2.ui.js

Fix bugs on flip input focus and also always flip input on top when there is no exchange rates

---

src/components/themed/Txt.js
src/modules/UI/components/FlipInput/FlipInput2.ui.js
src/modules/UI/components/FlipInput/styles.js

New component Txt that is themed Text component

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

Log requestSpend uniqueIdentifier

---

src/modules/UI/components/FlipInput/FlipInput2.ui.js

FlipInput: Use onKeyPress to format decimal amounts and remove cursor selections

---

src/components/themed/EdgeText.js
src/modules/UI/components/FlipInput/FlipInput2.ui.js

Rename Txt to EdgeText

---

src/components/themed/EdgeTextField.js

Create a themed EdgeTextField component

---

src/actions/WalletListMenuActions.js
src/components/themed/CheckPasswordModal.js

Private Seed Modal usage of new modals and clean up of old code

---

src/constants/WalletAndCurrencyConstants.js
src/locales/en_US.js
src/locales/strings/enUS.json

Re-add EOS import key instructions

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

Add uniqueIdentifier to edgeProvider spendTargets

---

patches/@react-native-community+blur+3.6.0.patch

Fix missing import

---

src/components/scenes/FioAddressListScene.js
src/modules/FioAddress/components/SelectFioAddress.js

* Check for current scene on fio address list scene when redirecting for registration. 
* Disable refreshing in select fio address component.

HOTFIX. Fix fio address redirection on send confirmation scene.

---

src/constants/WalletAndCurrencyConstants.js
src/locales/en_US.js
src/locales/strings/enUS.json

Add unique text for FIO import private key

---

src/actions/ScanActions.js

Replace createThreeButtonModal with ButtonsModal

---

src/actions/CreateWalletActions.js
src/actions/WalletActions.js
src/components/scenes/RequestScene.js
src/modules/UI/components/ExchangeQuote/ExchangeQuoteComponent.js

Replace createSimpleConfirmModal with ButtonsModal

---

src/actions/DeleteWalletModalActions.js
src/actions/ResyncWalletModalActions.js
src/actions/ScanActions.js
src/actions/SendConfirmationActions.js
src/actions/SettingsActions.js
src/actions/SplitWalletModalActions.js
src/components/common/AddressTextWithBlockExplorerModal.js
src/components/common/WalletListFooter.js
src/constants/IconConstants.js
src/modules/UI/components/Icon/Icon.ui.js

Replace old createYesNoModal with ButtonsModal

---

src/components/scenes/TransactionsExportScene.js

Fix QBO export not to produce CSV files

---

src/components/common/ArrowDownTextIconButton.js
src/components/common/TouchableTextIcon.js
src/components/scenes/FioAddressRegisterScene.js
src/components/scenes/FioDomainRegisterScene.js
src/modules/FioAddress/components/SelectFioAddress.js
src/modules/UI/components/FlipInput/CryptoExchangeFlipInputWrapperComponent.js
src/modules/UI/components/Header/Component/WalletSelector.ui.js

Make icon standard and just pass iconColor and iconSize as props on TouchableTextIcon

---

src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/components/FlipInput/FlipInput2.ui.js
src/modules/UI/components/FlipInput/styles.js

Paste button on flip input

---

package.json
yarn.lock

Upgrade edge-core-js to v0.17.16

---

ios/Podfile.lock
src/locales/en_US.js
src/locales/strings/enUS.json

Fio Confirm Scene Warning text changed

---

src/components/common/WalletList.js

Fix bug not showing all empty wallets at the same time

---

src/components/Main.ui.js
src/components/themed/MenuTab.js
src/theme/variables/edgeDark.js
src/theme/variables/edgeLight.js
src/types/Theme.js

Bottom Tab Menu themed

---

package.json
src/__tests__/__snapshots__/RootReducer.test.js.snap
src/actions/CreateWalletActions.js
src/components/scenes/RequestScene.js
src/constants/WalletAndCurrencyConstants.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/Core/Account/settings.js
src/util/corePlugins.js
yarn.lock

WAX Integration + EOSIO Tokens
