src/html/enUS/info.html, src/modules/UI/components/HelpModal/HelpModal.ui.js
The purpose of this pull request is to cause links within the helpModal to be opened by an *external* browser. Additionally, I have updated the contact info phone number and links to reflect new branding.
Asana task for external browser bug: https://app.asana.com/0/361770107085503/317312547827494/f
Asana task for updated contact info: https://app.asana.com/0/361770107085503/463937108594899/f
=> Implement external browser for helpModal (modified) links

src/locales/en_US.js, src/styles/scenes/EdgeLoginSceneStyle.js
Image components from remote hosts need explicit sizing. This also required changing the server side images on info1.edgesecure.co since remote images can't be easily proportionally scaled.
=> Correct wording on Edge Login and fix missing image

src/modules/UI/scenes/WalletList/components/WalletListRow/FullWalletListRow.ui.js, src/modules/UI/scenes/WalletList/components/WalletListRow/SortableWalletListRow.ui.js, src/modules/UI/scenes/WalletList/style.js
The purpose of this task is to increase the size of the cryptocurrency logos on the walletList scene (for both the full list and sort list).
Asana Task: https://app.asana.com/0/361770107085503/459375388568101/f
=> Enlarge crypto logos on walletList(s)

src/modules/UI/scenes/SendConfirmation/SendConfirmationConnector.js
Set the currencyCode in the parsedUri to the selected wallet currencyCode.
=> URGENT: Fix bug where ETH was being sent instead of wallet token

src/modules/UI/scenes/Login/Login.ui.js
Only remount the Login.ui scene when logging out. Check if nextProps.account.username is undefined as that will be the case upon logout but not upon login
=> Fix TouchID popup occurring on login

src/modules/Core/Account/callbacks.js
Remove logging of all transactions for onTransactionsChanged and onNewTransactions. Only log number of transactions and the txids.
Minimize debug logs for callbacks to a single line vs outputting an object. Saves many lines of debug spew
=> Minimize debug logging to reduce # of lines spewed on callbacks.

src/locales/en_US.js
The purpose of this task is to change syntax for public address input to be cryptocurrency-agnostic.
https://app.asana.com/0/361770107085503/459920947947995/f
=> Fix reference to 'Bitcoin' and 'Priate Keys' for Scan address modal

src/actions/CryptoExchangeActions.js
Add a precision to bns.div for display amount. Then use toFixed to cap the precision range.
=> Fix integer rounding of display amount in exchange modal

src/modules/UI/components/FlipInput/FlipInput.ui.js
The purpose of this task is to remove the teal underline in the FlipInput component for Android.
Asana Task: https://app.asana.com/0/361770107085503/459362679590645/f
=> Remove FlipInput underline on Android

src/modules/UI/components/FlipInput/FlipInput.ui.js, src/modules/UI/scenes/Settings/style.js
The purpose of this task is to address two areas where text is cut off on Android, the Request scene's FlipInput (top TextInput) and the currency denomination settings.
Asana Task: https://app.asana.com/0/361770107085503/479270660285757/f
=> Fix Android Text Cut Off on Currency Denomination Settings & Request (FlipInput)

src/modules/UI/components/Modal/Modal.ui.js, src/modules/UI/components/Modal/style.js
This removes the weird box present on some android phones. It is a direct result of layering two round items on top of each other. The fix was to kill the gradient, go with a 2 px border and have the icon center inside that.
=> Modify Modal to not cast square shadow on Android.

src/modules/UI/scenes/Scan/Scan.ui.js
The purpose of this task is to get Android to properly ask for camera permissions (on first install / load and when accessing Scan scene).
Asana Task: https://app.asana.com/0/361770107085503/482710794616256/f
=> Move Android Camera Permission to Scan Scene Render

src/modules/UI/scenes/Scan/components/AddressModal.js
The purpose of this task is to fix the onChangeText functionality on the Address modal of the Scan scene, which seems to have been broken when we switched over to the newer (prettier) TextInput components.
Asana Task: https://app.asana.com/0/361770107085503/484205403928766/f
=> Fix onChangeText for Address modal (Scan scene)

src/lib/LocaleStrings.js, src/locales/en_PH.js, src/locales/es.js, src/locales/strings.js, src/modules/Main.ui.js, src/modules/UI/scenes/TransactionList/TransactionList.ui.js, src/modules/UI/scenes/WalletList/WalletList.ui.js
Localization files are named using ISO codes (ie. en_US, es, es_MX) and actual language is selected via selectLocale()
This needs migration of string syntax from
`import strings from '../../../../locales/default'`
`const SHOW_BALANCE_TEXT = strings.enUS['string_show_balance']`
to
`import s from '../../../../locales/strings.js'`
`const SHOW_BALANCE_TEXT = s.strings.string_show_balance`
=> Create language localization framework

src/actions/CryptoExchangeActions.js, src/locales/en_US.js, src/modules/UI/Wallets/reducer.js, src/modules/UI/scenes/CryptoExchange/CryptoExchangeSupportedTokens.js, src/modules/UI/scenes/ManageTokens/ManageTokens.ui.js, src/types.js
This adds a filter to prevent a user from being able to select a token for Shape shift that is not supported.
=> Shape shift only token hack

src/actions/CryptoExchangeActions.js, src/connectors/components/CryptoExchangeRateConnector.js, src/constants/ActionConstants.js, src/locales/en_US.js, src/modules/UI/components/CryptoExchangeRate/CryptoExchangeRate.js, src/modules/UI/components/FlipInput/CryptoExchangeFlipInputWrapperComponent.js, src/modules/UI/scenes/CryptoExchange/CryptoExchangeSceneComponent.js, src/reducers/CryptoExchangeReducer.js
Starts Shape Shift screen with the ability for users to select what wallets they want instead of automatically doing it. 
Fixed errors caused by the above change
Added additional error handling when tokens are not available. 
Reset scene when shift is successful.
=> Clean start for exchange scene

src/modules/UI/components/HelpModal/HelpModal.ui.js, src/modules/UI/components/HelpModal/style.js, src/modules/UI/components/Modal/Modal.ui.js
iOS. Tap “Help” in upper left of most screens. The modal should show help content but is blank.
=> Fix: No content in help modal 

src/actions/CryptoExchangeActions.js, src/constants/ErrorConstants.js, src/constants/indexConstants.js
The core exports these error types symbolically, so use that instead.
=> Remove magic error strings

src/modules/Core/Account/reducer.js, src/modules/UI/Request/reducer.js, src/modules/UI/Settings/reducer.js, src/modules/UI/Wallets/reducer.js, src/modules/UI/components/TransactionAlert/reducer.js, src/modules/UI/scenes/CreateWallet/reducer.js, src/modules/UI/scenes/TransactionList/reducer.js, src/modules/UI/scenes/WalletList/reducer.js
Do not dereference action.data before the case statement of a reducer as the data may be NULL.
For ACTION.TOUCH_ID_SETTINGS, also check for data == NULL because the core-js-ui might pass a NULL touchIdInfo object
=> Fix multitude of crashes in GUI after account creation

src/modules/UI/scenes/Settings/SettingsOverview.ui.js
Do not check `value` in determining if an optional setting should be rendered
=> Fix TouchID missing from settings list 

src/modules/UI/Wallets/action.js
Do not enable any tokens that are marked enabled in the wallet file if they are not also in the accounts token file. The account contains the details of the custom token, which we cannot work without.
This fixes very easy to reproduce crashes due to out-of-sync account data and wallet data which can easily happen right now as we do not git sync very often.
=> URGENT: Fix crash due to enabled custom tokens

src/modules/UI/scenes/WalletList/WalletList.ui.js, src/modules/UI/scenes/WalletList/components/RenameWalletButtonsConnector.js, src/modules/UI/scenes/WalletList/reducer.js
Previous refactor of reducers caused return payload to return actual reducer function vs the payload data. Another error that proper flow typing would have caught.
=> Fix wallet rename causing spinning wallet reload

src/modules/Core/Wallets/api.js, src/modules/Login/action.js, src/modules/UI/Wallets/action.js
1. On login, call updateWalletRequest() after loadSettings so we have all the custom token info loaded off disk before we initialize the subwallets
2. Fix getEnabledTokens to also enable tokens from the currencyInfo
3. Clean up getEnabledTokensFromFile to use async/await and be easier to debug
=> Fix disappearing token subwallets

src/modules/Login/action.js
Call updateWalletsRequest() upon login even in the case when we have existing wallets
=> Fix spinning wallets on login

src/modules/Core/Wallets/action.js
Fixes issue with new device logins not enabling tokens hardcoded in currencyInfo
=> Enable tokens on updateWalletsRequest

src/modules/Main.ui.js
The purpose of this task was to fix the appearance of the **Exchange Scene**'s "Change Mining Fee" scene **header**. The fix was as simple as making the otherwise-white header transparent (one-line fix).
Asana Task: https://app.asana.com/0/361770107085503/514704167771592/f
=> Make Exchange Change Mining Fee Header Transparent

src/actions/CryptoExchangeActions.js, src/reducers/CryptoExchangeReducer.js
Make sure to properly add the fee whether the user is typing into the FROM wallet or the TO wallet. Tested with editing of both fiat and crypto FROM and TO amounts
=> Add shapeshift minerFee to exchange amount calculations

src/modules/UI/components/WalletListModal/components/WalletListModalBody.ui.js
Properly accept token if find() return 0. Only -1 means array element not found
=> Fix missing REP from showing in wallet list dropdown

src/modules/UI/scenes/CreateWallet/CreateWalletName.ui.js
The purpose of this task is to prevent the choppy animation / transition that occurs upon initial load when you try to create a wallet. The issues appears to be caused by the `autofocus` property for the FormField being set to true. I have disabled the autoFocus for the time being.
Asana Task: https://app.asana.com/0/361770107085503/523972073634899/f
=> Fix choppy scene issue on initial load to CreateWalletName

src/modules/UI/scenes/CreateWallet/CreateWalletName.ui.js, src/modules/UI/scenes/CreateWallet/CreateWalletSelectCrypto.ui.js, src/modules/UI/scenes/CreateWallet/CreateWalletSelectFiat.ui.js
The purpose of this task is to re-enable the alert(s) that show up when invalid data is present while pressing "Next" in the Create Wallet process. This includes the Wallet Name, Wallet Type (Crypto), and Wallet Fiat Type. The issue appeared to be that the "Next" button was disabled while data was invalid, so the `onNext` callback (which triggers the alert) was not being called.
All three of the following tasks are handled by this PR:
https://app.asana.com/0/361770107085503/523972073634902/f
https://app.asana.com/0/361770107085503/523972073634901/f
https://app.asana.com/0/361770107085503/523972073634900/f
=> Re-implement alert for blank / invalid CreateWallet data

package.json, src/locales/intl.js, src/locales/intl.test.js, src/modules/UI/components/FlipInput/FlipInput.ui.js
Add fallback locale-data as locale `en-US` for android. Figured out that with other locales polyfill has issue in FlipInput. Will work on it.
**EDIT:** Fixed FlipInput issue. Added 3 locales (en, de, ru). Used `en-US` as fallback if we don't have `locale-data` for user locale. 
Adding more polyfill-locales (mostly for Android) can be provided with simple importing `locale-data`, like
```
import 'intl/locale-data/jsonp/ru-RU'
```
=> Android: fix locale - set en-US

.eslintrc.js
`camelCase` and `no-throw-literal` are already covered by standard
=> Remove duplicated rules

src/modules/UI/components/Header/Component/WalletSelector.ui.js, src/modules/UI/components/Header/Component/WalletSelectorConnector.js
One contains the declarative static attributes of the Component and the other the dynamic state-bounded props.
This tiny bit of code removes somewhere in the ballpark of 50-100 unnecessary renders a sec to zero.
=> Separated WalletSelectorConnector into 2 files.

src/modules/UI/scenes/WalletList/style.js
Also only commented out the style because i'm not sure what it does, checked all the platforms and working fine.
=> Fix not scrolling of the wallet list when on iPhone X

src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js
* Previously, transaction details would be saved to the parent currency
* This change saves the transaction details in the currency of the
transaction
=> Fix saving transaction details

src/modules/UI/Settings/action.js, src/modules/UI/Settings/reducer.js
Settings reducer was not properly setting the isTouchIdEnabled and isTouchSupported booleans. This broke with the major login refactor.
Fix incorrect Flow type as isTouchEnabled is a boolean not Object/any
=> Fix missing touchId entry in Settings.

src/locales/en_US.js, src/modules/UI/scenes/AddToken/AddToken.ui.js, src/modules/UI/scenes/ManageTokens/ManageTokens.ui.js, src/modules/UI/scenes/ManageTokens/ManageTokensConnector.js
The purpose of this task is to show a newly added custom token as *enabled* (ie checkmark in the box of the ManageTokens scene) immediately after the custom token has been added successfully.
https://app.asana.com/0/361770107085503/521515139317756/f
=> Update new custom token enabled status upon successful addition

src/modules/Core/Wallets/api.js, src/modules/Core/selectors.js, src/modules/UI/Wallets/reducer.js, src/modules/UI/scenes/Request/Request.ui.js, src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js, src/modules/UI/scenes/WalletList/action.js, src/types.js
The core has a branch, `currency-wallet-flow`, that adds proper types for `AbcCurrencyWallet`. Merging that branch causes lots of errors in the GUI. This pull request fixes those.
=> Fix flow errors from core typing AbcCurrencyWallet

src/modules/UI/Wallets/reducer.js
Fixes crash upon relogin to same account since wallets may rapidly exist and then not-exist.
=> Only enable tokens on wallets that exist

src/modules/UI/Wallets/action.js
The purpose of this is to fix issue related to EditToken. It looks like the function for editing a token included parameters that were out of order (contractAddress and denomination). This should fix the issue.
Asana Task: https://app.asana.com/0/361770107085503/544304196013553/f
=> Fix EditToken parameter out of order issue

src/modules/UI/scenes/Settings/components/ConfirmPasswordModal.ui.js
Password was never stored in Redux, however the design of our modals allowed it to stay in local state even after the modal was closed. This fixes that.
=> Reset state of modal when submitting password for confirmation

src/modules/UI/components/FlipInput/CryptoExchangeFlipInputWrapperComponent.js, src/modules/UI/components/Header/Component/WalletNameHeader.ui.js, src/modules/UI/components/Header/Component/WalletSelectorConnector.js
Exchange scene drop down header doesn’t show token codes (https://app.asana.com/0/361770107085503/498144750192718/f)
=> Fix: show token code in exchange scene drop down header

package.json
Asana task: https://app.asana.com/0/361770107085503/520381260581210/f
I found that 
https://github.com/Airbitz/edge-react-gui/blob/c348927410c67b74832c69a35ce3530fd3628998/src/modules/Logs/action.js#L30
throws error on real device (Nexus 5) when "Remote JS debug" is disabled. With enabled debugging everything is working.  I assume it's related to https://github.com/zloirock/core-js/issues/368 . 
I would set `core-js` version strictly to `2.5.2` until it will be fixed on parent module.
=> Fix app freeze after doing sendLogs

src/modules/UI/scenes/CryptoExchange/CryptoExchangeConfirmTransactionModalComponent.js
The purpose of this task is to make the Exchange scene's confirmation slider a more appropriate width on tablets. I mimicked the width style that is used for the sendConfirmation scene.
Asana Task: https://app.asana.com/0/361770107085503/545202805762048/f
=> Center exchangeModal slider and reduce width

src/modules/UI/Settings/reducer.js, yarn.lock
https://app.asana.com/0/361770107085503/547828898227825
When logging in a new account, touchId information is not available. 
The gui attempts to load this into redux and crashes the login process.
This PR protects against that by using null checks.
=> Protect against incomplete login info

src/modules/UI/components/SafeAreaView/SafeAreaView.ui.js, src/theme/variables/airbitz.js
The purpose of this task is to take care of a bug in iOS version 10 where the header appeared smaller than normal. I believe this was due to a bug related to the system tray, or SafeAreaView.
Asana Task: https://app.asana.com/0/361770107085503/539228067649987/f
=> Fix iPad pro status bar / header issue on iOS 10

src/modules/UI/scenes/WalletList/components/WalletListRow/FullWalletListRow.ui.js
Asana task: https://app.asana.com/0/361770107085503/530358262723340/f
=> Fix Android flushing icons on loading wallets

src/connectors/components/HeaderMenuExchangeConnector.js, src/modules/UI/components/MenuDropDown/MenuDropDown.ui.js, src/modules/UI/scenes/ChangeMiningFee/ChangeMiningFee.ui.js, src/modules/UI/scenes/ChangeMiningFee/components/CustomFees/CustomFees.ui.js, src/modules/UI/scenes/ChangeMiningFee/components/CustomFees/CustomFeesModal.ui.js, src/modules/UI/scenes/ChangeMiningFee/components/CustomFees/CustomFeesModalConnector.js, src/modules/UI/scenes/SendConfirmation/SendConfirmationOptions.js, src/modules/UI/scenes/SendConfirmation/SendConfirmationOptionsConnector.js, yarn.lock
The purpose of this task is to base the custom mining fee type based on which scene it is coming from, since the exchange scene and sendConfirmation scenes both have source wallets. It will now look at selectedWallet from SendConfirmation scene and fromWallet for the cryptoExchange scene.
Asana Task: https://app.asana.com/0/361770107085503/498144750192722/f
=> Implement different version of passing sourceWallet to changeMiningFee

src/modules/UI/scenes/CreateWallet/CreateWalletSelectCrypto.ui.js, src/modules/UI/scenes/CreateWallet/CreateWalletSelectFiat.ui.js, src/modules/UI/scenes/CreateWallet/style.js
I made slight adjustments to the spacing for search results in the CreateWallet process in order to utilize space more efficiently.
Asana Task: none
=> Slight adjustments to layout on CreateWallet scenes to utilize space

src/modules/UI/scenes/CryptoExchange/CryptoExchangeSceneComponent.js, src/reducers/CryptoExchangeReducer.js
This resets the error messages in between each make spend, and makes sure there is a spinner showing while the app is thinking, and attempting a make spend. It provides necessary visual feedback and will not allow errors to remain
=> Add visual feedback for when new transactions are being attempted.

package.json, src/locales/en_US.js
Requires update to 0.8.0 of ethereum library which actually uses GWei as the gasPrice parameter
PR https://github.com/Airbitz/edge-currency-ethereum/pull/7 should first be reviewed, merged, and npm published before this PR is accepted. Otherwise we will get a build error due to missing npm version 0.8.0 of the ethereum library
=> Change string for custom gasPrice to be "Gas Price (GWei)"

src/modules/UI/Wallets/action.js
The purpose of this task is to limit the `SELECT_WALLET` action to only be fired off when the newly selected wallet is different from the currently selected wallet.
=> Make selectWallet only fire off if different from current wallet

src/modules/Main.ui.js, src/modules/MainConnector.js
updateCurrentSceneKey was incorrectly removed for TX_LIST so we were not marking the current scene when entering tx details. onTransactionsChanged -> refreshTransactionsRequest() was only enacting a change of the txlist if we were currently on the tx_list scene.
=> Fix failed refresh of txlist after editing tx details

src/modules/UI/scenes/Request/Request.ui.js
Fix crash due to sending a legacy LTC or BCH address into encodeUri() using the publicAddress parameter. encodeUri() expects legacy addresses to be passed in via the `legacyAddress` parameter or it throws Invalid Public Address error.
=> Fix legacy address crash

src/modules/UI/scenes/TransactionList/action.js
This PR fixes the issue where new transactions are appended to the bottom of the txList. They will now be put into their appropriate chronological order.
Asana Task: https://app.asana.com/0/361770107085503/587758195817684/f
=> Fix sorting issue when receiving new transaction

README.md
Where Xcode version is < 9, running `react-native run-ios` fails with the following:
```
ld: framework not found FileProvider for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Upgrading fixes this issue.
Add a requirement in the README to upgrade Xcode.
=> MacOS - Add Requirement to upgrade Xcode where version < 9

android/app/build.gradle, android/build.gradle, package.json, postinstall.sh, yarn.lock
Update JSC on android using jsc-android npm module
App launch gets about a 15% performance boost as mentioned in the jsc-android README. 
Launching app on Pixel 2, timings go from 3.75 to 3.2 seconds.
This will also enable upgrading to 64 bit once react-native-fast-crypto is upgraded to 64 bit since this version of JSC already includes 64 bit support.
=> Upgrade android JavascriptCore

src/modules/UI/Wallets/action.js
The purpose of this task is to restore the `upsertWallet` dispatch and call it to refresh a wallet once its `enabledTokens` have been loaded into redux. This also fixes the wallet rename not being processed until someone logs out then back in.
Asana Tasks: 
https://app.asana.com/0/361770107085503/615088050020510/f
https://app.asana.com/0/361770107085503/614531362120600/f
=> Revert deletion of upsertWallet dispatch

src/modules/UI/components/ExchangeRate/ExchangedExchangeRate.ui.js
In latest bitcoin plugin, BCH now uses 'cash' to denote the small denom of microbits
=> Check for 'cash' as denom name as well as 'bits'

src/modules/UI/Wallets/action.js, src/modules/UI/scenes/TransactionList/TransactionList.ui.js, src/reducers/permissions/actions.js
* Do not dispatch updatePermission if you already have it
* Optimize isSentTransaction to just check for "-" sign instead of doing full bignum math
* Do not call updateWalletEnableTokens if there are no tokens in wallet
=> Small performance optimizations

src/modules/UI/Wallets/action.js, src/modules/UI/Wallets/reducer.js
* Change throttling logic for refreshWallet to batch across all wallets, not per wallet since each dispatch causes a full revalidation of the redux state and rendering pipeline
* Change upsertWallet to allow multiple wallets to be upsert'ed in one call. Reduces the number of dispatches and re-renders.
=> Batch upsert for all wallets

src/constants/DropDownValueConstants.js
The purpose of this task is to get zCoin to show a "View XPub" option for the Wallet List options dropdown. The issue was that the currency code for the cryptocurrency was incorrect.
Asana Task: https://app.asana.com/0/361770107085503/669730821581731/f
=> Fix zCoin currencyCode for viewXPub dropdown

copy-core.sh, package.json, src/modules/Core/Wallets/api.js, src/modules/Core/selectors.js, yarn.lock
The `wallet.getBalance` change is a little worrying to me - I'm not sure how we *ever* got token balances, since the Ethereum plugin would ignore a string-type `options` parameter.
=> Upgrade to edge-core-js v0.9.3

src/modules/Login/action.js, src/modules/Main.ui.js
Ping util1.edge.app to check if current app installation was referred to by a specific referral link based on this device's IP. If referral link was for a specific currencyCode, then only create wallets for new accounts with that currency.
=> Add referral tracking

src/modules/UI/scenes/TransactionList/TransactionList.ui.js, src/modules/UI/scenes/TransactionList/components/TransactionRow.ui.js
The purpose of this task is to fix the missing fiat symbol on each row of the transaction list. It appears to have been lost via regression.
Asana Task: https://app.asana.com/0/361770107085503/705752231471101/f
=> Fix missing fiat symbol for txList

src/modules/UI/components/ControlPanel/Component/Main.js
The `Button` component was passing an event to the `logout` callback, which we were treating as a bogus username.
=> Fix logout to return to the PIN screen

src/locales/en_US.js, src/modules/Main.ui.js, src/modules/UI/scenes/Request/Request.ui.js, src/modules/UI/scenes/Request/RequestConnector.js, src/modules/UI/scenes/Request/components/XRPMinimumModal/XRPMinimumModal.ui.js
The purpose of this task is to show a warning for XRP wallets that lets the user know that they need to have a minimum of 20 XRP before they can get increased functionality. A few notes:
1.) The modal should show up on the Request scene
2.) The modal should only show up if XRP is the selected wallet and the balance is less than 20 XRP
3.) The modal should only be shown either a.) once per session
Asana Task: https://app.asana.com/0/361770107085503/711646399708941
=> Implement initial 20 XRP Minimum modal on Request scene

src/modules/Login/action.js, src/modules/UI/scenes/CreateWallet/CreateWalletName.ui.js
This leaves the currency name as "Ripple" so it can easily be searched when creating a new wallet
=> Quick hack to name XRP/Ripple wallets "My XRP"

src/locales/intl.js, src/locales/intl.test.js
Accept either comma or period as decimal separator and simply convert it to the current locale decimal separator no matter what. Fixes inability to enter a decimal when region doesn't match language.
=> Fix mixup of comma vs period when entering decimal in FlipInput

package.json, src/modules/UI/scenes/Request/Request.ui.js, src/modules/UI/scenes/Request/RequestConnector.js, yarn.lock
With new update to Monero library, getReceiveAddress may return a blank string when wallet is first created. This change is required to fully fix issues with users' accounts not getting indexed by MyMonero service in time to receive early transactions.
* Bump Monero library
* Make sure to catch error in encodeUri due to invalid public address
* If Request scene detects an invalid address, wait 2 seconds and then refresh the public address
=> Wait for address before displaying to user in Request scene

src/constants/WalletAndCurrencyConstants.js
The purpose of this task is to remove the Isle of Man Pound (IMP) currency from the list of fiats because it does not have any exchange rate.
Asana Task: https://app.asana.com/0/361770107085503/718202392108831
=> Removal of IMP currency (no exchange rate)

src/modules/Core/Account/settings.js, src/reducers/passwordReminder/passwordReminderReducer.js, src/reducers/passwordReminder/passwordReminderReducer.test.js
Some user's have been complaining that the reminders are too frequent even after they've entered the password a couple times. This backs it off by double.
=> Change password reminder stepoff to 4x vs 2x

src/constants/WalletAndCurrencyConstants.js, src/modules/UI/scenes/AddToken/AddToken.ui.js, src/modules/UI/scenes/EditToken/EditToken.ui.js
The purpose of this task is to allow the users to assign a 6-digit (previous 5-digit) currencyCode to custom tokens.
Asana Task: https://app.asana.com/0/361770107085503/735637907328392/f
=> Adjust 5-character currencyCode limit to 6

package.json, yarn.lock
The purpose of this task is to update the Monero plugin in order to hide the `NoAmountSpecifiedError`
Asana Task: https://app.asana.com/0/361770107085503/736453047132716/f
=> Bump Monero to proper version to hide NoAmountSpecifiedError

src/modules/UI/scenes/TransactionList/TransactionList.ui.js
The purpose of this task is to get the TransactionList to load transactions upon first entry. The transactions were not being called because `handleScrollEnd` was not being called by the `FlatList` component because no list was being rendered (aka you can't be at the end of the list if there is no list), and instead the `ListEmptyComponent` was being rendered initially, and there isn't really an end to that component per se because it is a normal component and not a list.
Fix was to force the GUI to fetch transactions upon `componentDidMount`
Asana Task: https://app.asana.com/0/361770107085503/759658666093565/f
=> Force txList to attempt to load transactions upon component mounting

src/modules/UI/scenes/Scan/reducers/scanEnabled.js
The purpose of this task is to re-enable scanning functionality after a user presses "Cancel" on the Sweep Private Key modal window. Before the scan scene would no longer scan anything after you pressed the "Cancel" button, which is not the desired behavior.
Asana Task: https://app.asana.com/0/361770107085503/716460273877813/f
=> Fix Sweep Private Key 'Cancel' not re-enabling scan

src/modules/UI/Wallets/reducer.js
Check for a cleared redux state before dereferencing state properties.
Fixes the occasional `undefined is not an object e[a.id].receiveAddress` error popup after logout.
=> Fix logout error popup

src/modules/UI/scenes/WalletList/style.js
The purpose of this task is to fix the positioning of the Bitcoin symbol on the WalletList (right side), which was positioned too high within the parentheses.
Asana Task: https://app.asana.com/0/361770107085503/772821084680783/f
=> Slight adjustment to positioning of Bitcoin currency symbol in WalletList

package.json, yarn.lock
When fetching an address, this defaults to the legacyAddress, falling
back to the publicAddress if no legacyAddress exists. This was necessary
to support LTC because simplex doesn't support M addresses.
=> Bump simplex plugin to latest version

src/modules/UI/scenes/SendConfirmation/SendConfirmation.ui.js, src/modules/UI/scenes/SendConfirmation/styles.js
The purpose of this task is to keep the ABSlider on the SendConfirmation scene static regardless of whether or not the ActivityIndicator is visible or not.
Asana Task: https://app.asana.com/0/361770107085503/774878206641550/f
=> Adjust SendConf styling to keep ABSlider position static

src/modules/UI/scenes/TransactionsExport/TransactionsExportSceneComponent.js
This adds a date time stamp to the end of the file name for QBO exports. It is necessary because if you change the file but the file name is the same, Quickbooks web just uses the data from the last import with the same file name.
Asana: https://app.asana.com/0/361770107085503/772821084680777
=> Added datestamp to file names for QBO

src/modules/UI/scenes/ChangePinPassword/ChangePasswordComponent.ui.js, src/modules/UI/scenes/PasswordRecovery/PasswordRecoveryComponent.ui.js, src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js
The purpose of this task is to give smaller devices more room on the Change Password, Password Recovery, and Transaction Details scenes to make sure that the keyboard does not cover the 'DONE' button(s)
Asana Task: https://app.asana.com/0/361770107085503/778189856161368/f
Asana Task: https://app.asana.com/0/361770107085503/778189856161365/f
=> Give extra room for ChangePassword + Password Recovery 'DONE' button

src/modules/Main.ui.js, src/modules/style.js
The purpose of this task is to re-style the navBar title on Android to be centered again. The recent upgrade to RN55 included upgrades of react-native-router-flux and react-navigation, which interrupted some styles for the navBar.
Asana Task: https://app.asana.com/0/361770107085503/796290981203649/f
=> Re-center navBar title area (header) after router upgrade (Android)

src/modules/UI/scenes/WalletList/components/WalletListRow/FullWalletListRow.ui.js
The purpose of this task is to fix the alignment of the crypto icons on the Wallet List, which appear to have been displaced either via regression or React Native upgrade.
Asana Task: https://app.asana.com/0/361770107085503/799828850647961/f
=> Fix vertical alignment of Wallet List icons

src/modules/UI/scenes/PasswordRecovery/PasswordRecoveryComponent.ui.js, src/modules/UI/scenes/Settings/__snapshots__/settingsOverview.test.js.snap, src/modules/UI/scenes/Settings/style.js, src/modules/UI/scenes/SpendingLimits/styles.js
The purpose of this task is to fix the footer background colors on a couple of the settings scenes (Password Recovery, Change Password, and Spending Limits). This bug appears to be a regression from the earlier task of adding extra space at the bottom of a few of the scenes so that the keyboard didn't cover the Save / Submit buttons.
Asana Task: https://app.asana.com/0/361770107085503/801891347444366/f
=> Fix Settings Scenes Background Colors

src/modules/Main.ui.js
The purpose of this task is to make sure that the "Create Wallet" scenes show the correct 'Back' button syntax.
Asana Task: https://app.asana.com/0/361770107085503/795095712879313/f
=> Change CreateWalletSelectCrypto back button to say 'Back'

src/modules/UI/Settings/reducer.js
Do not return a new object if settingsLegacy() or spendingLimits() functions do not change any state.
This prevents routines that pass `state.settings` through `mapStateToProps` from re-rendering
=> Optimize settings reducer

src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js
The purpose of this task is to properly handle numbers with commas as decimals (international) within the fiat input in the txDetails scene.
Asana Task: https://app.asana.com/0/361770107085503/588715697078159/f
=> Allow internationalized fiat amounts for txDetails (comma as decimal)

src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js
The purpose of this task is to refine an earlier PR by reverting the saved `amountFiat` on the txDetails scene to the previously correct amount if the input is invalid.
Asana Task: https://app.asana.com/0/361770107085503/588715697078159/f
=> Revert txDetails amountFiat to previous good state if invalid (NaN)

src/modules/UI/scenes/Otp/OtpSettingsSceneComponent.js
Fixes Asana task 
2FA - The button shows as "Disable 2FA" whether it is enabled or not. For example a brand new account shows as Disable instead of Enable
https://app.asana.com/0/361770107085503/814581022784612
=> fix 2FA button status where button was always disabled

src/modules/UI/scenes/SendConfirmation/SendConfirmation.ui.js, src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmation.test.js.snap
The purpose of this task is to fix the text being cut off on the Payment ID button on the Send Confirmation scene.
Asana Task: https://app.asana.com/0/361770107085503/812701187673600/f
=> Fix Payment ID text Cutoff on SendConfirmation

src/modules/UI/scenes/Request/Request.ui.js
The purpose of this task is to ensure that the 20 XRP minimum is displayed on first access to an XRP wallet at the Request scene. It seems it was displaying on 2nd entrance to Request scene beforehand.
Asana Task: https://app.asana.com/0/361770107085503/816034397889780/f
=> Fix 20 XRP modal not showing up on first entry to Request

src/modules/UI/scenes/Request/Request.ui.js, src/modules/UI/scenes/Request/RequestConnector.js, src/modules/UI/scenes/Request/__snapshots__/Request.test.js.snap
The purpose of this task is to show the public address immediately on the Request scene, making sure that the QR code generation does not delay the public address displaying. Once the new / real QR code has been generated then the QR barcode display will re-render.
Asana Task: https://app.asana.com/0/361770107085503/817257728515162/f
=> Fix Public Address Not Showing Immediately in Request Scene

src/modules/UI/scenes/Request/Request.ui.js
The purpose of this task is to fix the issue of the 20 XRP minimum modal not showing because the Request scene starts off with a `publicAddress` now rather than having it produced later in the React lifecycle.
Asana Task: https://app.asana.com/0/361770107085503/816034397889780/f
=> Fix XRP 20 modal regression

src/locales/en_US.js, src/locales/strings/enUS.json, src/modules/UI/scenes/EdgeLogin/EdgeLoginSceneComponent.js, src/styles/scenes/EdgeLoginSceneStyle.js
This pr adds a warning for edge login if an app does not pass an app id.
It fixes Asana task 
Edge Login: Add warning if user is logging into full access app
https://app.asana.com/0/361770107085503/770492945216288
=> added warning message to edge login if there is no appId

src/modules/UI/scenes/SendConfirmation/SendConfirmation.ui.js, src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmation.test.js.snap, src/modules/UI/scenes/SendConfirmation/styles.js
The purpose of this task is to remove the background color of the Unique Identifier (Payment ID) on the Send Confirmation scene.
Asana Task: https://app.asana.com/0/361770107085503/812701187673600/f
=> Make unique ID button transparent (SendConf)

src/modules/UI/components/HelpModal/HelpModal.ui.js, src/modules/UI/components/HelpModal/style.js
The purpose of this task is to prevent the width of the Help Modal from being too wide for the screen (as a result of device rotation).
Asana Task: https://app.asana.com/0/361770107085503/814809403791483/f
=> Fix HelpModal iPad Pro width issue

src/modules/UI/components/Header/Component/BackButton.ui.js, src/modules/UI/components/Header/style.js
The purpose of this task is to make it easier for users on Android to be able to press the back button in the top-left part of the screen (navbar).
Asana Task: https://app.asana.com/0/361770107085503/821244593415412/f
=> Make back arrow easier to press on Android

src/lib/configureStore.js
The purpose of this task is to explicitly define the number of actions show in the React Native Debugger so that the `maxAge` parameter can be modified according to a developer's needs.
There is no associated Asana task for this.
=> Set parameter for number of Redux actions to show in RN Debugger

src/locales/en_US.js, src/locales/strings/enUS.json, src/modules/UI/scenes/SendConfirmation/SendConfirmation.ui.js, src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmation.test.js.snap
There is a hard-coded "Balance: " string on the Send Confirmation scene. It needs to be removed and localized.
Asana Task: https://app.asana.com/0/361770107085503/843358520454250/f
=> Remove hard-coded string

src/modules/UI/components/WalletListModal/WalletListModal.ui.js
The purpose of this task is to ensure that the WalletList dropdown stretches all of the way down to the footer.
Asana Task: https://app.asana.com/0/361770107085503/716460273877812/f
=> Fix improper walletList dropdown height

src/modules/UI/scenes/TransactionList/TransactionList.ui.js
Convert key from number to string to prevent RN redbox error
=> Add keyExtractor to fix React error that FlatList key is not a string

src/modules/Core/Account/callbacks.js
Kevin might have a more elegant fix for this with `EdgeAccount.watch('currencyWallets', () => {})`, but this is the quick & dirty version.
=> Work around missing wallets problem

package.json, yarn.lock
* Implements eboost
* Removes parsing of xpriv and mnemonic seed for sweeping (was not tested thoroughly)
* Update Digibyte P2SH address format
* Fix currency names "Bitcoin Cash" "Bitcoin Gold" "Digibyte"
* Properly implement `changeSettings`
=> Bump bitcoin version

src/locales/en_US.js, src/locales/strings/enUS.json
The purpose of this task is to remove the 'And Directory' part of the helpModal title so that it only reads "Crypto Wallet".
Asana Task: https://app.asana.com/0/361770107085503/553467619718329/f
=> Remove 'and Directory' from helpModal title

src/modules/UI/scenes/Request/Request.ui.js
The purpose of this task is to move the QR code generation of the request scene from the constructor to `componentDidMount`
Asana Task: https://app.asana.com/0/361770107085503/830239350791970/f
=> Fix request side effect / constructor issue

src/locales/en_US.js, src/locales/strings/enUS.json
The purpose of this task is to fix the typo where the wallet name for "Bitcoin Cash" shows "BitcoinCash"
Asana Task: https://app.asana.com/0/361770107085503/847674127060668/f
=> Fix 'My BitcoinCash' Wallet Name

src/modules/UI/scenes/TransactionList/TransactionList.ui.js
The purpose of this task is to fix the font size differential issue on the Transaction List's balance box.
Asana Task: https://app.asana.com/0/361770107085503/858601807863699/f
=> Fix txList balance fontSize issue

src/modules/UI/scenes/Settings/style.js
The purpose of this task is to re-add the currencySettings title style that was accidentally removed during a recent PR / commit.
Asana Task: https://app.asana.com/0/361770107085503/868855858279049/f
=> Fix currencySettings header style (regression)

src/modules/Main.ui.js, src/modules/MainConnector.js, src/modules/UI/scenes/Settings/SettingsOverview.ui.js, src/modules/UI/scenes/Settings/SettingsOverviewConnector.js, src/modules/UI/scenes/Settings/action.js
The purpose of this task is three-fold:
* Bind "Disable 2FA" to immediately disable 2FA rather than just keep OTP reset in place
* Move modal reminder to *every* entrance of Settings Overview scene
* Make modal backdrop press keep OTP / 2FA unchanged
Asana Task: https://app.asana.com/0/361770107085503/848466472814189/f
=> Allow immediate OTP disable, move reminder to Settings onEnter, onBackDropPress No Change

src/modules/UI/components/MenuDropDown/MenuDropDown.test.js, src/modules/UI/components/MenuDropDown/MenuDropDown.ui.js, src/modules/UI/components/MenuDropDown/__snapshots__/MenuDropDown.test.js.snap, src/modules/UI/scenes/WalletList/components/WalletListRow/WalletListRowOptions.ui.js
The purpose of this task is to re-implement the menu dropdown icons (three dots) on the wallet list. I have also added a snapshot to help defend against future regressions.
Asana Task: https://app.asana.com/0/361770107085503/871467099103199/f
=> Fix wallet list menu dropdown and implement snapshot

src/modules/Core/Account/accountReducer.test.js, src/modules/Core/Account/reducer.js, src/modules/Login/action.js, src/modules/UI/Settings/reducer.js
This fixes issue of not having denominations ready in time for rendering certain scenes which need it. This also removes the need to have default denominations for currencies that will just use the primary denomination of the currency.
=> Populate default denominations from currency plugins

src/modules/UI/scenes/CryptoExchange/CryptoExchangeSceneComponent.js
The purpose of this task is to ensure that the keyboard gets dismissed once the user presses the 'Next' button on the new exchange scene.
Asana Task: https://app.asana.com/0/361770107085503/868855858279041/f
=> Force keyboard dismiss upon exchange quote 'Next' button press

src/modules/UI/scenes/TransactionList/TransactionList.ui.js
Also fix bug where Buy Crypto card shows for token wallets but mentions Ether. renderBuyCrypto was looking at the guiWallet currencyCode and not the selectedCurrencyCode
=> Add Buy Crypto card for XRP

src/actions/CryptoExchangeActions.js, src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js
Crash only occurs if shapeshift transaction was done on non-english phone. The "exchange:" part of the category was being translated when it is being used as a key to lookup into translations.
Fixed exchange scene to use "exchange:" as the category string always
Fixed TransactionDetails to handle an invalid category and fallback
=> Fix crash when entering txDetails from shapeshift transaction

src/lib/scaling.js, src/modules/UI/components/MenuDropDown/__snapshots__/MenuDropDown.test.js.snap, src/modules/UI/components/QRCode/__snapshots__/QRCode.test.js.snap, src/modules/UI/components/WalletListRow/WalletListRow.ui.js, src/modules/UI/scenes/ChangeMiningFee/__snapshots__/ChangeMiningFee.test.js.snap, src/modules/UI/scenes/OnBoarding/__snapshots__/OnBoardingComponent.test.js.snap, src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmation.test.js.snap, src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmationOptions.test.js.snap, src/modules/UI/scenes/Settings/__snapshots__/CurrencySettings.ui.test.js.snap, src/modules/UI/scenes/Settings/__snapshots__/settingsOverview.test.js.snap, src/modules/UI/scenes/TransactionDetails/__snapshots__/TransactionDetails.ui.test.js.snap, src/modules/UI/scenes/TransactionList/components/TransactionRow.test.js, src/modules/UI/scenes/TransactionList/components/TransactionRow.ui.js, src/modules/UI/scenes/TransactionList/components/__snapshots__/TransactionRow.test.js.snap, src/modules/UI/scenes/TransactionList/style.js, src/modules/UI/scenes/WalletList/components/WalletListRow/FullWalletListRow.ui.js, src/modules/UI/scenes/WalletList/components/WalletListRow/WalletListRowOptions.ui.js, src/modules/UI/scenes/WalletList/components/WalletListRow/WalletListTokenRow.ui.js, src/modules/UI/scenes/WalletList/style.js
* Change global scaling from .4 to .3
* Increase height of wallet list and transaction row
* Use same walletlist row component and style for iOS and Android
* Make transaction name and wallet name 2 rows if needed
* Add auto text sizing for iOS for Wallet name
* Decrease padding/margin to right of 3 dot options icon on wallet list
* Shrink height of date in tx list
* Make the wallet list token row formatted with the same alignment as regular wallets so that names and amounts line up
=> Fine tune various scaling parameters and styles

src/modules/UI/scenes/Settings/CurrencySettings.ui.js, src/modules/UI/scenes/Settings/__snapshots__/CurrencySettings.ui.test.js.snap
The purpose of this task is to prevent the currencySettings from crashing on Android for currencies that do **not** have custom nodes ability.
Asana Task: https://app.asana.com/0/361770107085503/868855858279050/f
=> Fix currencySettings Android crash

src/styles/scenes/CryptoExchangeSceneStyles.js
The purpose of this task is to prevent the "Next" / "Siguiente" button on the exchange scene from cutting off text
Asana Task: https://app.asana.com/0/361770107085503/875186582391430/f
=> Prevent 'Siguiente' button from cutting off text (Exchange Scene)

src/locales/intl.js, src/locales/intl.test.js, src/modules/UI/scenes/TransactionDetails/TransactionDetails.ui.js, src/modules/UI/scenes/TransactionDetails/__snapshots__/TransactionDetails.ui.test.js.snap
Do not add grouping separator when internationalizing fiat amount string. Parser when saving txdetails would think the group separator was a decimal separator and truncate the number.
=> Fix txDetails fiat amount thrown off by 1000

src/modules/UI/scenes/Scan/components/AddressInput.js, src/modules/UI/scenes/Scan/components/AddressInputButtons.js, src/modules/UI/scenes/Scan/components/AddressModal.js
The purpose of this task is to make sure the buttons on the addressModal (Scan scene) do not get covered by the keyboard on small iOS devices.
Asana Task: https://app.asana.com/0/361770107085503/874227037418031/f
=> Adjust addressModal style on small devices

src/modules/UI/components/MenuDropDown/__snapshots__/MenuDropDown.test.js.snap, src/modules/UI/scenes/SendConfirmation/__snapshots__/sendConfirmationOptions.test.js.snap, src/modules/UI/scenes/WalletList/components/WalletListRow/WalletListRowOptions.ui.js, src/styles/components/HeaderMenuDropDownStyles.js
The purpose of this task is to fix the wallet dropdown menu (and header dropdown) again. It appears the fix was reverted from the `develop` branch at some point.
Asana Task: https://app.asana.com/0/361770107085503/889507941391832/f
=> Fix menu dropdown width *again*

src/components/scenes/DefaultFiatSettingScene.js
Task: Settings Default Currency - The Underline in Select a currency needs to be longer
=> Settings - Default Fiat: Extend form width to 100%

src/actions/CryptoExchangeActions.js, src/locales/en_US.js, src/locales/strings/enUS.json
• added 3 or 15 second timer for getting exchange tokens.• added catch at beginning of function to harden against leaving scene
• tested by console logging when function is fired if it is we are no longer in exchange scene
• router considers opening side menu as leaving the scene
• no logout issues
fix Asana :
Exchange - refresh list of supported currencies every 15 seconds
https://app.asana.com/0/361770107085503/886135611556824
Exchange - Show "Loading supported currencies"
https://app.asana.com/0/361770107085503/886135611556826
=> Fix checking for supported tokens with slow networks PR2

src/modules/UI/components/ExchangeQuote/ExchangeQuoteComponent.js, src/styles/scenes/CryptoExchangeQuoteSceneStyles.js
The purpose of this task is to prevent long wallet names from overflowing to a 2nd line in the crypto exchange quote scene.
Asana Task: https://app.asana.com/0/361770107085503/883037346365188/f
=> Limit cryptoExchange wallet names to one line

src/__tests__/__snapshots__/sendConfirmation.test.js.snap, src/components/scenes/SendConfirmationScene.js, src/locales/en_US.js, src/locales/strings/enUS.json, src/modules/UI/components/Slider/Slider.ui.js, src/modules/UI/components/Slider/styles.js
https://app.asana.com/0/361770107085503/905291401659450/f
Disable slider on SendConfirmation until ready (fee returned and valid amount entered), Show activity indicator while waiting on fee return.
This prevents the user from attempting to send a transaction before makeSpend returns the fee and other info. You should see a grayed our slider button and "Enter an Amount" until you enter an amount, at which point a spinner will show until the fee info is loaded and the slider enables.
=> Disable slider on SendConfirmation until ready to send

src/components/common/TransactionDetailAmountArea.js, src/components/scenes/TransactionListScene.js
… as the amount so it will be vertically centered
Task: Transaction List - amount isn't vertically centered with currency symbol
Note: Why do we need to have a separate font for the currency symbol? Check first before merging
=> Transaction List/Details screen: change the amount font same as the currency symbol

package.json, src/actions/CryptoExchangeActions.js, src/connectors/components/SwapKYCModalConnector.js, src/locales/en_US.js, src/locales/strings/enUS.json, yarn.lock
* Bump edge-core-js to 0.12.18 which properly throws geoRestriction and noVerification errors
* Fix misspelling of 'shapeshift' as a plugin key. Fixes crash
* Change strings displayed due to noVerification and geoRestriction errors
=> Fix detection and display of ShapeShift errors

src/modules/Core/Wallets/EdgeWalletCallbackManager.js
The purpose of this task is to re-enable the Transaction Alert dropdown that is supposed to show from the top edge of the screen when a new transaction is received.
Asana Task: https://app.asana.com/0/361770107085503/924842927723660
=> Re-Enable transactionAlert Dropdown

src/components/scenes/SendConfirmationScene.js
The purpose of this task is to fix the calculation of the Send Confirmation network fee to take exchange denomination vs display denomination (default crypto denom from user settings) into consideration.
Asana Task: https://app.asana.com/0/361770107085503/919742673029010/f
=> Fix fee denomination + amount for SendConf

src/styles/scenes/TransactionListStyle.js
Task: Monero is cut off on iOS/Android 
=> Transaction List: Remove fixed height on transaction denomination and value row to not cut off monero denomination icon

src/actions/SendConfirmationActions.js, src/locales/en_US.js, src/locales/strings/enUS.json
Task: Visual text - Add a period at the end of the fail transaction popup
=> Add period on transaction popup failure message

src/actions/CryptoExchangeActions.js, src/locales/en_US.js, src/locales/strings/enUS.json
fixes : Asana 
Swap - Show address sent to swap partners
https://app.asana.com/0/361770107085503/879668277792914
ChangeNow - Exchange transaction does not tag ChangeNow in the transactions history screen
https://app.asana.com/0/361770107085503/944350842551518
ChangeNow - Inside the Notes of an exchange transaction does not show contact ChangeNow support email
https://app.asana.com/0/361770107085503/944694185807966
=> adjustwed swap metadata to use sawp info and have destination address

src/constants/DropDownValueConstants.js
The purpose of this task is to make the "XPub" Wallet List Option show up for E-Boost and Bitcoin Cash SV
Asana Task: https://app.asana.com/0/361770107085503/944776949971559/f
=> Add BSV and EBST to list of XPUB currencies

src/actions/SendConfirmationActions.js
fix 
Asana 
Tapping Send shows the previously seen transaction instead of bringing up the camera
https://app.asana.com/0/361770107085503/946310230497918
=> fix transaction detail stack issue

src/modules/UI/scenes/SendConfirmation/selectors.js, src/reducers/scenes/SendConfirmationReducer.js
Fix `otherParams` issue for BIP 70
=> Adjust getSpendInfo to consider otherParams

src/__tests__/__snapshots__/TransactionDetails.ui.test.js.snap, src/components/scenes/TransactionDetailsScene.js, src/modules/UI/components/PayeeIcon/style.js, src/styles/scenes/TransactionDetailsStyle.js
Task: Transaction details - Arrow icon is cut off - iOS only
=> Refactor payee icon on transaction details

src/__tests__/scenesReducer.test.js, src/__tests__/transactionListReducer.test.js, src/actions/TransactionListActions.js, src/reducers/scenes/TransactionListReducer.js
Also make sure we get all transactions by setting startEntries to undefined if we are at the end of the tx list and trying to get all remaining transactions.
=> Fix duplicate transactions from core by holding a txid map

src/util/makeContext.js
If running the core in a WebView will cause regressions, this pull request should surface those.
Most things work at this point, but spending Bitcoin-ish currencies produces an error due to bcoin objects leaking out of the plugin.
=> Run the core over a local bridge

src/actions/SettingsActions.js, src/components/modals/AutoLogoutModal.ui.js
Issues here: https://github.com/oblador/react-native-vector-icons/issues/823
Task: Auto Logoff in Settings - Icon replaced with ?
Send Logs in Settings - Icon replaced with ?
=> Remove outline icons of Ionicons

android/app/src/main/AndroidManifest.xml, ios/edge/Info.plist, src/__tests__/utils.test.js, src/util/utils.js
Support airbitz-ret, airbitz, edge, and edge-ret
Allows for broad support of edge login URIs
=> Add support for deeping link more edge related URIs

src/components/scenes/RequestScene.js
Fixes: Asana Android Request Email Share Address - Shows the file location of the device
https://app.asana.com/0/361770107085503/914173440500616
=> url to be blank for Android shares

src/components/scenes/ChangeMiningFeeScene.js, src/connectors/scenes/ChangeMiningFeeSendConfirmationConnector.ui.js
Asana task: Send - XMR/XRP/XLM custom mining fee modal is empty
https://app.asana.com/0/361770107085503/909519185512813
Should have been titled, do not show option for custom fees on those currencies. 
=> remove custom mining fee from some currencies

src/components/common/TransactionRow.js, src/modules/UI/components/ContactsLoader/ContactsLoader.ui.js
Add exchange provider names and icons to contact list so they get matched with pretagged transactions and then show icons on the tx list and details.
=> Add icons for exchange providers

src/__tests__/__snapshots__/sendConfirmation.test.js.snap, src/components/modals/UniqueIdentifierModal.js, src/components/scenes/SendConfirmationScene.js
Add check of what keyboard type on currency code, currently monero has the full keyboard
Task: Enable full keyboard when entering payment id Monero
=> Add keyboardType props on payment Id modal

src/modules/Login/action.js
Fixes saving of denoms for any currencies other than BTC, BCH, and ETH.
=> Update all denominationKeys

src/components/modals/KYCAlertModal.js
Fixes both ASANA: 
URGENT: Swap crashes accepting KYC modal 
https://app.asana.com/0/361770107085503/964023458287410
KYC Swap modal. Can't tap any links at bottom
https://app.asana.com/0/361770107085503/964023458287412
=> fix prop names in object causing crash

.flowconfig, package.json, yarn.lock
Upgrade react-native-camera to forked Edge version which limits scan preview size to 720p
=> Fix slow QR scanning speed on Android

src/connectors/scenes/ChangeMiningFeeSendConfirmationConnector.ui.js, src/constants/indexConstants.js
Re-fixing Send - XMR/XRP/XLM custom mining fee modal is empty
https://app.asana.com/0/361770107085503/909519185512813
Was broken by EOS implementation. changes. 
=> fix no custom fees for specific currencies

src/components/scenes/CreateWalletAccountSelectScene.js
The purpose of this task is to prevent a crash by disabling the "Continue" button during EOS wallet creation when the wallet has been created *but* the price quote has not yet been received.
Asana Task: https://app.asana.com/0/361770107085503/968867613128367/f
=> Fix EOS wallet creation crash (sendConf)

src/actions/CryptoExchangeActions.js, src/constants/indexConstants.js
Account based currencies will an throw error if user tries to spend to themselves. With the exchange scene, this is exactly what's done since the exchanger grabs an address from the same wallet for getMaxSpendable.
Fix by adding dummy addresses to specialCurrencyInfo for these currencies
=> Fix broken exchange max for accountbased currencies

src/components/Main.ui.js, src/locales/en_US.js, src/locales/strings/enUS.json
The purpose of this task is to ensure that the plugins route back to the GUI correctly, specifically so that the "Spend" plugins (ie BitRefill) do not route back to the "Buy and Sell" plugins scene.
Asana Task: https://app.asana.com/0/361770107085503/979724374279429/f
=> Fix issue with plugin routing back to GUI

src/components/common/TransactionRow.js, src/modules/Core/Wallets/api.js
The `merchant` field doesn't contain they payee name in the current implementation. Always use the domain name instead to avoid crashes.
=> Fix payment protocol destination detection

src/components/scenes/TransactionListScene.js
Task: If DGB has a dust balance that is on the negative 5th decimal place or 0.00001 then it will show a negative balance $-5.37 in this case
Note: The function intl.formatNumber() seems to be having error when processing numbers below 0.000001. Fix only the display and not the function itself. Best fix on the bug is that someone qualified should refactor intl.formatNumber to consider very small numbers.
=> Transaction list: Fiat Balance below 1e-6 is will be displayed as 0

src/modules/UI/components/WiredProgressBar/WiredProgressBar.ui.js
Task: Add green loading bar to Tx list
=> Don't show loading bar when the transactions are already loaded

src/modules/UI/components/SearchResults/SearchResults.ui.js
This is to prevent situations where the search results dropdowns result in the last item being covered by the footer.
Asana: https://app.asana.com/0/361770107085503/918691428554538/f
=> Add footer as padding for SearchResults

src/modules/Login/action.js
Likely an error with one of my recent commits. Iterating over an object, not an array.
=> Fix object iteration during initializeAccount

src/modules/Login/action.js
The purpose of this task is to fix the initializeAccount method to **not** execute the `catch` clause if there is no settings.json file, which was causing a "cannot find property ____ of undefined" error.
Asana Task: https://app.asana.com/0/361770107085503/1108083253570323/f
=> Better initializeAccount error-handling and prevent prop of undefined error

src/__tests__/createWalletReducer.test.js, src/__tests__/scenesReducer.test.js, src/actions/CreateWalletActions.js, src/actions/WalletActions.js, src/components/common/FullWalletListRow.js, src/components/scenes/CreateWalletAccountSelectScene.js, src/connectors/scenes/CreateWalletAccountSelectConnector.js, src/modules/Action.js, src/reducers/scenes/CreateWalletReducer.js
The purpose of this task is to get the EOS activation quote fetch network timeout duration reduced and properly handle the case in the UI (ie convey the issue to user and let them re-pick a wallet).
Asana Task: https://app.asana.com/0/361770107085503/1107900607511580/f
=> Handle EOS account payment timeouts better

src/modules/Login/action.js
The purpose of this task is to fix the mergeSettings implementation that is causing the yellow warnings for some accounts.
Asana Task: https://app.asana.com/0/361770107085503/1108475655773047/f
=> Fix mergeSettings implementation (remove yellow warnings)

src/components/scenes/CreateWalletAccountSetupScene.js
This task is to fix a bug on Android where a string literal being evaluated within JSX (but not within a <Text> tag) was causing a crash. 
Asana Task: https://app.asana.com/0/361770107085503/1107487776558543/f
=> Fix Android EOS crash, variable not boolean

src/actions/CreateWalletActions.js
The purpose of this task is to fix the crash that happens during logout after completing an EOS activation payment. This was due to the scene not being unmounted after a successful payment.
Asana Task: https://app.asana.com/0/361770107085503/1107487776558543/f
=> Fix EOS crash on logout

src/actions/WalletActions.js
Refresh all wallet addresses if we enter an EOS wallet that is not activated. This makes sure we call getReceiveAddress on all wallets to refresh their addresses so at least the following time we enter the wallet, we'll have up to date addresses which we use to detect activation.
=> Fix EOS activation not detected

src/modules/Core/Account/settings.js, src/modules/Settings/selectors.js
The purpose of this task is to fix the non-persistence of defaultFiat setting
Asana Task: https://app.asana.com/0/361770107085503/1108902637749922/f
=> Get both defaultFiat and isoDefaultFiat to both change on settings change

src/__tests__/Request.test.js, src/__tests__/Scan.ui.test.js, src/components/scenes/CryptoExchangeScene.js, src/components/scenes/RequestScene.js, src/components/scenes/ScanScene.js, src/connectors/scenes/RequestConnector.js, src/connectors/scenes/ScanConnector.js
The purpose of this task is to omit unactivated wallets (EOS) from dropdowns for requesting and sending.
Asana Task: https://app.asana.com/0/361770107085503/1108931850293728/f
=> Remove unactivated EOS from WalletListModal

src/components/scenes/TransactionListScene.js
The purpose of this task is to fix the cut-off occurring on Android at the bottom of the txList.
Asana Task: https://app.asana.com/0/361770107085503/1110495445154459/f
=> Include blank txList footer on Android

postinstall.sh
This will give the core enough time to create a context before the plugins start to load and consume the webview thread.
=> Defer plugin loading for 200ms for performance

src/actions/TransactionListActions.js
* Set lastUnfilteredIndex to 0 if we have no transactions to prevent throw
=> Fix transaction list infinite spinner on empty wallets

src/__tests__/__snapshots__/cryptoExchangeReducer.test.js.snap, src/components/scenes/CryptoExchangeScene.js, src/connectors/scenes/CryptoExchangeSceneConnector.js, src/reducers/CryptoExchangeReducer.js
Fixes P): Wallet Selector (exchange screen) - If a create wallet fails, the wallet selector button gets stuck spinning indefinitely
https://app.asana.com/0/361770107085503/1111016622465604
=> fix wallet spinner. tie to redux.

src/actions/SendConfirmationActions.js, src/components/scenes/SendConfirmationScene.js
The purpose of this task is to fix the transaction error that occurs while paying for EOS activation. The fix was to fix a regression by passing the `props` (not `state`) version of `nativeAmount` to the `signBroadcastAndSave` action. We are able to keep `exchangeAmount` as-is because it is only used for updating the displayed fiat amount on SendConfirmation (which the app should route away from on success, anyway).
Asana Task: https://app.asana.com/0/361770107085503/1111288373353711/f
=> Fix EOS nativeAmount tx error

src/__tests__/__snapshots__/sendConfirmation.test.js.snap, src/actions/SendConfirmationActions.js, src/components/scenes/PluginViewScene.js, src/components/scenes/SendConfirmationScene.js, src/connectors/scenes/SendConfirmationConnector.js, src/modules/UI/scenes/SendConfirmation/selectors.js
The purpose of this task is to fix the Send Confirmation bug whereby the order of makeSpend's requested differ from the order of the transactions returned (and therefore result in the user sending a tx other than the latest). Solution was to move some redux action functionality to the scene component.
=> Fix SendConf Make Spend Issue

src/modules/UI/scenes/SendConfirmation/selectors.js
The purpose of this task is to ensure that choosing a networkFee option on the SendConfirmation scene actually "sticks" / persists once the user starts changing the amount in the FlipInput. The recently-changed code was trying to access the `networkFee` on the `sceneState` object instead of `sceneState.guiSpendInfo` object.
Asana Task: https://app.asana.com/0/361770107085503/1112060050249485/f
=> Fix networkFee persistence issue

src/components/scenes/SendConfirmationScene.js, src/connectors/scenes/SendConfirmationConnector.js
The purpose of this task is to fix a regression whereby the Spending Limits PIN display was being decided by the **previous** fiat amount value. The solution was to bring that logic out of the connector (accessing older state) and into the scene method where it can access the "current" fiat value of the FlipInput.
Asana Task: https://app.asana.com/0/361770107085503/1112060050249480/f
=> Fix SendConf spending limits PIN issue

src/modules/UI/scenes/SendConfirmation/selectors.js
The purpose of this task is to ensure that customFees persist when the input field (FlipInput) has its text change.
Asana Task: https://app.asana.com/0/361770107085503/1112060050249485/f
=> Fix non-persistent customFee (and metaData)

patches/RCTFont.patch, postinstall.sh
This commit implements the following PR as a patch to RCTFont.mm.
https://github.com/facebook/react-native/pull/22607
This is an attempt at fixing a high count Bugsnag reported crash which has a profile similar to
https://github.com/facebook/react-native/issues/13588
=> Patch RCTFont.mm to fix crash

src/components/Main.ui.js, src/components/scenes/SpendingLimitsScene.js
This is claimed to be required react-native-router-flex to prevent crashes. Hopefully fixes reported crashes with signature:
"There is no route defined for key"
Reference: https://github.com/aksonov/react-native-router-flux/issues/2439
=> Add keys to all Scene components

src/components/scenes/CreateWalletAccountSelectScene.js
The purpose of this task to prevent the crash that occurs during the EOS Wallet Activation process when a user logs out via the sidebar. The crash was occurring because the logout dispatched action causes a change in the mapStateToProps returned value for CreateWalletAccountSelect (EOS) scene, triggering a render which tries to access the name property of an unreachable wallet.
A further investigation should be taken to look into how the logout mechanism works and if there is a way to prevent these types of errors from occurring during logout.
Asana Task: https://app.asana.com/0/361770107085503/1109183476243106/f
=> Fix crash on logout during EOS wallet-create process

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/co/edgesecure/app/MainActivity.java, src/components/Main.ui.js, src/components/common/HwBackButtonHandler.android.js
* Make default back button handler in Java only background app, not exit app
* Do not call Actions.pop() when at the WalletList screen. This will exit the app since we're at the top of the stack. Just return false which passes handling to Java to background the app.
* Return true when back button is hit from Exchange Quote scene. This will prevent app backgrounding and just go back to ExchangeScene
=> Fix Android back button behavior to prevent app crashes

src/components/scenes/CreateWalletSelectCryptoScene.js, src/connectors/scenes/CreateWalletSelectCryptoConnector.js, src/locales/en_US.js, src/locales/strings/enUS.json
The purpose of this task is to prevent the crashes occurring when a user **quickly** taps the "Create Wallet (+)" button immediately after login (before plugins have loaded). Instead of crashing with an error, I have modified the scene to just display a dropdown error alert.
Asana Task: https://app.asana.com/0/361770107085503/1112350860288128/f
=> Fix createWalletType crash to display error instead

src/actions/SendConfirmationActions.js, src/constants/WalletAndCurrencyConstants.js, src/locales/en_US.js, src/locales/strings/enUS.json
The purpose of this task is to add the paymentID and receive address to Monero's outgoing transactions. This should help users and tech support debug issues more easily.
Asana Task: https://app.asana.com/0/361770107085503/1109561748343713/f
=> Insert Monero paymentID and receive address into outgoing Monero notes

src/components/common/FullWalletListRow.js
The purpose of this task is to make sure that native tokens can be enabled and visible even if the custom token data (inserted before token was made native) show it being disabled.
Asana Task: https://app.asana.com/0/361770107085503/1113484716119560/f
=> Fix native token visibility issue

src/components/common/ManageTokenRow.js, src/components/scenes/ManageTokensScene.js
The purpose of this task is to make it so that a user is **unable** to edit or delete native tokens. The native token info should take precedence over any custom token info.
Asana Task: https://app.asana.com/0/361770107085503/1113720244890380/f
=> Disable editing of all native tokens

src/util/utils.js
The purpose of this task is to exclude disabled tokens from being added / included in an account's balance.
Asana Task: https://app.asana.com/0/361770107085503/1113940585317399/f
=> Exclude disabled tokens in calculated account balance

package.json, src/modules/UI/components/SafeAreaView/SafeAreaView.ui.js, yarn.lock
Task: Fix iPhone XS Max safe area
=> Added a new SafeAreaView dependency to accomodate new iPhone devices

src/components/scenes/CreateWalletReviewScene.js
The purpose of this task is to prevent the app from freezing after a wallet is created. The solution was to prevent the GUI from attempting to use `setState` to start animating a scene that react-native-router-flux was in the process of removing (ie popping).
Asana Task: https://app.asana.com/0/361770107085503/1114642775214512/f
=> Prevent animation of popped scene (causing freezing)

src/components/common/FullWalletListRow.js, src/modules/UI/selectors.js
The purpose of this task is to move some of the heavy calculations of the WalletListRow out of the connector and into the component.
Asana Task: https://app.asana.com/0/361770107085503/1114902118803440/f
=> Performance: Move calculateWalletFiatBalance out of connector (into component)

src/components/scenes/CreateWalletChoiceScene.js
The purpose of this task is to prevent an infinite loop for creating a new ETH wallet (rather than importing). This issue was most likely leftover from when the import wallet scene order was changed during development (Import vs. Create scene used to be before selectCryptoType).
Asana Task: https://app.asana.com/0/361770107085503/838232040088964/f
=> Prevent 'infinite loop' for new ETH wallet creation

src/components/scenes/TransactionsExportScene.js
The purpose of this task is to prevent crashing from occurring when someone attempts to export CSV on an empty wallet.
Asana Task: https://app.asana.com/0/361770107085503/1116555037085238/f
=> Fix CSV export issue on empty wallets

src/modules/Login/action.js
The purpose of this task is to quick the timing of the first wallet being selected upon account creation. This way the likelihood of issues with Request or Scan scene (or sidebar) are reduced (by 2/3).
Asana Task: https://app.asana.com/0/361770107085503/1115936477486324
=> Make selectedWallet load earlier to prevent routing quirkiness

src/actions/EdgeLoginActions.js, src/locales/en_US.js, src/locales/strings/enUS.json
This fixes Asana 
Edge Login spins forever in poor networks
https://app.asana.com/0/361770107085503/1113807296910175
This makes the error message more human friendly when there is a connection failure.
=> create more friendly error message

src/components/common/TransactionRow.js
The purpose of this task is to handle the case where the wallet block height is lagging behind the transaction block height and get the TransactionList to show as 'Pending' rather than a negative confirmation number.
Asana Task: https://app.asana.com/0/361770107085503/1116927447707180/f
=> Tx with blockHeight greater than current wallet block height to show as pending (not negative)

src/components/scenes/PluginViewYAOBScene.js, src/locales/strings/enUS.json, src/modules/DeepLinkingManager.js
This is the new API for deep links with 'plugin' as the path name. It is currently simplex only. Simplex plugin with this deep link has not been integrated in yet.
=> new API for deep linking

src/actions/TransactionListActions.js
The purpose of this task is to prevent the GUI from showing new transactions in the current Transaction List **if the transactions don't belong to the selected wallet**.
Asana Task: https://app.asana.com/0/361770107085503/1110931370399261/f
=> Prevent new transactions from showing up in wrong wallet

src/__tests__/__snapshots__/sendConfirmation.test.js.snap, src/components/scenes/SendConfirmationScene.js
Task: Send Confirmation Screen - Entering amounts causes the app to "stutter"  where the address/fees flash see video - Make the fees not disappear when you type in amounts keep it static
=> Make send confirmation fee static

src/components/common/WalletListTokenRow.js, src/connectors/WalletListTokenRowConnector.js, src/util/utils.js
The purpose of this task is to limit the number of times that `getCurrencyAccountFiatBalanceFromWallet` is called. Looks to reduce the number of times method is called by a factor of ~5-10x for a wallet with a few tokens enabled.
Asana Task: https://app.asana.com/0/361770107085503/1114902118803440/f
=> Limit WalletListTokenRow Calculations

copy-bitcoin.sh, src/modules/UI/components/ControlPanel/ControlPanelConnector.js, src/styles/SettingsComponentsStyle.js
The exchange rate in the side menu correctly shows the token exchange rate but shows the ETH icon rather than the token icon.
If it's a native token it should show the token icon. If there is no token it should show the ETH icon.
Asana Task: https://app.asana.com/0/361770107085503/1108089014657894/f
=> Side menu shows ETH icon when in token wallet

Jenkinsfile
Most Jenkins builds were failing, due to slashes getting into the version numbers.
=> Do not produce invalid versions

src/components/Main.ui.js, src/connectors/MainConnector.js, src/modules/UI/components/ControlPanel/Component/Main.js
=> Don't show Wallet Empty modal when user taps Sweep Private Key from side menu

src/components/scenes/PluginViewYAOBScene.js, src/modules/UI/scenes/Plugins/bridgeApi.js
There is a bug with edgeProvider `getReceiveAddress` returning the old address after a wallet changed. The instance needed to be updated with the current state in order to get the correct wallet
=> fix state management in EdgeProvider class

src/components/scenes/RequestScene.js
Task: Share button Request Address - Remove unnecessary extra text to just address only (makes it difficult to copy/paste)
=> When using the share on request scene, the wallet address is the only text shared

src/components/scenes/PluginViewYAOBScene.js
Request from Liberty x to have a custom tag on the end of the user-agent to make it easier to know when dealing with edgeProvider. 
=> added custom end to user-agent

src/styles/scenes/CryptoExchangeSceneStyles.js
The purpose of this task is to adjust the header for the cryptoExchangeScene, which was messed up from upgrading to React Native 59 and upgrading RNRF to a more recent version.
Asana Task: https://app.asana.com/0/361770107085503/1122906197217279/f
=> Adjust header for cryptoExchange scene

src/components/scenes/CryptoExchangeScene.js
The purpose of this PR is to prevent the re-triggering of the KYC alert on the Exchange Scene
Asana Task: https://app.asana.com/0/361770107085503/1121407886680028/f
=> Prevent re-triggering of KYC alert pop-up on Exchange scene

src/components/scenes/CryptoExchangeQuoteScene.js, src/constants/IconConstants.js, src/locales/en_US.js, src/locales/strings/enUS.json, src/modules/UI/components/ExchangeQuote/ExchangeQuoteComponent.js, src/styles/scenes/CryptoExchangeQuoteSceneStyles.js
If you are getting a quote from an exchange that is set to be an estimate we show it in orange with a help modal for more detail. 
=> surface estimates for quotes

src/modules/UI/components/ControlPanel/style.js
The purpose of this task is to fix the blank white area that shows up on Android devices that have no menu bar at the bottom.
Asana Taks: https://app.asana.com/0/361770107085503/1124490608274765/f
=> Adjust background color for gap on Android

src/components/scenes/TransactionListScene.js
The purpose of this task is to add more spacing to the bottom of the txList so that Android devices without a bottom menu bar will not cause the last item in the txList to be cut off.
Asana Task: https://app.asana.com/0/361770107085503/1124490608274766/f
=> Add more space to txList bottom

ios/Podfile.lock, package.json, src/components/scenes/PluginViewListScene.js, src/components/scenes/PluginViewScene.js, src/modules/UI/scenes/Plugins/BackButton.js, yarn.lock
This fork includes a native solution to the back-button woes.
=> Use our own `react-native-webview` to fix plugins

copy-plugin.js
Fix Asana : 
Moon pay should say “buy or sell Crypto with credit card or Apple Pay“ no need to mention Europe anymore since we have the filter
https://app.asana.com/0/361770107085503/1128104739220760
Safello Details
https://app.asana.com/0/361770107085503/1128134476977134
LibertyX - Capitalize the word "instant" to "Instant"
https://app.asana.com/0/361770107085503/1128104739220766
Safello - Remove the 3 seconds after confirmation text
https://app.asana.com/0/361770107085503/1128104739220764
=> tweak copy for plugin descriptions

src/modules/UI/scenes/Plugins/EdgeProvider.js
Fixes asana task 
Plugins Wallet Selector - In the Choose Wallet selector popup/dropdown, if that window is open unable to close it unless a wallet is selected
https://app.asana.com/0/361770107085503/1128194388068639
=> added x to wallet picker to close

src/actions/CryptoExchangeActions.js
This fixes Asana task 
Exchange - $5,000 of BTC to USDC shows a negative US amount of -$4.92 to be received
https://app.asana.com/0/361770107085503/1128216423913285
=> fix denomination gettter

copy-plugin.js, src/components/scenes/PluginViewScene.js, src/types.js
This gives partners the ability to lock all the traffic within the webview to be within their domain. It is also flexible since plugins like Simplex are local but go to their website as well. 
=> modify whitelist for plugins. Lock domain

src/components/scenes/SendConfirmationScene.js, src/modules/UI/scenes/Plugins/EdgeProvider.js
This pr solves the issue where a user clicks to make a spend from a partner plugin, and then they hit the back button. Edge provider did not resolve. Now it resolves a transaction to null if there is no transaction so the partner can handle null
=> fix backbutton to callback for Edge Provider

src/actions/CryptoExchangeActions.js
This is similar to the problem with USDC from before. when it was the to wallet. 
Fixes Asana : Exchange - If USDC is the sending source, the amounts are shown as negative at the confirmation screen
https://app.asana.com/0/361770107085503/1131139664426679
=> fix negatives with USDC on exchange quotes

postinstall.sh
We cannot use `let` or `const` on these old WebView versions.
=> Work around old WebView versions

src/components/common/SceneWrapper.js
The keyboard animation isn't perfect on Android, since the `Dimensions` module is buggy. If we don't need the keyboard animation, skip it entirely.
=> Adjust the SceneWrapper on Android

src/components/Main.ui.js, src/locales/en_US.js, src/locales/strings/enUS.json, src/modules/UI/components/Header/Component/ExitButton.js, src/modules/UI/scenes/Plugins/EdgeProvider.js
This pr adds an exit button to the right of the plugin header for exiting out of a plugin at any time. It also expands on the edgeProvider API to exit programmatically.
=> exit from plugin view screens.

src/modules/Login/action.js
Kylan recently added the crashing line a few lines down, with no check that the object exists.
=> Prevent denominations crash in settings

src/__tests__/__snapshots__/ChangeMiningFee.test.js.snap, src/components/scenes/ChangeMiningFeeScene.js
=> Prevent the custom fee inputs from switching places

package.json, src/modules/UI/scenes/Plugins/EdgeProvider.js, yarn.lock
This pr brings in latest bity changes that are also awaiting pr's. 
In addition it adds toast to Edge provider. 
Also in edge provider, tokens are now correctly spendable as well as select able.
=> updates to bity

src/styles/scenes/CreateWalletStyle.js
Task: After successfully importing a XRP, ETH, XLM wallet, the success icon is very slightly cut off on the sides
=> Fix success icon after importing wallet.

src/modules/UI/components/FlipInput/FlipInput2.ui.js
Task: Auto popup numpad when user taps flip input (https://app.asana.com/0/361770107085503/1145262796979869)
=> Focus upper flip input when flip or bottom number is pressed

src/modules/UI/components/FlipInput/FlipInput2.ui.js
Task: Auto popup numpad when user taps flip input (https://app.asana.com/0/361770107085503/1145262796979869)
=> Add 'done' at top of keypad on both flip inputs

src/components/scenes/LoginScene.js, src/connectors/scenes/LoginConnector.js
Task: Send Logs  from Login screen tap logo 5 times like Airbitz (https://app.asana.com/0/361770107085503/1135306975343601)
Note: Approve https://github.com/EdgeApp/edge-login-ui/pull/185 for this to be functional
=> Send Logs on clicking edge logo 5x

src/locales/en_US.js
'maximum network fee' is more accurate for currencies like ETH
=> update mining fee string

ios/Podfile.lock, src/modules/UI/components/FlipInput/ExchangedFlipInput2.js
Task: Send screen - fiat and crypto values flipped from rest of app (https://app.asana.com/0/361770107085503/1127823520648213)
=> When exchange rate is present, the flip input fiat is on the top

src/components/scenes/CreateWalletAccountSelectScene.js
Check if there is an activation cost and supported currencies before user can select an actiavtion wallet.
=> Added loader on the create wallet EOS select wallet button

src/actions/SendConfirmationActions.js, src/components/scenes/SendConfirmationScene.js, src/connectors/scenes/SendConfirmationConnector.js
Task - PIN shows invalid even if PIN entry is not shown for BRZ - https://app.asana.com/0/361770107085503/1163402411159817
=> Fix pin not showing on send confirmation when hitting spend limits

src/components/modals/AddressModal.js
It is a one-liner to increase the UI for users. on mobile phones, most of the time domains are going to be capitalized and it is very annoying to back and fix from "Brad.crypto" to "brad.crypto" 
this change should allow us to stop being the case-sensitive
=> Trim and lowercase the domain before resolving

src/components/scenes/PasswordRecoveryScene.js
Task: Password recovery questions list doesn't fill the screen - https://app.asana.com/0/361770107085503/1126866685130798
NOTE: Merge with - https://github.com/EdgeApp/edge-login-ui/pull/207
=> Remove Scrollview on Password Recovery Screen

src/actions/ScanActions.js
The barcode scanner had too much special-case logic which didn't include this link type. 
Scanning the barcode at https://deep.edge.app/swap didn't work before, but now it does.
=> Fix scanning edge://swap links

src/components/modals/WalletListModal2.js
Task: Exchange Screen - Receiving Wallet - Create Wallets list will still appear even if the wallet already exists - https://app.asana.com/0/361770107085503/1173045433614033
=> Fix "create wallets" not filtered when wallets exist

src/modules/UI/components/FlipInput/FlipInput2.ui.js, src/modules/UI/components/FlipInput/styles.js
Task: Send Screen - Place fiat currency symbol next to input on android - https://app.asana.com/0/361770107085503/1164052871025755
=> Fix formatting of currency symbols on Flip Input 

src/modules/UI/components/FlipInput/FlipInput2.ui.js
`displayAmount` could be `undefined` and throws an error when trying to render it as a number.
Default to an empty string if so.
=> Default display amount to empty string if undefined.

src/components/common/CryptoExchangeWalletListRow.js
Task: Wallet picker shows parent ETH wallet when searching for tokens - https://app.asana.com/0/281171002982981/1191574370628988
=> Fix bug when filtering tokens not showing up

src/components/Main.ui.js
Clicking back button on the FIO Request Address Screen fails. Recommended fix found on this Github Issue thread: https://github.com/aksonov/react-native-router-flux/issues/3410
*Steps To Reproduce:*
1. Login to application
2. Go to any screen other than the wallet screen (such as the Exchange screen) in the bottom navigation bar 
3. Open the side menu and select the "FIO Names" navigation option
4. After the screen loads, click the back button and you will see that nothing happens
Actual Behavior: 
User name able to go back to previous screen when back button pressed
Expect Behavior: User should go back to the wallet screen
GIFs below showing the issue before fix and after fix.
=> nav update to fix transition

src/actions/DeleteWalletModalActions.js, src/components/modals/ButtonsModal.js, src/components/themed/ModalParts.js, src/locales/en_US.js, src/locales/strings/enUS.json
I left a comment on #2199, but it's too late to do anything since it's already merged. Here is the code change I was proposing over there.
=> Restore bold text on the delete wallet modal

index.js, src/components/App.js, src/components/scenes/CrashScene.js, src/components/services/EdgeCoreManager.js, src/components/services/ErrorBoundary.js
If Bugsnag isn't loaded, such as in the debugger, provide our own Error boundary component instead.
=> Make the Bugsnag error boundary optional

src/modules/UI/components/FlipInput/FlipInput2.ui.js
Tapping a numeric key on some keyboards, like Samsung Keyboard, will create an event in addition to onChangeText. This causes onKeyPress to be called twice and duplicate the entered value. Fix is to prevent events with a 0-9 key from calling onKeyPress
=> Don't initiate onKeyPress for events triggered by tapping a number

src/modules/Settings/selectors.js
If the core sends back a transaction before the front end has loaded settings, it's possible for us to have a blank entry for the denomination of a currency code. In such a case, return a blank currency code which will fall back to a dummy denomination object preventing a crash.
=> Fix crash when transaction is received before settings are loaded

patches/readable-stream+2.3.6.patch
This doesn't seem to prevent the app from working, but it does produce frequent red-screen errors while debugging.
=> Fix an annoying crash from react-native-tcp

src/components/themed/Tile.js, src/modules/FioAddress/components/SelectFioAddress.js
* Transaction details
* Advanced transaction details
* FIO Send Domain
* FIO send request details
* FIO address settings
* FIO domain settings (the scene is not using Tile, PR for domain scenes is not reviewed #2298, waiting for new FIO designs)
* Send Confirmation Scene
=> Removed flex for tile container.

Jenkinsfile, deploy.js
This change purposes a new build parameter to optionally enable a verbosity mode to disable xcpretty and future silencing of noisy output in the build console output. The motivation is to add convenience to our process in troubleshooting build issues as they arise. This parameter is disabled by default; it is enabled only during a manual run (Build with parameters).
=> VERBOSE Build Parameter

src/components/themed/WalletProgressIcon.js
Task: https://app.asana.com/0/281171002982981/1199605136645462
Task description:
"Difficult to distinguish if an individual wallet icon is fully loaded or not.
Set wallet to begin with green circle at 5% start and stop at 95%. If it is able to fully sync completely then go 100% and green circle disappear.
Otherwise if the wallet cannot sync it should either be stuck between 5% or 95%."
=> Make wallet progress bar loader start at 5% and stop at 95% until it reaches 100%

src/components/themed/Tile.js
Having <> as a children of TouchableWithoutFeedback renders it not tappable.
Tested it with TouchableOpacity and TouchableHighlight and it works, so only TouchableWithoutFeedback is affected
Replace it with `<View />` instead
=> Tile bug fix not being tappable

src/components/themed/MenuTab.js
As the default navigation routes are stacks, and `Constants.WALLET_LIST` is one of those stack. Tapping the menu tab bar of wallets will only point into the stack. Any current scene the stack has will always show when you navigate to it. This fix ensure that if the route will go to the  `Constants.WALLET_LIST` stack, it will specifically always go to the `Constants.WALLET_LIST_SCENE` itself
=> Tapping the Wallet List on the menu will always go to the Wallet List Scene

src/components/themed/PasswordReminderModal.js
Added a Scrollview on Password Reminder Modal messages so when keyboard is opened it will shrink to a minimum size to fix bug when modal overlaps the upper screen of the phone
=> Password Reminder Modal on focus height fix

src/components/common/AirshipModal.js
The upstream react-native-airship library has more stable layout code, so use that modal implementation to fix cut-off text on Android.
=> Power un-themed Airship modals using upstream code

src/components/themed/WalletListRow.js
Fix is to remove adjustsFontSizeToFit that is recently added on Android EdgeText. adjustsFontSizeToFit on android somehow weirdly compress unicode text (as the icon is actually just a text.
Also added some paddings to center the option icon vertically.
=> Wallet List, Swipe Row Options, fix icon bug on android not showing properly

src/modules/ExchangeRates/action.js
`Promise.all()` will halt/reject when any of the promise does catch error. Fix is to suppress the error and just returns 0 upon rejection of any individual fetches. Promise.allSettled() is the correct function for this scenario but somehow not included in this javascript
Tested this by just introducing a new entry `new Promise((_, reject) => setTimeout(reject, 100))`. No real life test has been done
=> Fix exchange rate fetches not querying other exchange rates when one server is down

src/components/scenes/TransactionListScene.js, src/components/themed/TransactionListComponents.js
- Made the the 'no results' text centered
- Also did fix the loader when loading transactions on android (need to
have specific color)
=> Transaction List Search List. Added loader when waiting for search results

ios/Podfile.lock, package.json, src/components/services/NetworkActivity.js, src/components/services/Services.js, yarn.lock
Now that we are on RN63, we can get this working again. Otherwise, if we don't actually want this feature, we should just delete the whole thing (removing `isConnected` altogether). I assume we still want this feature, so here is a PR to put it back.
=> Re-enable the network connectivity checker

src/components/themed/TransactionListTop.js
Added new truncate decimals function in utils with test and implement on Transaction List Wallet Crypto Amount
=> Transaction List, Wallet Crypto Amount, fix bug 0s of whole number being truncated

src/components/scenes/TransactionListScene.js
no visual changes
verified functionality on ios simulator
=> Remove unsafe method in TransactionList

src/components/themed/WalletList.js, src/components/themed/WalletListEmptyRow.js
- Make the Wallet List Empty Row have the same behavior as the Wallet List Row
=> Fix wallet list empty row crashing the app when being swiped

src/components/Main.ui.js, src/components/scenes/ScanScene.js, src/constants/WalletAndCurrencyConstants.js, src/locales/en_US.js, src/locales/strings/enUS.json, src/modules/UI/components/ControlPanel/Component/Main.js, src/modules/UI/components/ControlPanel/Component/MainConnector.js
NOTE: Enabled sweepable private keys as instructed verbatim. "BTC, LTC, BCH, DASH, BSV, dgb, rvn, doge, firo, Smart"
=> Sweep Private Key: Updated process of sweep private key on the sidebar menu

src/components/scenes/GuiPluginViewScene.js
Initializing the webview with the default true value prevents camera initialization for Moonpay's widget
=> Set webview flag mediaPlaybackRequiresUserAction to false

android/app/build.gradle
Edge uses the current date as the version code, such as "21042201" for the first build made on 2021-04-22. If we multiply these dates by 1000, that will exceed the maximum possible version code of 2^31 (about 2 billion).
Instead, simply multiply by 10. This will slide the date over one decimal place, allowing the platform number to become the final digit.
Since we are multiplying our dates by 10 now, the new version codes will definitely be larger than the old version codes, so uploads will work without trouble. Before, the version codes were just the date plus roughly one year per platform (actually 1048576 * platform number, which happened to line up with the year slot).
=> Fix our `versionCode` calculation for Android

ios/Podfile.lock, package.json, src/actions/TransactionExportActions.js, yarn.lock
The CSV library depends on `stream`, but the polyfill we had installed was missing a critical property, so it crashed. Switch to the browser build instead, which doesn't have this issue.
=> Fix the `stream` import crash

.eslintignore, .eslintrc.json, .gitignore, e2e/createAccount/createAccount.test.js, e2e/init.js, e2e/loginLogout/passwordLogin.test.js, e2e/utils.js, package.json, yarn.lock
- Get a detox test running on iOS: 
- You can see this by running ```yarn test:e2e``` or ```detox test -c ios.sim.debug -l verbose``` 
<br>
- Setup eslint for detox
<br>
- Building the app for test:
- Currently the detox build command ```yarn test:e2e:build``` or ```detox build``` is not working
- Workaround this by changing the binary path for the specified configuration in the ```package.json``` (line 241) with your path for the .app file that is generated after building the app in xcode for a simulator.
- We will want this working properly before trying to include in the CI pipeline. May need to have an active apple developer account with a co.edgesecure.app provisioning profile. 
<br>
- Resetting state of the app …
=> 1 working DETOX test(others skipped)

src/actions/SendConfirmationActions.js, src/locales/en_US.js, src/locales/strings/enUS.json
NOTE: should merge with https://github.com/EdgeApp/edge-currency-accountbased/pull/274
=> Added error when XRP destination tag exceeds 9 characters

src/app.js
- [ X ] n/a
---
To add a warning and error toggle to the warning/error box that appears in the app when running in debug mode. These boxes may reduce the visibility of controls causing tests to fail. Some test automation workflows are more efficient when the app can be changed and refreshed in debug mode(eg adding testIDs)
Add "DISABLE_WARNINGS" to your .env file at the top of the repo to "true".
=> Add Toggle for Warning and Error Messages

src/util/tracking.js
Android native code expects an array when passing an items property
=> Pass params.items as array to firebase.logEvent

src/components/scenes/GuiPluginListScene.js
Fix: Problem with Flatlist id having duplicates. Added more stuff to make it unique
=> Fix changing countries does not update the plugin list

src/components/themed/WalletProgressIcon.js
=> Wallet Progress Icon. Fix warning message about unmounted icons being updated by setTimeout

src/__tests__/__snapshots__/RootReducer.test.js.snap, src/actions/FioActions.js, src/modules/Core/Wallets/action.js, src/modules/FioAddress/action.js, src/modules/FioAddress/util.js, src/modules/Login/action.js, src/reducers/FioReducer.js, src/types/reduxActions.js
Change algorithm how fio names are checking for expiration after login. Now you could see reminder on new devices. Reminder would appear in all needed cases.
https://user-images.githubusercontent.com/22767467/121952076-721f2700-cd64-11eb-85cd-2e13baae78ad.mp4
=> Change check expired fio names algorithm to show reminder

package.json, src/__tests__/fixtures.json, src/__tests__/utils.test.js, src/actions/CryptoExchangeActions.js, src/actions/SendConfirmationActions.js, src/util/utils.js, yarn.lock
This adds an amount to the insufficient funds error modal when attempting to send a token but can't due to having an insufficient amount of the parent currency to pay the transaction fee.
=> Show the minimum amount of parent currency necessary to pay transaction fee

src/actions/FioActions.js, src/modules/FioAddress/action.js, src/modules/FioAddress/util.js
This PR fixes auto redirect to fio address registration on fio names scene. In 'expire reminder' algorithm we need check for fio names separately, because it causing refreshing fio names scene.
=> Fio Names redirect to register fix.

src/__tests__/__snapshots__/SettingsScene.test.js.snap, src/components/themed/EdgeText.js
=> Add style adjustments in edgeText for android.

src/actions/SendConfirmationActions.js, src/components/scenes/ChangeMiningFeeScene.js, src/components/scenes/SendScene.js
These changes fix weird behavior on send scene when user tries to change fee. Now we set amount to 0 by default if amount is not set when user changes fee.
=> Fix fee changing on send scene

src/modules/UI/components/ControlPanel/ControlPanel.ui.js
If there is no selected wallet, we need to return sane defaults in the connector.
=> Fix the control panel crash at login

src/components/modals/UniqueIdentifierModal.js
- Do not crash when submitting a unique identifier.
=> Fix the unique identifier modal crash

src/components/themed/AddressTile.js
When the app is coming into foreground, read from the clipboard in case
a new address was copied while the app was in the background.
=> Scan clipboard for address on return to send scene

src/modules/UI/components/Slider/Slider.js
Add `useEffect` for the reset prop to invoke `resetSlider` once when 
reset prop changes from false to true.
=> Fix slider reset prop effect

src/components/scenes/SendScene.js
=> Fix where pin input tile is being overlaid by the keyboard on android

src/components/themed/AddressTile.js
EIP-681 plugin support requires a currencyCode for added security.
Without a currencyCode, the plugin cannot determine if the intent is to
pay using a token transfer for a particular contract address in the URI.
=> Pass currencyCode to parseUri when verifying clipboard

src/components/modals/FioExpiredModal.js
The button supports this natively now, so we can delete a bunch of code.
Also fixed the Flow type of the modal, which would have triggered the sketchy-null checks if we had them enabled.
=> Fix the expired FIO button centering

src/components/themed/FlipInput.js
=> Fix bug where clicking max spend and then toggling back will make the fiat amount load longer

src/components/scenes/TransactionDetailsScene.js
=> Fix bug on Transaction Details where fiat amount is blank and closing the modal will make the fiat amount blank

src/components/scenes/FioRequestListScene.js
Querying the blockchain will always be behind user action so this removes the FIO request from the list before the plugin returns an array without the paid request.
=> Remove paid requests from the request list

src/components/scenes/TransactionDetailsScene.js
1. Fix an issue where the number would not show/save the decimal numbers for users that use comma as a decimal point.
2. Fix the format for the current fiat amount to use the same local notation as the other Fiat value.
=> Use standard decimal point notation

src/actions/CryptoExchangeActions.js, src/components/scenes/CryptoExchangeQuoteScene.js, src/components/scenes/CryptoExchangeScene.js, src/types/routerTypes.js
Note: Suggest that the correct fix is to have a reset function on navigation/action to remount the Scene
=> Add state reset on Crypto Exchange Scene

src/components/themed/FlipInput.js
=> Blur the keyboard before re-focus works for some Android devices

android/app/src/main/AndroidManifest.xml
This is a new requirement for Android version 30. Requests to launch other apps are filtered by this setting and is necessary to allow users to bounce out to the browser to view transaction and address explorer links.
=> Add queries section to Android manifest

src/components/themed/LineTextDivider.js
=> Change LineTextDivider font weight from 'bold' to 'medium'

patches/@react-native-community+blur+3.6.0.patch
Just disable blur on Android API 27 and below, until we can debug further. This seems to clean up the Firebase device testing errors.
=> Hack around crashes by disabling blur

src/components/scenes/WcConnectScene.js, src/components/services/EdgeWalletCallbackManager.js
- Prevent calling wcInit when switching wallet
- Pass public address and wallet ID to plugin (the connectors no longer have wallet scope)
- Call disconnect to close the websocket if the user leaves the scene without approving the connection
=> Fix Wallet Connect initialization 

android/app/src/main/AndroidManifest.xml
[Stackoverflow](https://stackoverflow.com/questions/62440105/apk-size-increased-35mb-when-bumping-min-sdk-from-21-to-24)
I also tested it on the Yolo branch and it seems to be working
---
- https://app.asana.com/0/0/1201411731543821
=> Force Android to create a compressed APK

src/components/themed/ControlPanel.js
Selected walletId and currencyCode were being provided to
selectWalletFromModal() instead of the resulting selection from
the WalletListModal component.
Update the call to selectWalletFromModal to the correct params
given from the user input captured from the WalletListModal.
=> Fix selectWalletFromModal Params

src/components/scenes/GuiPluginListScene.js
There is nowhere in the code where `route.params` can be `undefined`, and yet we are getting rare crashes on iOS. Avoid that.
I cannot test this because we don't know how to reproduce the crash. Let's get it in the stores and see if Bugsnag cleans up.
=> Work around an unexplained bugsnag crash

src/constants/plugins/buyPluginList.json
Reorder Banxa Buy options so that POLi is not the 1st option in the buy list for Australia. POLi does not accept new customers but returning customers only.
---
- https://app.asana.com/0/0/1200457843986540
=> Reordered Banxa Buy Options

src/components/scenes/SendScene.js
The little fix got lost in a rebase. The current default string is:
Fee
0 ( 0)
This changes it to:
Fee
0 (0)
=> Fix random extra space

src/components/scenes/ManageTokensScene.js, src/components/themed/WalletList.js, src/components/themed/WalletListCurrencyRow.js, src/types/types.js
There are some scenes and components that attempt to access new GuiWallets before they exist in state. This utility wraps the GuiWallet and returns safe defaults where these edge cases exist.
---
- https://app.asana.com/0/0/1201744067064433
=> Create utility to safely use a GuiWallet where it may not exist yet

src/components/themed/WalletList.js, src/components/themed/WalletListCurrencyRow.js, src/components/themed/WalletListSortableRow.js, src/selectors/WalletSelectors.js
These two functions didn't handle custom tokens. They were replaced with a new function called calculateFiatBalance that accepts an exchange denomination instead of a currency code.
---
- https://app.asana.com/0/0/1201760396470480
=> Replace calculateWalletFiatBalanceWithoutState and calculateWalletFiatBalanceUsingDefaultIsoFiat

src/components/themed/AddressTile.js
Previous fix was not properly detecting if the selected wallet was ERC20
- [ x] Tested on iOS Tablet
- [ x] Tested on small Android
https://user-images.githubusercontent.com/90650827/152460273-41cefec6-dc28-4595-8d67-67b6429fde13.mp4
=> Show BitPay error properly for ERC20 wallets

src/components/scenes/StakingChangeScene.js
- [x ] Tested on iOS Tablet
- [x ] Tested on small Android
=> Use the transaction's `unlockDate` from `makeSpend` in change scene

src/actions/SendConfirmationActions.js
This fixes a bug caused by the race-condition between concurrent
`makeSpend` invocations.
---
- https://app.asana.com/0/0/1201854955729406
=> Add nonce/counter to ensure correct makeSpend is used

src/components/themed/AddressTile.js
Bitpay v2 isn't widely supported across the plugins so parseUri would throw and skip the bitpay check.
---
- https://app.asana.com/0/0/1201931726642895
=> Add additional bitpay url handling to address tile

src/actions/BitPayActions.js
Bitpay doesn't seem to calculate the segwit discount so we need to bump the fees so transactions with many inputs have a larger chance of success
---
- https://app.asana.com/0/0/1201818782291351
=> Bump up Bitpay fees

src/components/scenes/Staking/StakeModifyScene.js, src/components/themed/EditableAmountTile.js
Earned tile normally relies on an initial quote fetch request (Claim Rewards scene) or an unstake amount (Unstake and Claim Rewards scene). 
Force the earned tile to always show the amount pulled from the existing allocations instead of the fetched quote based on user amount modifications.
---
- https://app.asana.com/0/0/1202090255556889
=> Fix/tomb staking v2/init claim row

src/actions/SendConfirmationActions.js, src/components/scenes/SendScene.js
After choosing a FIO handle, handleChangeAddress must update the guiMakeSpendInfo through sendConfirmationUpdateTx. However, since there is no amount at the time the address is chosen, sendConfirmationUpdateTx early exits and the fioAddress in the guiMakeSpendInfo is lost.
Fix by dispatching an update with a null tx but with guiMakeSpendInfo
Also fix bug where SendScene connector tries to access this.props instead of 'props'
---
- https://app.asana.com/0/0/1202052231522987
=> Fix missing FIO handle on SendConfirmation

src/components/themed/FlipInput.js
state.overridePrimaryDecimalAmount's default value is '' if it is not explicitly set in the incoming props. This ends up later getting set to '0' in UNSAFE_componentWillReceiveProps, causing a re-render, overwriting any user input that may have already been set before the re-render.
Change the default value of overridePrimaryDecimalAmount's to '0' instead of ''
---
- https://app.asana.com/0/0/1202109297809356
=> Set overridePrimaryDecimalAmount's default value to '0'

src/components/themed/CryptoExchangeFlipInputWrapperComponent.js
Previously this only displayed the parent currency when the flipinput wasn't in focus
---
- https://app.asana.com/0/0/1202127286291113
=> Fix icon in CryptoExchangeFlipInputWrapper

src/components/scenes/TransactionDetailsScene.js
Payout currency denomination was looking at the wrong walletId.
Tokens were using empty string as the code.
---
- https://app.asana.com/0/0/1202163449679150
=> Fix denomination and currency symbol bugs

src/plugins/stake-plugins/stakePolicy.js
Because `.sort()` mutates the array in-place, this causes the mutation
to leak outside of the scope of the `deriveStakePolicyId`.
One solution is to clone the array before the sort, but a conscious
decision to revert this sorting is made because it is actually
unnecessary to sort.
Furthermore, it makes more sense to not sort because it matches the
official pool names by Tomb Finance (e.g. TOMB_FTM_LP not FTM_TOMB_LP)
and it avoids the need for yet another change to the `stakePolicyIds`
on the info-server.
---
- https://app.asana.com/0/0/1202169512131807
=> Remove in-place sort on stake/reward assets in policyInfo

src/components/themed/WalletList.js, src/components/themed/WalletListSortableRow.js, src/selectors/WalletSelectors.js
The problem was we were using `parseFloat` on a formatted number string.
We fix this by moving the formatting into the component, where it
more rightly belongs.
---
- https://app.asana.com/0/0/1201771696787124
=> Fix 'highest' wallet sort

ios/Podfile.lock, package.json, patches/edge-login-ui-rn+0.9.32.patch, src/components/themed/QrCode.js, yarn.lock
Since we are using react-native-svg, we don't need a second native graphics library.
=> Remove @react-native-community/art dependency

android/app/build.gradle
We had an outdated native dependency that wasn't compatible.
=> Fix startup crash on Android 12

src/components/modals/WalletListModal.js
The onBlur callback of OutlinedTextInput search box was hooked up to a call to setSearching(false), clearing the search whenever the user unfocused (onblur) the search box.
Additionally, the expected behavior is such that any time the search is focused OR the user has an active search entered (focused or not), the wallet list is NOT grouped.
Any time the  search input is blank AND unfocused, the wallet list IS grouped.
Update the search state logic such that the behavior is correct for all scenarios.
---
- https://app.asana.com/0/0/1202259259603058
=> Update WalletListModal search state logic

src/components/scenes/RequestScene.js
Use backwards-compatible  currencyCode prop for FiatText in RequestScene.
- [ x] n/a
---
- https://app.asana.com/0/0/1202268905852763
=> Use currencyCode prop for FiatText in RequestScene

src/components/text/TickerText.js
TickerText ultimately returns a plain Text object , but the font is not enforced. Update TickerText to enforce the font set by the theme.
- [x ] n/a
---
- https://app.asana.com/0/0/1202270489802954
=> Enforce theme font for TickerText

src/modules/UI/scenes/Plugins/EdgeProvider.js
Changes to the wallet list asset filtering cause wallet lists shown for providers to crash when the providers provide invalid allowed currency codes.
The pre-existing functionality in these scenarios was to simply show a wallet list modal with no filtering.
Update so the pre-existing functionality is retained and all wallets are shown when invalid allowedCurrencyCodes are given from our providers.
---
- https://app.asana.com/0/0/1202255988900613
- https://app.asana.com/0/0/1202263028533454
=> Add handling for undefined allowedCurrencyCodes from EdgeProviders

src/components/scenes/ManageTokensScene.js
Fix the manage tokens modal to only show top-level wallets with editable tokens.
=> Fix the manage tokens wallet list modal

src/components/text/TickerText.js
Original issue reported was pre-existing on live on all scenes and components by system-wide custom font changes on Android.
- [ x] n/a
=> Revert change to TickerText font

package.json, src/modules/UI/scenes/Plugins/EdgeProvider.js, yarn.lock
Add react-native-custom-tabs as described here: https://github.com/adminphoeniixx/react-native-custom-tabs
The original react-native-custom-tabs package is obsolete and the one above is a fork with a couple commits so it works with RN >60
---
- https://app.asana.com/0/0/1199681412563301
=> Add custom tabs launched to Edge Provider

src/__tests__/modals/FlipInputModal.test.js, src/__tests__/modals/__snapshots__/FlipInputModal.test.js.snap, src/components/common/ExchangeRate.js, src/components/modals/FlipInputModal.js, src/components/modals/WcSmartContractModal.js, src/components/scenes/RequestScene.js, src/components/text/FiatText.js, src/components/tiles/FiatAmountTile.js, src/types/types.js
New hooks have forced the deprecation of this prop in favor tokenId
---
- https://app.asana.com/0/0/1202312168060953
=> Deprecate currency code from FiatAmountTile and FiatText

src/actions/ExchangeRateActions.js
The balances object contains other stuff like FIO:STAKED keys that don't need an exchange rate and won't ever find them
---
- https://app.asana.com/0/0/1202342403689844
=> Use enabledTokenIds instead of balance keys

src/actions/ExchangeRateActions.js, src/hooks/useTokenDisplayData.js, src/util/utils.js
We can use the date as-is and let the server normalize. This change uncovered the (small and infrequent) possibility in useTokenDisplayData where the calculated yesterday date string might not exist in the exchange rate cache so the check is more general and just looks for a key with a date. We could get fancier with an actual date string regex but the extra underscore check is sufficient for how the cache is filled up and used.
=> Don't bother rounding yesterday's date

src/components/scenes/CreateWalletSelectCryptoScene.js, src/components/themed/WalletList.js, src/components/themed/WalletListFooter.js, src/modules/UI/scenes/Plugins/EdgeProvider.js, src/util/CurrencyInfoHelpers.js
1. Adds the 'create wallet' rows back to "Add Token" wallet picker
2. Disable a WAX (or any keysOnlyMode) Wallet from being created
3. Disable a WAX (or any keysOnlyMode) Wallet from being used in an edgeProvider
---
- https://app.asana.com/0/0/1202319717091534
- https://app.asana.com/0/0/1202326792172978
=> Wallet Picker Fixes

src/__tests__/components/ExchangeQuoteComponent.test.js, src/__tests__/components/__snapshots__/ExchangeQuoteComponent.test.js.snap, src/components/scenes/CryptoExchangeQuoteScene.js, src/components/themed/ExchangeQuoteComponent.js
Fixed the issue where for tokens it would use the wrong parent code
=> Add the a missing walletId to the currencyIcon in the Exchange Quote Scene

src/actions/ExchangeRateActions.js, src/util/utils.js
The rates server providers are too rate limited to reliably serve historical rates at 30 second accuracy.
=> Revert change to yesterdate rounding

src/plugins/borrow-plugins/plugins/aave/AaveNetwork.js, src/plugins/borrow-plugins/plugins/aave/index.js
Fix the performance issue caused by fetching all the token balances for all supported AAVE reserver tokens for v1. Solution is to limit which tokens are enabled for the network until some caching/persistence is implemented to improve the loading performance post initialization.
---
- https://app.asana.com/0/0/1202369707618481
=> Limit reserve tokens by configuration

src/__tests__/components/__snapshots__/OutlinedTextInput.test.js.snap, src/__tests__/modals/__snapshots__/WalletListModal.test.js.snap, src/components/modals/TextInputModal.js, src/components/themed/OutlinedTextInput.js
=> Fixed alignment of 'Invalid Password' error text

src/__tests__/__snapshots__/sendConfirmationReducer.test.js.snap, src/components/scenes/SendScene.js, src/reducers/scenes/SendConfirmationReducer.js
This has been broken for a LONG time and was incorrectly showing metadata.name. The JSON payment protocol was also incorrectly putting notes into the name which hid this bug.
=> Fix showing metadata notes

README.md
The link in the README was outdated as it pointed to React Native v6.4.
Fixed the link so that it points to v6.7.
=> fix React Native doc link

src/actions/ScanActions.js
If FIO plugin is disabled, the sweep private keys feature should still
work.
This is particularly useful when developing because devs may disable
plugins.
=> Do not require FIO plugin in order to sweep keys

src/components/modals/WalletListModal.js, src/components/scenes/CryptoExchangeScene.js, src/modules/UI/scenes/Plugins/EdgeProvider.js
In the pictures you can see I have a keysOnlyMode wallet (smartcash) which doesn't appear in any list other then the exchange-from and the main wallet list
---
- https://app.asana.com/0/0/1202475595731510
=> Add the 'allowKeysOnlyMode' and default to hide the 'keysOnlyMode' plugins in the walletListModal

src/components/data/row/CryptoFiatAmountRow.js, src/components/text/FiatText.js, src/hooks/useFiatText.js
Based on an input native fiat amount, wallet, and token, return a row showing:
- Crypto icon,
- The equivalent formatted/localized crypto amount
- Fiat icon
- Fiat (display) amount
---
- https://app.asana.com/0/0/1202491779403713
=> Implement CryptoFiatAmountGroup

src/__tests__/components/CurrencyIcon.test.js, src/components/data/row/CurrencyRow.js, src/components/icons/CryptoIcon.js, src/components/shared/CurrencyGroup.js, src/components/themed/WalletListCurrencyRow.js
The contents of WalletListCurrencyRow is reused across several places in the AAVE feature.
Refactor the contents of the WalletListCurrencyRow into CurrencyRow for reuse.
---
- https://app.asana.com/0/0/1202491779403706
=> Refactor CurrencyRow out from WalletListCurrencyRow

src/actions/DeepLinkingActions.js, src/types/DeepLinkTypes.js, src/util/DeepLinkParser.js
This fixes YOLO_DEEP_LINK dev env.json config. Before these changes, the redirect would repeat in an infinite loop.
=> Add DevLink to DeepLink

package.json, src/modules/UI/scenes/Plugins/EdgeProvider.js, yarn.lock
This PR cleans up token handling in EdgeProvider and updates to the latest edge-plugin-wyre which requires the newer EdgeProvider to properly handle MATIC and MATIC-USDC tokens. 
This is pretty valuable as many AAVE users borrow MATIC-USDC and need to sell it to their bank.
---
- https://app.asana.com/0/0/1202542030026805
=> Enable MATIC/USDC sell on Wyre

src/__tests__/edgeProvider.test.js, src/actions/ScanActions.js, src/components/modals/WalletListModal.js, src/modules/UI/scenes/Plugins/EdgeProvider.js, src/util/utils.js
- Change chooseCurrencyWallet to not show wallets for codes that are both mainnet and ETH tokens. This removes similar logic from the code that chooses what currency code to return after selection
- Flatten logic in chooseCurrencyWallet that decides what currency code to return
- Add unit tests for getReturnCurrencyCode and upgradeExtendedCurrencyCodes
---
- https://app.asana.com/0/0/1202578075245361
=> Harden EdgeProvider

src/components/scenes/SwapSettingsScene.js
This removes the state from the swap settings scene where there was a theoretical race condition could make the state out of sync with the actual plugin settings. This also removes reference to needsActivation which isn't used.
---
- https://app.asana.com/0/0/1202604584900504
=> Remove state from SwapSettingsScene

src/components/scenes/SwapSettingsScene.js
These updates all change the same file on disk. When writing multiple changes simultaneously we risk overwriting new changes with old values.
=> Update changes to swap settings one at a time

src/actions/CreateWalletActions.js, src/components/scenes/CrashScene.js, src/locales/en_US.js, src/locales/strings/enUS.json, src/theme/edgeConfig.js, src/theme/testConfig.js, src/types/types.js
We currently allow configuration of all aspects of our app that refer to 'Edge' in order to enable white-labeling. 
The support email is not a part of that configuration and is still hard-coded throughout our app.
Update AppConfig to include supportEmail, and update all hard-coded references to 'support@edge.app' to use 'config.supportEmail' instead. 
=> Add supportEmail to AppConfig

src/components/themed/ControlPanel.js
Sweep private key filters only by currency code.
Tighten filtering so that the wallet's native currency is taken into account in the wallet picker for sweep private key.
---
- https://app.asana.com/0/0/1202647424989390
- https://app.asana.com/0/0/1202648122272329
=> Tighten filtering for sweep private key

src/__tests__/components/TransactionRow.test.js, src/components/themed/TransactionListRow.js
This fixes a race condition with the GuiWallet redux loading state.
none
---
- https://app.asana.com/0/0/1202633128622522
=> Refactor TransactionListRow to no longer use GuiWallet

src/components/scenes/SettingsScene.js
=> Fixed incorrect icon spacing in SettingsScene currency rows

src/actions/LoginActions.js, src/reducers/CoreReducer.js, src/reducers/scenes/SettingsReducer.js, src/types/reduxActions.js
This means we will show the correct sort order immediately, and not have to wait for the complicated settings processing to take place.
none
=> Load the synced settings prior to login

src/components/progress-indicators/CircleTimer.js
Dismiss the setTimeout when the quote screen is unmounted.
none
---
- https://app.asana.com/0/0/1202872656296573
=> Prevent swap re-quotes from occurring when not on quote scene

src/components/scenes/Loans/LoanCreateConfirmationScene.js
A plain FillLoader was used while waiting for LoanCreateConfirmationScene to load, showing up as white since there was no background.
Add SceneWrapper around FillLoader during LoanCreateConfirmationScene init so there's a background.
none
---
- https://app.asana.com/0/0/1202925555994050
=> Add SceneWrapper around FillLoader

patches/pretty-format++ansi-styles+5.2.0.patch
This patches the ansi-styles package removing the unsupported named-group in a regex.
none
=> Patch ansi-styles package for Hermes runtime compatibility

src/plugins/gui/fiatPlugin.js
In the case of no payment methods, don't throw but return false for linked bank accounts
Also return false if wyreAccountId or wyreSecret don't exist
none
=> Fix track link bank promo cards

src/__tests__/__snapshots__/Request.test.tsx.snap, src/components/scenes/RequestScene.tsx
The flip input used to check for an empty string inputAccessoryViewID but that was changed recently to just accept the prop as passed in (which is correct). Therefore the fix needs to be in the request scene which created the prop.
---
- https://app.asana.com/0/0/1203028877160239
=> Fix missing Done row on iOS devices in Request scene

src/components/Main.ui.tsx, src/components/scenes/Loans/LoanAddCollateralScene.ts, src/components/scenes/Loans/LoanBorrowMoreScene.ts, src/components/scenes/Loans/LoanCloseScene.tsx, src/components/scenes/Loans/LoanCreateConfirmationScene.tsx, src/components/scenes/Loans/LoanCreateScene.tsx, src/components/scenes/Loans/LoanDetailsScene.tsx, src/components/scenes/Loans/LoanRepayScene.ts, src/components/scenes/Loans/LoanStatusScene.tsx, src/components/scenes/Loans/LoanWithdrawCollateralScene.ts, src/components/scenes/Loans/ManageCollateralScene.tsx, src/types/routerTypes.tsx
Note that this PR reintroduces a bug with the back button at the top left of the loan status scene after creating a loan. All back button functionality to be updated/fixed in [Loan Management: BackButton routing](https://app.asana.com/0/1200382638405084/1203094883503756/f)(https://app.asana.com/0/1200382638405084/1203094883503756/f)
none
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
---
- https://app.asana.com/0/0/1203025246279924
=> AAVE - Add 'Done' button to LoanStatusScene

src/components/services/DeepLinkingManager.ts, src/controllers/action-queue/types/pushPayloadTypes.ts
Not all push messages are handled in this path (like security alerts) so an unrecognized message can be ignored instead of throwing.
---
- https://app.asana.com/0/0/1203145897232074
=> Don't display cleaner error for push messages

src/components/modals/NumericInput.tsx, src/components/themed/OutlinedTextInput.tsx, src/locales/intl.ts, src/plugins/gui/scenes/EnterAmountScene.tsx
Wraps a TextInput but forces international formatting of display value Use in EnterAmountScene through OutlineTextInput
none
---
- https://app.asana.com/0/0/1203136033933192
=> Implement NumericInput component

src/components/themed/WalletList.tsx
Did not want to get rid of pluginId searching completely (for cases like zcoin/firo) but also need to prevent tokens from appearing in the results when search for the mainnet currency.
---
- https://app.asana.com/0/0/1203162131822926
=> Only search pluginIds for mainnet wallet create items

src/components/scenes/Loans/LoanDetailsScene.tsx
Disable the 'Borrow More' button if no collaterals are available
none
---
- https://app.asana.com/0/0/1203203783991241
=> Disable borrow button if no deposited collaterals

src/components/cards/WarningCard.tsx, src/components/scenes/SendScene.tsx
ScamWarningCard is now a generic warning card that accepts a list of bullet points (as well as a title/header/footer) and will render the bullet points with correct vertical alignment. 
Should be visually identical to the [original ScamWarningCard](https://github.com/EdgeApp/edge-react-gui/pull/3682)
=> Refactored ScamWarningCard to a generic WarningCard

src/actions/ScamWarningActions.tsx, src/components/cards/WarningCard.tsx, src/components/scenes/SendScene.tsx, src/constants/constantSettings.ts
If the SendScene is opened with a pre-populated address,
1. Either from swiping the wallet list row OR
2. From the ControlPanel (side menu)
Then, show a scam warning in a ConfirmAndContinue modal once.
Subsequent initializations of the SendScene will then never show the scam warning modal.
none
---
- https://app.asana.com/0/0/1203082480130376
=> Update Scam Warning

src/__tests__/scenes/CreateWalletSelectCryptoScene.test.tsx, src/actions/LoginActions.tsx, src/actions/RecoveryReminderActions.tsx, src/components/Main.ui.tsx, src/components/scenes/CreateWalletSelectCryptoScene.tsx, src/modules/Core/Account/settings.ts, src/reducers/scenes/SettingsReducer.ts, src/types/reduxActions.ts, src/types/routerTypes.tsx
Reuse the CreateWalletSelectCryptoScene component after the account is created and before the wallet list loads for the first time.
---
- https://app.asana.com/0/0/1203152643001448
=> Allow new user to select initial wallets

src/components/scenes/Loans/LoanCreateScene.tsx, src/hooks/useTokenDisplayData.ts
In the use case described by the bug report, the user does not have USDC enabled. After finalizing all input fields in the LoanCreateScene, useTokenDisplayData returns 0. This causes a divide by 0 crash.
Additionally, this part of the implementation was operating on the assumption that the borrowEngineWallet will always == collateral source wallet, which is no longer the case with the support of native BTC collateral.
Fix the asset logic around this area to resolve the two points mentioned.
none
---
- https://app.asana.com/0/0/1203313944862165
=> Fix asset logic on LoanCreateScene

src/components/scenes/FioRequestConfirmationScene.tsx, src/components/scenes/FioRequestListScene.tsx, src/components/themed/FioRequestRow.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json, src/modules/FioAddress/components/ConnectWallets.tsx, src/modules/FioAddress/util.ts
FIO uses BSC for Binance smart chain. Edge uses BNB so we need to convert back and forth to make them compatible.
This was technically started some time ago to make connected wallets work but these other features didn't really work and displayed data was messed up.
---
- https://app.asana.com/0/0/1202301192532726
=> Fix FIO-specific chain code handling

src/__tests__/components/__snapshots__/SceneHeader.test.tsx.snap, src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap, src/components/themed/SceneHeader.tsx
At the time of the review for PR #3627, a styling change was made to the SceneHeader that did not affect any users of SceneHeader at the time.
However, PR #3789 made use of the SceneHeader in a way that was not anticipated by PR #3627.
When both PRs merged, the styling bug was visible.
Update SceneHeader such that title row-specific styling (including tertiary children) does not affect the styling of the regular children.
none
---
- https://app.asana.com/0/0/1203355923167245
=> Fix styling on SceneHeader

src/__tests__/scenes/TransactionDetailsScene.test.tsx, src/actions/SendConfirmationActions.tsx, src/actions/TransactionListActions.ts, src/components/navigation/TransactionDropdown.tsx, src/components/scenes/TransactionDetailsScene.tsx
https://github.com/EdgeApp/edge-core-js/pull/484
---
- https://app.asana.com/0/0/1202793832335293
=> Use `walletId` over deprecated `wallet` on `EdgeTransaction`

src/components/hoc/withLoanAccount.tsx
navigation.popToTop() does not reliably navigate back to the dashboard scene in all scenarios.
In any case where the loan account is not available, always navigate to the dashboard scene.
none
---
- https://app.asana.com/0/0/1203444815739776
=> AAVE: Explicit dashboard navigation on null LoanAccount

src/components/scenes/Loans/LoanCreateScene.tsx
Tokens used for AAVE are not guaranteed to be enabled during the Create workflow - for example if the user selects BTC->bank. 
Tokens were being enabled upon ActionProgram creation after transitioning to LoanCreateConfirmationScene. 
However, the scene already needs the tokens to be enabled prior to entering the scene to properly calculate the nativeAmount passed to it.
Force enable the tokens prior to entering the LoanCreateConfirmationScene.
none
---
- https://app.asana.com/0/0/1203476237006127
=> Force enable WBTC+USDC tokens on LoanCreateScene

src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/components/data/row/IconDataRow.tsx, src/components/modals/WalletListModal.tsx, src/components/text/TickerText.tsx, src/components/themed/WalletListCurrencyRow.tsx
- Use EdgeText in TickerText, change API for IconDataRow
- Adjust styling in IconDataRow, WalletListCurrencyRow
-fix: cutoff text in wallet list
none
---
- https://app.asana.com/0/0/1203356149915792
=> Fix cutoff text in wallet list

src/plugins/borrow-plugins/plugins/aave/AaveBorrowEngineFactory.ts
Each AAVE smart contract interaction handled by Edge now overrides any existing (typically infinite) token allowances with only what is needed.
AAVE: Restrict token allowances to only what is needed for each smart contract call.
none
=> Restrict token allowance

src/util/ActionProgramUtils.ts
This fixes issue that dry-running the `LoanWithdrawActionOp` does not invoke the `approve()` method for the `ApprovableAction` from the `BorrowEngine` API and therefore does not mutate the `BorrowEngine.collaterals` array.
none
none
---
- https://app.asana.com/0/0/1203486127856838
=> Parallelize all EVM transaction for close loan

src/controllers/action-queue/runtime/evaluateAction.ts
USDC balance isn't available when using the 'wyre-sell' action op specifically in the case of being contained in a par, preceeded by a borrow, and with this par being the first op of the ActionProgram.
AAVE: Force 'skipChecks: true' for all wyre-sell ops
none
---
- https://app.asana.com/0/0/1203355923167213
=> Force 'skipChecks: true' for all wyre-sell ops

src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
- Send unstake request amount based on Thorchain 1e8 units not the native amount of the asset.
- Only allow claim/unstake if there is a staked balance
none
none
---
- https://app.asana.com/0/0/1203527000978872
- https://app.asana.com/0/0/1203527770648185
=> Fix TC Savers bugs

src/components/scenes/SendScene2.tsx
Always send the currencyCode in the spendInfo otherwise getMaxSpendable will fail as it doesn't know how to use tokenId
none
none
---
- https://app.asana.com/0/0/1203547137900308
=> Fix max spend

src/actions/BitPayActions.tsx
This would override any custom fee settings a user might want to set.
Handling of payment protocol and its custom fees by the plugin is a legacy feature that is now handled entirely in the GUI.
none
none
---
- https://app.asana.com/0/0/1203587144810191
=> Remove payment protocol custom fee from spendInfo.otherParams

ios/edge/Info.plist
The old key has been deprecated for
`NSLocationAlwaysAndWhenInUseUsageDescription` for all iOS >11 versions. Because we don't support iOS 11, we no longer need the `NSLocationWhenInUseUsageDescription` key.
none
none
---
- https://app.asana.com/0/0/1203519984726837
=> Update Info.plist NSLocation* property

src/actions/BitPayActions.tsx, src/constants/WalletAndCurrencyConstants.ts
At least with Bitpay, payment protocol requests desire a sat/byte fee that doesn't include the segwit discount. Ensure that we scale by 1.8x in the client-side code since no longer use the plugin side payment protocol scaling.
none
none
---
- https://app.asana.com/0/0/1203593993627360
=> Fix payment protocol payments from segwit wallets

ios/edge/Info.plist
This property is still required for iOS +11. This was confused with the deprecated `NSLocationAlwaysUsageDescription` property.
none
none
=> Add `NSLocationWhenInUseUsageDescription` back to Info.plist

src/components/scenes/SendScene2.tsx
- Validate spending limits last after max spend validation.
- Reset spending limits and maxspend flags after user deletes last pub address
none
none
---
- https://app.asana.com/0/0/1203622745621650
=> Fix spending limits after max spend

src/components/scenes/Staking/StakeModifyScene.tsx, src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts, src/plugins/stake-plugins/types.ts
Force use of the exact unstake amount when simulating an unstake. The 'unstake' directive also includes the earned amount of the sample Saver which will cause much more slippage.
none
none
---
- https://app.asana.com/0/0/1203655596713996
=> Fix future unstake estimate

src/util/CurrencyInfoHelpers.ts
- Added: Non-segwit wallet options for Litecoin and Digibyte to support Jaxx wallet imports
none
---
- https://app.asana.com/0/0/1203651461107953
=> No Segwit DGB/LTC in GUI

src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
This prevents previous deposits from not showing
none
none
---
- https://app.asana.com/0/0/1203661324582192
=> Fix Savers to only use a wallet's `publicAddress` not `segwitAddress`

src/plugins/borrow-plugins/plugins/aave/AaveBorrowEngineFactory.ts
'buyAllBalance' prop of the eth tx only needs the '164' Augustus function when repaying the full principal.
none
none
---
- https://app.asana.com/0/0/1203683948680923
=> AAVE: Fix partial repay with collateral transaction failure

src/types/routerTypes.tsx
This is like the `NavigationProp` type, but doesn't contain any scene-specific methods.
none
none
---
- https://app.asana.com/0/0/1203659728447752
=> Define a `NavigationBase` type

src/__tests__/components/__snapshots__/MenuTab.test.tsx.snap, src/actions/CreateWalletActions.tsx, src/actions/CryptoExchangeActions.tsx, src/components/scenes/Loans/LoanCreateConfirmationScene.tsx, src/types/routerTypes.tsx, src/util/fake/fakeNavigation.ts
Somehow this slipped into the types, even though it doesn't actually exist.
none
none
---
- https://app.asana.com/0/0/1203773088083078
=> Remove non-existing `navigation.popTo` method

src/components/Main.ui.tsx
=> Fix crash caused by missing navigation prop for MenuTab

src/components/themed/TransactionRow.tsx
If the confirmations is a number, then show the appropriate localized
string and interpolation function.
Otherwise, treat `'syncing'` and/or undefined using the synchronization
localized string.
none
none
---
- https://app.asana.com/0/0/1203762594629679
=> Fix treatment of EdgeTransaction confirmations

src/actions/DeepLinkingActions.ts
Mark deep link as HANDLED in redux before calling handleLink.
handleLink may take time to handle the link as it may need the user to choose a wallet or send a transaction before the link is "handled". This prevents repeated calls into handleLink while the first call is being handled.
none
none
---
- https://app.asana.com/0/0/1203822895117897
=> Fix multiple wallet picker popups on deeplink payments

src/actions/PaymentProtoActions.tsx, src/types/PaymentProtoTypes.ts
These don't appear to be used anywhere (and aren't present in the tested response object) so they shouldn't be here.
---
- https://app.asana.com/0/0/1203822895117909
=> Loosen up asPaymentProtoVerificationResponse cleaner

src/components/tiles/AddressTile2.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json
Added the option to send to self when the user has 2 or more wallets/tokens of the same type.
none
https://user-images.githubusercontent.com/4023066/215663708-b0082e4f-ad82-49ae-abdb-2cbd99130691.mp4
---
- https://app.asana.com/0/0/1203374649830361
=> Add UI to SendScene for self-transfers

src/__tests__/DeepLink.test.ts, src/util/DeepLinkParser.ts
- added: Support `https://deep.edge.app/recovery#token` deep links.
none
---
- https://app.asana.com/0/0/1203495863964074
=> Parse `deep.edge.app/recovery#token` URI's

src/actions/WalletActions.tsx
Use biggystring not lodash for `lt` comparison
none
none
---
- https://app.asana.com/0/0/1203924335664727
=> Fix insufficient funds error when activating xrp tokens

src/__tests__/scenes/__snapshots__/ChangePasswordScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/ChangePinScene.test.tsx.snap, src/components/scenes/ChangePasswordScene.tsx, src/components/scenes/ChangePinScene.tsx, src/components/scenes/PasswordRecoveryScene.tsx
The `showHeader` prop is unused in both these scenes and needs to be removed before merging [Recovery UI2](https://github.com/EdgeApp/edge-login-ui-rn/tree/itay/recovery-ui2), since that PR removes the last remaining [usage](https://github.com/EdgeApp/edge-login-ui-rn/blob/6131489867e3e57e868904bc2693118355876d1d/src/components/common/Header.tsx#L22-L26) of the old UI1 Header and deletes the component. 
none
none
=> Recovery UI2 - GUI updates

src/components/Main.tsx, src/components/data/row/CoinRankRow.tsx, src/components/scenes/CoinRankingDetailsScene.tsx, src/components/scenes/CoinRankingScene.tsx
Add CoinRanking scenes back to Main.tsx
Fix CoinRankScene styling
Add USD to CoinRankingDetailsScene
none
none
---
- https://app.asana.com/0/0/1203924091043564
=> CoinRanking (Markets) UI fixes/updates

src/hooks/animations/useFadeAnimation.ts
I introduced a bug with [PR for UI2 login approval](https://github.com/EdgeApp/edge-react-gui/pull/3467/files#diff-7a3691109c1561a76149d6d534378553eeda20972de91d9d0d9271cf82be3111L21) that omitted adding the `delay` prop to `useEffect`'s `DependencyList` argument in `useFadeAnimation.js`.
This PR corrects that bug. 
none
none
=> Fixed missing `delay` dependency in `useFadeAnimation`

src/components/scenes/Staking/StakeModifyScene.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json, src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts, src/plugins/stake-plugins/types.ts
none
none
---
- https://app.asana.com/0/0/1203568650150747
=> Add better error message when stake pools are full

src/modules/FioAddress/components/ConnectWallets.tsx
Based on the BugSnag report, this is the only possible location the crash could be occurring. I haven't been able to test this yet, but the PR should be safe either way.
none
none
---
- https://app.asana.com/0/0/1203922135849938
=> Fix the FIO wallet connection crash

src/components/modals/WalletListMenuModal.tsx, src/constants/WalletAndCurrencyConstants.ts, src/envConfig.ts, src/locales/en_US.ts, src/locales/strings/enUS.json, src/util/corePlugins.ts, src/util/fake/fakeRootState.ts
I thought it was important to allow OP to be splittable since it shares the same currency code with Ethereum. Since the splittable wallet list causes the wallet options modal to extend beyond small screens I went ahead and made it scrollable and unlocked the other splittable wallet types.
https://github.com/EdgeApp/edge-currency-accountbased/pull/511
https://github.com/EdgeApp/edge-exchange-plugins/pull/262
---
- https://app.asana.com/0/0/1203860831628486
=> Add Optimism

src/components/data/row/CurrencyRow.tsx, src/constants/WalletAndCurrencyConstants.ts
Token codes are very similar and hard to distinguish. ie USD.bs USD.gh so show names instead
none
none
---
- https://app.asana.com/0/0/1204057404044797
=> Show full token names for XRP

src/__tests__/components/BuyCrypto.test.tsx, src/__tests__/components/CreateWalletSelectCryptoRow.test.tsx, src/__tests__/components/CurrencyIcon.test.tsx, src/__tests__/components/MenuTabs.test.tsx, src/__tests__/components/PromoCard.test.tsx, src/__tests__/components/TransactionListRow.test.tsx, src/__tests__/components/TransactionListTop.test.tsx, src/__tests__/components/WalletListFooter.test.tsx, src/__tests__/components/__snapshots__/MenuTabs.test.tsx.snap, src/__tests__/modals/AdvancedDetailsModal.test.tsx, src/__tests__/modals/CategoryModal.test.tsx, src/__tests__/modals/WalletListModal.test.tsx, src/__tests__/scenes/CreateWalletImportScene.test.tsx, src/__tests__/scenes/CreateWalletSelectCryptoScene.test.tsx, src/__tests__/scenes/CreateWalletSelectFiatScene.test.tsx, src/__tests__/scenes/CurrencyNotificationScene.test.tsx, src/__tests__/scenes/CurrencySettings.ui.test.tsx, src/__tests__/scenes/EdgeLoginScene.test.tsx, src/__tests__/scenes/SendScene2.ui.test.tsx, src/__tests__/scenes/SettingsScene.test.tsx, src/__tests__/scenes/TransactionDetailsScene.test.tsx, src/__tests__/scenes/__snapshots__/EdgeLoginScene.test.tsx.snap, src/util/fake/FakeProviders.tsx, src/util/fake/fakeRootState.ts
This PR only edits unit tests, not run-time code.
It creates a new `FakeProvider` component that is responsible for providing a Redux store to test components. It takes an optional initial state prop, which lets us get some type-safety on these fake initial states.
In the future, this component will also provide a place to mount other context providers, such as `SafeAreaProvider`.
none
none
---
- https://app.asana.com/0/0/1204095781890178
=> Add a fake provider for testing

src/constants/plugins/buyPluginList.json, src/constants/plugins/sellPluginList.json
- Disable buy/sell via XanPool PayNow for Singapore countries
none
---
- https://app.asana.com/0/0/1204035151622698
=> Disable the xanpool PayNow buy/sell plugins for Singapore

src/actions/PaymentProtoActions.tsx, src/components/tiles/AddressTile.tsx, src/components/tiles/AddressTile2.tsx, src/modules/UI/scenes/Plugins/EdgeProvider.tsx
- Ensure currencyCode is set in launchPaymentProto
- Use navigation.replace() if launchPaymentProto() is called from SendScene2
none
none
---
- https://app.asana.com/0/0/1204076663985470
=> Fix payment protocol from wallet sendscene

src/__tests__/DeepLink.test.ts, src/actions/DeepLinkingActions.ts, src/components/scenes/GuiPluginListScene.tsx, src/plugins/gui/creditCardPlugin.ts, src/plugins/gui/fiatPlugin.tsx, src/plugins/gui/fiatPluginTypes.ts, src/types/DeepLinkTypes.ts, src/types/routerTypes.tsx, src/util/DeepLinkParser.ts
- Extend plugin URI format to require in path:
- direction
- providerId
- paymentType
- Drill down providerId into Fiat Plugins
- Make fiat plugin filter providers if providerId exists
/plugin/[pluginId]/[direction]/[providerId]/[paymentType]
direction = "buy" or "sell"
if pluginId is the last in path, direction is assumed "buy" and this link would deep link into old HTML webview plugins (not native FiatPlugins which providers). Note, path must not have a trailing '/' after pluginId
deepPath is everything after the [paymentType]
ie.
```
edge://plugin/ionia
edge://plugin/creditcard/buy/moonpay/credit
https://deep.edge.app/plugin/creditcard/buy/moonpay/credit
https://deep.edge.app/plugin/creditcard/buy/moonpay/iach
https://deep.edge.app/plugin/creditcard/buy/simplex/credit …
```
=> Support plugin provider in deep links

src/components/modals/LogsModal.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json
- Only match sensitive words surrounded by quotes (and maybe slashes). So `"loginKey"` or `"loginKey\\\\"` would match, but not `loginKey`.
none
---
- https://app.asana.com/0/0/1204108903827493
=> Fix the log upload regexp

src/components/scenes/Loans/LoanDashboardScene.tsx, src/controllers/loan-manager/redux/actions.ts
- fixed: Allow the loan dashboard scene to appear correctly, even if the account has stuck-spinning wallets.
none
---
- https://app.asana.com/0/0/1204200309083389
=> Fix the loan manager to work around suck wallets

package.json, src/components/modals/WcSmartContractModal.tsx, src/components/navigation/FlashNotification.tsx, yarn.lock
- changed: Implement Ethereum WalletConnect response handling in the GUI over the plugin using the updated WalletConnect API provided by the plugin.
- https://github.com/EdgeApp/edge-currency-accountbased/pull/533
---
- https://app.asana.com/0/0/1204222679938644
=> Implement `wcRequestResponse` from the Ethereum plugin engine

package.json, src/controllers/edgeProvider/EdgeProviderServer.tsx, yarn.lock
- changed: Use signMessage core API for EdgeProvider 
- https://github.com/EdgeApp/edge-currency-plugins/pull/364
---
- https://app.asana.com/0/0/1204276252180229
=> Use signMessage core API for EdgeProvider

src/components/Main.tsx, src/components/scenes/GuiPluginViewScene.tsx, src/components/scenes/TransactionListScene.tsx
Also remove the second copy, so the scene only exists inside the tab navigator.
none
none
---
- https://app.asana.com/0/0/1204340335884555
- https://app.asana.com/0/0/1204343630586365
=> Fix the bottom gap on the transaction list scene

src/actions/DeepLinkingActions.ts, src/plugins/gui/fiatPlugin.tsx, src/util/DeepLinkParser.ts
I have no idea if this is the right thing or not, but it does clear up the "unsupported asset" error.
none
none
---
- https://app.asana.com/0/0/1204353815854945
=> Allow fiat deep links to omit elements

src/__tests__/scenes/RequestScene.test.tsx, src/__tests__/scenes/__snapshots__/RequestScene.test.tsx.snap, src/components/scenes/RequestScene.tsx
- Hide balance in RequestScene consistently with the rest of the app
none
---
- https://app.asana.com/0/0/1204167844639231
=> Respect isAccountBalanceVisible state prop in RequestScene

android/app/build.gradle
Following the issue tracked [here](https://github.com/facebook/react-native/issues/32884) leads us to resolving the Android image caching issue by downgrading a dependency.
- Fixed: Bug in Android causing incorrect static images/icons to display in various places throughout the app
none
---
- https://app.asana.com/0/0/1204353886812628
=> Downgrade fresco:animated-gif package

src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/components/modals/ListModal.tsx, src/components/themed/ModalParts.tsx, src/components/themed/WalletList.tsx
- fixed: Make the last item tappable in the wallet list modal and default swap setting modal.
none
---
- https://app.asana.com/0/0/1204392945688667
=> Add proper bottom padding to fade-out modals

src/actions/WalletListMenuActions.tsx, src/components/modals/WalletListMenuModal.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json
- Changed: Monero "Private View Key" wallet menu option replaces "View XPub Address" and includes disclaimer.
none
---
- https://app.asana.com/0/0/1204176035281206
=> Add "Private View Key" menu option for Monero wallets

ios/Podfile.lock, package.json, src/actions/RequestReviewActions.tsx, yarn.lock
iOS does not support this functionality
- added: In-app review comment support for android.
none
---
- https://app.asana.com/0/0/1204129806235163
=> In-app review comment support for Android

.gitignore, maestro/02-launch-login/C310-launch-no-crash.yaml, maestro/02-launch-login/C311-relaunch-no-crash.yaml, maestro/02-launch-login/entrypoint.yaml, maestro/common/clear-app-data.yaml, maestro/common/close-modal-hack.yaml, maestro/common/launch-cleared.yaml, maestro/common/launch.yaml, maestro/entrypoint.yaml, package.json
The following Maestro Q/A automation tests are added:
| Name 	| Expected Result 	|
|---	|---	|
| C310-launch-no-crash.yaml 	| User is able to open Edge without crashing 	|
| C311-relaunch-no-crash.yaml 	| Edge should not crash when relaunching the App 	|
| ~C314-login-no-2fa.yaml~ 	| ~User is able to login with a valid Username and Password without 2FA or IP2FA blocked.~ 	|
| ~C431-create-account.yaml~ 	| ~Tapping "Create" takes user to new Wallet List Scene with: BTC, ETH, LTC, BCH, DASH.~ 	|
| ~C753-login-2fa.yaml~ 	| ~User is able to login with a valid Username + Password + Backup Code~ 	|
EDIT: The final three tests in the above table have been removed from this PR as they require refactoring due to UI changes. 
Additionally this PR sets up the:
- `./maestro` subfolder
- …
=> Initial Maestro Q/A tests & common utility flows

src/__tests__/components/__snapshots__/CurrencyIcon.test.tsx.snap, src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap, src/components/progress-indicators/WalletSyncCircle.tsx
This logic appears only to be present for two reasons:
1. To prevent the the sync circle from showing briefly while fading out
on a wallet with a fully synced state.
2. To hard-reset (without timing) the syncRatio when re-syncing.
In order to replace this extra state in order to simplify and fix
inconsistency issues:
1. Instead, we default to 0 opacity for the circle and immediately
invoke the `syncRatio` handler in the subscriber useEffect.
2. We derive the done state using `syncRatio.value` for the logic where
its needed.
- Fixed: WalletSyncCircle inconsistency issues with wallets that are stuck syncing.
none
---
- …
=> Remove problematic isDone logic from WalletSyncCircle

src/components/scenes/TransactionListScene.tsx
We should navigate back if the token is disabled from Archive Wallet action.
- Fixed: Navigate back when disabling a token from the transaction list scene.
none
---
- https://app.asana.com/0/0/1204356538335349
=> Add back navigation on transaction list if token becomes disabled

src/plugins/gui/providers/banxaProvider.ts
Broken in 0acc8c6: 'pluginId' was being passed to parse the asset, but it was using the pluginId (later clarified to providerId) of Banxa, instead of the pluginId of the asset requested from the quote.
- fixed: Banxa failing to provide a credit quote
none
---
- https://app.asana.com/0/0/1204497037101681
=> Fix Banxa quoting

src/plugins/stake-plugins/uniswapV2/pluginInfo.ts
Remove deprecated TOMB v1/v2 farming functionality.
Leave potentially useful fns and definitions for TOMB v3 farming.
- removed: TOMB v1/v2 farming
none
---
- https://app.asana.com/0/0/1204464353321471
=> Remove TombSwap v1/v2 farming on FTM

src/actions/LoginActions.tsx
Remove await from registerNotificationsV2 as we should NEVER wait on network ops to complete logins.
none
none
---
- https://app.asana.com/0/0/1204547794852799
=> Fix login lag

src/components/themed/OutlinedTextInput.tsx
Test text to demonstrate alignment fix correctness on android:
- fixed: Android text input domain misalignment when creating a FIO handle
none
---
- https://app.asana.com/0/0/1204554700015542
=> Fix OutlinedTextInput suffix style for Android

src/components/tiles/TransactionFiatTiles.tsx
- fixed: Do not save NaN fiat amounts (such as by entering a blank string).
none
---
- https://app.asana.com/0/0/1204252182594185
=> Fix a broken NaN check for fiat metadata

src/util/categories.ts
Assume the entire category is a primary category and append a ':' to the end. If it doesn't match the GUI will default to income or expense accordingly
none
none
---
- https://app.asana.com/0/0/1204352698460546
=> Fix categories with no ':'

src/plugins/gui/amountQuotePlugin.ts, src/plugins/gui/fiatPlugin.tsx, src/plugins/gui/fiatPluginTypes.ts, src/plugins/gui/hooks/useStateManager.ts, src/plugins/gui/providers/bityProvider.ts, src/plugins/gui/scenes/FiatPluginEnterAmountScene.tsx, src/types/routerTypes.tsx
- Refactor Fiat Plugin `enterAmount` API
none
---
- https://app.asana.com/0/0/1204595281258495
=> Refactor Fiat Plugin `enterAmount` API

src/plugins/gui/scenes/RewardsCardWelcomeScene.tsx
- Fixed: Bug with minimum font scaling on Visa Card Program welcome scene
none
=> Fix RewardCardWelcomeScene minimum font scaling

src/constants/WalletAndCurrencyConstants.ts, src/plugins/gui/RewardsCardPlugin.tsx
- Changed: Re-enable DASH for Visa® Card Program
none
---
- https://app.asana.com/0/0/1204651918588690
=> Re-enable DASH for Visa® Card Program

src/actions/DeepLinkingActions.ts, src/actions/ScamWarningActions.tsx, src/actions/ScanActions.tsx, src/components/scenes/SendScene2.tsx, src/components/themed/TransactionListTop.tsx, src/components/themed/WalletListSwipeableCurrencyRow.tsx
- Fixed: Bug with scam warning modal shown in unwanted instances; only show once for first manual navigation to send scene.
none
---
- https://app.asana.com/0/0/1204622252075405
=> Make scamWarning explicitly shown for Payment Protocol deep-linking

src/locales/en_US.ts, src/locales/strings/enUS.json, src/plugins/gui/RewardsCardPlugin.tsx, src/plugins/gui/scenes/RewardsCardDashboardScene.tsx
- Changed: Show an empty list with a message after deleting last Visa® card
none
---
- https://app.asana.com/0/0/1204684166560243
=> Fix last card delete handling

package.json
Add `--active-arch-only` flag for faster local builds based on react-native v0.71 docs:
>  This should reduce your native build time by a [~75% factor.](https://reactnative.dev/docs/0.71/build-speed#build-only-one-abi-during-development-android-only)
- `android:dev` adds `--active-arch-only`.
- `android:dev:test-release` additionally includes the `--variant=release` flag allows for [local release builds](https://reactnative.dev/docs/0.67/signed-apk-android#testing-the-release-build-of-your-app).
none
none
none
---
- https://app.asana.com/0/0/1204680683447164
=> Added `android:dev` and `android:dev:test-release` commands.

src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
Do not allow claiming only staking rewards on Thorchain Savers
none
---
- https://app.asana.com/0/0/1204592467395668
=> Set rewardsNotClaimable for TC Savers

src/components/scenes/GettingStartedScene.tsx, src/util/tracking.ts
The event `Signup_Account_Review_Done` was incorrectly named implying the end of the signup process, while in reality it happens at the very beginning of the signup flow (after USPs are viewed).
Rename to `Signup_Welcome`
none
none
---
- https://app.asana.com/0/0/1204664120652186
- https://app.asana.com/0/0/1204697741640174
=> Rename tracking event for usp swipe

src/components/scenes/Fio/FioStakingChangeScene.tsx
Using getMaxSpendable without the stake method name follows the transfer path which results in a higher fee and therefore lower staked amount.
---
- https://app.asana.com/0/0/1204728849187738
=> Use stake method params in FIO max stake

src/components/scenes/GettingStartedScene.tsx
- Fixed: Remove bottom gap on iOS devices on GettingStartedScene (USP)
- Fixed: Fix GettingStartedScene (USP) spacing for smaller display devices (e.g. iPod Touch)
none
---
- https://app.asana.com/0/0/1204392823967163
=> GettingStartedScene style adjustments

src/actions/CreateWalletActions.tsx, src/components/scenes/SendScene.tsx, src/types/routerTypes.tsx
- Changed: Use SendScene2 for HBAR/EOS wallet activation transaction
none
---
- https://app.asana.com/0/0/1203527749920557
=> Use SendScene2 for HBAR/EOS wallet activation transaction

src/plugins/gui/RewardsCardPlugin.tsx
- Fixed: Hard coded USD fiat currency for enter amount for Visa® Card Program.
none
---
- https://app.asana.com/0/0/1204779772531292
=> Hard code fiat currency code to USD for rewards card plugin

src/hooks/useWatch.ts
When changing the watched object (such as switching wallets), there is a one-tick delay before the hook's return value updates. We need to remove this delay to fix some bugs.
- fixed: Do not accidentally back out of the transaction list scene when selecting a token wallet from the drop-down.
none
---
- https://app.asana.com/0/0/1204827955021786
- https://app.asana.com/0/0/1204845530898852
=> Speed up the useWatch hook

src/components/Main.tsx, src/components/themed/SideMenu.tsx
Edit: After talking to Jon, we have decided to make the scene automatically go back, instead of offering a button. It's one less thing to press.
~When React Native does a live-reload, sometimes the app gets stuck in a weird state. Providing a simple logout button makes development much easier, since it provides a way to get back to the login screen:~
none
https://github.com/EdgeApp/edge-react-gui/pull/4269
---
- https://app.asana.com/0/0/1204845813405431
- https://app.asana.com/0/0/1204827955021796
=> Provide a side-menu fallback component

android/app/build.gradle, patches/edge-login-ui-rn+2.2.0.patch, patches/react-native-piratechain+0.3.2.patch, patches/react-native-smart-splash-screen+2.3.5.patch, patches/react-native-zcash+0.3.2.patch
Google moved this library from the "android.support" namespace to the "androidx" namespace a few years ago. Not everybody has upgraded, so fix the stragglers.
This PR uses patch-package to solve the appcompat problem once and for all. Once this is merged, we can updot / upgrade react-native-zcash, react-native-piratechain, and edge-login-ui-rn at our leisure, since they will work together correctly. If we don't merge this first, Android builds will be broken in various exciting ways if we updot any of those 3 libraries.
none
none
---
- https://app.asana.com/0/0/1204867804743082
=> Eliminate the legacy appcompat library

src/components/services/AirshipInstance.tsx, src/util/translateError.ts
Instead of sending the string to Bugsnag, we send the entire error
object so we retain the stack trace.
We will fallback to using `translateError` for unknown data types.
- Fixed: Bugsnag error reporting for showError includes error stack trace
none
---
- https://app.asana.com/0/0/1204848238190311
=> Fix showError to submit Error object to Bugsnag

maestro/10-assets/C184035-utxo-01.yaml
Crypto balance on walletlist is dependent on the fiat value to determine rounding. This causes intermittent errors
none
none
---
- https://app.asana.com/0/0/1204947202980134
=> Change tests to not check walletlist balance

src/components/scenes/LoginScene.tsx
We weren't re-rendering correctly when the account logged in, so our previous login-scene state got left behind.
none
none
---
- https://app.asana.com/0/0/1205003154684908
=> Correctly track changes to the account status

deployPatches/edge/develop/edgeXcscheme.patch, ios/edge.xcodeproj/xcshareddata/xcschemes/edge.xcscheme
Disable Firebase debug flag for iOS production builds
- changed: Disable Firebase debug flag for iOS production builds
none
---
- https://app.asana.com/0/0/1203804137771411
=> Disable Firebase Debug for iOS develop production builds

src/actions/WalletListMenuActions.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json
none
none
---
- https://app.asana.com/0/0/1205066911531007
=> Change the private key warning modal text to use a dynamic wallet name

src/__tests__/modals/__snapshots__/PasswordReminderModal.test.tsx.snap, src/components/buttons/ButtonsContainer.tsx, src/components/modals/PasswordReminderModal.tsx
Punted task to modify OutlinedTextInput such that this bug can no longer happen: https://app.asana.com/0/0/1205078580542521/f
- fixed: Password Reminder button overlap with error text on wrong password
none
---
- https://app.asana.com/0/0/1205013500013787
=> Fix PasswordReminderModal Button Overlap

src/__tests__/components/__snapshots__/OutlinedTextInput.test.tsx.snap, src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap, src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap, src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/components/themed/OutlinedTextInput.tsx
The "suffix" feature on the FIO registration scene works by making the text input tiny. As the user enters text, the input gets wider, and the suffix moves to the right.
This means that the text input itself is tiny to start, so there is no tappable area for a user to long-press on. This is unacceptable, so the FIO effect needs to go. We can still keep the suffix, just not attached to the text:
none
none
---
- https://app.asana.com/0/0/1205064445212746
=> Fix text input

src/components/modals/WalletListMenuModal.tsx
We used to wait for the action to finish, but resyncing the wallet can take a while, leaving the menu visible. Instead, drop the modal immediately.
none
none
---
- https://app.asana.com/0/0/1205100282680505
=> Drop the wallet menu as soon as possible

src/components/scenes/GettingStartedScene.tsx
If the user forgets accounts (deletes), then the `localUsers.length`
change would trigger the effect which handles the routing to the login
scene.
none
none
---
- https://app.asana.com/0/0/1205126719735957
=> Fix GettingStartedScene from routing after forgetting accounts

src/components/scenes/TransactionListScene.tsx
- fixed: Do not crash on the transaction list when deleting the custom token currently being viewed.
none
---
- https://app.asana.com/0/0/1205140379827765
=> Do not crash the transaction list on token delete

src/components/buttons/ButtonsContainer.tsx, src/components/hoc/styled.tsx, src/components/modals/FioCreateHandleModal.tsx, src/components/notification/NotificationCard.tsx, src/components/notification/NotificationView.tsx, src/components/scenes/GettingStartedScene.tsx, src/components/scenes/SendScene2.tsx, src/components/themed/SettingsRow.tsx, src/plugins/gui/scenes/RewardsCardDashboardScene.tsx, src/plugins/gui/scenes/RewardsCardWelcomeScene.tsx, src/util/parseMarkedText.tsx
This enables basic styled components which do not need the props nor
theme.
- Fixed: Updated `styled` HOC to handle caching and optionality of `theme`/`props` parameters.
none
---
- https://app.asana.com/0/0/1205078606742009
=> Improve`styled` HOC

deployPatches/edge/develop/edgeXcscheme.patch, ios/edge.xcodeproj/xcshareddata/xcschemes/edge.xcscheme
Default iOS edge.xcscheme is now with FIRDebug disabled, while the patch for the develop build enables it.
- fixed: iOS Firebase debug settings improperly set.
none
---
- https://app.asana.com/0/0/1205227220396846
=> Reverse the default and patch values for FIRDebug

src/components/scenes/GettingStartedScene.tsx
For some reason, the fix in #4358 was too broad and caused regressions in the logout behavior for accounts created from the USPs. This change resolves the regression while preserving the original fix.
none
none
---
- https://app.asana.com/0/0/1205225723936372
=> Fix broken 1st logout routing for accounts created from USPs 

src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/actions/LoginActions.tsx, src/components/Main.tsx, src/components/scenes/CreateWalletSelectCryptoScene.tsx, src/types/routerTypes.tsx
Split the scene into newAccountFlow/non-newAccountFlow usage to allow independent configuration of header button visibility in Main.tsx
- removed: Header buttons for new accounts' initial wallet creation
none
---
- https://app.asana.com/0/0/1205214041882472
=> Remove Header Buttons for New Account Wallet Creation

src/components/modals/HelpModal.tsx
We still want to avoid modals on top of modals as in the old implementation, so opening a browser window is the next best thing.
We may want to consider opening a browser for this modal in all cases (logged in/out) since the pages are difficult to navigate without a browser back button.
- fixed: Help modal links inoperable while logged out
none
---
- https://app.asana.com/0/0/1205332221444460
=> Open links in a browser if account isn't logged in

src/components/modals/FlipInputModal2.tsx, src/components/themed/FlipInput2.tsx
Force the FlipInput modal to be fullscreen for Android devices. Also fix the Android-specific visual cutoff of the right side of the 'Amount' placeholder text while there is no user input:
Old vs new:
Comparison - iOS(top) Android(bottom):
- fixed: Android FlipInputModal visual cutoffs
none
---
- https://app.asana.com/0/0/1205341170579571
=> Set FlipInputModal2 to fullscreen for Android

src/actions/FirstOpenActions.tsx, src/constants/constantSettings.ts, src/util/tracking.ts
Allow greater control over this tracking aspect compared to Firebase's/Google Analytics' built-in "first_open" param.
Currently limited to all events reported by the GUI, but would be nice to extend this to all events. See Asana task dependencies for this punted "nice-to-have"
none
none
---
- https://app.asana.com/0/0/1205244918309566
=> Analytics: Add "isFirstOpen" Param 

src/components/text/CryptoText.tsx, src/components/themed/FioRequestRow.tsx, src/components/tiles/NetworkFeeTile.tsx, src/hooks/useCryptoText.ts, src/util/cryptoTextUtils.ts
The FioRequest interface represents crypto amounts in "typical" amount multipliers as seen in any modern crypto website/product/social verbiage - i.e. "1.23 BTC." These are known in Edge as "exchange" denomination multipliers.
Properly factor in the "exchangeDenomination" (described above) and "displayDenomination" (user denom/mult setting) in the FioRequestRow crypto amount
- fixed: Properly factor user currency display denomination settings in FIO requests.
none
---
- https://app.asana.com/0/0/1205301258048819
=> Fix FIO Request Crypto Text Multiplier

src/components/scenes/SendScene2.tsx
I ran out of time to fix this properly. We'll make a task for 3.18 to fix this for real, but at least the UX is improved.
- changed: When sending to a FIO address, and something goes wrong on the FIO chain, don't show the send itself as having failed.
none
---
- https://app.asana.com/0/0/1205280031506078
=> Add a catch when saving FIO metadata

src/components/themed/ExplorerCard.tsx, src/constants/WalletAndCurrencyConstants.ts
Disable tx history for Liberland plugins and hide the explorer button if there is no explorer available
---
- https://app.asana.com/0/0/1205380689310357
=> Fix Liberland tx history scene display

src/constants/WalletAndCurrencyConstants.ts
- changed: Deprecated BSV to keys-only mode.
none
---
- https://app.asana.com/0/0/1205330404045845
=> Enable keysOnlyMode for BSV

src/__tests__/scenes/CreateWalletAccountSetupScene.test.tsx, src/actions/WalletActions.tsx, src/components/scenes/CreateWalletAccountSelectScene.tsx, src/components/scenes/CreateWalletAccountSetupScene.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json, src/types/routerTypes.tsx
- changed: Retheme wallet activation scene
none
---
- https://app.asana.com/0/0/1205308890818471
=> Retheme CreateWalletAccountSelectScene

src/components/modals/ScanModal.tsx
We accidentally deleted this in 1c8ea1f333119a8da4ba3366c11f047f8ce421e6
none
none
---
- https://app.asana.com/0/0/1205417996153449
=> Put an "X" back on the scan modal

src/components/scenes/SendScene2.tsx
Quick hack fix to prevent crash to due null `amount`. Better fix will be to use cleaners for LocalSettings
fixed: Send scene crash due to null spending limits
none
---
- https://app.asana.com/0/0/1205441271949809
=> Prevent crash on SendScene2

src/components/services/EdgeCoreManager.tsx, src/envConfig.ts
added: Maestro testing ability to use custom testing login/sync/info servers
none
---
- https://app.asana.com/0/0/1205265280373599
=> Use test servers for maestro

src/plugins/stake-plugins/uniswapV2/policyInfo/optimism.ts, src/plugins/stake-plugins/uniswapV2/stakePolicy.ts, src/plugins/stake-plugins/uniswapV2/uniV2Plugin.ts
For ease of use for the user, we show pools that utilize WETH in both ETH and WETH wallets. They are counted as unique stake policies despite being the same exact pool underneath. The other staked assets in the pool (like OP in WETH/OP) is therefore counted twice when the wallet determines it's total staked balance. Also, the user was presented with two options, ETH/OP and WETH/OP when staking OP.
This commit removes duplicate pools if the `getPolicies` caller uses the currencyCode filter. It now has enough unique functionality to remove the need for the shared policy filter utility function.
---
- https://app.asana.com/0/0/1205532912231602
=> Filter Uniswap based policies by pool address in addition to currency code

CHANGELOG.md, src/components/services/AirshipInstance.tsx
Add setTimeout to ensure bridge.resolve is called in another 'tick'
none
none
---
- https://app.asana.com/0/0/1205551203742083
=> Fix stuck showToastSpinner

ios/Podfile, ios/edge.xcodeproj/project.pbxproj
- changed: Require iOS 13 or higher.
none
---
- https://app.asana.com/0/0/1205491072465658
=> Require iOS 13 or greater

CHANGELOG.md, src/__tests__/scenes/__snapshots__/RequestScene.test.tsx.snap, src/components/scenes/RequestScene.tsx
- fixed: Possible balance text overflow in Receive scene
none
---
- https://app.asana.com/0/0/1205078841293962
=> Receive: Fix Balance Text Overflow

src/components/scenes/SendScene.tsx, src/components/scenes/SendScene2.tsx, src/constants/WalletAndCurrencyConstants.ts
- changed: Disable slider while attempting to send zero amounts if unsupported for the asset
none
---
- https://app.asana.com/0/0/1205210905206152
=> Disable Slider for Sending Zero Amounts

src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap, src/actions/SettingsActions.tsx, src/actions/WalletActions.tsx, src/actions/WalletListMenuActions.tsx, src/components/modals/WalletListMenuModal.tsx, src/components/services/WalletLifecycle.ts, src/locales/en_US.ts, src/locales/strings/enUS.json, src/reducers/scenes/SettingsReducer.ts, src/types/reduxActions.ts
- added: Wallet menu option to 'pause' wallet, preventing boot
none
---
- https://app.asana.com/0/0/1205412692015465
- https://app.asana.com/0/0/1205321359129572
=> Implement user-paused wallets

CHANGELOG.md, src/components/modals/TransferModal.tsx
Previously was only allowing tokens to work
- fixed: Deposit/Send footer buttons for native currencies
none
---
- https://app.asana.com/0/0/1205587559823777
=> Fix deposit/send footer modal for native currencies

CHANGELOG.md, src/actions/SettingsActions.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json
- added: Toast message when pausing or unpausing wallets
none
---
- https://app.asana.com/0/0/1205591566453680
=> Show toast on pause/unpause wallet

CHANGELOG.md, src/components/modals/FioCreateHandleModal.tsx
- fixed: Extra close (x) button on FIO modal
none
---
- https://app.asana.com/0/0/1205533593327784
=> Remove extra close button on FIO modal

src/components/scenes/LoginScene.tsx, src/envConfig.ts
Bug steps:
1. Press Sign Up
2. Press Get Started
3. Go Back 2x (new username, password login)
4. Observe the wrong scene: GettingStarted USPs instead of legacy landing
legacyLanding being undefined at the end of the steps to produce the bug was causing incorrect maybeHandleComplete routing to be returned
none
none
---
- https://app.asana.com/0/0/1205586035325311
=> GUI: Fix Back Routing for Legacy Landing Variant

src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap, src/components/modals/WalletListMenuModal.tsx, src/components/services/WalletLifecycle.ts, src/reducers/scenes/SettingsReducer.ts
Otherwise we might boot wallets that should stay paused.
none
---
- https://app.asana.com/0/0/1205605002662319
=> Don't start booting wallets until settings are loaded

CHANGELOG.md, package.json, src/components/cards/AssetStatusCard.tsx, src/components/cards/StatusCard.tsx, src/components/scenes/TransactionListScene.tsx, yarn.lock
- added: Informative card in transaction list for asset-specific communications
https://github.com/EdgeApp/edge-info-server/pull/102
---
- https://app.asana.com/0/0/1205222764697390
=> Implement AssetStatusCard (Sync Info Warning)

src/components/scenes/Staking/StakeModifyScene.tsx, src/components/scenes/Staking/StakeOverviewScene.tsx, src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts, src/plugins/stake-plugins/types.ts, src/plugins/stake-plugins/uniswapV2/policies/VelodromeV2StakePolicy.ts, src/types/routerTypes.tsx
none
---
- https://app.asana.com/0/0/1205742372677369
=> Only use 'unstakeAndClaim' for visuals

CHANGELOG.md, src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap, src/components/Main.tsx, src/components/scenes/AssetSettingsScene.tsx, src/components/scenes/SettingsScene.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json, src/types/routerTypes.tsx
Move asset-specific settings into their own settings page
none
---
- https://app.asana.com/0/0/1204864676553122
=> Move CurrencySettings into new "Asset Settings" Scene

CHANGELOG.md, src/actions/NotificationActions.ts, src/components/scenes/CurrencyNotificationScene.tsx, src/components/scenes/LoginScene.tsx, src/components/scenes/NotificationScene.tsx, src/controllers/action-queue/types/pushApiTypes.ts
none
---
- https://app.asana.com/0/0/1205643992747530
=> Remove price-change push event subscription for deprecated currencies

CHANGELOG.md, src/__tests__/components/__snapshots__/PromoCard.test.tsx.snap, src/components/cards/AssetStatusCard.tsx, src/components/cards/IconMessageCard.tsx, src/components/cards/PromoCard.tsx, src/components/cards/StatusCard.tsx
- Fix fallback language in AssetStatusCard
- Unify PromoCard and AssetStatusCard styling. PromoCard wasn't even visually a card to begin with.
none
---
- https://app.asana.com/0/0/1205822925785320
=> AssetStatusCard and PromoCard Fixes

CHANGELOG.md, src/components/scenes/TransactionListScene.tsx
For fixing appVersion targeting after this release. 
assetStatus endpoint will now be reserved for 3.20 messaging, and assetStatusCards for 3.21+
none
---
- https://app.asana.com/0/0/1205865322432429
=> Rename assetStatus -> assetStatusCards

CHANGELOG.md, src/components/services/Services.tsx
This seems to drastically slow down UI interactivity. Should be disabled on non-beta anyway.
none
---
- https://app.asana.com/0/0/1205935097933105
=> Disable LoanManagerService if not in beta

src/components/tiles/SwapDetailsTiles.tsx
A tx created by makeTx that also has swapData  will crash since it is assume to be created by makeSpend where core always adds the spendTargets.
In the case of a makeTx there are no spendTargets so use tx.nativeAmount instead.
none
---
- https://app.asana.com/0/0/1205930491280477
=> Prevent crash when tx has no spendTargets

CHANGELOG.md, src/actions/FirstOpenActions.tsx
Add special handling to properly force this value to false if the experiment config validation succeeds
Not deprecating the existing var for clean data because we are moving to Posthog and a self hosted solution, which are new to this release.
none
---
- https://app.asana.com/0/0/1205981666228532
=> Analytics: Fix isFirstOpen

CHANGELOG.md, src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap, src/__tests__/modals/__snapshots__/AddressModal.test.tsx.snap, src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap, src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/components/modals/AddressModal.tsx, src/components/themed/OutlinedTextInput.tsx
ENS name resolution only works on Ethereum network. 
`ethers.getDefaultProvider` does not reliably succeed in resolving ENS names.
- Port over `validText` from loginUI's implementation of `OutlinedTextInput` and fix styling on the modal. This change caused differences in unit test colors. **The original implementation rendered red in tests for some reason while the new one renders mint, as expected.**
- Rely on accountbased to multicast `ethers` `JsonRpcProviders` instead to reliably resolve ENS names.
https://github.com/EdgeApp/edge-currency-accountbased/pull/666
---
- …
=> Fix ENS Name Resolution

src/__tests__/components/__snapshots__/TransactionListRow.test.tsx.snap, src/__tests__/modals/__snapshots__/AdvancedDetailsCard.test.tsx.snap, src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap, src/components/scenes/TransactionDetailsScene.tsx, src/components/themed/TransactionListRow.tsx, src/components/ui4/AdvancedDetailsCard.tsx, src/components/ui4/CardUi4.tsx, src/components/ui4/CurrencyViewUi4.tsx, src/components/ui4/RowUi4.tsx
This was originally planned to do after all UI4 components were merged, but this PR does an initial adjustment to styling to catch up on some regressions after various rebases and changes to common components during the development of UI4.
Once all UI4 components are merged, it is still preferred not to have this much unique styling for each user of common components as done in this PR.
**NOTE: This PR is NOT a comprehensive fix for all styling issues, mainly just to address regressions.** Additional styling fixes are planned in https://app.asana.com/0/1200382638405084/1206062091848325/f
none
---
- To see the specific tasks where the Asana app for GitHub is being …
=> UI4: Initial Fixes

CHANGELOG.md, src/plugins/gui/providers/paybisProvider.ts
Use assetId not currencyCode to map from Paybis codes to Edge tokenId
none
---
- https://app.asana.com/0/0/1206165444414256
=> Fix paybis sell Tron USDT

src/__tests__/components/__snapshots__/TransactionListRow.test.tsx.snap, src/__tests__/modals/__snapshots__/AdvancedDetailsCard.test.tsx.snap, src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap, src/components/ui4/RowUi4.tsx, src/components/ui4/SectionView.tsx
Fix tappability for non 'touchable' tappable modes. Previously only 'touchable' was tappable, but did not include 'copy,' 'editable,' etc.
Also increase tappable area beyond the bounds of the right icon to
improve ease of use.
none
---
- https://app.asana.com/0/0/1206210011193789
=> Fix tappability for non 'touchable' tappable modes

src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap, src/components/ui4/RowUi4.tsx, src/components/ui4/SwapDetailsCard.tsx
Increase tappable row area to 100%, add missing section dividers to SwapDetailsCard
none
---
- https://app.asana.com/0/0/1206226659048761
=> UI4: TransactionDetailsScene Fixes

CHANGELOG.md, src/experimentConfig.ts
Enable Light Account 2.0 in experiment config
Other minor fixes: 
- We don't want to regenerate the entire experiment config if some var fails cleaning.
- Don't regenerate `legacyLanding` if the value saved is not `uspLanding`
none
---
- https://app.asana.com/0/0/1206225857137542
=> Enable Light Account 2.0 + experimentConfig fixes

src/actions/CreateWalletActions.tsx, src/actions/DeepLinkingActions.ts, src/actions/SettingsActions.tsx, src/components/Main.tsx, src/components/scenes/CreateWalletCompletionScene.tsx, src/components/scenes/CreateWalletSelectCryptoScene.tsx, src/components/scenes/CreateWalletSelectFiatScene.tsx, src/components/scenes/Fio/FioAddressRegisterSelectWalletScene.tsx, src/components/scenes/Fio/FioDomainRegisterSelectWalletScene.tsx, src/components/scenes/Fio/FioNameConfirmScene.tsx, src/components/scenes/MigrateWalletCompletionScene.tsx, src/components/themed/MenuTabs.tsx, src/types/routerTypes.tsx
- Clicking "View Assets" on the balance card results in missing tabs.
- Also add placeholder home icon while icon choice is finalized
none
---
- https://app.asana.com/0/0/1206237514290781
=> UI4: Fix tab routing

CHANGELOG.md, src/components/scenes/MigrateWalletCompletionScene.tsx
Since we're broadcasting and saving the tx, the engine should adjust the nonce accordingly and we shouldn't pass this array.
---
- https://app.asana.com/0/0/1206116889339878
=> Don't pass pendingTxs with spendInfo in migrate flow

ios/Podfile.lock, package.json, src/__tests__/actions/TransactionExportActions.test.ts, src/__tests__/components/ExchangeQuoteComponent.test.tsx, src/__tests__/components/TransactionListRow.test.tsx, src/__tests__/exportCsvResult.csv, src/__tests__/exportQboResult.qbo, src/__tests__/modals/AccelerateTxModal.test.tsx, src/__tests__/modals/AdvancedDetailsCard.test.tsx, src/__tests__/scenes/CryptoExchangeQuoteScene.test.tsx, src/__tests__/scenes/TransactionDetailsScene.test.tsx, src/actions/TransactionExportActions.tsx, src/actions/WalletActions.tsx, src/components/data/row/CurrencyRow.tsx, src/components/icons/CryptoIcon.tsx, src/components/scenes/MigrateWalletCalculateFeeScene.tsx, src/components/scenes/TransactionDetailsScene.tsx, src/components/services/AccountCallbackManager.tsx, src/components/text/CryptoText.tsx, src/components/text/FiatText.tsx, src/components/text/TickerText.tsx, src/components/themed/TransactionListRow.tsx, src/controllers/edgeProvider/EdgeProviderServer.tsx, src/controllers/edgeProvider/types/edgeProviderCleaners.ts, src/hooks/useCryptoText.ts, src/hooks/useTokenDisplayData.ts, src/hooks/useWalletBalance.ts, src/util/CurrencyInfoHelpers.ts, src/util/fake/fakeCurrencyPlugin.ts, yarn.lock
This upgrades to the non-breaking edge-core-js v1.14.0 release, prior to the 2.0 release.
none
---
- https://app.asana.com/0/0/1206276732585479
=> Less deprecation

package.json, src/components/ui4/BlogCard.tsx, src/components/ui4/CarouselUi4.tsx, src/components/ui4/PromoCardUi4.tsx, src/components/ui4/scenes/HomeSceneUi4.tsx, yarn.lock
none
---
- https://app.asana.com/0/0/1206081443211356
=> UI4: Finish Blog Posts/Learn Section

CHANGELOG.md, src/components/scenes/WcConnectionsScene.tsx, src/components/services/WalletConnectService.tsx
This retries the initialization of the WalletConnect client if it fails. Also, a small red text was added to the connections scene to indicate if the app hasn't connect yet
none
---
- https://app.asana.com/0/0/1206080746926242
=> Retry failed wallet connect initializations

CHANGELOG.md, src/__tests__/components/__snapshots__/MenuTabs.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CryptoExchangeQuoteScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CurrencyNotificationScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CurrencySettings.ui.test.tsx.snap, src/__tests__/scenes/__snapshots__/EdgeLoginScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap, src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap, src/components/common/SceneWrapper.tsx, src/components/scenes/WalletListScene.tsx, src/components/services/Providers.tsx, src/components/themed/MenuTabs.tsx, src/components/themed/SceneDrawer.tsx, src/components/themed/WalletListHeader.tsx, src/components/themed/WalletListSearch.tsx, src/components/themed/WalletListSwipeable.tsx, src/hooks/useSharedEvent.ts, src/state/SceneDrawerState.tsx, src/state/SceneScrollState.tsx, src/state/createStateProvider.tsx, src/state/renderStateProviders.tsx, src/util/fake/FakeProviders.tsx
https://github.com/EdgeApp/edge-react-gui/pull/4683
---
- https://app.asana.com/0/0/1205826921045596
=> App Tabs and Search

CHANGELOG.md, src/actions/PaymentProtoActions.tsx, src/util/DeepLinkParser.ts
none
---
- https://app.asana.com/0/0/1206219824791965
=> Disable RBF for payment protocol transactions

src/components/themed/FlipInput2.tsx
We introduce a Placeholder component to ensure we have consistent
rendering of placeholder text (no weird line-breaks on Android).
Next we simplify the platform specific styling for Android with one
negative marginRight prop measured on the input value's character
length.
none
---
- https://app.asana.com/0/0/1206199793234419
=> Fix placeholder and consistent Android/iOS styling for FlipInput2

Jenkinsfile, android/app/build.gradle, ios/Podfile.lock, ios/edge.xcodeproj/project.pbxproj, jestSetup.js, package.json, scripts/deploy.ts, yarn.lock
none
---
- https://app.asana.com/0/0/1206319239693160
=> Fix bugsnag source maps

src/__tests__/components/__snapshots__/LineTextDivider.test.tsx.snap, src/__tests__/components/__snapshots__/MenuTabs.test.tsx.snap, src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap, src/__tests__/modals/__snapshots__/HelpModal.test.tsx.snap, src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CryptoExchangeQuoteScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CurrencyNotificationScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CurrencySettings.ui.test.tsx.snap, src/__tests__/scenes/__snapshots__/EdgeLoginScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/FioAddressRegisterScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/FioDomainRegisterScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/RequestScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap, src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap, src/components/themed/MenuTabs.tsx, src/components/themed/SafeSlider.tsx, src/components/themed/Slider.tsx, src/components/ui4/CryptoIconUi4.tsx, src/components/ui4/ModalUi4.tsx, src/theme/variables/edgeDark.ts, src/theme/variables/edgeLight.ts, src/theme/variables/testDark.ts, src/theme/variables/testLight.ts, src/types/Theme.ts
none
---
- https://app.asana.com/0/0/1206324069027286
=> Tweak colors

src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap, src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/components/icons/ThemedIcons.tsx, src/components/themed/FilledTextInput.tsx
Swapping the eye icon was leading to color glitches, due to some bug deep within react-native-reanimated.
The solution involves rendering a single `Animated.Text` component, and simply changing the text content inside. This avoids re-wiring the Reanimated dependency graph, which is what seems to be causing the problem.
We achieve this with *almost* the same icon API as before by adding an `off` property to the eye icon, to switch between the two variants. We also refactor the animated icon implementation to use a raw text element, instead of the react-native-vector-icon wrapper component.
none
---
- To see the specific tasks where the Asana app for GitHub is being …
=> Fix animated icon glitches

src/components/common/EdgeAnim.tsx, src/components/scenes/CoinRankingScene.tsx, src/components/scenes/GettingStartedScene.tsx, src/components/scenes/TransactionListScene.tsx, src/components/themed/WalletListSwipeable.tsx
Disable layout animations that are also gesture animated. These are broken on Android
none
---
- https://app.asana.com/0/0/1206322748919970
- https://app.asana.com/0/0/1206124087516563
=> Fix and Tweak Animations

src/__tests__/components/__snapshots__/FilledTextInput.test.tsx.snap, src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap, src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/components/scenes/InputTesterScene.tsx, src/components/themed/FilledTextInput.tsx, src/components/themed/SimpleTextInput.tsx
Also add more test cases to InputTester
none
---
- https://app.asana.com/0/0/1206354619455584
=> Tweak FilledTextInput spacing

src/components/themed/FilledTextInput.tsx, src/components/themed/SimpleTextInput.tsx
none
---
- https://app.asana.com/0/0/1206379497162078
- https://app.asana.com/0/0/1206379497162105
=> Set autoCapitalize to 'none' by default for secureTextEntry inputs

src/__tests__/components/__snapshots__/SelectableRow.test.tsx.snap, src/__tests__/modals/__snapshots__/AddressModal.test.tsx.snap, src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap, src/__tests__/modals/__snapshots__/HelpModal.test.tsx.snap, src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap, src/components/FioAddress/DomainListModal.tsx, src/components/modals/AddressModal.tsx, src/components/modals/ButtonsModal.tsx, src/components/modals/CategoryModal.tsx, src/components/modals/CountryListModal.tsx, src/components/modals/FiatListModal.tsx, src/components/modals/HelpModal.tsx, src/components/modals/ListModal.tsx, src/components/modals/PermissionsSettingModal.tsx, src/components/modals/TransferModal.tsx, src/components/modals/WcSmartContractModal.tsx, src/components/modals/WebViewModal.tsx, src/components/scenes/CreateWalletImportScene.tsx, src/components/scenes/Fio/FioStakingChangeScene.tsx, src/components/themed/ModalParts.tsx, src/components/themed/SelectableRow.tsx, src/components/ui4/ModalUi4.tsx, src/theme/variables/edgeDark.ts
- Remove blurOnClear from ListModal altogether
- Fix ModalUi4 title handling, small X button adjustment
- **Remove custom padding altogether from ModalUi4.** 
-- This is less risky than trying to change ModalUi4 to support legacy + UI4 styling patterns.
- Misc restyling: AddressModal, SelectableRow (used on TransferModal)
none
---
- https://app.asana.com/0/0/1206379497162045
=> UI4: Modal Fixes 2

src/components/themed/MenuTabs.tsx, src/theme/variables/edgeDark.ts, src/theme/variables/edgeLight.ts, src/theme/variables/testDark.ts, src/theme/variables/testLight.ts, src/types/Theme.ts
This makes the app feel more pro.
none
iOS:
https://github.com/EdgeApp/edge-react-gui/assets/517469/d634c3a5-291a-4172-b611-4a3abda2a917
Android Before:
[before.webm](https://github.com/EdgeApp/edge-react-gui/assets/517469/9d209605-62db-4549-960f-930e90c9b36b)
Android After:
[after.webm](https://github.com/EdgeApp/edge-react-gui/assets/517469/c5588fff-ce97-4704-bc34-d75772c0c9c2)
=> Change header/tabbar background color to match app background color

src/components/themed/TransactionListRow.tsx, src/hooks/redux/useContactThumbnail.ts
We were using inconsistent checks, so in one place "" would be a missing icon, but in another place only `undefined` would count.
Standardize on checking for `!= null` everywhere, but also filter out "" in the `useContactThumbnail` hook to get the best of both worlds.
none
---
- https://app.asana.com/0/0/1206227157907408
=> Fix visuals for missing contact thumbnails

src/components/modals/BackupModal.tsx
---
- https://app.asana.com/0/0/1206072694496683
=> Fix margin on BackupModal

src/components/scenes/Fio/FioStakingChangeScene.tsx, src/components/scenes/TransactionDetailsScene.tsx
---
- https://app.asana.com/0/0/1206280885176725
=> Save FIO staking transactions

src/components/scenes/GuiPluginListScene.tsx
- Do not use SectionView but just a DividerLine
- Revert from using `overflow: 'visible'` due to bug on Android and use insets given by SceneWrapper instead.
none
---
- https://app.asana.com/0/0/1206433947858612
=> Fix buy sell list

src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/components/themed/SimpleTextInput.tsx
Use regular placeholder props instead of a separate element because
the delay between entering text and animating the placeholder away
is too noticeable that it looks bad.
none
---
- https://app.asana.com/0/0/1206421724981295
=> Remove animated PlaceholderText for SimpleTextInput

src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap, src/components/tiles/AddressTile2.tsx
This scene below was unchanged, just showing that it is working despite the reported issue in the task
none
---
- https://app.asana.com/0/0/1206319183602848
=> Revert Newly Added Font Scaling From UI4

jestSetup.js, src/__tests__/scenes/__snapshots__/CryptoExchangeQuoteScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap, src/components/themed/MenuTabs.tsx
We include padding on all devices with the exception of iPhone's with
a notch (and therefore with extra inset padding). This means we include
equal top and bottom padding to the MenuTabs for iPads in addition to
Android devices.
none
---
- https://app.asana.com/0/0/1206455300465101
=> Update device-specific bottom padding to MenuTabs

src/components/scenes/GettingStartedScene.tsx, src/theme/variables/edgeDark.ts, src/theme/variables/edgeLight.ts, src/theme/variables/testDark.ts, src/theme/variables/testLight.ts, src/types/Theme.ts
This color is an opaque representation of a real modal's complex background.
none
---
- https://app.asana.com/0/0/1206471773351597
=> Use "modalLikeBackground" in GettingStartedScene

src/components/scenes/RequestScene.tsx
The combination of styles across the scene, single `qrContainer` style, `QrCode`, and `AddressQr` was allowing the QR code to overflow beyond its container bounds. 
Modifying `QrCode` and/or `AddressQr` styles was fragile and fixing single QR would break multi-QR and vice versa.
Ultimately, the simplest fix found was to change `flexDirection` for the single QR case.
iOS:
none
---
- https://app.asana.com/0/0/1206493350744524
=> Fix Receive QR Style

src/__tests__/components/__snapshots__/BalanceCard.test.tsx.snap, src/__tests__/modals/__snapshots__/AdvancedDetailsCard.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/EdgeLoginScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap, src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap, src/components/scenes/CoinRankingScene.tsx, src/components/scenes/GuiPluginListScene.tsx, src/components/ui4/ButtonUi4.tsx, src/components/ui4/RowUi4.tsx
An Android emulator was set up to approximate the display of the Fold 3 device based on where the `PasswordReminderModal`'s text appeared to wrap in the bug report.
LoginUi 3.2.3 fixes the legacy landing scene in English:
The following is an artificially narrow appearance with the `ButtonUi4` changes mirrored to LoginUi:
Other screens:
none
---
- https://app.asana.com/0/0/1206468789158141
=> UI4: Narrow Device Scaling

jestSetup.js, src/actions/DeviceSettingsActions.ts, src/components/scenes/GuiPluginListScene.tsx, src/types/types.ts
This is the last thing we use the old async-storage module for. However, some WalletConnect dependencies still need it, so we leave it in package.json.
none
---
- https://app.asana.com/0/0/1206453986039455
=> Move the developer-mode plugin URI to DeviceSettings

src/components/common/SceneWrapper.tsx, src/components/scenes/CoinRankingScene.tsx, src/components/scenes/TransactionListScene.tsx, src/components/scenes/WalletListScene.tsx, src/components/themed/SceneFooterWrapper.tsx, src/components/themed/SearchFooter.tsx
The unique key ensures that we always render a new component when the
render function changes and this in-turn triggers onLayout.
none
---
- https://app.asana.com/0/0/1206481495752132
=> Cache the footer render in MenuTabs and give it a unique key

CHANGELOG.md, src/__tests__/components/__snapshots__/FilledTextInput.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap, src/components/scenes/DevTestScene.tsx, src/components/themed/FilledTextInput.tsx
- Used negative margins. Not ideal, but a lower impact change to avoid affecting the layouts app-wide.
- Only apply this special styling if there is no counter, since we already styled the app according to visibility of counters.
none
---
- https://app.asana.com/0/0/1206471966737303
=> Make FilledTextInput take up constant space

src/components/navigation/FlashNotification.tsx
This is UI3 paradigm. Now that we have dismiss-able airship dropdowns,
we no longer need the footer and the included X button.
none
---
- https://app.asana.com/0/0/1206539946111764
=> Remove ModalFooter from FlashNotification

CHANGELOG.md, src/__tests__/components/__snapshots__/TransactionListRow.test.tsx.snap, src/components/themed/TransactionListRow.tsx
Fix the 2nd line of text in tx list card rows:
- Center align text
- Add a right margin
none
---
- https://app.asana.com/0/0/1206512051627949
=> Fix TransactionListRow Styling

src/__tests__/scenes/__snapshots__/CryptoExchangeScene.test.tsx.snap, src/components/scenes/CryptoExchangeScene.tsx
none
---
- https://app.asana.com/0/0/1206638192938067
=> Fix Exchange Scene "max" button width

src/__tests__/scenes/__snapshots__/CryptoExchangeScene.test.tsx.snap, src/components/modals/FlipInputModal2.tsx, src/components/scenes/CryptoExchangeScene.tsx
none
---
- https://app.asana.com/0/0/1206656306638757
=> Fix MiniButton alignSelf on FlipInputModal2

src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/components/scenes/CreateWalletImportScene.tsx, src/components/themed/FilledTextInput.tsx
Bug in RN sometimes enables autocomplete even though it's disabled.
none
---
- https://app.asana.com/0/0/1206803533123091
=> Hack FilledTextInput to not autocomplete in private key entry

CHANGELOG.md, src/actions/BackupModalActions.tsx, src/actions/DeepLinkingActions.ts, src/actions/ScanActions.tsx, src/components/FioAddress/ConnectWallets.tsx, src/components/modals/PriceChangeBuySellSwapModal.tsx, src/components/modals/TransferModal.tsx, src/components/scenes/GuiPluginListScene.tsx, src/components/scenes/GuiPluginViewScene.tsx, src/components/scenes/WcConnectionsScene.tsx, src/components/themed/BuyCrypto.tsx
Audit deeplinks:
- 'paymentProto' - Simply routes to send scene. User flow after that already blocks light accounts.
Block with backup modal:
- Request for Address Links
- azteco deeplink action (only entry point for azteco)
- fiatPlugin: openExternalWebView
- ScanActions sweepPrivateKeys()
Pop navigation on mount: 
-- 'plugin'->'pluginView'->EdgeProviderComponent
-- fiatPlugin: openWebView -> 'guiPluginWebView'/FiatPluginWebViewComponent 
none
---
- https://app.asana.com/0/0/1206549609896201
=> Block Light Account Plugin Deeplinks

src/components/themed/SideMenu.tsx
This pull request updates the unique ID used for generating share referral links. It replaces the previous method of using base58ToUuid with a new method that generates an anonymized referral ID using hash.js. This ensures that the referral links are more secure and unique.
none
---
- https://app.asana.com/0/0/1206488798092857
=> Update unique ID for share referral links

src/actions/CreateWalletActions.tsx, src/actions/CryptoExchangeActions.tsx, src/components/scenes/Fio/FioAddressRegisterSelectWalletScene.tsx, src/components/scenes/Fio/FioAddressSettingsScene.tsx, src/components/scenes/Fio/FioCreateHandleScene.tsx, src/components/scenes/Fio/FioDomainRegisterSelectWalletScene.tsx, src/components/scenes/Fio/FioDomainSettingsScene.tsx, src/components/scenes/Fio/FioNameConfirmScene.tsx, src/controllers/edgeProvider/EdgeProviderServer.tsx, src/plugins/gui/fiatPlugin.tsx, src/plugins/gui/fiatPluginTypes.ts, src/plugins/gui/providers/banxaProvider.ts, src/plugins/gui/providers/kadoProvider.ts, src/plugins/gui/providers/paybisProvider.ts, src/util/CryptoAmount.ts, src/util/tracking.ts
Conversion tracking was broken in some cases. Wrong values, including our very ambiguous `pluginId`, were being used to calculate dollar conversion values. As a result, `logEvent` either silently failed without sending out the tracking event, or reported the incorrect amount values.
Refactor tracking in general, introduce an MVP of `CryptoAmount`, and make props more explicit. All of those combined ought to reduce the likelihood of similar future mistakes.
none
---
- https://app.asana.com/0/0/1206683289208449
=> Refactor Conversion Tracking

src/components/common/SceneWrapper.tsx
none
---
- https://app.asana.com/0/0/1206897264651547
=> Update RequestScene to expect notifications

src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/components/themed/WalletList.tsx
Must use a react-native-gesture-handler compatible component, and neither FlashList nor SectionList have RNGH-wrapped counterparts.
We aren't using any sticky headers anymore so there's no point in using SectionList. Therefore, settled on FlatList.
none
---
- https://app.asana.com/0/0/1206901341251751
=> Refactor the WalletList to always use a FlatList

CHANGELOG.md, src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
While we were actually unstaking the correct amount including the earned amount, we didn't properly show that to the user or log it in the savedAction
none
---
- https://app.asana.com/0/0/1206958843387214
=> Show correct unstake amount

CHANGELOG.md, src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
Savers txs require specific input/output ordering and an RBF tx will likely mess up the ordering.
none
---
- https://app.asana.com/0/0/1206924062004099
=> Do not allow RBF for Thorchain Savers txs

src/components/scenes/SwapCreateScene.tsx, src/components/themed/SwapInput.tsx
Redo: Something funky happened with this PR https://github.com/EdgeApp/edge-react-gui/pull/4946
none
=> Only show secondary placeholder for SwapInput when next is not hidden

CHANGELOG.md, src/__tests__/components/WiredProgressBar.test.tsx, src/__tests__/components/__snapshots__/WiredProgressBar.test.tsx.snap, src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap, src/actions/LoginActions.tsx, src/actions/ResyncWalletModalActions.tsx, src/actions/WalletActions.tsx, src/components/services/AccountCallbackManager.tsx, src/components/themed/WiredProgressBar.tsx, src/reducers/scenes/WalletsReducer.ts, src/types/reduxActions.ts
This pull request refactors the WiredProgressBar to turn it into a functional component. 
It also updates the component to always reflect the account wallet state and removes the unused redux state "walletLoadingProgress".
none
---
- https://app.asana.com/0/0/1206746867341833
=> WiredProgressBar Updates

src/plugins/gui/amountQuotePlugin.ts, src/plugins/gui/fiatPlugin.tsx
For light accounts:
- Change executePlugin to allow buys with native plugins
- Add check for buy/sell direction in the max $50 check when accepting the quote
none
---
- https://app.asana.com/0/0/1207049347208575
=> Fix light account buy/sell limitation logic

CHANGELOG.md, src/plugins/gui/amountQuotePlugin.ts
Convert $500 to fiat denom of wallet and round to highest decimal precision. This prevents getting a default quote for excessively small or large amounts
none
---
- https://app.asana.com/0/0/1207000283682116
=> Properly set default fiat value for non-USD amounts

CHANGELOG.md, src/components/themed/WalletListCurrencyRow.tsx
none
---
- https://app.asana.com/0/0/1205615584415997
=> Decrease opacity in Wallet list row for better visibility

android/app/src/main/java/co/edgesecure/app/MainActivity.kt, ios/edge/AppDelegate.mm
See:
- https://developer.apple.com/library/archive/qa/qa1838/_index.html
- https://jonaskuiler.medium.com/creating-a-security-screen-on-ios-and-android-in-react-native-97703092e2de
For Android, the Medium solution is good, but there is a better one on the newest Android.
For iOS, the Apple solution is actually simpler than the Medium solution. Yes, I had to pay for for Medium to learn that. Drat.
none
---
- https://app.asana.com/0/0/1206346732396824
=> Hide the app contents while in the background

src/components/scenes/CreateWalletSelectCryptoScene.tsx
Fade did not visually respond to state changes
that occured while the Fade was out of view at the
bottom of the list.
none
---
- https://app.asana.com/0/0/1207102554866836
=> Fix Fade props for "Add Custom Token"

index.ts, src/components/text/ReText.tsx
Only call Animated.addWhitelistedNativeProps once
No longer OK to call multiple times after expo and/or reanimated updates.
https://github.com/software-mansion/react-native-reanimated/discussions/5621
https://github.com/software-mansion/react-native-reanimated/issues/5432
none
---
- https://app.asana.com/0/0/1207195854678887
=> Fix Markets SwipeChart

android/app/src/main/java/co/edgesecure/app/MainActivity.kt
On older Android versions, we either lose the ability to take screenshots, or we leave the app visible in the task switcher. There is no middle ground until recently, where they added an API to hide the app in the switcher while allowing screenshots.
none
---
- https://app.asana.com/0/0/1207169437567098
=> Re-enable screenshots on Android

CHANGELOG.md, src/__tests__/modals/CountryListModal.test.tsx, src/__tests__/modals/LogsModal.test.tsx, src/__tests__/modals/TextInputModal.test.tsx, src/__tests__/modals/__snapshots__/AddressModal.test.tsx.snap, src/__tests__/modals/__snapshots__/CountryListModal.test.tsx.snap, src/__tests__/modals/__snapshots__/LogsModal.test.tsx.snap, src/__tests__/modals/__snapshots__/PasswordReminderModal.test.tsx.snap, src/__tests__/modals/__snapshots__/TextInputModal.test.tsx.snap, src/components/modals/AddressModal.tsx, src/components/modals/CategoryModal.tsx, src/components/modals/ListModal.tsx, src/components/modals/LogsModal.tsx, src/components/modals/PasswordReminderModal.tsx, src/components/modals/TextInputModal.tsx, src/components/scenes/DevTestScene.tsx, src/components/themed/FilledTextInput.tsx, src/types/FormTypes.ts
- Retained total margins for the most part. Prioritizing consistency over 100% retaining original margins.
- `PasswordReminderModal`, `TextInputModal`: Changes might look like they're losing vertical margins between `FilledTextInput` and buttons, but using the new standard `ModalButtons` takes care of that by providing extra top button margins.
- Added unit tests for changed modals that had no coverage
https://github.com/EdgeApp/edge-react-gui/pull/5009
---
- https://app.asana.com/0/0/1206366276415248
=> Standard FilledTextInput Modal Margins

src/components/settings/SettingsRow.tsx
The `useAnimatedStyle` worklet was capturing `props`, which includes `props.children`. Since Reanimated calls `Object.freeze` on any captured values, the React runtime dies because it cannot modify things it expects to modify.
none
---
- https://app.asana.com/0/0/1207319673522842
=> Fix the settings row crash

src/components/common/SceneWrapper.tsx, src/components/themed/FilledTextInput.tsx, src/components/themed/FlipInput2.tsx, src/components/themed/MenuTabs.tsx, src/components/themed/SimpleTextInput.tsx, src/hooks/useSharedEvent.ts, src/plugins/gui/scenes/AddressFormScene.tsx, src/state/SceneFooterState.tsx
The Babel plugin auto-detects worklet dependencies, so according to the documentation, passing these lists is superflous. They are only needed on the web, when the Babel plugin is missing.
none
---
- https://app.asana.com/0/0/1207319749532395
=> Remove superfluous dependency lists from reanimated

src/components/scenes/WalletListScene.tsx, src/components/themed/SceneFooterWrapper.tsx, src/components/themed/SearchFooter.tsx
none
---
- https://app.asana.com/0/0/1207403013474769
=> Add back missing key prop for SceneWrapperFooter to fix rendering

CHANGELOG.md, src/actions/ScamWarningActions.tsx
Pending further refinement
none
---
- https://app.asana.com/0/0/1207395879537966
=> Comment out new ScamWarning

src/components/Main.tsx, src/components/scenes/GettingStartedScene.tsx
This happened because the getting-started scene would navigate back to the login scene. Instead of navigating inside an effect, just set up the initial route prop correctly.
none
---
- https://app.asana.com/0/0/1207446566171049
=> Fix the stuck spinner on login

src/components/Main.tsx, src/components/themed/SideMenu.tsx
Unclear what dependencies changed to make this issue surface, but we just got lucky before.
This change properly flexes the side menu
Updates to RN/RN Navigation are likely the culprit. Likely some defaults were changed, and in combination with our 
Since the `Drawer` itself is absolutely positioned and does translations to `right` under the hood, we cannot rely on flex and must set a specific width. 
Without setting an explicit width, though the side menu appears properly sized, the drawer itself takes up extra invisible horizontal space to the left of the menu. This extra horizontal space is not tappable and prevents the side menu from closing when tapping outside of the menu.
Below are after the updates:
none
If you have made **any** …
=> Properly size and flex the side menu

src/hooks/useWalletConnect.tsx
You don't actually need to support that events you just need to pretend to. We already do this with the other WalletConnect chains so we can do it for Cosmos, too.
---
- https://app.asana.com/0/0/1207489271357886
=> Add events to Cosmos WalletConnect supported namespaces

src/components/scenes/GettingStartedScene.tsx, src/components/scenes/SwapProcessingScene.tsx, src/components/themed/SafeSlider.tsx, src/components/themed/Slider.tsx
The use of `navigation.navigate` to pop back to a scene in the stack has
been deprecate behavior in react-navigation v7.
none
---
- https://app.asana.com/0/0/1205615584416006
=> Fix Swap Scene bugs

src/components/scenes/GuiPluginListScene.tsx, src/components/services/Services.tsx
React Navigation v7 caused the regression. Services and tabs mount twice immediately on login now.
Apply hack fixes to known problem areas as an interim fix
none
---
- https://app.asana.com/0/0/1207497117195103
=> React Navigation v7 Hack fixes

jest.config.js, jestSetup.js, src/components/common/SceneWrapper.tsx
Our header-height calculation was getting different results than react-navigation, leading to a gap. Switching to the `useHeaderHeight` hook causes us to use the same number that react-navigation itself is using, making the calculation moot. One difference is that this hook includes the top safe area inset in the height, so we need to stop adding that in separately.
none
---
- https://app.asana.com/0/0/1207515890919849
=> Use the header dimensions from `useHeaderHeight`

src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap, src/actions/CreateWalletActions.tsx, src/actions/LocalSettingsActions.ts, src/actions/LoginActions.tsx, src/actions/TokenTermsActions.tsx, src/components/scenes/CreateWalletCompletionScene.tsx, src/components/scenes/CreateWalletSelectCryptoScene.tsx, src/components/themed/ManageTokensRow.tsx, src/components/themed/WalletListCreateRow.tsx, src/types/types.ts
Token warning now:
- Does NOT show after wallet creation completes
- Shows immediately when toggling to enable a token
- Shows once per chain/currency plugin instead of once per wallet
none
---
- https://app.asana.com/0/0/1207532762643127
=> Token Warning Updates

CHANGELOG.md, src/components/scenes/WcConnectScene.tsx, src/components/scenes/WcConnectionsScene.tsx
Passing a wallet into the scene means we don't need to use redux selected wallet ID
---
- https://app.asana.com/0/0/1207574551270982
=> WalletConnect: Select wallet before navigating to connect scene

CHANGELOG.md, src/components/scenes/GuiPluginViewScene.tsx, src/components/scenes/WebViewScene.tsx, src/plugins/gui/scenes/FiatPluginWebView.tsx
BitRefill specifically was going through GuiPluginViewScene, though the fix was applied to various WebViews.
none
---
- https://app.asana.com/0/0/1207393172981960
=> Add "avoidKeyboard" in GuiPluginViewScene, WebViewScene, FiatPluginWebView

CHANGELOG.md, src/components/scenes/CreateWalletSelectCryptoScene.tsx, src/selectors/getCreateWalletList.ts
LTC split: 
Normal create:
https://github.com/EdgeApp/edge-currency-plugins/pull/407
---
- https://app.asana.com/0/0/1207269774668906
=> Disallow (no-segwit) split option

src/components/scenes/WcConnectScene.tsx
none
---
- https://app.asana.com/0/0/1207518013887811
=> Apply `withWallet` to `WcConnectScene`

CHANGELOG.md, src/components/services/ContactsLoader.ts, src/envConfig.ts, src/util/corePlugins.ts
https://github.com/EdgeApp/edge-exchange-plugins/pull/330
---
- https://app.asana.com/0/0/1207641048632575
=> Enable Rango Exchange swap plugin

CHANGELOG.md, package.json, src/components/scenes/LoginScene.tsx, yarn.lock
Fixes red error due to server outage
none
---
- https://app.asana.com/0/0/1207673266723881
=> Remove react-native-check-version

src/components/services/AccountCallbackManager.tsx
This ensures we get rates as soon as the wallets are loaded and we don't wait until the next 30s rates query.
On the iOS simulator, this PR changes the amount of time for the Total Balance card to show a balance from 25s to 4s
none
---
- https://app.asana.com/0/0/1207749579877501
=> Immediately reload rates as soon as the wallet list changes

src/components/scenes/Loans/LoanDashboardScene.tsx, src/util/CurrencyInfoHelpers.ts
Getting rid of this helper function actually leads to simpler code. We were doing a doing a super-inefficient O(n^2) loop when a simple key-value lookup would have been enough.
none
It's hard to test this without AAVE being present.
---
- https://app.asana.com/0/0/1207670071437624
=> Remove the `getCurrencyInfos` helper function

src/actions/ReceiveDropdown.tsx
We can't use `useSelector` in a redux action.
none
---
- https://app.asana.com/0/0/1207760128838465
=> Restore missing receive drop-down

ios/edge/Info.plist
We received an App Store warning about this. Destop arm64 users need to have a correct version number. Without this info, the App store auto-guesses the supported version.
none
The only way to test this is to upload a version to the store.
---
- https://app.asana.com/0/0/1207653199428272
=> Increase our minimum MacOS version to 13.0

src/actions/LoginActions.tsx, src/components/scenes/GettingStartedScene.tsx
Various hack-ish fixes for iOS and Android to resolve logout routing, and a fix to the getting started button for Android no longer working somehow
none
---
- https://app.asana.com/0/0/1207787615031270
=> Fix logout routing for all cases

CHANGELOG.md, src/components/charts/SwipeChart.tsx, src/components/data/row/CoinRankRow.tsx, src/components/scenes/CoinRankingDetailsScene.tsx, src/components/scenes/CoinRankingScene.tsx, src/components/ui4/MarketsCardUi4.tsx, src/hooks/useFiatText.ts, src/util/utils.ts
Fix non-usd fiat setting support.
- Fall back to USD for non-CoinGecko-supported fiat currencies
- Fix various string formattings
- Fix errors on opening the Markets scenes
https://github.com/EdgeApp/edge-rates-server/pull/102
---
- https://app.asana.com/0/0/1207648985179833
=> Fix Markets Scenes

src/components/Main.tsx
We need to push the buy / sell SEPA scenes into the buy / sell tabs, so the `navigation.pop` can correctly remove them. Otherwise, calling `navigation.pop` will remove the plugin list scene itself, followed by removing the main app, because the scenes we want to remove are on a different tab.
none
---
- https://app.asana.com/0/0/1207822127480559
=> Move buy / sell scenes into the right tabs

CHANGELOG.md, src/components/scenes/GettingStartedScene.tsx, src/components/scenes/LoginScene.tsx
Ensure we always only have either login or gui stacks mounted
none
---
- https://app.asana.com/0/0/1207848254943124
=> Fix login routing 2

src/components/Main.tsx, src/types/routerTypes.tsx
We want to put the leaf navigators at the top, and the parent navigators below. That way, when eventually tighten up the types, we can mention the child navigator's type when we describe the parent navigator's type.
none
---
- https://app.asana.com/0/0/1207860741273233
=> Router sorting

CHANGELOG.md, src/components/scenes/CoinRankingScene.tsx
Previously, the fetch would start at 0 no matter what when scrolling to the end of the list, so each additional page takes longer.
1. New pages are loaded faster, and fetches don't overlap with one another
2. Fiat setting changes are properly handled regardless of cached data
none
---
- https://app.asana.com/0/0/1207750010733325
=> Improve scrolling fetching

CHANGELOG.md, src/plugins/gui/providers/bityProvider.ts
A generic signing function that doesn't expect a specific encoding per plugin
https://github.com/EdgeApp/edge-core-js/pull/605
=> Use newly implemented signBytes() instead of signMessage()

CHANGELOG.md, src/components/common/EdgeCarousel.tsx
A known issue with a built-in workaround for `react-native-snap-carousel.`
none
---
- https://app.asana.com/0/0/1207973610789783
=> Fix EdgeCarousel's first render

CHANGELOG.md, src/__tests__/components/__snapshots__/FilledTextInput.test.tsx.snap, src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap, src/__tests__/modals/__snapshots__/CountryListModal.test.tsx.snap, src/__tests__/modals/__snapshots__/LogsModal.test.tsx.snap, src/__tests__/modals/__snapshots__/TextInputModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/components/themed/FilledTextInput.tsx
In Android, TextInput context menus break specifically when setting both `autoCapitalize="none"` and `secureTextEntry=false`
Ensure we always keep `secureTextEntry` on the React Native component `undefined` unless explicitly true.
none
=> Fix FilledTextInput using `autoCapitalize` for Android

src/components/scenes/TransactionListScene.tsx
Broken after removing the "drag down to search" feature.
Reinstate a gutted `refreshControl` to `Animated.FlatList` props
Several props are populated on this component, any of them could be causing some sort of Android-specific conflict.
Since we _do_ know that this broken when refreshControl was removed, just add it back with no functionality.
none
---
- https://app.asana.com/0/0/1208100508540956
=> Fix Android TransactionList Scroll Gestures

CHANGELOG.md, src/plugins/gui/amountQuotePlugin.ts
none
---
- https://app.asana.com/0/0/1208118584277144
=> Light Account: $50 USD Default Fiat Buy

CHANGELOG.md, src/components/scenes/Fio/FioAddressRegisterSelectWalletScene.tsx, src/components/scenes/Fio/FioRequestConfirmationScene.tsx, src/components/scenes/LoginScene.tsx, src/components/scenes/SettingsScene.tsx, src/components/scenes/Staking/StakeModifyScene.tsx
Often we are already showing some sort of error on the scene itself, or the error is attached to a simple info-only situation
none
---
- https://app.asana.com/0/0/1207474082380292
=> 2nd pass of unecessary showErrors on scenes

CHANGELOG.md, src/components/themed/TransactionListTop.tsx
Mainnet assets were not properly being accounted for
none
---
- https://app.asana.com/0/0/1208094537055699
=> Fix TransactionListTop default swap asset logic

CHANGELOG.md, src/plugins/gui/providers/bityProvider.ts
none
---
- https://app.asana.com/0/0/1207999015284787
=> Restrict bity to no-KYC assets

src/components/services/AccountCallbackManager.tsx
This suppresses any errors from this background task (specifically the
404 error from FIO's fetchFioAddresses method).
none
---
- https://app.asana.com/0/0/1208215298507086
=> Silently fail refreshConnectedWallets in AccountCallbackManager

CHANGELOG.md, src/actions/ScanActions.tsx
none
---
- https://app.asana.com/0/0/1208107373867083
=> Allow private key sweep in light accounts for amounts less than $50

CHANGELOG.md, src/components/scenes/SwapCreateScene.tsx, src/components/themed/ExchangedFlipInput2.tsx
none
---
- https://app.asana.com/0/0/1208195470799424
=> Fix display bug caused by flipping inputs on SwapCreateScene

CHANGELOG.md, src/components/scenes/SwapCreateScene.tsx, src/components/scenes/SwapProcessingScene.tsx
Minor changes: the original spec was not exhaustive. Amounts are also relevant to certain errors, not just the assets selected.
(Potentially) Amount-related errors:
```
'Entered amount plus fees exceeds wallet balance.' 
'Amount is above the max limit of %1$s %2$s. This max limit is subject to change based on market conditions'
Amount is below the min limit of %1$s %2$s. This min limit is subject to change based on market conditions
```
(Potentially) Asset-related errors:
```
No enabled exchanges support %1$s to %2$s.
Location restricted. Unable to complete exchange.
```
none
---
- …
=> Clear previous swap errors when entering new amounts or assets

CHANGELOG.md, src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap, src/components/tiles/AddressTile2.tsx
Was possible to tap the card-wide touch area when enter/myself/scan/paste icons were visible
none
---
- https://app.asana.com/0/0/1208060267886365
=> Fix press handling on AddressTile2

CHANGELOG.md, src/components/scenes/EditTokenScene.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json
Also remove case of overriding a built-in tokenId
---
- https://app.asana.com/0/0/1208105698943626
=> Use `currencyConfig.getTokenId` instead of `addCustomToken` hack

CHANGELOG.md, src/actions/CategoriesActions.ts, src/components/services/ContactsLoader.ts, src/envConfig.ts, src/util/corePlugins.ts
https://github.com/EdgeApp/edge-exchange-plugins/pull/341
---
- https://app.asana.com/0/0/1208356966046148
=> Add Maya Protocol

CHANGELOG.md, src/actions/WalletActions.tsx, src/components/scenes/ConfirmScene.tsx, src/components/scenes/TransactionListScene.tsx, src/components/themed/MainButton.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json
This is to resolve an issue where the wallet state hasn't completed
checking if a newly added token is activated or not. This means the
user can enter the transaction list scene without activating the wallet.
In that case, we'll at least navigate in retrospect.
Watch for changes to the `unactivedTokenIds` property on the wallet.
If the tokenId within the transaction list appears in the
`unactivedTokenids` array, then we'll properly handle the activation
user journey.
none
---
- https://app.asana.com/0/0/1208383880746617
=> Dispatch `activateWalletTokens` from TransactionListScene

CHANGELOG.md, src/components/themed/SideMenu.tsx
Android cannot ellipsize text when font scaling is in effect, so font scaling is disabled for Android.
none
---
- https://app.asana.com/0/0/1208392906130444
=> Fix long username cutoff not showing ellipses

CHANGELOG.md, src/plugins/gui/fiatPlugin.tsx, src/plugins/gui/fiatPluginTypes.ts, src/plugins/gui/scenes/AddressFormScene.tsx, src/plugins/gui/scenes/InfoDisplayScene.tsx, src/plugins/gui/scenes/SepaFormScene.tsx, src/types/routerTypes.tsx
none
---
- https://app.asana.com/0/0/1208412342196765
=> Move scene param types to their respective fiat plugin scene files

CHANGELOG.md, src/components/scenes/SweepPrivateKeyCalculateFeeScene.tsx
none
---
- https://app.asana.com/0/0/1208056566426971
=> Use account default fiat for transaction fee display in `SweepPrivateKeyCalculateFeeScene`

CHANGELOG.md, src/components/modals/WcSmartContractModal.tsx
none
---
- https://app.asana.com/0/0/1207763168583636
=> Call signTx after signing or broadcasting transactions from WalletConnect

CHANGELOG.md, src/actions/WalletListMenuActions.tsx, src/components/modals/WalletListMenuModal.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json
none
---
- https://app.asana.com/0/0/1208306014567567
=> Add "Go to Parent Wallet" wallet menu option

src/components/scenes/SwapSuccessScene.tsx, src/components/scenes/TransactionDetailsScene.tsx
none
---
- https://app.asana.com/0/0/1208620532667214
=> Fix routing for swap flow

scripts/makeNativeHeaders.ts, src/actions/NotificationActions.ts, src/components/services/EdgeCoreManager.tsx, src/envConfig.ts, src/util/PushClient/PushClient.ts
none
---
- https://app.asana.com/0/0/1208425702564709
=> HMAC API keys

CHANGELOG.md, src/components/scenes/SwapProcessingScene.tsx, src/components/services/EdgeCoreManager.tsx, src/util/tracking.ts
none
---
- https://app.asana.com/0/0/1206334009226435
=> Add swap error logging to Sentry

CHANGELOG.md, src/components/services/AirshipInstance.tsx, src/components/services/EdgeCoreManager.tsx, src/plugins/gui/amountQuotePlugin.ts, src/plugins/gui/fiatProviderTypes.ts, src/util/addMetadataToContext.ts, src/util/normalizeError.ts, src/util/tracking.ts, src/util/translateError.ts
https://github.com/EdgeApp/edge-react-gui/pull/5322#pullrequestreview-2396571473
---
- https://app.asana.com/0/0/1206334009226436
=> Log unhandled FiatProviderError errors

src/components/scenes/SwapSuccessScene.tsx
none
---
- https://app.asana.com/0/0/1208641019361782
=> Fix transaction details navigation from SwapSuccessScene

CHANGELOG.md, src/plugins/gui/providers/kadoProvider.ts
none
---
- https://app.asana.com/0/0/1208676607688447
=> Add `hideDepositDetails` to WidgetParams for Kado integration

src/components/scenes/Staking/EarnScene.tsx, src/components/scenes/Staking/StakeOptionsScene.tsx, src/components/themed/TransactionListTop.tsx, src/plugins/stake-plugins/generic/GenericStakePlugin.ts, src/plugins/stake-plugins/generic/policyAdapters/EthereumKilnAdaptor.ts, src/plugins/stake-plugins/generic/policyAdapters/GlifInfinityPoolAdapter.ts, src/plugins/stake-plugins/types.ts, src/plugins/stake-plugins/uniswapV2/uniV2Plugin.ts, src/util/stakeUtils.ts
none
---
- https://app.asana.com/0/0/1208691894373413
=> Earn scene loop handling adjustments

CHANGELOG.md, src/components/scenes/SwapCreateScene.tsx, src/components/themed/FlipInput2.tsx, src/components/themed/SwapInput.tsx
none
---
- https://app.asana.com/0/0/1208401503658333
=> Fix amount bug after changing wallet for SwapCreateScene SwapInput

src/components/scenes/DefaultFiatSettingScene.tsx, src/components/scenes/WalletListScene.tsx, src/constants/plugins/sellPluginList.json
none
---
- https://app.asana.com/0/0/1208741639032717
=> More small fixes

src/__tests__/utils/ProviderSupportStore.test.ts, src/plugins/gui/providers/ProviderSupportStore.ts, src/plugins/gui/providers/bityProvider.ts, src/plugins/gui/providers/common.ts, src/util/cleaners.ts
none
Example is support store for bity.
```json
{
"*": {
"AT": true,
"BE": true,
"BG": true,
"CH": true,
"CZ": true,
"DK": true,
"EE": true,
"FI": true,
"FR": true,
"DE": true,
"GR": true,
"HU": true,
"IE": true,
"IT": true,
"LV": true,
"LT": true,
"LU": true,
"NL": true,
"PL": true,
"PT": true,
"RO": true,
"SK": true,
"SI": true,
"ES": true,
"SE": true,
"HR": true,
"LI": true,
"NO": true,
"SM": true,
"GB": true,
"*": {
"*": {
"sepa": {
"bitcoin:null": true,
"ethereum:null": true,
"ethereum:a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48": true,
"ethereum:dac17f958d2ee523a2206206994597c13d831ec7": true
}
}
}
},
"sell": { "*": { "iso:CHF": { "sepa": true }, "iso:EUR": { …
```
=> Implement SupportedAssetStore for bityProvider

src/__tests__/components/__snapshots__/MenuTabs.test.tsx.snap, src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap, src/__tests__/modals/__snapshots__/CountryListModal.test.tsx.snap, src/__tests__/modals/__snapshots__/HelpModal.test.tsx.snap, src/__tests__/modals/__snapshots__/LogsModal.test.tsx.snap, src/__tests__/modals/__snapshots__/TextInputModal.test.tsx.snap, src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap, src/__tests__/scenes/__snapshots__/SwapConfirmationScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/SwapCreateScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/SwapSuccessScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap, src/components/common/BlurBackground.tsx, src/components/navigation/HeaderBackground.tsx, src/components/themed/MenuTabs.tsx
This regressed as a result of changes to support rounded blur corners for iOS in the latest `NotificationCard` updates (66b4bdd).
none
---
- https://app.asana.com/0/0/1208710423836257
=> Fix incorrect rounded corners on iOS

src/__tests__/components/__snapshots__/MenuTabs.test.tsx.snap, src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap, src/__tests__/modals/__snapshots__/CountryListModal.test.tsx.snap, src/__tests__/modals/__snapshots__/HelpModal.test.tsx.snap, src/__tests__/modals/__snapshots__/LogsModal.test.tsx.snap, src/__tests__/modals/__snapshots__/TextInputModal.test.tsx.snap, src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap, src/__tests__/scenes/__snapshots__/SwapConfirmationScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/SwapCreateScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/SwapSuccessScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap, src/components/common/BlurBackground.tsx
none
---
- https://app.asana.com/0/0/1208743699951543
=> Fix styling in `BlurBackground.tsx`

CHANGELOG.md, src/plugins/gui/scenes/FiatPluginEnterAmountScene.tsx
none
---
- https://app.asana.com/0/0/1208615827323069
=> Handle light account backup while on `FiatPluginEnterAmountScene`

.gitignore, scripts/deploy.ts, scripts/secretFiles.ts
none
---
- https://app.asana.com/0/0/1208791835386251
=> Use Fastlane API-key authentication

CHANGELOG.md, src/components/scenes/TransactionDetailsScene.tsx, src/constants/WalletAndCurrencyConstants.ts
none
---
- https://app.asana.com/0/0/1208779233688498
=> Add support for LLD tx history

CHANGELOG.md, src/components/services/EdgeCoreManager.tsx
Because Sentry's default fingerprint algorithm is based on stack-traces,
we need to add additional tagging for custom fingerprint rules for
issue grouping based on the tag and event message.
We'll filter using the error name (EdgeCrashEvent), and we'll group by
error message and the source tag.
We cannot group by context data, but
we'll add all the data from the event in a scope's context for easy
reference when reviewing issues.
none
---
- https://app.asana.com/0/0/1208383880746610
=> Improve EdgeCrashEvent reporting

CHANGELOG.md, src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/components/modals/WalletListModal.tsx, src/components/themed/SimpleTextInput.tsx
https://github.com/user-attachments/assets/f36bd194-9f0a-4f3c-b790-054b6f66740e
none
---
- https://app.asana.com/0/0/1208782217930336
=> Implement iOS "Cancel" button

CHANGELOG.md, src/components/text/FiatText.tsx, src/components/themed/TransactionListTop.tsx, src/constants/WalletAndCurrencyConstants.ts
none
---
- https://app.asana.com/0/0/1208848967378659
=> Deprecate Binance Beacon Chain

CHANGELOG.md, src/components/scenes/WalletListScene.tsx
none
---
- https://app.asana.com/0/0/1208906064127526
=> Always show Add Wallet button on WalletListScene

CHANGELOG.md, src/util/stakeUtils.ts
none
---
- https://app.asana.com/0/0/1208888909961645
=> Use chain icon for staking cards

src/components/Main.tsx, src/components/themed/SideMenu.tsx
none
---
- https://app.asana.com/0/0/1208887349854068
=> Narrow-down SideMenu props and memoize

src/plugins/gui/providers/banxaProvider.ts, src/plugins/gui/providers/simplexProvider.ts
none
---
- https://app.asana.com/0/0/1208977034875100
=> Patch return URL status

src/components/scenes/Staking/EarnScene.tsx
We were missing loading the staking position for the impending scene
transition.
none
---
- https://app.asana.com/0/0/1208993351823602
=> Fix crash on EarnScene

CHANGELOG.md, src/plugins/stake-plugins/generic/policyAdapters/CoreumStakeKitAdaptor.ts, src/plugins/stake-plugins/generic/util/stakeKitUtils.ts
none
---
- https://app.asana.com/0/0/1208958905936261
=> Add error handling to StakeKit utils

CHANGELOG.md, scripts/cleanDirectories.ts, scripts/deploy.ts
Helps prevent disk full errors
none
---
- https://app.asana.com/0/0/1209011926347186
=> Clean old archive directories on builds

CHANGELOG.md, src/actions/DeepLinkingActions.tsx, src/util/DeepLinkParser.ts
none
---
- https://app.asana.com/0/0/1208022684274583
=> Disallow deprecated wallets from parsing links

CHANGELOG.md, src/components/scenes/GettingStartedScene.tsx, src/experimentConfig.ts
In favor of the 'alreadyHaveAccount' variant
none
---
- https://app.asana.com/0/0/1208949347458626
=> Conclude 'uspSigninCta' experiment

CHANGELOG.md, src/components/scenes/Staking/StakeModifyScene.tsx, src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
https://dev.thorchain.org/saving-guide/quickstart-guide.html#3-send-memoless-savers-transactions
none
---
- https://app.asana.com/0/0/1208980067767534
=> Thorchain Staking - Enforce "dust_thresholds"

CHANGELOG.md, src/actions/CategoriesActions.ts, src/components/services/ContactsLoader.ts, src/envConfig.ts, src/util/corePlugins.ts
https://github.com/EdgeApp/edge-exchange-plugins/pull/360
---
- https://app.asana.com/0/0/1208752773501977
=> Add Unizen DEX

src/components/modals/SurveyModal.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json
"Youtube" is now a sub-option
none
---
- https://app.asana.com/0/0/1209184348523431
=> SurveyModal2 Fix "Social Media" option

src/plugins/gui/providers/mtpelerinProvider.ts, src/plugins/gui/scenes/FiatPluginWebView.tsx
none
---
- https://app.asana.com/0/0/1209107130480799
=> Fix back navigation for Mt Pelerin quotes

CHANGELOG.md, src/plugins/stake-plugins/uniswapV2/policies/VelodromeV2StakePolicy.ts
none
---
- https://app.asana.com/0/0/1208980067767536
=> Include unstaked LP token balance in staked balances

CHANGELOG.md, src/components/scenes/CoinRankingDetailsScene.tsx
**TODO: Fix Earn button functionality**
none
---
- https://app.asana.com/0/0/1208943014243441
=> Markets - Buy/Sell/Earn/Trade Buttons

CHANGELOG.md, src/actions/ReceiveDropdown.tsx, src/components/scenes/WalletDetailsScene.tsx, src/components/themed/TransactionListRow.tsx, src/components/tiles/NetworkFeeTile.tsx, src/hooks/useTokenDisplayData.ts
none
---
- https://app.asana.com/0/0/1209259612887729
=> Fix `useSelector` calls for accessing non-existent `exchangeRates`

src/components/text/AssetChangeText.tsx, src/hooks/useTokenDisplayData.ts
This got fat-fingered in commit 00416fa21822c5aff8e87d114b7746901e2a79f6
none
---
- https://app.asana.com/0/0/1209310446890230
=> Fix broken USD rate lookup

src/components/notification/NotificationView.tsx, src/components/scenes/NotificationCenterScene.tsx, src/components/services/NotificationService.ts, src/util/otpReminder.tsx, src/util/otpUtils.ts, yarn.lock
- Isolate the modals to their own file
- Create a hook to ensure changes to otp disk settings are picked up by
the `NotificationService`
- Pull all logic for otp reminder notification state into `NotificationService`
none
---
- https://app.asana.com/0/0/1209310723615615
=> Fix 2FA/otp Reminder Notification

CHANGELOG.md, src/hooks/useTransactionList.ts
- **Fix yarn.lock**
- **Rename txs identifier**
- **Fix bug with relevant changedTxs set**
none
---
- https://app.asana.com/0/0/1209197463729195
=> Fix transaction metadata loading issues

src/actions/ExchangeRateActions.ts, src/util/utils.ts
Pull request #5423 contained a bunch of logic errors, so clean everything up in a way that makes it less confusing and less buggy.
- Break up long lines.
- Fix misleading comments.
- Give variables better names.
- Don't copy data needlessly.
- Stomp old cache entries instead of mutating them.
- Only add the account fiat pair once, instead of in two separate places.
- Expire cache entries once a load-time, instead of doing this in three separate places.
- Do not store reverse rates in the cache, but derive them at the very end.
- Move `getYesterdayDateRoundDownHour` into this file, since it's only used here.
none
---
- To see the specific tasks where the Asana app for …
=> Reorganize & clean exchange-rate logic

ios/Podfile.lock, patches/react-native-piratechain+0.5.6.patch, react-native.config.js, src/constants/WalletAndCurrencyConstants.ts
Patch is to resolve SQLite related xcode 16 build issues
---
- https://app.asana.com/0/0/1209403345687854
=> Re-enable Piratechain on iOS

CHANGELOG.md, src/constants/WalletAndCurrencyConstants.ts, src/envConfig.ts, src/locales/en_US.ts, src/locales/strings/enUS.json, src/util/corePlugins.ts
- **Fix yarn.lock**
- **Add abstract core plugin**
none
---
- https://app.asana.com/0/0/1209257679727561
=> Abstract L2

CHANGELOG.md, src/plugins/stake-plugins/generic/pluginInfo/ethereumKilnPool.ts
none
---
- https://app.asana.com/0/0/1209253728558845
=> Force max unstake on Kiln ETH positions

CHANGELOG.md, src/__tests__/components/TransactionListRow.test.tsx, src/actions/CategoriesActions.ts
none
---
- https://app.asana.com/0/0/1208274844820487
=> Correct the `displayName` in `getTxActionDisplayInfo`

CHANGELOG.md, src/components/themed/FilledTextInput.tsx
By setting a selection using setNativeProps, the input forces the
selection continuously. We need to unset the selection once the user
has change the text on the input.
none
---
- https://app.asana.com/0/0/1209373617256156
=> Remove selection after text change

CHANGELOG.md, src/__tests__/components/__snapshots__/FilledTextInput.test.tsx.snap, src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap, src/__tests__/modals/__snapshots__/CountryListModal.test.tsx.snap, src/__tests__/modals/__snapshots__/LogsModal.test.tsx.snap, src/__tests__/modals/__snapshots__/TextInputModal.test.tsx.snap, src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/components/themed/FilledTextInput.tsx, src/components/themed/SimpleTextInput.tsx
The reason for this change is to fix bugs on Android related to
controlled TextInput components. Cursor placement is not accurate when
entering text for a controlled TextInput on Android.
A semi-controlled component is one where the value of the input is
controlled by the component imperatively; not declaratively. This is
done via the `setNativeProps` method on the TextInput.
This is a nice solution because it abstracts away the imperative nature
of an uncontrolled component (TextInput) with a parent controlled
component (SimpleTextInput/FilledTextInput).
none
---
- …
=> Make text input components semi-controlled

CHANGELOG.md, src/components/cards/SwapDetailsCard.tsx
Dynamically populate txId in `SwapDetailsCard` if a "{{TXID}}" tag is found in the `orderUri`
none
---
- https://app.asana.com/0/0/1209129210512692
=> Update SwapDetailsCard to handle {{TXID}} tags

CHANGELOG.md, src/__tests__/components/__snapshots__/CurrencyIcon.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletEditNameScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap, src/components/icons/CryptoIcon.tsx, src/components/icons/WalletIcon.tsx
Regressed from 0fdff1c
- x] Yes
none
---
- https://app.asana.com/0/0/1209555807611142
=> Fix `CryptoIcon's` secondary icon

CHANGELOG.md, src/components/scenes/CoinRankingDetailsScene.tsx
Can probably fully remove `stakingWallets,` but making a low-impact change for now.
none
---
- https://app.asana.com/0/0/1209408349186154
=> Improve loading time for Earn button

src/__tests__/components/__snapshots__/FilledTextInput.test.tsx.snap, src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap, src/__tests__/modals/__snapshots__/CountryListModal.test.tsx.snap, src/__tests__/modals/__snapshots__/LogsModal.test.tsx.snap, src/__tests__/modals/__snapshots__/TextInputModal.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap, src/__tests__/utils/intl.ts, src/components/themed/FilledTextInput.tsx, src/plugins/gui/scenes/FiatPluginEnterAmountScene.tsx
The `FilledTextInput` component was relying on a child component to handle its number formatting, but that component is incompatible with our new semi-controlled approach. Just use the intl utility functions to provide the same behavior directly.
none
---
- https://app.asana.com/0/0/1209567077707086
=> Fix numeric input mode for FilledTextInput

src/components/themed/TransactionListTop.tsx
none
---
- https://app.asana.com/0/0/1209672347131720
=> Use `getStakePlugins` instead of `walletStakingState`

CHANGELOG.md, src/plugins/stake-plugins/generic/policyAdapters/CardanoKilnAdaptor.ts
Kiln can sometimes send Cardano transaction with spend UTXOs when Kiln's network state is out of sync. We can protect from this if the engine gives information about the spend-ability of the transaction.
https://github.com/EdgeApp/edge-currency-accountbased/pull/914
---
- https://app.asana.com/0/0/1209540063113868
=> Protect against unspendable staking transactions

src/actions/ExchangeRateActions.ts
none
---
- https://app.asana.com/0/0/1209766448150961
=> Use a redux value to determine if we need to load rates from disk

CHANGELOG.md, src/components/common/EdgeCarousel.tsx
Locale-specific data isn't immediately avialable before `countryCode` loads and when this happens, `EdgeCarousel` doesn't react
none
---
- https://app.asana.com/0/0/1208440993939949
=> React to data changes in `EdgeCarousel`

CHANGELOG.md, src/components/common/EdgeCarousel.tsx
This affects only iOS only when there is exactly one card. 
This is the conflict between the original rendering hack that was required to get iOS to work with exactly 1 card and the recent fix for: Home - Fix blogPostsGeo (swapix article) https://app.asana.com/0/1200234943382353/1208440993939949/f
none
---
- https://app.asana.com/0/0/1209868735707894
=> Remove iOS rendering hack in `EdgeCarousel`

CHANGELOG.md, src/components/common/SceneWrapper.tsx
For scenes that don't avoid the keyboard, the scene boundaries should never change.
none
---
- https://app.asana.com/0/0/1209438524785867
- https://app.asana.com/0/0/1209551697973955
=> Make bottom insets static if the scene does not `avoidKeyboard`

CHANGELOG.md, src/components/notification/NotificationCard.tsx, src/components/notification/NotificationView.tsx
none
---
- https://app.asana.com/0/0/1210037451254556
=> Add Maestro `testID` support in `NotificationCard`

src/components/scenes/DuressModeHowToScene.tsx, src/util/parseMarkdown.tsx
The problem was caused by using Text element `Paragraph` as the container element for the entire markdown block. We shouldn't nest Text elements with the exception of inline-elements necessary for emphasis, bold, etc.
none
---
- https://app.asana.com/0/0/1210118083810748
=> Fix Android display bugs in DuressModeHowToScene

CHANGELOG.md, src/components/scenes/GettingStartedScene.tsx
Somehow the styling used was causing the button to move with the animation. Using an absolute style with some adjustments to retain the look of the scene before changes.
none
---
- https://app.asana.com/0/0/1210151007813283
=> Anchor the primary button on `GettingStartedScene`

CHANGELOG.md, src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap, src/components/scenes/SettingsScene.tsx, src/components/scenes/SpendingLimitsScene.tsx
none
---
- https://app.asana.com/0/0/1210231939720696
=> Lock spending limits settings row by password

CHANGELOG.md, src/components/themed/TransactionListRow.tsx
We used to morph between sync text and a timestamp prior to https://github.com/EdgeApp/edge-react-gui/pull/5519. Now that we split those elements, we need to show them both at once.
none
---
- https://app.asana.com/0/0/1210252740635119
=> Add timestamp while syncing

src/actions/LogActions.tsx, src/actions/LoginActions.tsx, src/components/modals/LogsModal.tsx
none
---
- https://app.asana.com/0/0/1210210161761264
=> We're not in Kansas anymore

CHANGELOG.md, src/components/scenes/EditTokenScene.tsx
https://github.com/EdgeApp/edge-core-js/pull/658
https://github.com/EdgeApp/edge-currency-accountbased/pull/936
---
- https://app.asana.com/0/0/1210145057911911
=> Use `getTokenDetails` in `EditTokenScene`

CHANGELOG.md, src/plugins/gui/providers/paybisProvider.ts
none
---
- https://app.asana.com/0/0/1209932293457578
=> Fix Paybis min/max regex to also support integers

CHANGELOG.md, ios/Podfile.lock, ios/edge.xcodeproj/project.pbxproj, package.json, src/actions/FirstOpenActions.tsx, src/types/brigad-react-native-adservices.d.ts, src/types/react-native-apple-ads-attribution.d.ts, src/util/tracking.ts, yarn.lock
none
---
- https://app.asana.com/0/0/1210374719087124
=> Apple Ads Attribution (without IDFA)

src/plugins/gui/providers/moonpayProvider.ts
none
---
- https://app.asana.com/0/0/1210446427096845
=> Special case Moonpay/Ripple destination tag handling

CHANGELOG.md, src/plugins/stake-plugins/generic/policyAdapters/EthereumKilnAdaptor.ts, src/plugins/stake-plugins/generic/util/KilnApi.ts
We should correctly show the balance value from Kiln which is in ETH to the user. This will break unstaking because `requestExit` expects a shares amount. So we implement a conversion from ETH to share tokens before unstaking.
none
---
- https://app.asana.com/0/0/1210466283625657
=> Fix ETH Kiln staking balance and unstaking

CHANGELOG.md, src/components/modals/AddressModal.tsx, src/components/tiles/AddressTile2.tsx, src/util/resolveName.ts
This is to support name resolution from the plugin/wallet, specifically for Zano aliases. In the future, all name resolution can be handled by plugins via a standardized `.resolveName` method on the wallet object, but for now it's a drafted API via `otherMethods`.
none
---
- https://app.asana.com/0/0/1210548343287631
=> Resolve names using `wallet.otherMethods.resolveName`

CHANGELOG.md, src/components/notification/NotificationView.tsx
This change makes it so it's never possible to see the password reminder in the NotificationCenterScene, but it's ok because of the extensive pw reminder logic we already have.
none
---
- https://app.asana.com/0/0/1210438561936187
=> Update pw banner dismissal to mimick modal dismissal

CHANGELOG.md, src/components/charts/SwipeChart.tsx
none
---
- https://app.asana.com/0/0/1210455526607540
=> Fix `SwipeChart` reactivity to `assetId` changes

CHANGELOG.md, src/envConfig.ts
none
---
- https://app.asana.com/0/0/1210632259923465
=> Update `OSMOSIS_INIT` type

CHANGELOG.md, src/plugins/gui/providers/moonpayProvider.ts
none
---
- https://app.asana.com/0/0/1210587047210443
=> Add `walletAddress` to moonpay api call for buy quotes

CHANGELOG.md, src/components/scenes/CreateWalletSelectCryptoScene.tsx
none
---
- https://app.asana.com/0/0/1204836492041680
=> Fix maestro button

patches/react-native-vision-camera+4.7.1.patch
They are trying to send a camera-update event before the React Native JS side is ready to receive it.
The upstream bug is: https://github.com/mrousavy/react-native-vision-camera/issues/3609
none
---
- https://app.asana.com/0/0/1211064422811771
=> Fix Android crash in react-native-vision-camera

CHANGELOG.md, src/components/cards/HomeTileCard.tsx, src/components/scenes/HomeScene.tsx, src/locales/en_US.ts, src/locales/strings/enUS.json, src/theme/variables/edgeDark.ts, src/theme/variables/edgeLight.ts, src/theme/variables/testDark.ts, src/theme/variables/testLight.ts, src/types/Theme.ts
Adds a new full-width button between Education Articles and Markets sections
that launches the Bitrefill EdgeProvider webview for purchasing gift cards.
none
---
- https://app.asana.com/0/0/1211152646252610
=> feat: Add Spend Crypto button to Home scene

eslint.config.mjs, src/util/network.ts
https://github.com/EdgeApp/edge-rates-server/pull/115
---
- https://app.asana.com/0/0/1211309911794804
=> Use two rates server lists

CHANGELOG.md, src/actions/CategoriesActions.ts, src/components/services/ContactsLoader.ts, src/util/corePlugins.ts
https://github.com/EdgeApp/edge-currency-plugins/pull/439
https://github.com/EdgeApp/react-native-zano/pull/7
https://github.com/EdgeApp/edge-currency-accountbased/pull/975
https://github.com/EdgeApp/edge-exchange-plugins/pull/402
---
- https://app.asana.com/0/0/1211255931597791
=> Add Bridgeless

CHANGELOG.md, src/__tests__/scenes/__snapshots__/RequestScene.test.tsx.snap, src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap, src/components/scenes/RequestScene.tsx, src/components/tiles/AddressTile2.tsx
none
---
- https://app.asana.com/0/0/1211339212811151
=> Fix long address font scaling

eslint.config.mjs, src/__tests__/scenes/__snapshots__/SwapConfirmationScene.test.tsx.snap, src/components/themed/ExchangeQuoteComponent.tsx, src/components/tiles/NetworkFeeTile.tsx, src/hooks/useFiatText.ts
Also create a new flag `zeroTruncation`, to capture the previous strange behavior. For fiat amounts of 0 and 0.0001, here is how the hook used to behave:
- autoPrecision = true: "0.00" / "0.0001"
- autoPrecision = false: "0" / "0.00"
- autoPrecision = undefined: "0" / "0.0001"
Now the zero handling and small-amount precision handling are explicit & independent.
none
---
- https://app.asana.com/0/0/1211447058372219
=> Default auto-precision to true in `useFiatText`
