EdgeApp/edge-react-gui

src/components/Main.ui.js
src/components/navigation/CurrencySettingsTitle.js
src/components/navigation/TransactionDetailsTitle.js

ui2: Themed Header fixes

---

src/components/themed/WalletListRow.js

ui2: Fix Wallet List Slider responsiveness

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/constants/WalletAndCurrencyConstants.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/Core/Account/settings.js
src/reducers/scenes/SettingsReducer.js

Do not merge until bitcoin and exchange plugins is updated

Change zcoin to firo

---

src/actions/DeepLinkingActions.js

Turning the `handleLink` function async as part of the Azteco integration broke recovery handling. The call sites expect a boolean, not a promise.

Fix deep linking

---

src/__tests__/__snapshots__/sendConfirmation.test.js.snap
src/modules/FioAddress/components/SelectFioAddress.js

Fio Address Select on send themed.

---

src/components/scenes/FioAddressRegisteredScene.js

Fio Address Registered scene themed.

---

src/components/scenes/FioAddressSettingsScene.js

Fio Address Settings scene themed.

---

src/__tests__/__snapshots__/SettingsScene.test.js.snap
src/components/scenes/SwapSettingsScene.js
src/components/themed/SettingsHeaderRow.js
src/components/themed/SettingsRow.js
src/theme/variables/edgeDark.js

ui2: Removed background color and seperators on Settings Scene

---

src/components/themed/AddressTile.js
src/components/themed/Tile.js
src/components/themed/WalletListRow.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/theme/variables/edgeDark.js
src/theme/variables/edgeLight.js
src/types/Theme.js

ui2: New 2.0 design on tiles

---

src/util/corePlugins.js

Re-enable WAX

---

src/components/scenes/GuiPluginViewScene.js

Fix the way we add metadata to Bugsnag reports

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/modules/Core/Account/settings.js

Depends on https://github.com/EdgeApp/edge-currency-accountbased/pull/234

Add AAVE tokens

---

src/components/Main.ui.js
src/components/navigation/EdgeLogoHeader.js
src/components/scenes/WalletListScene.js
src/components/themed/ThemedButtons.js
src/components/themed/WalletList.js
src/components/themed/WalletListEmptyRow.js
src/components/themed/WalletListFooter.js
src/components/themed/WalletListRow.js
src/components/themed/WalletListSortableRow.js
src/components/themed/WiredBalanceBox.js
src/theme/variables/edgeDark.js
src/theme/variables/edgeLight.js

ui2: Wallet List Scene 2.0 design

---

deploy.js

This needs to be pushed to a free test branch before committing, so we know if it works or not.

Add release notes to the appcenter release step

---

src/locales/en_US.js
src/locales/strings/enUS.json

This address the comment on this PR https://github.com/EdgeApp/edge-react-gui/pull/2319

ui2: Remove unused strings

---

src/__tests__/__snapshots__/TransactionDetails.ui.test.js.snap
src/components/scenes/TransactionDetailsScene.js

Transaction Details Scene: Center the category text inside its box

---

package.json
src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json
yarn.lock

Dependent on: https://github.com/EdgeApp/edge-plugin-bity/pull/22

Update Bity description

---

src/components/scenes/GuiPluginListScene.js
src/theme/variables/edgeDark.js
src/theme/variables/edgeLight.js
src/types/Theme.js

FYI: Cannot move partner icons as they are not local files but links to different sites/repos.
Fix to PR https://github.com/EdgeApp/edge-react-gui/pull/2340

ui2: Adding of images the theme files and some minor fixup to PR #2340

---

android/app/src/main/java/co/edgesecure/app/MainApplication.java
ios/edge/AppDelegate.m

I'm not sure how best to test this.

Stop sending console messages with bugsnag reports

---

README.md

- [ x ] n/a
Added bundler to README

Added bundler needed to run in Readme.

---

src/components/navigation/SideMenuButton.js

ui2: Enlarge touchable space of the header right side button

---

src/components/scenes/TransactionDetailsScene.js

- [ x ] Tested on iOS Simulator

Fixed crypto denomination string in Exchange details

---

src/__tests__/__snapshots__/SettingsScene.test.js.snap
src/components/navigation/EdgeLogoHeader.js
src/components/scenes/TransactionListScene.js
src/components/scenes/WalletListScene.js
src/components/themed/EdgeTextField.js
src/components/themed/TransactionListComponents.js
src/components/themed/TransactionListTop.js
src/components/themed/TransactionRow.js
src/components/themed/WalletList.js
src/components/themed/WalletListFooter.js
src/components/themed/WalletListHeader.js
src/components/themed/WalletListRow.js
src/components/themed/WalletListSortableRow.js
src/components/themed/WiredBalanceBox.js
src/locales/en_US.js
src/locales/intl.js
src/locales/strings/enUS.json
src/theme/variables/edgeDark.js
src/theme/variables/edgeLight.js
src/types/Theme.js

NOTE: The commit for arrow icons on Transaction List Scene has a hack to be centered as the whitespace of the icon leans towards the left. See image below:

ui2: Theme 2.0 UI fixes

---

src/components/themed/Tile.js
src/components/themed/TransactionListTop.js
src/components/themed/WalletList.js

ui2 minor fixes

---

src/components/themed/TransactionListTop.js

Fix bug on Transaction List crypto amount not showing when balance is 0

---

src/components/Main.ui.js
src/components/scenes/FioSentRequestDetailsScene.js

FIO. Sent request details header.

---

src/components/scenes/TransactionListScene.js
src/components/scenes/WalletListScene.js
src/components/themed/EdgeTextField.js
src/components/themed/TransactionListComponents.js
src/components/themed/TransactionListTop.js
src/components/themed/WalletList.js
src/components/themed/WalletListHeader.js
src/util/utils.js

ui2: Search List Fixes

---

src/components/scenes/FioRequestListScene.js
src/components/scenes/RequestScene.js
src/modules/UI/scenes/Plugins/EdgeProvider.js

Only set publicAddress when encoding and check legacyAddress when parsing 

---

src/components/themed/TransactionListTop.js

This makes the Wallet Name on the TransactionList Scene tappable to drop down the Wallet Modal selector

Transaction List Wallet Name Selector

---

src/components/themed/EdgeTextField.js
src/components/themed/TransactionListTop.js
src/components/themed/WalletListHeader.js

Also clean up some unnecessary styles.

Fix the styles so the clear and the done button is centered vertically

---

src/components/themed/WalletList.js
src/util/utils.js

Currency name bug fix when searching tokens on Wallet List Scene

---

src/components/navigation/BackButton.js
src/components/navigation/SideMenuButton.js
src/components/themed/HeaderTextButton.js

- Fix some spacings on headers left side to coincide with the theme.rem(1) margins

Fix styles on side menu button/hamburger being cut off when screen size is bigger

---

src/components/modals/WalletListMenuModal.js

Wallet List Scene, Wallet List Options Modal, justify left the currency code with icon

---

src/modules/FioAddress/components/SelectFioAddress.js

Changed styles of Fio address select on send.

---

android/app/src/main/java/co/edgesecure/app/MessagesWorker.java
ios/edge/AppDelegate.m

Check for pending vouchers in the native code

---

src/components/scenes/TransactionListScene.js

Transaction List, Added checks on pull to refresh to be disabled when no transacitons

---

src/components/scenes/SendConfirmationScene.js

no visual changes
not sure what this code does or how to test that it didn't break anything, but this code looks to me like it doesnt change anything
tested on android emulator

Remove unsafe method from SendConfirmation

---

src/components/modals/SwapPreferredModal.js

Themed the Preferred Exchange Modal on Exchange Settings Scene

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/constants/WalletAndCurrencyConstants.js
src/modules/Core/Account/settings.js

Change test btc code to void conflict
To be merged after updating accountbased, exchange, and bitcoin plugins.

Add defi tokens

---

src/modules/Login/action.js

prevent auto creating wallets on non-new accounts

---

src/__tests__/fixtures.json
src/__tests__/utils.test.js
src/components/themed/TransactionListRow.js
src/components/themed/TransactionListTop.js
src/components/themed/WalletList.js
src/modules/UI/components/FlipInput/ExchangedFlipInput2.js
src/util/utils.js

Wallet/Transaction List rows, crypto amount to show correct decimal places

---

src/actions/SettingsActions.js
src/modules/Logs/action.js

Fetch function doesn't throw when there's no connectivity (like airplane mode).

Throw error if there is no internet connectivity to send logs

---

src/components/modals/TransactionAdvanceDetails.js

Put space between the fees used string and the fees

---

src/components/navigation/TransactionDropdown.js

Added currency code at the end of the amount

---

src/locales/strings.js

Must also include PR from login-ui: https://github.com/EdgeApp/edge-login-ui/pull/257

Activate Deutsch (German) language on the locales

---

src/components/modals/WalletListModal.js

Fix bug on wallet list modal where if wallet is created then tries to select it after but created wallet is not yet on the redux state.

---

ios/Podfile
ios/Podfile.lock
package.json
src/__tests__/Scan.ui.test.js
src/__tests__/__snapshots__/RootReducer.test.js.snap
src/__tests__/permissionsReducer.test.js
src/components/services/PermissionsManager.js
src/reducers/PermissionsReducer.js
yarn.lock

Upgraded permissions library and dependent codes on it

---

src/__tests__/Scan.ui.test.js
src/__tests__/__snapshots__/Scan.ui.test.js.snap
src/__tests__/permissionsReducer.test.js
src/components/modals/ScanModal.js
src/components/scenes/ScanScene.js
src/components/services/ContactsLoader.js
testSetup.js

Camera: tested on android hardware
Contacts: tested on android hardware and iOS simulator
Location: I don't think location is used anywhere on the app

Fix bugs where contacts and camera are not being loaded

---

src/components/scenes/SendScene.js

Fix Send Scene amount not showing the correct fiat value

---

src/components/scenes/SendScene.js
src/components/themed/AddressTile.js
src/components/themed/WalletListRow.js

Swiping wallet list row goes to new send scene and opens camera automatically

---

src/components/scenes/SendScene.js

Re-added uniqueIdentifier module on the Send Scene

---

src/components/scenes/SendScene.js

Send Scene: No error showing when no amount on some currencies and slider disabled when there is an error

---

Jenkinsfile

Overriding index triggers to prevent excessive GUI builds.

---

src/components/modals/FlipInputModal.js
src/components/services/Services.js

Note: Remove Modal Close Button. as the Done Button or the check button on the android keyboard does the same thing

Send Scene: Refactor the design Flip Input Modal component

---

src/__tests__/__snapshots__/TransactionDetails.ui.test.js.snap
src/components/modals/TransactionAdvanceDetails.js
src/components/scenes/FioAddressRegisterScene.js
src/components/scenes/FioDomainRegisterScene.js
src/components/scenes/FioSentRequestDetailsScene.js
src/components/scenes/TransactionDetailsScene.js
src/components/themed/AddressTile.js
src/components/themed/Tile.js
src/modules/FioAddress/components/FioActionSubmit.js

Fix Tile styles and component using it

---

src/actions/DeepLinkingActions.js
src/components/scenes/SendScene.js

Note: parseScannedUri function might be improved as it still check selectedWalletId and selectedCurrencyCode

Scan Scene: Fix deepLink payment request

---

src/components/scenes/SendScene.js

Send Scene: Fix width of slider

---

src/components/themed/WalletList.js

Have wallet list throw error when specific crash "Cannot operate on base16 float values" is detected

---

src/actions/SendConfirmationActions.js
src/components/scenes/SendScene.js
src/components/themed/PinDots.js

NOTE: When the pin error occurs upon slide this does NOT reset the slider. This is also happening on the old send confirmation scene and the code does indicate it does not reset the slider.

Send Scene: Added Pin Input module

---

src/components/scenes/SendScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

Added transaction metadata display. Display name used on deeplink

---

src/__tests__/__snapshots__/Request.test.js.snap
src/components/scenes/RequestScene.js
src/components/themed/FlipInput.js
src/components/themed/ShareButtons.js
src/components/themed/ThemedButtons.js

Tweak flip input font sizes

---

src/actions/ScanActions.js
src/components/services/DeepLinkingManager.js
src/util/tracking.js

Deeplink Fixes

---

src/__tests__/__snapshots__/Request.test.js.snap
src/components/scenes/RequestScene.js
src/components/themed/ShareButtons.js

- remove wallet balance
- adjust font size and vertical spacing

Update formatting of request screen to give QR code more space

---

src/components/scenes/RequestScene.js
src/components/themed/ExchangedFlipInput.js
src/components/themed/FlipInput.js

Request scene fix FIO request

---

src/components/services/PermissionsManager.js
src/reducers/PermissionsReducer.js

and make PermissionStatuses use RESULTS based on react-native-permissions

Bug Fix: Remove dispatch on requestPermission

---

src/components/scenes/RequestScene.js
src/components/themed/ExchangedFlipInput.js
src/components/themed/FlipInput.js

Fix tokens not showing the correct icon on Request Scene

---

src/theme/variables/edgeDark.js

Merged along with  https://github.com/EdgeApp/edge-login-ui/pull/275

Change modal color as per new design

---

src/actions/ScanActions.js
src/components/Main.ui.js

Fix bugs that shows buy crypto modal on non selected wallet

---

ios/edge/AppDelegate.m

NOTE: DO NOT MERGE until https://github.com/EdgeApp/edge-login-ui/pull/269 is merged

Remove check notifications permission on app start

---

src/components/modals/AddressModal.js
src/components/scenes/FioAddressRegisterScene.js
src/components/scenes/FioDomainRegisterScene.js
src/components/themed/EdgeTextField.js
src/components/themed/ModalParts.js
src/components/themed/ThemedButtons.js
src/modules/FioAddress/components/DomainListModal.js
src/modules/FioAddress/components/EditNameModal.js
src/theme/variables/edgeDark.js

FIO Domain picker ui2 design.

---

src/actions/TransactionExportActions.js

Fix the CSV export bug

---

src/modules/UI/components/ControlPanel/Component/Main.js

Side Menu to close drawer when on the same page

---

ios/Podfile.lock
src/__tests__/fixtures.json
src/__tests__/utils.test.js
src/components/scenes/SendScene.js
src/components/scenes/TransactionDetailsScene.js
src/components/themed/TransactionListRow.js
src/components/themed/TransactionListTop.js
src/components/themed/WalletList.js
src/util/utils.js

This is for the bugsnag. Bugsnag: utils.js:83

Refactor guiDenominations and apply to Transaction Details Scene

---

src/components/Main.ui.js
src/components/scenes/CreateWalletReviewScene.js
src/components/themed/Tile.js

Create wallet confirmation UI2 design.

---

package.json
src/components/services/ContactsLoader.js
yarn.lock

Fix iOS contact list not showing

---

ios/Podfile.lock
src/components/common/ExchangeRate.js
src/components/scenes/RequestScene.js

Fix warnings that have shouldComponentUpdate() on React.PureComponent

---

src/constants/WalletAndCurrencyConstants.js

On XLM, use a normal keyboard on Memo Id modal on the Send Screen

---

src/actions/TransactionExportActions.js

Fix the QBO export crash

---

src/actions/SendConfirmationActions.js

Send scene update transaction amount. Make sure xrp currency info error code is present

---

src/components/modals/CountrySelectionModal.js
src/components/themed/ModalParts.js

UI2 country picker.

---

package.json
src/components/modals/TransactionAccelerateModal.js
yarn.lock

Fix ETH accelerate tx metadata bug

---

src/components/modals/AddressModal.js
src/components/scenes/FioRequestConfirmationScene.js
src/components/themed/AddressTile.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/FioAddress/util.js

Have checks on Send and Request scene when a FIO address being sent has already expired

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/constants/WalletAndCurrencyConstants.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/Core/Account/settings.js
src/modules/Core/Wallets/action.js
src/util/corePlugins.js

This will remain a draft PR until edge-currency-accountbased is upgraded.

Add Fantom chain

---

src/components/scenes/CryptoExchangeSuccessScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/FioAddress/components/FioActionSubmit.js

Added text for exchange success scene. Fix slider on fio action.

---

src/components/modals/AccelerateTxModel.js
src/components/modals/TransactionAccelerateModal.js
src/components/scenes/TransactionDetailsScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

Clarify fee doubling and show fiat amount for accelerate tx model

---

src/components/Main.ui.js

Add side menu button on the Settings and Terms of Service scenes

---

src/__tests__/__snapshots__/SettingsScene.test.js.snap
src/components/themed/EdgeText.js
src/components/themed/WalletListFooter.js
src/locales/strings/enUS.json

Visual issue on the italian UI - "+ Add token" overlaps "+ add Wallet"

---

src/constants/WalletAndCurrencyConstants.js

Added new currencies that is sweepable

---

src/__tests__/__snapshots__/SettingsScene.test.js.snap
src/components/themed/ThemedButtons.js

Fix text android spacing on themed buttons

---

src/modules/UI/components/Slider/Slider.js
src/util/hooks.js

I haven't figured out how to test these, but the types are based on the docs.

Add Flow type wrappers for the React hooks

---

src/components/themed/Fade.js

https://user-images.githubusercontent.com/68349436/118699591-60f10200-b81a-11eb-910e-c5a14374f567.mov

Use reanimated for the Fade component

---

src/components/scenes/FioRequestListScene.js

FIO - Change order of FIO Requests to show most recent at the top

---

.travis.yml
Jenkinsfile
env.example.json
jest.config.js
jestSetup.js
package.json
webpack.config.js
yarn.lock

Only use Travis to run code-quality checks

---

src/actions/SendConfirmationActions.js

Send Scene: Fix errors not showing up correctly

---

src/components/modals/FlipInputModal.js
src/connectors/components/HeaderMenuExchangeConnector.js

Remove max button for Monero

---

src/modules/FioAddress/util.js

Depends on https://github.com/EdgeApp/edge-currency-accountbased/pull/295

Added new error type when registering FIO name. [HAS DEPENDENCY]

---

src/components/scenes/RequestScene.js
src/locales/en_US.js
src/locales/strings/de.json
src/locales/strings/enUS.json
src/locales/strings/it.json

Implement subject email to share massage

---

src/components/scenes/SendScene.js

Fixed render fees on send conformation scene

---

src/constants/WalletAndCurrencyConstants.js

Import private key
Add custom tokens
Dummy address

Add additional features to FTM

---

src/components/scenes/TransactionDetailsScene.js

Transaction Details Scene. Added checks on transactions native amount

---

src/components/scenes/TransactionDetailsScene.js

Fix btc denomination exchange details

---

src/actions/SendConfirmationActions.js
src/locales/en_US.js
src/locales/strings/enUS.json

Send Scene. High Fee Warning Modal change message

---

src/components/modals/WalletListMenuModal.js
src/constants/WalletAndCurrencyConstants.js

Remove split bch

---

src/modules/Core/Wallets/action.js

- Tokens now appear on first login.

Load tokens when new wallets appear

---

src/components/scenes/FioAddressRegisterScene.js
src/components/scenes/FioAddressSettingsScene.js
src/components/scenes/FioDomainSettingsScene.js
src/modules/FioAddress/components/FioActionSubmit.js

Change FioActionSubmit component to show wallet picker if needed.

Allow FIO name renewals from any FIO wallet

---

package.json
src/__tests__/TransactionExportActions.test.js
src/actions/TransactionExportActions.js
yarn.lock

NOTE: do not merged until https://github.com/EdgeApp/edge-core-js/pull/383 is merged.

CSV transaction export added device description

---

src/actions/ScanActions.js
src/components/modals/paymentProtocolUriReceived.js
src/components/themed/AddressTile.js

Fix/Forgot to connect BIP 70 BitPay URL’s on new send screen AND deep linking from browser

---

.git-blame-ignore-revs

- .git-blame-ignore-revs file to exclude formatting commits

Sam/Git Blame Ignore Revs

---

src/actions/WalletListMenuActions.js
src/locales/en_US.js
src/locales/strings/enUS.json

Add extra message on eth when archiving wallet

---

src/components/themed/EdgeOutlinedField.js
src/components/themed/ManageTokensHeader.js
src/components/themed/TransactionListTop.js

Fix outlined field visual issues

---

.github/workflows/pr-checks.yml
.github/workflows/pr-rebase.yml

- GitHub Workflow using block-wip-pr-action

Sam/Github Workflow

---

src/components/modals/WalletListMenuModal.js
src/constants/WalletAndCurrencyConstants.js
src/util/hooks.js

Refactoring wallet list menu modal

---

src/components/modals/WalletListModal.js
src/components/scenes/CreateWalletNameScene.js
src/components/themed/EdgeOutlinedField.js
src/modules/FioAddress/components/DomainListModal.js

Outlined field size changes

---

src/components/modals/ButtonsModal.js
src/components/modals/ContactsPermissionModal.js
src/components/services/PermissionsManager.js

Android contacts permission

---

src/components/themed/Fade.js

Here I move fixes for Fade component from login-ui

Fix ability of Fade component to hide children after animation

---

src/components/scenes/TransactionsExportScene.js
src/modules/UI/scenes/SendConfirmation/selectors.js

Fix error when spending limit is exceeded

Fix empty export

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/constants/plugins/buyPluginList.json

Moonpay plugin updated info

---

src/components/scenes/FioAddressListScene.js
src/components/themed/Fade.js

When user does not have any fio names and goes to the fio names scene, it would not be redirected to the fio address registration scene now, but would see empty fio names scene.

Do not redirect to address registration when no fio names

---

src/components/services/Services.js

Fix the edge-login-ui-rn Airship stacking order

---

src/util/utils.js

https://user-images.githubusercontent.com/68349436/126503364-63043ce8-94b4-42c5-81da-e5bc573319b8.mov
https://user-images.githubusercontent.com/68349436/126503099-52349b6d-4f05-48f2-8ade-3889ce70acaf.mov
https://user-images.githubusercontent.com/68349436/126503416-5512d21a-5cb0-4676-855d-1203f203f782.mov

Remove unnecessary filter logic when all spaces in the wallet name are removed

---

src/components/scenes/CryptoExchangeSuccessScene.js
src/components/themed/Fade.js
src/hooks/animations/useFadeAnimation.js

https://user-images.githubusercontent.com/68349436/126489051-669d9de3-bea4-4297-8001-78fd7d5eeff0.mov

Add Custom Token UI2: fix fade

---

src/components/themed/ModalParts.js
src/components/themed/SceneHeader.js

Add Custom Token UI2: bold text

---

src/components/themed/Checkbox.js

Add Custom Token UI2: checkbox

---

src/components/modals/MismatchTokenParamsModal.js

Add Custom Token UI2: mismatch modal

---

src/actions/SettingsActions.js
src/components/themed/TransactionListTop.js
src/modules/UI/scenes/SendConfirmation/selectors.js
src/selectors/WalletSelectors.js
src/util/utils.js

Fix convertCurrency function multiplication to use Biggystring

---

src/components/modals/TransactionAdvanceDetails.js
src/locales/en_US.js

Add device name to transaction details

---

src/components/scenes/TransactionDetailsScene.js

Fix getCurrentFiat function on TransactionDetailsScene.js component to use bns operations

---

src/components/themed/EdgeText.js
src/components/themed/WalletListRow.js

Inconsistent text

---

src/components/scenes/CryptoExchangeQuoteScene.js
src/components/scenes/CryptoExchangeScene.js
src/components/themed/Alert.js
src/constants/WalletAndCurrencyConstants.js
src/hooks/useSpacing.js
src/locales/en_US.js

Show minimum balance warning

---

src/components/modals/AutoLogoutModal.js
src/theme/variables/edgeDark.js
src/theme/variables/edgeLight.js
src/types/Theme.js

 AutoLogoutModal text color changes when phone theme is changed

---

src/components/scenes/FioAddressDetailsScene.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/FioAddress/util.js

Expired fio

---

src/components/themed/BlinkingCursor.js
src/components/themed/FlipInput.js
src/hooks/animations/useBlinkAnimation.js

https://user-images.githubusercontent.com/68349436/127688805-b51053ab-91df-4c29-9cd4-5b41ecf86490.mov

Blinking cursor

---

src/components/common/ExchangeRate.js

Fix ExchangeRateComponent functions to use bns operations. Also fixed the prop types

---

src/components/themed/WalletList.js
src/selectors/WalletSelectors.js

Fix convertCurrencyWithoutState function multiplication to use Biggystring

---

src/components/scenes/AddTokenScene.js

Fixed duplicate token warning messages not appearing

---

src/actions/ExchangeRateActions.js
src/actions/ScanActions.js
src/components/scenes/CryptoExchangeScene.js
src/components/scenes/SendScene.js
src/components/themed/ExchangedFlipInput.js
src/components/themed/FlipInput.js
src/components/themed/WalletListCurrencyRow.js
src/modules/FioAddress/util.js
src/modules/UI/components/ControlPanel/ControlPanel.ui.js
src/selectors/WalletSelectors.js
src/util/utils.js

Harden checks for string based numbers

---

src/actions/WalletListMenuActions.js
src/components/modals/RawTextModal.js
src/components/scenes/TransactionDetailsScene.js

Reimplement the raw text modal using modern parts

---

src/components/scenes/SwapSettingsScene.js

Added a tappable icon on preferred exchange on the exchange settings scene

---

src/components/scenes/ManageTokensScene.js

Manage Token Scene updates when adding/deleting custom tokens

---

src/components/scenes/CryptoExchangeScene.js

Change the button label from "Done" to "Next"

---

src/components/modals/WalletListMenuModal.js

Added resync wallet option on tokens

---

src/modules/UI/components/ControlPanel/ControlPanel.ui.js

Close keyboard when opening the Sidemenu

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/__tests__/__snapshots__/spendingLimits.test.js.snap
src/actions/LoginActions.js
src/actions/SettingsActions.js
src/actions/SpendingLimitsActions.js
src/modules/Core/Account/settings.js
src/reducers/SpendingLimitsReducer.js
src/reducers/scenes/SettingsReducer.js
src/types/reduxActions.js
src/types/types.js

Spending Limit per Currency: Add per currency spending limits to redux

---

src/components/scenes/SpendingLimitsScene.js

Spending Limit per Currency: Connect "SpendingLimitsScene" to the plugin-specific spending limits

---

src/components/common/QrPeephole.js
src/components/modals/ScanModal.js
src/hooks/useLayout.js
src/theme/variables/edgeDark.js
src/theme/variables/edgeLight.js
src/types/Theme.js

Fixes for overlay background color and landscape (tablet) layout.

UI2 Scan Design Fixes

---

src/components/Main.ui.js

Remove the tab bar from the request scene

---

src/components/Main.ui.js

Fix the FIO request button navigation

---

src/components/scenes/CryptoExchangeScene.js
src/components/themed/MainButton.js
src/components/themed/MiniButton.js
src/hooks/usePendingPress.js

Replace exchange max with a new mini button component

---

env.example.json
src/util/corePlugins.js

ftmscan.com requires an api key

Add Fantom init options

---

src/components/themed/WalletListSwipeRow.js

Dismiss keyboard when searching and going out of the Wallet List scene

---

src/components/scenes/EditTokenScene.js

Fixed edit token scene crashing

---

src/actions/SendConfirmationActions.js
src/components/scenes/FioDomainSettingsScene.js
src/modules/UI/scenes/SendConfirmation/selectors.js

Create transaction in Send scene with empty amount in defined cases.

Fix FIO name transfer

---

src/actions/CryptoExchangeActions.js
src/components/modals/SwapVerifyTermsModal.js
src/components/scenes/CryptoExchangeQuoteScene.js

Rethemed KYC modal to match new dark theme

---

package.json
webpack.config.js

Use env for webpack mode flag

---

src/components/themed/FlipInput.js

Remove easing on flip input blinking animation

---

src/components/navigation/TransactionDetailsTitle.js

Transaction details time to only have either am or pm

---

src/components/modals/UpdateModal.js
src/components/scenes/LoginScene.js

Rethemed UpdateModal & removed onUpdate prop

---

env.example.json
src/assets/images/exchange/index.js
src/components/modals/SwapVerifyTermsModal.js
src/components/services/ContactsLoader.js
src/theme/variables/edgeDark.js
src/theme/variables/edgeLight.js
src/types/Theme.js
src/util/corePlugins.js

Removed inactive swap partners (Faast and CoinSwitch)

---

src/components/scenes/FioRequestListScene.js

https://user-images.githubusercontent.com/22767467/129910260-0b12aa15-1824-474d-be35-e05844d1e7a2.mp4

Load Fio requests by chunks

---

ios/edge.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings

Build fix for Xcode 13

---

src/actions/LoginActions.js

Close all modals when auto logout is triggered

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/constants/plugins/buyPluginList.json

Moonpay title to add Debit Card

---

README.md

Update the readme with accurate onboarding instructions

---

src/components/themed/FlipInput.js

Flip Input blinking cursor aligned on numerical text

---

src/__tests__/__snapshots__/Request.test.js.snap
src/components/modals/FlipInputModal.js
src/components/scenes/RequestScene.js
src/components/themed/CryptoExchangeFlipInputWrapperComponent.js
src/components/themed/ExchangedFlipInput.js
src/components/themed/FlipInput.js
src/locales/en_US.js
src/locales/strings/enUS.json

Error message when non allowed characters on Flip Input

---

src/actions/TransactionListActions.js
src/components/navigation/TransactionDetailsTitle.js
src/components/scenes/TransactionListScene.js
src/locales/en_US.js
src/locales/intl.js
src/locales/strings/enUS.json
src/types/types.js
src/util/utils.js

Date fns on transactions dateTime

---

src/components/scenes/CryptoExchangeScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

Warning appears if there are insufficient funds for an exchange, prior to pressing next 

---

package.json
src/components/modals/FlipInputModal.js
src/components/scenes/SendScene.js
yarn.lock

https://user-images.githubusercontent.com/4023066/135000889-ab296df0-5ffb-4e19-bf6b-af4a60acd728.mov

Fixed truncated error message text when sending time-locked Monero

---

src/components/scenes/CryptoExchangeScene.js

Do not fetch a quote if the amount exceeds the wallets balance

---

src/components/modals/FlipInputModal.js

Fix android spendable balance error

---

src/constants/WalletAndCurrencyConstants.js

Remove BSV the buy crypto on Transaction List

---

src/components/navigation/HeaderTextButton.js
src/components/navigation/HeaderTitle.js

Text headers style changes (text fontFamily from regular to medium)

---

src/__tests__/__snapshots__/SettingsScene.test.js.snap
src/components/themed/MainButton.js

Main buttons style changes

---

src/components/scenes/CryptoExchangeScene.js

Exchange scene checkExceedsAmount function to use exchangeDenomination.name

---

src/components/themed/ModalParts.js

Change Modal title font face from 'bold' to 'medium'

---

src/components/modals/HelpModal.js

Dismiss Keyboard when help modal is opened

---

package.json
src/actions/TransactionListActions.js
src/actions/WalletActions.js
src/components/scenes/AddTokenScene.js
src/components/scenes/EditTokenScene.js
src/modules/Core/Wallets/EnabledTokens.js
src/reducers/scenes/SettingsReducer.js
src/reducers/scenes/WalletsReducer.js
src/util/utils.js

I removed the usage of lodash and I think I either found a bug or dead code, not sure yet.

Remove usage of lodash

---

src/__tests__/__snapshots__/TransactionDetails.ui.test.js.snap
src/components/scenes/TransactionDetailsScene.js

Done button on Transaction Details

---

src/components/scenes/LoginScene.js

Change the login header font to medium

---

src/components/themed/CryptoFiatAmountTile.js

This is a hotfix commit from Eli to fix lint issues.

Fix lint issues in CryptoFiatAmountTile

---

src/components/modals/WcSmartContractModal.js

This is handled in the plugin so we just need to check that it's there

Remove default gas price

---

patches/@react-native-community+blur+3.6.0.patch

Upgrade to com.eightbitlab:blurview v1.6.6

---

src/components/modals/AccelerateTxModel.js

Sam/Fix/RBF Metadata

---

android/app/build.gradle
android/app/src/main/java/co/edgesecure/app/MainApplication.java
android/app/src/main/java/co/edgesecure/app/MessagesWorker.java

Make MessagesWorker compatible with zcash

---

patches/@react-native-community+blur+3.6.0.patch
src/components/scenes/LoginScene.js
src/components/themed/ThemedModal.js

This fixes the crash on Android 7.1.1 devices.

Switch to a SIMD blur algorithm

---

src/components/scenes/SendScene.js
src/constants/WalletAndCurrencyConstants.js

- Fix noChangeMiningFee
- Add xpub option

ZEC style fixes

---

src/__tests__/__snapshots__/Request.test.js.snap
src/components/modals/QrModal.js
src/components/scenes/RequestScene.js
src/components/themed/QrCode.js

Remove placeholder string for qr code with fade-in effect

---

src/constants/plugins/GuiPlugins.js

Enable recurring buys in the moonpay plugin

---

src/components/modals/CountryListModal.js
src/components/themed/SelectableRow.js

---
- https://app.asana.com/0/0/1201404302089060

Added an "autoWidthContent" flag to allow resizing of only the content

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/modules/Core/Account/settings.js

This is needed to fix the already existing exchange transaction metadata 

Adding settings for "ZADDR" which is sideshifts alias for Zcash.

---

src/components/scenes/ChangeMiningFeeScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

---
- https://app.asana.com/0/0/1201228749540734

Fees scene change warning message title for custom fees

---

env.example.json
src/assets/images/exchange/index.js
src/theme/variables/edgeDark.js
src/theme/variables/edgeLight.js
src/types/Theme.js
src/util/corePlugins.js

---
- https://app.asana.com/0/0/1201230082513464

Remove all totle references

---

src/components/themed/WalletListCreateRow.js
src/components/themed/WalletListFooter.js
src/constants/WalletAndCurrencyConstants.js
src/modules/UI/components/ControlPanel/Component/Main.js

---
- https://app.asana.com/0/0/1200795948081533

Select Crypto wallet when adding token

---

src/components/modals/ButtonsModal.js
src/components/modals/ContactsPermissionModal.js

---
- https://app.asana.com/0/0/1201050090794912

Make contacts permission modal fullscreen

---

src/components/scenes/SendScene.js

---
- https://app.asana.com/0/0/1201456415788821

Refactor the submit method to fix edge cases where it would hang

---

android/app/src/main/AndroidManifest.xml

---
- https://app.asana.com/0/0/1201462538951880

Remove redundant intent filters and add bankid and swish

---

src/components/themed/ControlPanel.js

Decouple old users list from recent users list.
- [x ] Tested on iOS Tablet
- [ x] Tested on small Android
https://user-images.githubusercontent.com/90650827/144953943-fb62c5f2-c873-404d-a602-11be761dc3a7.mp4
---
- https://app.asana.com/0/0/1201475202577111

Fix arrangeUsers()

---

src/components/themed/WalletListCreateRow.js

The previous implementation created the wallet via the
account directly, instead of using the existing workflow
for dispatching and waiting for wallet creation to complete.
Update the WalletListCreateRow to dispatch a call to the
existing wallet creation workflow in createCurrencyWallet.
- [ x] Tested on iOS Tablet
- [ x] Tested on small Android
https://user-images.githubusercontent.com/90650827/145313797-49ad8e10-d396-489c-bc92-e9a35f7b3ebd.mp4
---
- https://app.asana.com/0/0/1201475202577093

Wait for Wallet Creation

---

src/components/scenes/FioRequestListScene.js
src/components/scenes/SendScene.js

https://user-images.githubusercontent.com/4012041/145462355-8b5514a1-08ca-45f6-b8cf-bc58fe1a4c6f.mov
---
- https://app.asana.com/0/0/1201456415788821

Fio request fix

---

src/components/themed/ControlPanel.js

Remove album button 

---

src/components/modals/ScanModal.js

---
- https://app.asana.com/0/0/1200572485189734

Scan modal default to "enable camera access on settings" modal if not granted

---

src/components/scenes/GuiPluginViewScene.js

---
- https://app.asana.com/0/0/1201069587997243

Fix Gui Plugin View bottom gap on bigger screens

---

src/components/themed/OutlinedTextInput.js

Add both a maxLength constraint and a visual counter
indicating remaining character quota to OutlinedTextInput.
Animations:
V1 (a7066aeab9489e0ed86eba8bae1d2a83f77bd566):
https://user-images.githubusercontent.com/90650827/146090619-5895f9dc-b152-4a90-8db3-47da7d502e17.mp4
https://user-images.githubusercontent.com/90650827/146090372-f5d58f2c-ad19-4333-a4f3-7e6eb93ca8c0.mp4
V2 (a7066aeab9489e0ed86eba8bae1d2a83f77bd566):
https://user-images.githubusercontent.com/90650827/146107392-6008c920-0500-44ca-bb8f-e5825718b30a.mp4
https://user-images.githubusercontent.com/90650827/146107437-40e843c9-7071-47c3-b2de-b589e080887b.mp4
---
- …

Add Max Length to OutlinedTextInput

---

src/components/navigation/BackButton.js
src/components/navigation/EdgeLogoHeader.js
src/components/navigation/HeaderTextButton.js
src/components/navigation/HeaderTitle.js

---
- https://app.asana.com/0/0/1201462538951866

Tweak header alignments

---

src/constants/WalletAndCurrencyConstants.js

---
- https://app.asana.com/0/0/1201570852147224

Use isCustomTokensSupported to create list of currency codes to show add/edit token menu option

---

src/components/scenes/FioRequestListScene.js

Filter out pending fio requests if payer address does not exist in the wallet
---
- https://app.asana.com/0/0/1201461442110378

FIO. Reject pending fio request issue.

---

src/components/scenes/CryptoExchangeScene.js

---
- https://app.asana.com/0/0/1201595744753452

Don't check toCurrency wallet balance

---

src/components/scenes/FioRequestConfirmationScene.js

---
- https://app.asana.com/0/0/1200935279565606

Set connected fio address by default as Request From

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json

Add Matic to Wyre

---

src/components/modals/ListModal.js

Allow the listModal to autoFocus based on whether the input is a "search" input or not
---
- https://app.asana.com/0/0/1201621837365749

Autofocus the keyboard when needed (contact modal)

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/constants/WalletAndCurrencyConstants.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/Core/Account/settings.js
src/util/corePlugins.js

---
- https://app.asana.com/0/0/1201571049076293

Add Avalanche (AVAX)

---

src/components/scenes/FioRequestConfirmationScene.js
src/modules/FioAddress/util.js

FIO requests can cost "up to two transactions" but the API won't return a new bundle fee unless you're at 0 remaining transactions. This adds a check for the corner case. We can leave the fee check as that would provide the most up to date information in the small chance state is out of date.

Show bundle purchase reminder if attempting to send request with only one bundle remaining

---

README.md

---
- https://app.asana.com/0/0/1201642026855963

Add Zcash library build instructions to README

---

src/components/scenes/FioAddressSettingsScene.js
src/components/scenes/FioDomainSettingsScene.js

Remove 'Purchase more bundled transactions' from:
-FioAddressSettingsScene
-FioDomainSettingsScene
- [ x] Tested on iOS Tablet
- [x ] Tested on small Android
---
- https://app.asana.com/0/0/1201647619367977

Remove 'Purchase more bundled transactions' from fio settings scenes

---

src/locales/en_US.js
src/locales/strings/enUS.json

---
- https://app.asana.com/0/0/1201648863265278

Use the correct format string in the token fee agreement modal

---

src/actions/WalletListMenuActions.js
src/components/scenes/ManageTokensScene.js
src/components/themed/WalletListFooter.js
src/types/routerTypes.js

---
- https://app.asana.com/0/0/1201649141683416

Pass wallet ID to manage tokens scene instead of gui wallet

---

src/components/modals/FlipInputModal.js

- [ x] Tested on iOS Tablet
- [ x] Tested on small Android
---
- https://app.asana.com/0/0/1201654918345081

Show Max button depending on if currency supports MaxSpend

---

src/actions/SendConfirmationActions.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/FioAddress/util.js

---
- https://app.asana.com/0/0/1201666565129274

Show appropriate error message from record_obt_data failure

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/__tests__/__snapshots__/cryptoExchangeReducer.test.js.snap
src/actions/CryptoExchangeActions.js
src/components/scenes/CryptoExchangeQuoteScene.js
src/components/scenes/CryptoExchangeScene.js
src/components/themed/CryptoExchangeFlipInputWrapperComponent.js
src/reducers/CryptoExchangeReducer.js
src/selectors/DenominationSelectors.js
src/types/reduxActions.js

---
- https://app.asana.com/0/0/1201654424669170

Remove GuiWallet from CryptoExchangeScene

---

env.example.json
package.json
src/components/services/EdgeCoreManager.js
webpack.config.js
yarn.lock

Add ENV.DEBUG_PLUGINS flag and webpack-dev-server for plugin-bundle

---

src/components/modals/TransactionAdvanceDetails.js

---
- https://app.asana.com/0/0/1200856758632240

Display device info from EdgeTransaction, if present

---

src/constants/plugins/buyPluginList.json

---
- https://app.asana.com/0/0/1201542146088169

Re-enable Transak in India

---

src/constants/WalletAndCurrencyConstants.js

---
- https://app.asana.com/0/0/1201411731543806

Add ZEC memo support

---

src/components/themed/ControlPanel.js

---
- https://app.asana.com/0/0/1201660234465304

Fix font scaling for long usernames

---

src/actions/WalletListMenuActions.js
src/components/modals/WalletListMenuModal.js

---
- https://app.asana.com/0/0/1201676547072842

Allow deletion of broken wallets

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json

---
- https://app.asana.com/0/0/1201605573973026
- https://app.asana.com/0/0/1201566563293764

Fix spacing between numbers and time units

---

src/components/modals/AccelerateTxModel.js
src/components/modals/FlipInputModal.js
src/components/scenes/CryptoExchangeScene.js
src/components/scenes/SendScene.js
src/components/scenes/TransactionDetailsScene.js
src/util/CurrencyWalletHelpers.js
src/util/utils.js

---
- https://app.asana.com/0/0/1201676493629104

Fix fee amount display in flip input modal

---

src/components/modals/FlipInputModal.js
src/components/scenes/StakingChangeScene.js

Sam/fio staking bug/flipinput amount

---

src/components/scenes/StakingChangeScene.js

---
- https://app.asana.com/0/0/1201746980881045

Constrain FIO staking APY return to two decimals

---

src/modules/FioAddress/components/FioActionSubmit.js

---
- https://app.asana.com/0/0/1201747496244008
- https://app.asana.com/0/0/1201747488748618

Get proper wallet for FioActionSubmit denomination info

---

src/components/themed/OutlinedTextInput.js

Worklet functions cannot take default parameters, so get rid of that.

Fix Reanimated red-box error on login

---

src/components/themed/WalletList.js

Fixes the following:
1. Tokens available in the list and shown as a wallet to pick from
2. Unable to find some tokens
---
- https://app.asana.com/0/0/1201759114163498
- https://app.asana.com/0/0/1201759098170882

Fix multiple issues with the wallet list search

---

src/components/modals/WalletListModal.js
src/components/scenes/CryptoExchangeScene.js
src/components/themed/WalletList.js
src/util/CurrencyInfoHelpers.js

---
- https://app.asana.com/0/0/1201667380760097

Prevent currencies that needs activation from being created from the wallet list modal

---

package.json
src/components/services/EdgeCoreManager.js
webpack.config.js

---
- https://app.asana.com/0/0/1201810828119028

Plugin debugging fixes for Android emulator

---

src/actions/LogActions.js

---
- https://app.asana.com/0/0/1201810828119046

Add `imported` key field to logs

---

src/components/modals/FlipInputModal.js

---
- https://app.asana.com/0/0/1201800170796591

Use fee exchange denomination in renderFees

---

src/__tests__/TransactionRow.test.js
src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/__tests__/fixtures.json
src/components/scenes/GuiPluginListScene.js
src/components/services/ContactsLoader.js
src/constants/CountryConstants.js
src/constants/WalletAndCurrencyConstants.js
src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json
src/util/CurrencyInfoHelpers.js
src/util/ThemeCache.js

---
- https://app.asana.com/0/0/1201388567936687

Use the correct CDN to get the plugin logo for the contact modal

---

src/actions/LoginActions.js

Do not crash if custom tokens exist for missing currencies

---

env.example.json
src/constants/WalletAndCurrencyConstants.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/util/corePlugins.js

---
- https://app.asana.com/0/0/1199694892324663

Add Binance Smart Chain (BNB)

---

src/actions/WalletActions.js
src/components/services/EdgeWalletCallbackManager.js
src/util/utils.js

Improve logs with date and wallet info

---

README.md
ios/Podfile
ios/Podfile.lock
patches/react-native-zcash+0.2.0.patch

Upgrade to ZcashLightClientKit v0.13.0-beta.1 (git)

---

src/__tests__/Request.test.js
src/__tests__/__snapshots__/Request.test.js.snap
src/components/scenes/RequestScene.js
src/util/CurrencyWalletHelpers.js

---
- https://app.asana.com/0/0/1200122479966758

Add balance and exchange rate to RequestScene

---

src/constants/plugins/GuiPlugins.js
src/constants/plugins/buyPluginList.json

---
- https://app.asana.com/0/0/1201839790357430

Remove Transak

---

src/components/modals/TransactionAdvanceDetails.js
src/components/themed/Tile.js
src/locales/en_US.js
src/locales/strings/enUS.json

---
- https://app.asana.com/0/0/1201611015895049

Advanced transaction modal design fixes

---

src/components/scenes/SendScene.js
src/components/themed/EditableAmountTile.js

---
- https://app.asana.com/0/0/1201952055618882

Refactor EditableAmountTile out from SendScene

---

src/components/themed/EdgeText.js
src/components/themed/TitleText.js
src/modules/UI/components/FormattedText/FormattedText.ui.js

---
- https://app.asana.com/0/0/1201622044701688

Disable allowFontScaling on EdgeText

---

src/components/modals/FlipInputModal.js

---
- https://app.asana.com/0/0/1202037640226328

Fix token balance display in flip input modal

---

package.json
src/plugins/stake-plugins/TxBuilder.js
src/plugins/stake-plugins/abi/MASONRY_ABI.json
src/plugins/stake-plugins/abi/TOMB_TREASURY_ABI.json
src/plugins/stake-plugins/abi/TSHARE_ABI.json
src/plugins/stake-plugins/contracts.js
src/plugins/stake-plugins/index.js
src/plugins/stake-plugins/pluginInfo.js
src/plugins/stake-plugins/stakePolicy.js
src/plugins/stake-plugins/types.js
src/plugins/stake-plugins/util/getSeed.js
src/plugins/stake-plugins/util/hex.js
src/plugins/stake-plugins/util/promiseAny.js
yarn.lock

---
- https://app.asana.com/0/0/1201944123917959

Stake Plugin API

---

src/actions/BitPayActions.js

JSON Payment Protocol V2 - Transmit Signed Tx - Multiple Outputs

---

src/components/themed/TransactionListTop.js

Fix amount + token font scaling in transaction list

---

src/plugins/stake-plugins/index.js

---
- https://app.asana.com/0/0/1202043265098871

Hard-code gasLimit for approve call

---

src/components/themed/WalletListSwipeRow.js

Somehow these two got flipped around.

Make the wallet list swipe buttons do the right thing

---

src/actions/WalletListMenuActions.js
src/locales/en_US.js
src/locales/strings/enUS.json

Add copy button to get-seed wallet list action menu

---

src/plugins/stake-plugins/pluginInfo.js
src/plugins/stake-plugins/policies/masonryPolicy.js
src/plugins/stake-plugins/stakePolicy.js
src/plugins/stake-plugins/types.js

---
- https://app.asana.com/0/0/1202076180403938

Add `pluginId` to `QuoteAllocation` type

---

src/__tests__/__snapshots__/Request.test.js.snap
src/actions/DeepLinkingActions.js
src/actions/ScanActions.js
src/actions/SendConfirmationActions.js
src/actions/WalletActions.js
src/actions/WalletListActions.js
src/components/scenes/FioConnectWalletConfirmScene.js
src/components/scenes/FioRequestConfirmationScene.js
src/components/scenes/RequestScene.js
src/components/scenes/WcConnectScene.js
src/components/services/EdgeWalletCallbackManager.js
src/components/themed/WalletListSwipeRow.js
src/modules/FioAddress/components/ConnectWallets.js
src/modules/FioAddress/util.js
src/modules/UI/scenes/Plugins/EdgeProvider.js
src/reducers/scenes/WalletsReducer.js
src/types/reduxActions.js
src/types/types.js
src/util/utils.js

Perf optimization to prevent needing to call getReceiveAddress() for all wallets each time a wallet update occurs. 
---
- https://app.asana.com/0/0/1202060614291040

Remove receive address from redux

---

src/components/scenes/Staking/StakeOverviewScene.js
src/hooks/useFiatText.js

1) Fix fiat amount on currency row so it shows 2 decimal places
2) Fix incorrect currency code passed to CryptoFiatAmountTile
3) Don't export root state from selector
---
- https://app.asana.com/0/0/1202103734570600

Fix display amounts

---

src/plugins/stake-plugins/index.js
src/plugins/stake-plugins/stakePolicy.js
src/plugins/stake-plugins/types.js

---
- https://app.asana.com/0/0/1202076180403989

Fix/tomb staking v2/info server apy

---

src/components/themed/WalletListCurrencyRow.js

---
- https://app.asana.com/0/0/1202088775226475

Fix precision for the crypto amount in the wallet list for international users

---

src/components/themed/WalletListCurrencyRow.js
yarn.lock

---
- https://app.asana.com/0/0/1202110770250905

Fixes the fiat balance of the wallet showing the exchange rate

---

ios/Podfile.lock
package.json
src/components/modals/AutoLogoutModal.js
yarn.lock

Fix the autologout modal

---

src/components/modals/FlipInputModal.js
src/components/scenes/Staking/StakeModifyScene.js

---
- https://app.asana.com/0/0/1202076180403983

Add hideMaxButton prop to FlipInputModal, enable on StakeModifyScene

---

src/components/scenes/SendScene.js
src/components/scenes/Staking/StakeModifyScene.js
src/components/themed/ErrorTile.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/plugins/stake-plugins/policies/cemeteryPolicy.js
src/plugins/stake-plugins/policies/masonryPolicy.js

---
- https://app.asana.com/0/0/1202102788046358

Fix/tomb staking v2/insufficient funds error

---

src/components/scenes/Staking/StakeModifyScene.js

Revert to v1 max button calculation

---

src/__tests__/components/__snapshots__/WalletListRow.test.js.snap
src/actions/WalletActions.js
src/components/themed/WalletList.js
src/components/themed/WalletListRow.js
src/components/themed/WalletListSwipeRow.js
src/plugins/stake-plugins/contracts.js

---
- https://app.asana.com/0/0/1201944031769927

Performance fixes

---

src/plugins/stake-plugins/policies/cemeteryPolicy.js
src/plugins/stake-plugins/policies/masonryPolicy.js

Use Promise.all instead of await
---
- https://app.asana.com/0/0/1202118645065536

Optimize fetchStakePosition

---

src/components/scenes/Staking/StakeModifyScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

---
- https://app.asana.com/0/0/1202088412414283

Always show warning message

---

src/components/themed/WalletSyncCircle.js

https://user-images.githubusercontent.com/4012041/163292700-428ba481-53c7-4c71-bfe6-fc659204b9c0.mp4
---
- https://app.asana.com/0/0/1202126996392148

Start at 5% instead of 0% since 0% is indistinguishable from fully synced.

---

src/components/scenes/Staking/StakeOverviewScene.js

Spacing updated from 1rem between buttons to 0.5rem
---
- https://app.asana.com/0/0/1202110955438473

Update button spacing on StakeOverviewScene

---

src/components/scenes/ManageTokensScene.js
src/components/themed/ManageTokensRow.js
src/components/themed/WalletListRow.js

If you have made **any** visual changes to the GU
I. Make sure you have:
---
- https://app.asana.com/0/0/1202130560834266

Fix icons in Manage token scene

---

src/actions/WalletActions.js
src/components/services/EdgeWalletCallbackManager.js
src/components/themed/ManageTokensRow.js
src/plugins/stake-plugins/metadataCache.js
src/plugins/stake-plugins/policies/cemeteryPolicy.js
src/plugins/stake-plugins/policies/masonryPolicy.js
src/selectors/WalletSelectors.js

---
- https://app.asana.com/0/0/1202092936764695

Fix/tomb staking v2/staking tx list

---

src/components/scenes/Staking/StakeModifyScene.js
src/components/services/EdgeWalletCallbackManager.js

Fixes the warning we get after staking

---

env.example.json

Add Quicknode API key to more places in the env.json

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/constants/plugins/buyPluginList.json

---
- https://app.asana.com/0/0/1201965984308913

Prioritize moonpay over simplex

---

src/components/themed/OutlinedTextInput.js

https://user-images.githubusercontent.com/17136567/156232947-e7b079be-527d-4686-ae8f-732d63db6ebc.mp4

Show/Hide password text on OutlinedTextInput component

---

src/components/modals/WalletListModal.js
src/components/scenes/CreateWalletAccountSelectScene.js
src/components/scenes/FioAddressRegisterScene.js
src/components/scenes/FioAddressRegisterSelectWalletScene.js
src/components/scenes/FioDomainRegisterScene.js
src/components/scenes/FioDomainRegisterSelectWalletScene.js
src/components/scenes/FioRequestListScene.js
src/components/themed/WalletList.js
src/modules/FioAddress/components/FioActionSubmit.js
src/modules/UI/scenes/Plugins/EdgeProvider.js
src/types/types.js
src/util/utils.js

---
- https://app.asana.com/0/0/1201752545090997

Add EdgeTokenIdExtended to Edge Provider's chooseCurrencyWallets

---

src/actions/SendConfirmationActions.js
src/locales/en_US.js
src/locales/strings/enUS.json

---
- https://app.asana.com/0/0/1202037049641279

Updates to the highFeeWarning modal

---

src/modules/UI/components/Buttons/PrimaryButton.ui.js

---
- https://app.asana.com/0/0/1202179867819106

Fix PrimaryButton missing style

---

src/__tests__/components/__snapshots__/ExchangedFlipInput.test.js.snap
src/actions/CryptoExchangeActions.js
src/components/themed/ExchangedFlipInput.js
src/components/themed/FlipInput.js
src/components/themed/WalletListCreateRow.js
src/constants/WalletAndCurrencyConstants.js
src/modules/Core/Wallets/EnabledTokens.js
src/types/types.js

1 and 2: These address the error messages that appear when creating a wallet and token from the wallet list modal
3: Fix parent token icon overlay on flipinput (was defaulting to ETH)
4: Fix for race condition that resulted in setting the local token file multiple times with and and then without tokens
5: Use the default wallet name when creating a wallet from create wallet row
---
- https://app.asana.com/0/0/1202185717167127

Exchange Scene: Create token fixes

---

src/components/scenes/Staking/StakeModifyScene.js
src/plugins/stake-plugins/policies/cemeteryPolicy.js

---
- https://app.asana.com/0/0/1202191033559100

Include tokenId in changeQuoteRequest for claim actions

---

src/constants/plugins/GuiPlugins.js
src/modules/UI/scenes/Plugins/EdgeProvider.js
src/types/GuiPluginTypes.js

---
- https://app.asana.com/0/0/1202193502311252

Temporary fix to prevent sending the wrong token to Wyre.

---

src/hooks/useFiatText.js

---
- https://app.asana.com/0/0/1202163139223324

Check if the non localized amount is zero instead of the localized one

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1202187021652349

v2.14.0 Changelog

---

env.example.json
src/components/services/ContactsLoader.js
src/util/corePlugins.js

---
- https://app.asana.com/0/0/1202187021652357

Enable LetsExchange

---

src/__tests__/scenes/__snapshots__/DefaultFiatSettingScene.test.js.snap
src/components/Main.ui.js
src/components/scenes/DefaultFiatSettingScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

---
- https://app.asana.com/0/0/1201476465036420

Re-style DefaultFiatSettingScene

---

src/components/themed/WalletList.js
src/modules/UI/scenes/Plugins/EdgeProvider.js
src/types/types.js
src/util/CurrencyInfoHelpers.js
src/util/utils.js

---
- https://app.asana.com/0/0/1202193781379741

Fix filtering of EdgeTokenIdExtended arrays in EdgeProvider chooseCurrencyWallet

---

src/components/scenes/FioRequestListScene.js
src/components/themed/FioRequestRow.js

---
- https://app.asana.com/0/0/1202066615400901

Fix FIO Request sorting and timezone

---

src/components/modals/WcSmartContractModal.js

---
- https://app.asana.com/0/0/1201344822981010

Fixed small WalletConnect warning text

---

src/plugins/stake-plugins/policies/cemeteryPolicy.js
src/plugins/stake-plugins/policies/masonryPolicy.js

Use explicit gasPrice value for all transactions in stake workflow

---

src/constants/plugins/GuiPlugins.js
src/modules/UI/scenes/Plugins/EdgeProvider.js
src/types/GuiPluginTypes.js

---
- https://app.asana.com/0/0/1202255797698875

Add a `fixCurrencyCodes` filter for GUI plugins

---

src/components/modals/ScanModal.js
src/components/themed/ControlPanel.js

---
- https://app.asana.com/0/0/1202249148039751

Remove the isFlash, isAlbum and isTextInput props and always show them

---

src/constants/plugins/GuiPlugins.js

This gets Dai and a few others to show up again.

Fix invalid tokenIds in MoonPay and Wyre

---

src/__tests__/__snapshots__/Request.test.js.snap
src/components/common/ExchangeRate.js
src/components/scenes/RequestScene.js
src/components/text/CryptoText.js
src/components/text/FiatText.js
src/components/text/TickerText.js
src/components/themed/WalletListCurrencyRow.js
src/components/tiles/FiatAmountTile.js
src/hooks/useTokenDisplayData.js

Remove dead code from amount text components

---

src/components/themed/WalletListCurrencyRow.js
src/hooks/useWalletBalance.js

Subscribe to the balance more carefully

---

src/actions/AccountActions.js
src/components/modals/TextInputModal.js

https://user-images.githubusercontent.com/4023066/168376934-a3c04afd-4f0f-4a38-82cd-82b6579ab221.mp4

Removed autofocus from master password confirmation modal 

---

src/hooks/useWalletBalance.js

Fix useWalletBalance to update on change

---

src/components/services/SortedWalletList.js

Fixes missing tokens on the wallet list upon login.
---
- https://app.asana.com/0/0/1202276333823106

Set the initial enabledTokenIds on subscribe

---

src/actions/ExchangeRateActions.js
src/components/text/TickerText.js
src/hooks/useTokenDisplayData.js

---
- https://app.asana.com/0/0/1202277011263320

Wallets List Exchange Rate related visual issues

---

src/components/services/AccountCallbackManager.js

---
- https://app.asana.com/0/0/1202273639965839

Fix broken action calls in AccountCallbackManager

---

src/components/scenes/CurrencySettingsScene.js

---
- https://app.asana.com/0/0/1202248461628089

Add default fallback electrum server settings object to asMaybe cleaner

---

src/components/services/WalletLifecycle.js

1. Use the sortedWalletList to boot the wallets in the same order they appear in the wallet list
2. Increase the boot limit on iOS to 8
---
- https://app.asana.com/0/0/1202276085925285

Load sorted wallet list

---

src/__tests__/components/BuyCrypto.test.js
src/__tests__/components/__snapshots__/BuyCrypto.test.js.snap
src/components/modals/WalletListMenuModal.js
src/components/scenes/CreateWalletSelectCryptoScene.js
src/components/scenes/RequestScene.js
src/components/scenes/TransactionListScene.js
src/components/scenes/WcConnectScene.js
src/components/themed/BuyCrypto.js
src/constants/WalletAndCurrencyConstants.js
src/modules/FioAddress/components/ConnectWallets.js
src/modules/FioAddress/util.js
src/util/utils.js

---
- https://app.asana.com/0/0/1202287318591638

BNB and FIO fixes

---

env.example.json
src/components/scenes/LoginScene.js

Add YOLO_PIN to login with pin for development

---

src/plugins/borrow-plugins/types.js

---
- https://app.asana.com/0/0/1202187333983852

Borrow API spec

---

src/actions/BitPayActions.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/modules/UI/scenes/Plugins/EdgeProvider.js

Payment protocol support in EdgeProvider 

---

src/components/scenes/Staking/StakeOptionsScene.js

---
- https://app.asana.com/0/0/1202316743850210

Fix array reference in stake options scene

---

src/components/themed/ControlPanel.js
src/hooks/useSelectedWallet.js

We were grabbing the selected wallet in an unsafe way,
so pull all that logic into a hook and give it a cleanup.
---
- https://app.asana.com/0/0/1202325280482200

Fix the side menu crash on wallet archive

---

src/util/DeepLinkParser.js
src/util/GuiPluginTools.js
src/util/WebUtils.js

---
- https://app.asana.com/0/0/1202301962449599

Use url-parse to stringify uri query string

---

src/components/scenes/Staking/StakeOverviewScene.js
src/plugins/stake-plugins/policies/cemeteryPolicy.js
src/plugins/stake-plugins/policies/masonryPolicy.js

Allow custom disabling for any of the staking options

---

src/plugins/stake-plugins/contracts.js
src/plugins/stake-plugins/pluginInfo.js

---
- https://app.asana.com/0/0/1202331169166603

Re-enable unstaking and claiming on the SpookySwapLiquidityPool

---

src/components/Main.ui.js

---
- https://app.asana.com/0/0/1202336353801175

Don't show the side menu if user has logged off

---

ios/Podfile.lock
package.json
src/components/scenes/OtpRepairScene.js
src/components/scenes/PasswordRecoveryScene.js
yarn.lock

Pass Branding appName for password recovery scene

---

src/util/utils.js

---
- https://app.asana.com/0/0/1202348626648603

Don't try to add the balance of wallets that are not there anymore

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

---
- https://app.asana.com/0/0/1202356314982260

Revert currencyCode to UID when returning from chooseCurrencyWallet

---

src/locales/intl.js

| Italian ![Simulator Screen Shot - iPhone 13 mini - 2022-05-25 at 02 02 03](https://user-images.githubusercontent.com/4023066/170113319-7dd46345-7375-4518-ad31-f1c6ed43f007.png)  |  English ![Simulator Screen Shot - iPhone 13 mini - 2022-05-25 at 02 03 12](https://user-images.githubusercontent.com/4023066/170113064-c2e7a171-8009-4c67-a6ed-bd1e09492639.png)  |
|---|---|

Localized date formatting for TransactionList (Italian dates)

---

src/components/modals/WalletListModal.js
src/components/scenes/CreateWalletChoiceScene.js
src/components/scenes/EditTokenScene.js
src/components/scenes/ManageTokensScene.js
src/components/scenes/WalletListScene.js
src/components/themed/ManageTokensRow.js
src/components/themed/WalletList.js
src/components/themed/WalletListCreateRow.js
src/components/themed/WalletListCurrencyRow.js
src/components/themed/WalletListFooter.js
src/components/themed/WalletListSwipeable.js
src/components/themed/WalletListSwipeableCurrencyRow.js
src/components/themed/WalletListSwipeableLoadingRow.js
src/hooks/useHandler.js
src/modules/UI/components/Slider/Slider.js

Add a `useCallbork` hook

---

src/components/scenes/Staking/StakeOverviewScene.js

---
- https://app.asana.com/0/0/1202376524941851

Fix missing mainnet currency tile

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1202377793436110

v2.15.0 Changelog

---

src/modules/UI/scenes/Plugins/EdgeProvider.js

Specifying a value = undefined will delete the key/value pair

Allow edgeProvider writeData to delete keys

---

src/plugins/stake-plugins/index.js
src/plugins/stake-plugins/types.js

---
- https://app.asana.com/0/0/1202384179565904

Remove _id and _rev from info server stake policy type

---

src/constants/plugins/GuiPlugins.js

Change Ionia display name

---

ios/Podfile.lock
metro.config.js
package.json
yarn.lock

---
- https://app.asana.com/0/0/1202400247249241

Use 'react-native-bignumber' as a drop-in replacement for bn.js

---

src/__tests__/__snapshots__/GuiPlugins.test.js.snap
src/components/themed/ControlPanel.js
src/constants/plugins/GuiPlugins.js
src/constants/plugins/sellPluginList.json

Change Edge Mastercard pluginId to 'card'

---

src/components/scenes/ManageTokensScene.js

---
- https://app.asana.com/0/0/1202376524737423

Add missing dependencies to the extraData prop

---

src/components/themed/WalletListSortable.js

https://user-images.githubusercontent.com/4012041/172305522-8ce54d99-65d0-4b53-abc3-d7ef57c15b09.mp4
---
- https://app.asana.com/0/0/1202400149162703
- https://app.asana.com/0/0/1202399334889053

Fix manual wallet sorting

---

src/actions/SendConfirmationActions.js
src/components/scenes/SendScene.js

https://user-images.githubusercontent.com/4012041/172350056-03d961fa-ab2c-4736-8a24-11dbb2b03d7b.mp4
https://user-images.githubusercontent.com/4012041/172350064-35eafcef-7afa-4c9c-aec5-22022d24c6b2.mp4
https://user-images.githubusercontent.com/4012041/172350075-691b8d38-7b57-4c65-b56f-64c409ca576c.mp4
---
- https://app.asana.com/0/0/1202400149162703

Make sure the slider in the scene send gets reset/disabled correctly

---

src/components/themed/OutlinedTextInput.js

Fix an issue where the it was calling a prop outside of the scope of the animation thread

---

src/__tests__/components/__snapshots__/TransactionListRow.test.js.snap
src/__tests__/components/__snapshots__/TransactionRow.test.js.snap
src/components/scenes/TransactionDetailsScene.js
src/components/services/AccountCallbackManager.js
src/components/themed/TransactionListRow.js
src/components/themed/TransactionRow.js
src/modules/UI/scenes/Plugins/EdgeProvider.js

Support new EdgeTransaction confirmation field

---

src/theme/edgeConfig.js

Add Litecoin as a default wallet

---

src/theme/edgeConfig.js

---
- https://app.asana.com/0/0/1202444611436042

Add Dash to default wallets and reorg based on Market-Cap

---

src/constants/plugins/sellPluginList.json

---
- https://app.asana.com/0/0/1202407369963171

Add banxa sell

---

src/components/services/DeepLinkingManager.js

---
- https://app.asana.com/0/0/1200051810094156

Remove dispatch dependency from DeepLinkingManager's useEffect

---

babel.config.js
ios/Podfile.lock
jestSetup.js
package.json
src/components/modals/ScanModal.js
yarn.lock

Revert Use 'react-native-vision-camera' instead of the deprecated `react-native-camera`

---

src/constants/WalletAndCurrencyConstants.js

Add `isImportKeySupported` to UFO and EBOOST

---

config.js
env.example.json
src/components/modals/SwapVerifyTermsModal.js
src/util/corePlugins.js

---
- https://app.asana.com/0/0/1202476191377174

Remove 'Changelly'

---

src/__tests__/components/__snapshots__/TransactionListTop.test.js.snap
src/components/themed/TransactionListTop.js

|                                                                                       iPod touch                                                                                      |                                                                 iPad Pro                                                                 |
|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------------------------------------------------------------:|
| ![Simulator Screen Shot - iPod touch (7th generation) - 2022-06-23 at 05 09 …

Fixed TOMB staking button placement

---

src/constants/WalletAndCurrencyConstants.js

Remove keysOnlyMode from feathercoin

---

src/components/modals/HelpModal.js
yarn.lock

---
- https://app.asana.com/0/0/1201957615380295

Links Edge site to external browser for Android

---

src/components/hoc/MaybeCurrencySetting.js
src/components/scenes/FioStakingOverviewScene.js
src/components/scenes/ManageTokensScene.js
src/components/scenes/WalletListScene.js
src/components/services/SortedWalletList.js
src/components/themed/ControlPanel.js
src/components/themed/WalletListSortable.js
src/hooks/useSelectedWallet.js
src/hooks/useTokenDisplayData.js
src/hooks/useWalletName.js
src/hooks/useWatch.js

Fix the typing for 'useWatch' and remove the 'useWatch' aliases

---

ios/Podfile.lock
package.json
yarn.lock

Remove duplicated yarn lock dependencies

---

src/__tests__/__snapshots__/SettingsScene.test.js.snap
src/components/common/Collapsable.js
src/components/scenes/SettingsScene.js

https://user-images.githubusercontent.com/4012041/177700701-7255bff1-3575-43f0-afb1-fe3169aece49.mp4
---
- https://app.asana.com/0/0/1202564042685861

Hide/Show the delete option on lock/unlock settings and change text color to red to match figma

---

src/__tests__/components/__snapshots__/TransactionListTop.test.js.snap
src/components/themed/TransactionListTop.js

---
- https://app.asana.com/0/0/1202572719115196
- https://app.asana.com/0/0/1202577681549216

Separate the staking amount from the button and update the styles

---

src/constants/plugins/buyPluginList.json

---
- https://app.asana.com/0/0/1202585369401129

Add the buy option for Turkish banks using Banxa

---

src/__tests__/components/__snapshots__/ExchangeQuoteComponent.test.js.snap
src/__tests__/scenes/__snapshots__/CryptoExchangeQuoteScene.test.js.snap
src/components/scenes/CryptoExchangeQuoteScene.js
src/components/themed/Alert.js
src/components/themed/ExchangeQuoteComponent.js
src/locales/en_US.js
src/locales/strings/enUS.json

| iPhone 8                                                                                                                                                                 	| iPad Pro                                                                                                                                                                 	|
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| <img width="424" alt="Screen Shot …

Show high fee warning in exchange scene when fee is >= 5%

---

src/components/services/ContactsLoader.js
src/util/corePlugins.js

This is the code from PR https://github.com/EdgeApp/edge-react-gui/pull/3218 but with conflicts resolved. Mostly just removing unnecessary code.

Add Change Hero

---

src/hooks/useCryptoText.js

Fixes corrupt precision adjustments
---
- https://app.asana.com/0/0/1202641127936736

Fix incorrect denom of crypto amount when in airplane mode

---

.github/PULL_REQUEST_TEMPLATE.md

Include PR deps section in PULL_REQUEST_TEMPLATE.md

---

src/plugins/gui/fiatPlugin.js
src/plugins/gui/providers/simplexProvider.js

- [ x Tested on small-screen device (iPod Touch)

Add showCreateWallet to fiat plugin modal

---

src/actions/BitPayActions.js

Note that this one is blocked by: https://github.com/EdgeApp/edge-currency-plugins/pull/337

Conform unsignedTx to currency-plugins change

---

src/__tests__/components/TransactionListRow.test.js
src/__tests__/components/TransactionRow.test.js
src/__tests__/components/__snapshots__/TransactionListRow.test.js.snap
src/__tests__/components/__snapshots__/TransactionRow.test.js.snap

Fix tests for TransactionListRow component

---

src/components/scenes/SendScene.js

none
---
- https://app.asana.com/0/0/1202681927864037

Fix undefined name

---

src/components/scenes/RequestScene.js

Fix curencyInfo undefined error

---

src/components/themed/ControlPanel.js

The previous fix from PR #3535 only filtered out **enabled tokens** on wallets **owned in the account** against intersections with sweepable currency codes. 
It did not take into account when for example, 
- If the user did NOT own a FTM wallet OR 
- Did NOT have the fantom-bitcoin token enabled.
Update the fix so that **ALL tokens are disabled** from the Sweep Private Key feature.
PR #3535

Update sweep private key filtering

---

src/__tests__/__snapshots__/RootReducer.test.js.snap
src/components/services/ActionQueue.js
src/components/services/Services.js
src/controllers/action-queue/ActionProgram.js
src/controllers/action-queue/ActionQueueStore.js
src/controllers/action-queue/cleaners.js
src/controllers/action-queue/redux/actions.js
src/controllers/action-queue/redux/reducers.js
src/controllers/action-queue/types.js
src/reducers/RootReducer.js
src/types/reduxActions.js

Action queue (scheduler)

---

src/components/services/ActionQueue.js
src/controllers/action-queue/runtime.js
src/plugins/borrow-plugins/common/ApprovableCall.js
src/plugins/borrow-plugins/common/util/composeApprovableActions.js
src/plugins/borrow-plugins/types.js
src/plugins/helpers/borrowPluginHelpers.js
src/types/reduxActions.js

https://github.com/EdgeApp/edge-react-gui/pull/3526

Action queue runtime

---

src/components/modals/FlipInputModal.js

Fixed incorrect parent token icon in FlipInputModal

---

src/plugins/gui/creditCardPlugin.js

Use tokenId instead of currencyCode of tokens
none
---
- https://app.asana.com/0/0/1202706843337824

Show tokens in fiat plugin wallet list modal

---

src/components/modals/WalletListModal.js

none
---
- https://app.asana.com/0/0/1202692790499017

Add error handling for add tokens in airplane mode

---

src/controllers/action-queue/display.js

This file somehow got dropped while rebasing 3fed5bc3
none

Add ActionQueue display API (addendum)

---

src/actions/CreateWalletActions.js
src/actions/CryptoExchangeActions.js
src/actions/DeleteWalletModalActions.js
src/actions/LogActions.js
src/actions/LoginActions.js
src/actions/NotificationActions.js
src/actions/ScanActions.js
src/actions/SendConfirmationActions.js
src/actions/SettingsActions.js
src/actions/WalletListActions.js
src/actions/WalletListMenuActions.js
src/app.js
src/components/scenes/ChangePasswordScene.js
src/components/scenes/ChangePinScene.js
src/components/scenes/EditTokenScene.js
src/components/scenes/NotificationScene.js
src/components/scenes/OtpSettingsScene.js
src/components/themed/ManageTokensRow.js
src/components/themed/MaybeCustomServersSetting.js
src/modules/Core/Account/settings.js
src/modules/Logs/api.js
src/util/logger.js

none
---
- https://app.asana.com/0/0/1202506473095599

Add activity log

---

src/components/themed/SelectableRow.js

---
- https://app.asana.com/0/0/1201396921093263
- https://app.asana.com/0/0/1191598790263107

Fixed incorrect row subtitle color in CountryListModal

---

src/plugins/gui/providers/simplexProvider.js

Simplex changed their API response
none
---
- https://app.asana.com/0/0/1202719778434322

Fix simplex wrong limit errors

---

src/components/Main.ui.js

LoanStatusScene shows is the visual representation of the state of an ActionQueue, specifically for AAVE loans in this implementation.
The "in progress/active" step is the last item in the list to be highlighted, and the corresponding StepProgressBar will be half-filled in this state.
Before steps are complete, a button to cancel the actions is available. Pressing it presents a confirm/continue modal, allowing the user to cancel the pending ActionQueue steps. 
When all steps are completed, confettii fires.
---
- https://app.asana.com/0/0/1202600755487929

Implement LoanStatusScene

---

src/plugins/gui/creditCardPlugin.js
src/plugins/gui/pluginUtils.js
src/plugins/gui/scenes/EnterAmountScene.js

none
---
- https://app.asana.com/0/0/1202764583533713

Localize all amount input and display

---

src/components/tiles/AddressTile.js

Fix invalid address on scan

---

src/util/utils.js

App may crash when there is a race condition while trying to compute the
total balance of the account. The race condition is triggered by core
wallets and GUI wallets try to update at the same time.
Resolved the conflict by using the core wallets as a single source of
truth.
none
---
- https://app.asana.com/0/0/1202723644919390

Fix user cannot access account

---

src/locales/en_US.js
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1201967330244238

Made text change to crash scene to help users avoid reinstalling.

---

src/util/utils.js

The `// $FlowFixMe` should have been a clue that the logic wasn't right here. Flip it around so type type-checker proves correctness for us.
none

Remove Flow hack in balance calculation

---

src/modules/Core/Account/settings.js

---
- https://app.asana.com/0/0/1202794727653452

Return synced_account_defaults if they fail to load from disk

---

src/components/scenes/CryptoExchangeScene.js
src/locales/en_US.js
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1202807600136152

Add check for disabled swap assets from info server

---

src/components/scenes/Loans/LoanAddCollateralScene.js
src/components/scenes/Loans/LoanBorrowMoreScene.js
src/components/scenes/Loans/LoanRepayScene.js
src/components/scenes/Loans/LoanStatusScene.js
src/components/scenes/Loans/LoanWithdrawCollateralScene.js
src/controllers/action-queue/cleaners.js
src/controllers/action-queue/display.js
src/controllers/action-queue/runtime.js
src/controllers/action-queue/types.js
src/plugins/borrow-plugins/common/ApprovableCall.js
src/plugins/borrow-plugins/common/util/composeApprovableActions.js
src/plugins/borrow-plugins/plugins/aave/BorrowEngineFactory.js
src/plugins/borrow-plugins/types.js
src/util/safeFilters.js

[Sam/aq store fix #3561](https://github.com/EdgeApp/edge-react-gui/pull/3561)

Action queue dryrun

---

src/controllers/action-queue/cleaners.js
src/controllers/action-queue/display.js
src/controllers/action-queue/push.js
src/controllers/action-queue/redux/actions.js
src/controllers/action-queue/runtime.js
src/controllers/action-queue/types.js
src/controllers/action-queue/types/pushApiTypes.js
src/controllers/action-queue/types/pushCleaners.js
src/controllers/action-queue/types/pushTypes.js
src/locales/en_US.js
src/locales/strings/enUS.json
src/util/cleaners/asBase64.js
src/util/cleaners/asHex.js
src/util/exhaustiveCheck.js
src/util/trace.js

[Sam/aq store fix #3561](https://github.com/EdgeApp/edge-react-gui/pull/3561)
[Action queue dryrun #3538](https://github.com/EdgeApp/edge-react-gui/pull/3538)

Action queue push int

---

src/components/scenes/CryptoExchangeScene.js

---
- https://app.asana.com/0/0/1202839028163375

Exit early from getQuote if the user hasn't selected both wallets

---

src/components/scenes/Loans/LoanCreateScene.js
src/components/tiles/AprCard.js
src/locales/en_US.js
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1202775908143169

Fix double % display on apr

---

src/util/utils.js

none
---
- https://app.asana.com/0/0/1202842635030915

Stop approvals from showing in TransactionListDropdown

---

src/components/scenes/Loans/LoanDashboardScene.js
src/components/scenes/Loans/ManageCollateralScene.js

Per Paul's requests:
- Remove check for an existing loan from a wallet selected from the wallet picker, this is no longer a valid use case
- Disable the ability to create a wallet from the wallet picker
- Update behavior to:
- Only show wallet picker if the user owns multiple polygon wallets
- Auto-select a polygon wallet if the user owns only one
- Auto-create (and auto-select) a polygon wallet if the user doesn't own any
none
---
- https://app.asana.com/0/0/1202842635030927

Update 'New Loan' button functionality

---

src/components/services/ActionQueueService.js
src/components/services/Services.js
src/controllers/action-queue/ActionQueueStore.js
src/controllers/action-queue/cleaners.js
src/controllers/action-queue/push.js
src/controllers/action-queue/redux/actions.js
src/controllers/action-queue/runtime.js
src/controllers/action-queue/types.js

This is a redo of https://github.com/EdgeApp/edge-react-gui/pull/3607 because that accidentally was merged with the wrong rebase.
none

Sam/aq client (redo)

---

config.js
src/controllers/action-queue/runtime.js

Add a enableDryrun flag to the ACTION_QUEUE ENV

---

src/controllers/action-queue/runtime.js

Fix checkActionEffect broken from rebase mistake

---

src/locales/en_US.js
src/locales/strings/enUS.json
src/plugins/gui/scenes/EnterAmountScene.js

none
---
- https://app.asana.com/0/0/1202895674767106

Change Powered By to make tappability clearer

---

ios/Podfile.lock
package.json
yarn.lock

none
---
- https://app.asana.com/0/0/1202916988885881

Remove unused react-native-fast-crypto

---

package.json
src/components/cards/LoanSummaryCard.js
src/components/scenes/Loans/LoanAddCollateralScene.js
src/components/scenes/Loans/LoanBorrowMoreScene.js
src/components/scenes/Loans/LoanCloseScene.js
src/components/scenes/Loans/LoanCreateScene.js
src/components/scenes/Loans/LoanDashboardScene.js
src/components/scenes/Loans/LoanDetailsScene.js
src/components/scenes/Loans/LoanRepayScene.js
src/components/scenes/Loans/LoanWithdrawCollateralScene.js
src/components/scenes/Loans/ManageCollateralScene.js
src/components/tiles/InterestRateChangeTile.js
src/components/tiles/LoanToValueTile.js
src/plugins/borrow-plugins/plugins/aave/BorrowEngineFactory.js
src/plugins/borrow-plugins/types.js
src/util/withWatchableProps.js

none
---
- https://app.asana.com/0/0/1202895685301473

AAVE: Handle Borrow Engine state changes in LoanManager

---

package.json
src/components/services/ContactsLoader.js
src/util/corePlugins.js
yarn.lock

- Upgrade edge-exchange-plugins to v0.13.8
none
---
- https://app.asana.com/0/0/1202935969322494

Enable thorchain

---

src/components/scenes/NotificationScene.js

Price change notifications are device specific instead of account specific so we should show all of them regardless of the logged in account. 
---
- https://app.asana.com/0/0/1202948311373391

Show all currency notifications relevant to the device

---

src/app.js

none
---
- https://app.asana.com/0/0/1202859004377824

Revert unexpected console.error behavior for RN

---

android/app/src/main/AndroidManifest.xml
src/actions/NotificationActions.js

---
- https://app.asana.com/0/0/1202949101311902

Price change notification fixes

---

src/components/themed/ControlPanel.js

Fix dropdown overflow display bug in ConrtolPanel

---

src/components/scenes/Loans/LoanDetailsScene.js

none
---
- https://app.asana.com/0/0/1202925489554331

Remove showError in AAVE while exchange rates are loading

---

package.json
src/components/scenes/Loans/LoanStatusScene.js
src/components/services/ActionQueueService.js
src/controllers/action-queue/ActionQueueStore.js
src/controllers/action-queue/cleaners.js
src/controllers/action-queue/display.js
src/controllers/action-queue/push.js
src/controllers/action-queue/redux/actions.js
src/controllers/action-queue/redux/reducers.js
src/controllers/action-queue/runtime.js
src/controllers/action-queue/types.js
src/controllers/action-queue/types/pushApiTypes.js
src/controllers/action-queue/util/encoding.js
src/util/PeriodicTask.js
yarn.lock

none
---
- https://app.asana.com/0/0/1202895685301468

AAVE: ActionQueue - Implement Cancel Support

---

package.json
src/components/layout/Space.tsx
src/components/modals/WalletListModal.tsx
src/controllers/action-queue/WyreClient.ts
suppressTsErrors.sh

none
---
- https://app.asana.com/0/0/1202999203410825

TypeScript cleanup

---

package.json
src/actions/NotificationActions.js
src/actions/SettingsActions.js
src/components/scenes/CurrencyNotificationScene.js
src/components/scenes/NotificationScene.js
src/controllers/action-queue/push.js
src/controllers/action-queue/types/pushApiTypes.js
src/controllers/action-queue/util/encoding.js
yarn.lock

---
- https://app.asana.com/0/0/1202966393126770

Add loginIds to /device endpoint requests

---

src/constants/plugins/buyPluginList.json

---
- https://app.asana.com/0/0/1202997211107594

Disable Newsagent

---

src/controllers/action-queue/runtime.ts

none
---
- https://app.asana.com/0/0/1202998266966413

Fix unexpected null childEffect for SeqActionOp

---

src/controllers/action-queue/WyreClient.ts

none
---
- https://app.asana.com/0/0/1203008188455322

Do not include inactive payment methods

---

src/actions/CryptoExchangeActions.tsx

Add metadata to quote.approve() call and remove call to saveTxMetadata f3786a
none
---
- https://app.asana.com/0/0/1202983612669723

Fix missing metadata in swaps

---

src/__tests__/scenes/CurrencyNotificationScene.test.tsx
src/actions/NotificationActions.ts
src/actions/SettingsActions.tsx
src/components/scenes/CurrencyNotificationScene.tsx
src/components/scenes/NotificationScene.tsx
src/controllers/action-queue/types/pushApiTypes.ts

---
- https://app.asana.com/0/0/1202966393126770

Add loginIds to /device calls

---

src/actions/DeepLinkingActions.ts
src/components/modals/PriceChangeBuySellSwapModal.tsx
src/components/services/DeepLinkingManager.ts
src/controllers/action-queue/types/pushPayloadTypes.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/types/DeepLinkTypes.ts
src/util/DeepLinkParser.ts

---
- https://app.asana.com/0/0/1202555663767418

Add firebase message listeners and price change notification modal

---

src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/components/scenes/Staking/StakeOptionsScene.tsx
src/components/themed/TransactionListTop.tsx
src/types/routerTypes.tsx

---
- https://app.asana.com/0/0/1202391753908310

Remove extra info server fetch for stake policies, add spinner to TransactionList stake button

---

src/controllers/action-queue/WyreClient.ts

none
---
- https://app.asana.com/0/0/1203031993581634

Fix "No item named wyreAccountId" error leak on LoanCreateScene

---

src/controllers/action-queue/runtime.ts

none
---
- https://app.asana.com/0/0/1203034403908932

Include pendingTxs in makeSpend for wyre-sell (WyreSellActionOp)

---

src/components/scenes/Loans/LoanDashboardScene.tsx

none
---
- https://app.asana.com/0/0/1203034403908917

Whitelist Ethereum wallets for AAVE

---

src/components/scenes/Loans/LoanCreateScene.tsx

none
---
- https://app.asana.com/0/0/1203020953556924
- https://app.asana.com/0/0/1203015146283995

Add APR to the FiatAmountInputCard modal message

---

src/components/scenes/Loans/LoanCloseScene.tsx

none
---
- https://app.asana.com/0/0/1203034403908928

Avoid unnecessary call to BorrowEngine in LoanCloseScenen

---

src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/actions/WalletListMenuActions.tsx
src/components/modals/WalletListMenuModal.tsx
src/components/scenes/FioStakingChangeScene.tsx
src/components/scenes/TransactionListScene.tsx
src/components/themed/TransactionListComponents.tsx
src/components/themed/TransactionListTop.tsx
src/constants/WalletAndCurrencyConstants.ts
src/reducers/scenes/WalletsReducer.ts
src/types/types.ts

none
---
- https://app.asana.com/0/0/1202964302590013

Add settings button to Transaction List

---

src/components/themed/TransactionListTop.tsx

---
- https://app.asana.com/0/0/1203067840406087

Fix staked amount string

---

scripts/configure.ts
src/util/corePlugins.ts

---
- https://app.asana.com/0/0/1200432242640024

Remove unused exchange rate data sources

---

src/components/Main.ui.tsx
src/components/scenes/ExtraTabScene.tsx
src/components/scenes/GuiPluginListScene.tsx
src/components/themed/MenuTab.tsx
src/components/themed/VectorIcon.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json
src/theme/testConfig.ts
src/types/GuiPluginTypes.ts
src/types/routerTypes.tsx
src/types/types.ts

none
---
- https://app.asana.com/0/0/1202687715819276

Add more white label config options

---

src/components/scenes/SendScene.tsx

none
https://user-images.githubusercontent.com/4023066/192337862-0c0291ff-1f5d-4ad5-b890-ec418fc308f7.mp4

Show scam warning prior to address entry

---

src/components/scenes/WalletListScene.tsx
src/components/themed/WalletList.tsx
src/components/themed/WalletListCreateRow.tsx
src/components/themed/WalletListSwipeable.tsx
tsconfig.json

---
- https://app.asana.com/0/0/1202429146875994
- https://app.asana.com/0/0/1202887459567794

Add create wallet/token to wallet list scene search and allow selection of parent wallet for new tokens

---

src/actions/TransactionExportActions.tsx
src/components/scenes/TransactionsExportScene.tsx
src/components/themed/TransactionListRow.tsx

none
---
- https://app.asana.com/0/0/1203096402919670

Fix fiat amount in txlist and export

---

src/components/text/TickerText.tsx

none
---
- https://app.asana.com/0/0/1202986947056213

Show negative percentage symbol in wallet list

---

src/components/scenes/Loans/LoanCreateConfirmationScene.tsx
src/components/scenes/Loans/ManageCollateralScene.tsx

none
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
---
- https://app.asana.com/0/0/1203094883503756

AAVE Back Routing Fixes

---

src/components/scenes/Loans/ManageCollateralScene.tsx

Remove extra call to runLoanActionProgram

---

src/components/scenes/Loans/LoanCreateConfirmationScene.tsx
src/controllers/loan-manager/redux/actions.ts

none
---
- https://app.asana.com/0/0/1203147300024903
- https://app.asana.com/0/0/1203135362263501

Use updateLoanAccount over createLoanAccount for confirmation scene

---

src/actions/DeleteWalletModalActions.tsx

none
---
- https://app.asana.com/0/0/1203059707202833

Remove loan accounts when archiving wallet

---

src/controllers/loan-manager/redux/actions.ts

Fix misplaced await

---

src/components/scenes/TransactionListScene.tsx

none
---
- https://app.asana.com/0/0/1203111210852322

Fix the logout crash on TransactionDetails

---

src/__tests__/scenes/CreateWalletSelectFiatScene.test.tsx
src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap
src/actions/CreateWalletActions.tsx
src/components/scenes/CreateWalletSelectFiatScene.tsx
src/components/themed/WalletListCreateRow.tsx

---
- https://app.asana.com/0/0/1203145897232098

Add unique wallet name helper function

---

src/components/scenes/GuiPluginListScene.tsx

Only show Wyre when a user has a linked bank account with them
none
---
- https://app.asana.com/0/0/1203186994552049

Remove Wyre for new users

---

src/__tests__/components/TransactionListRow.test.tsx
src/actions/TransactionListActions.ts
src/components/scenes/TransactionListScene.tsx
src/reducers/scenes/TransactionListReducer.ts
src/types/reduxActions.ts
src/types/types.ts

none
---
- https://app.asana.com/0/0/1203101814782468

Fix wrong fiat in tx list

---

src/components/tiles/AddressTile.tsx

I tried to do this at the plugin level but ran into challenges with respect to the way `EdgeCurrencyTools` is implemented without access to networking interfaces. By rigging an ethers provider instance into this part of the accountbased implementation I ran into tests failing due to timeouts caused by not properly cleaning up this instance which would otherwise have been cleaned up with start/stop engine methods.
This solution resolves ENS names at the GUI-level specifically for Ethereum wallets in a very straight-forward approach.
none
---
- https://app.asana.com/0/0/1202780140462098

Resolve ENS domain names for Ethereum wallets

---

src/__tests__/scenes/CreateWalletImportScene.test.tsx
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/components/scenes/CreateWalletImportScene.tsx
src/components/scenes/CreateWalletSelectCryptoScene.tsx

---
- https://app.asana.com/0/0/1203194225116502

Create wallet flow cleanups

---

src/components/scenes/ExchangedFlipInputTester.tsx
src/components/scenes/TransactionListScene.tsx
src/components/themed/ExchangedFlipInput2.tsx
src/components/themed/FlipInput2.tsx
src/hooks/useDisplayDenom.ts
src/hooks/useExchangeDenom.ts
src/selectors/DenominationSelectors.ts

none
---
- https://app.asana.com/0/0/1203162131822904

New flip input

---

package.json
scripts/configure.ts
src/components/services/ContactsLoader.ts
src/util/corePlugins.ts
yarn.lock

---
- https://app.asana.com/0/0/1203223435791098

Add Swapuz

---

src/__tests__/__snapshots__/GuiPlugins.test.ts.snap
src/constants/plugins/GuiPlugins.ts
src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json

none
---
- https://app.asana.com/0/0/1203202096227621

Change "Instant ACH" to "ACH Bank Transfer"

---

src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap
src/components/scenes/CreateWalletCompletionScene.tsx
src/components/scenes/CreateWalletImportScene.tsx
src/components/scenes/CreateWalletSelectCryptoScene.tsx
src/components/scenes/CreateWalletSelectFiatScene.tsx

The avoidKeyboard prop behaves differently across devices and was effectively changing the size of the screen on some Samsung devices which affects absolute placement. The prop isn't needed so it's safe to remove. 
---
- https://app.asana.com/0/0/1203198852999817

Remove avoid keyboard prop and svg resizing

---

src/components/services/Services.tsx
src/types/reduxTypes.ts
src/util/middleware/errorAlert.ts
src/util/middleware/loginStatusChecker.ts
src/util/middleware/perfLogger.ts

I tracked down some tricky error suppression comments, and found that our Redux type setup was slightly incorrect.
none
---
- https://app.asana.com/0/0/1203238362784701

Fix type errors in our Redux setup

---

src/plugins/gui/providers/moonpayProvider.ts

none
---
- https://app.asana.com/0/0/1203252063631227

Fix googlepay on moonpay

---

src/components/scenes/TransactionListScene.tsx

---
- https://app.asana.com/0/0/1203218445109629

Logout crash fixes

---

src/components/scenes/Loans/LoanDashboardScene.tsx

none
---
- https://app.asana.com/0/0/1203194315623284

Update default network to MATIC for new loans

---

src/components/scenes/Loans/LoanCreateConfirmationScene.tsx
src/components/scenes/Loans/LoanCreateScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

Update minimums for polygon loan creation to $110 WBTC, $5 MATIC
none

Implement minimums for polygon

---

src/components/scenes/Loans/LoanManageScene.tsx

none
---
- https://app.asana.com/0/0/1203229899601420

Use the correct selected asset wallet for the deposit action

---

src/components/scenes/Loans/LoanDetailsScene.tsx

Refactor the page-long inlined JSX into a function to avoid confusion when updating conditions.
none
---
- https://app.asana.com/0/0/1202949203074528

Refactor Details Scene Loan Action cards

---

src/components/cards/FiatAmountInputCard.tsx

Fix setState warning
Fix value result when pressing submit with no input
none
---
- https://app.asana.com/0/0/1203246012013909

Fix FiatAmountInputCard

---

src/components/scenes/Loans/LoanCloseScene.tsx

none
---
- https://app.asana.com/0/0/1203288128483402

Reduce padding for tiles

---

src/components/scenes/TransactionDetailsScene.tsx

none
---
- https://app.asana.com/0/0/1203295100408480

Disable the the accelerate transaction modal

---

src/components/scenes/Loans/LoanCreateScene.tsx

none
---
- https://app.asana.com/0/0/1203297162489012

Fix swap minimums

---

src/components/scenes/TransactionDetailsScene.tsx

---
- https://app.asana.com/0/0/1203295880622057

Fix incorrect denom in transaction details scene

---

src/controllers/action-queue/cleaners.ts

Fix action queue asActionProgram cleaner

---

src/components/scenes/Loans/LoanDetailsScene.tsx

Hide empty debts in Loan Breakdown

---

src/components/themed/TransactionRow.tsx

none
---
- https://app.asana.com/0/0/1203272763143159

Do not show category if it is an empty string

---

src/components/scenes/Loans/LoanCreateConfirmationScene.tsx
src/controllers/action-queue/cleaners.ts
src/controllers/action-queue/runtime/evaluateAction.ts
src/controllers/action-queue/types.ts

Support a manual payoutNativeAmount that will cause the swap op to be effective.
none
---
- https://app.asana.com/0/0/1203305657654497

Add payoutNativeAmount to the 'swap' action

---

src/__tests__/components/CreateWalletSelectCryptoRow.test.tsx
src/__tests__/components/CurrencyIcon.test.tsx
src/__tests__/components/TransactionListRow.test.tsx
src/__tests__/components/TransactionRow.test.tsx
src/__tests__/components/WalletListFooter.test.tsx
src/__tests__/modals/AdvancedDetailsModal.test.tsx
src/__tests__/modals/CategoryModal.test.tsx
src/__tests__/modals/WalletListModal.test.tsx
src/__tests__/scenes/CreateWalletImportScene.test.tsx
src/__tests__/scenes/CreateWalletSelectCryptoScene.test.tsx
src/__tests__/scenes/CreateWalletSelectFiatScene.test.tsx
src/__tests__/scenes/CurrencyNotificationScene.test.tsx
src/__tests__/scenes/CurrencySettings.ui.test.tsx
src/__tests__/scenes/SettingsScene.test.tsx
src/__tests__/scenes/TransactionDetailsScene.test.tsx

none
---
- https://app.asana.com/0/0/1203330592347681

Use react-test-renderer according to its docs

---

src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/__tests__/scenes/CryptoExchangeQuoteScene.test.tsx
src/__tests__/scenes/Request.test.tsx
src/__tests__/scenes/__snapshots__/Request.test.tsx.snap
src/actions/CryptoExchangeActions.tsx
src/actions/SplitWalletModalActions.tsx
src/actions/WalletListMenuActions.tsx
src/components/modals/WalletListMenuModal.tsx
src/components/modals/WcSmartContractModal.tsx
src/components/scenes/CryptoExchangeQuoteScene.tsx
src/components/scenes/EditTokenScene.tsx
src/components/scenes/FioAddressRegisterScene.tsx
src/components/scenes/FioDomainRegisterScene.tsx
src/components/scenes/Staking/StakeModifyScene.tsx
src/components/scenes/TransactionsExportScene.tsx
src/components/services/SortedWalletList.ts
src/components/themed/ManageTokensRow.tsx
src/hooks/useWalletName.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/modules/FioAddress/components/FioActionSubmit.tsx
src/modules/FioAddress/util.ts
src/modules/UI/scenes/Plugins/EdgeProvider.tsx
src/reducers/scenes/SettingsReducer.ts
src/reducers/scenes/WalletsReducer.ts
src/util/CurrencyWalletHelpers.ts

none
---
- https://app.asana.com/0/0/1203326088773359

Consistent wallet naming

---

src/__tests__/components/TransactionListTop.test.tsx
src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/components/scenes/TransactionListScene.tsx
src/components/themed/TransactionListComponents.tsx
src/components/themed/TransactionListTop.tsx
src/reducers/scenes/WalletsReducer.ts

Commit c96e50d2fcb59fc55bfc8b595836763b2bdfe108 didn't update the top wallet selector to use the route props, so switching wallets doesn't work correctly. This finishes the work.
none
---
- https://app.asana.com/0/0/1203339273564865

Fix tx list selector

---

src/components/cards/LoanDetailsSummaryCard.tsx

Remove info icon from LoanDetailsSummaryCard

---

android/build.gradle

none
---
- https://app.asana.com/0/0/1203152643001415

Drop support for Android 6 and older

---

src/__tests__/modals/__snapshots__/AdvancedDetailsModal.test.tsx.snap
src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap
src/components/themed/ModalParts.tsx

none
---
- https://app.asana.com/0/0/1203229172293404

Use X icon for closing modals

---

src/components/themed/Thermostat.tsx
src/components/tiles/LtvRatioTile.tsx
src/plugins/borrow-plugins/plugins/aave/BorrowEngineFactory.ts

none
---
- https://app.asana.com/0/0/1203348627056673

Fix crash from non-numeric ltvValue

---

Jenkinsfile
scripts/cleaners.ts
scripts/gitVersionFile.ts

none
---
- https://app.asana.com/0/0/1203256232564054

Use git to get version file

---

src/actions/ScanActions.tsx
src/components/common/FormField.tsx
src/components/scenes/SendScene.tsx
src/components/text/CryptoText.tsx
src/components/themed/FioRequestRow.tsx
src/components/themed/OutlinedTextInput.tsx
src/components/themed/SwipeableRow.tsx
src/components/themed/TransactionListTop.tsx
src/components/themed/WalletListHeader.tsx
src/components/tiles/InterestRateChangeTile.tsx
src/hooks/useDisplayDenom.ts
src/hooks/useExchangeDenom.ts
src/reducers/FioReducer.ts
src/types/reduxActions.ts
src/util/matchJson.ts

none
---
- https://app.asana.com/0/0/1203347438849145

Random fixes

---

src/components/scenes/FormScene.tsx
src/components/scenes/Loans/LoanCloseScene.tsx

none
---
- https://app.asana.com/0/0/1203374649830373

Remove unnecessary styling from SceneHeader in AAVE Scenes

---

src/components/scenes/Loans/LoanCreateScene.tsx
src/components/scenes/Loans/LoanDetailsScene.tsx
src/components/scenes/Loans/LoanManageScene.tsx
src/types/routerTypes.tsx
src/util/borrowUtils.ts

Fix filtering rules for wallet pickers on various AAVE scenes.
none
---
- https://app.asana.com/0/0/1203358690101909

AAVE: Asset Selection Filter Fixes

---

package.json
src/components/cards/LoanDetailsSummaryCard.tsx
src/components/modals/WalletListModal.tsx
src/components/scenes/Loans/LoanCloseScene.tsx
src/components/tiles/LtvRatioTile.tsx
src/controllers/action-queue/runtime/evaluateAction.ts
src/controllers/loan-manager/redux/actions.ts
src/controllers/loan-manager/store.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/borrow-plugins/common/ApprovableCall.ts
src/plugins/borrow-plugins/plugins/aave/AaveBorrowEngineFactory.ts
src/util/ActionProgramUtils.ts
yarn.lock

- https://github.com/EdgeApp/edge-currency-accountbased/pull/462
---
- https://app.asana.com/0/0/1203381477966191

Add token amount metadata to borrowEngine smart-contract calls

---

src/actions/DeleteWalletModalActions.tsx
src/actions/WalletListMenuActions.tsx
src/components/modals/WalletListMenuModal.tsx
src/components/themed/ManageTokensRow.tsx

none
---
- https://app.asana.com/0/0/1201858684329251

Disable a token wallet from the wallet's option modal

---

src/components/services/ContactsLoader.ts
src/util/corePlugins.ts

Add: Thorchain DEX Aggregator
none
---
- https://app.asana.com/0/0/1203430168400865

Add thorchain dex aggregator

---

src/components/scenes/Loans/LoanManageScene.tsx

none
---
- https://app.asana.com/0/0/1203415142574763

Fix 'AAVE - Borrow more results in error "Alert! Non-USDC token borrowing not yet implemented"'

---

src/components/hoc/withLoanAccount.tsx
src/components/scenes/Loans/LoanCloseScene.tsx
src/components/scenes/Loans/LoanDetailsScene.tsx
src/components/scenes/Loans/LoanManageScene.tsx
src/components/scenes/Loans/LoanStatusScene.tsx
src/components/services/ActionQueueService.ts
src/controllers/action-queue/cleaners.ts
src/controllers/action-queue/types.ts
src/controllers/action-queue/util/getEffectErrors.ts
src/hooks/useFiatText.ts
src/plugins/borrow-plugins/plugins/aave/AaveBorrowEngineFactory.ts
src/util/PushClient/PushClient.ts
src/util/toBigNumberString.ts

none
---
- https://app.asana.com/0/0/1203414798785237

Fix AAVE crashes

---

src/components/themed/TransactionListRow.tsx
src/hooks/useHistoricalRate.ts
src/util/utils.ts

- Fixed: Incorrect fiat amount metadata after a spend-to-self transaction
none
---
- https://app.asana.com/0/0/1202951457000423

BTC - Send - Metadata are wrong

---

src/types/routerTypes.tsx

The original changes to replace() were never used.
Revert this change.
none
---
- https://app.asana.com/0/0/1203468165055736

Revert changes to navigation.replace()

---

src/constants/WalletAndCurrencyConstants.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/corePlugins.ts

---
- https://app.asana.com/0/0/1203476992457208

Add Tron (TRX)

---

src/components/cards/LoanSummaryCard.tsx
src/components/scenes/Loans/LoanDetailsScene.tsx

none
---
- https://app.asana.com/0/0/1203355923167208

AAVE + Dev mode: Show Wallet Names

---

src/actions/WalletListMenuActions.tsx

none
---
- https://app.asana.com/0/0/1203459955370369

Fix the wallet archive feature

---

jestSetup.js
src/__tests__/components/__snapshots__/CurrencyIcon.test.tsx.snap
src/__tests__/components/__snapshots__/OutlinedTextInput.test.tsx.snap
src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap

none
---
- https://app.asana.com/0/0/1203487494850448

Fix jest mocks

---

src/components/cards/FiatAmountInputCard.tsx

Fix localization handling on FiatAmountInputCard 
Set 2 decimal max precision on FiatAmountInputCard
none
---
- https://app.asana.com/0/0/1203475087427001

Fix localization handling on FiatAmountInputCard

---

src/controllers/loan-manager/redux/actions.ts

This reverts commit 51a3419e292943b1344461fac503fa01f13fc2fd.
none
none
---
- https://app.asana.com/0/0/1203486127856848

Revert "Update activity logs for saveLoanAccount"

---

.github/PULL_REQUEST_TEMPLATE.md

none
none
---
- https://app.asana.com/0/0/1203452497793361

Add Changelog Entries section to PR template

---

src/components/themed/TransactionListTop.tsx

Do not put in changelog since this fixes a bug introduced within release
none
---
- https://app.asana.com/0/0/1203493678800033

Fix infinite render due to setState for non stakable assets

---

src/plugins/stake-plugins/uniswapV2/policies/cemeteryPolicy.ts
src/plugins/stake-plugins/uniswapV2/policies/masonryPolicy.ts

Each smart contract interaction handled by Edge now overrides any existing (typically infinite) token allowances with only what is needed.
TombSwap: Restrict token allowances to only what is needed for each smart contract call.
none
---
- https://app.asana.com/0/0/1203472287438103

Restrict token allowance

---

src/components/scenes/Loans/LoanCloseScene.tsx
src/components/scenes/Loans/LoanCreateConfirmationScene.tsx
src/components/scenes/Loans/LoanCreateScene.tsx
src/components/scenes/Loans/LoanDetailsScene.tsx
src/components/scenes/Loans/LoanManageScene.tsx
src/controllers/action-queue/cleaners.ts
src/controllers/action-queue/display.ts
src/controllers/action-queue/types.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/ActionProgramUtils.ts

Fix/update various LoanStatusScene related items:
- Skip LoanStatusScene routing if program contains only 1 op
- Fix the generic "Action Group" program display message for Loan Close, Borrow More
- Adjust action card summary styling on the LoanDetailsScene
- Fix back button routing and weird extra scene transitions after creating new loans
N/A (Beta)
none
---
- https://app.asana.com/0/0/1203536450138324

Loan Status Improvements

---

src/components/scenes/FormScene.tsx
src/components/scenes/Loans/LoanCloseScene.tsx

none
none
---
- https://app.asana.com/0/0/1203527770648161

Fix disabled slider text

---

src/components/scenes/GuiPluginListScene.tsx
src/plugins/gui/creditCardPlugin.ts

none
none
---
- https://app.asana.com/0/0/1203505192040050

Allow partial set of ENV.PLUGIN_API_KEYS

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1203572005453985

2.28.0 Changelog

---

src/components/services/AirshipInstance.tsx

Send showError and showWarning messages to Bugsnag
none
---
- https://app.asana.com/0/0/1203572162743940

Send any showError and showWarning calls to Bugsnag

---

src/__tests__/components/__snapshots__/CreateWalletSelectCryptoRow.test.tsx.snap
src/__tests__/components/__snapshots__/CurrencyIcon.test.tsx.snap
src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap
src/util/CdnUris.ts

none
none
---
- https://app.asana.com/0/0/1203572217324218

Switch to UI3 currency icons

---

src/components/scenes/TransactionDetailsScene.tsx

Fixes missing historical fiat value when entering TxDetails from anywhere but the transaction list.
Fix missing fiat amounts in Transaction Details screen
none
---
- https://app.asana.com/0/0/1203580495691920

Get historical fiat in TxDetails

---

src/actions/TransactionListActions.ts
src/components/scenes/TransactionListScene.tsx
src/util/utils.ts

none
none
---
- https://app.asana.com/0/0/1203580386834270

Move spam tx filtering to render function

---

.gitignore
android/app/build.gradle
ios/Podfile
ios/Podfile.lock
ios/edge.xcodeproj/project.pbxproj
package.json
scripts/prepare.sh
src/constants/WalletAndCurrencyConstants.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/corePlugins.ts
yarn.lock

---
- https://app.asana.com/0/0/1202288034748113

Add Piratechain

---

src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts

none
none
---
- https://app.asana.com/0/0/1203598419533694

Remove extra slash from thorchain URL

---

src/components/themed/Thermostat.tsx

Original: 
Changed: 
AAVE: Use themed colors (positiveText, negativeText) for Thermostat (LTV) component
none
---
- https://app.asana.com/0/0/1203590158113499

Update thermostat to use theme colors

---

src/components/scenes/SettingsScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

https://user-images.githubusercontent.com/4023066/209682400-be73face-6271-4f63-a521-b4cc3f356f6b.mp4
---
- https://app.asana.com/0/0/1202577808849950

Show account deletion feedback

---

src/__tests__/modals/AccelerateTxModal.test.tsx
src/__tests__/modals/__snapshots__/AccelerateTxModal.test.tsx.snap
src/components/modals/AccelerateTxModal.tsx
src/components/scenes/TransactionDetailsScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/fake/fakeCurrencyPlugin.ts
src/util/translateError.ts

- Changed: Re-enable accelerate transaction feature using new core API
- https://github.com/EdgeApp/edge-core-js/pull/493
- https://github.com/EdgeApp/edge-currency-accountbased/pull/483
---
- https://app.asana.com/0/0/1203595178388214

Re-enable Accelerate Transaction

---

src/components/scenes/Staking/StakeModifyScene.tsx
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
src/plugins/stake-plugins/types.ts

Disable max button for TC Savers
none
---
- https://app.asana.com/0/0/1203604430648293

Disable max button for TC Savers staking

---

src/components/cards/EarnCryptoCard.tsx
src/components/themed/BuyCrypto.tsx
src/components/themed/ControlPanel.tsx
src/types/types.ts

none
none
---
- https://app.asana.com/0/0/1203598419533713

Allow hiding Ionia rewards for other apps

---

src/components/services/Services.tsx
src/components/themed/WalletList.tsx
src/util/serverState.ts

none
none
---
- https://app.asana.com/0/0/1203660914876625

Restrict wallet creation per assetOverrides from info server

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1203660431077343

v3.0.0 Changelog

---

src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/components/themed/ExchangedFlipInput2.tsx
src/components/tiles/EditableAmountTile.tsx

none
Properly round amounts in Send Scene instead of truncating.
none
none
---
- https://app.asana.com/0/0/1203557731071573
- https://app.asana.com/0/0/1203582862868960

Round amounts in SendScene/ExchangedFlipInput

---

src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/__tests__/scenes/__snapshots__/RequestScene.test.tsx.snap
src/locales/en_US.ts
src/locales/strings/enUS.json

none
none
|                                                      TransactionListTop                                                     |                                                      RequestScene                                                     |
|:---------------------------------------------------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------:|
| ![TransactionListTop](https://user-images.githubusercontent.com/4023066/211092812-90421fdc-5691-433e-94b2-13750daf8e8d.png) | ![RequestScene](https://user-images.githubusercontent.com/4023066/211092872-ad936484-b53c-46de …

Change 'Request' to 'Receive'

---

src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap
src/components/scenes/SettingsScene.tsx
src/components/themed/SettingsRow.tsx
src/components/themed/SettingsTappableRow.tsx

Show 'Delete Account' in the settings scene when locked
none
|                                                      Locked                                                     |                                                      Unlocked                                                     |
|:---------------------------------------------------------------------------------------------------------------:|:-----------------------------------------------------------------------------------------------------------------:|
| ![locked](https://user-images.githubusercontent.com/4023066/211089445-a1345809-477f-41fd-8903-5402a5546736.png) | ![unlocked](https://user-images.githubusercontent.com/4023066/211089562-7404248a-ec6f-4 …

Show 'Delete Account' in the settings scene when locked

---

src/components/themed/ExchangedFlipInput.tsx

This guy relies on some bad hacks to work correctly. We removed those hacks in 56135da548dee880be7a21e2786d270363f6b901, but now we are putting them back in a more explicit way.
none
none
---
- https://app.asana.com/0/0/1203661324582201

Fix the legacy FlipInput component

---

ios/Podfile.lock
ios/edge.xcodeproj/project.pbxproj
package.json
scripts/configure.ts
scripts/hack-travis.mjs
scripts/prepare.sh
src/components/services/EdgeCoreManager.tsx
src/declare-modules.d.ts
src/util/corePluginBundle.js
yarn.lock

changed: Use the upstream edge-currency-accountbased bundle instead of re-bundling it ourselves.
https://github.com/EdgeApp/edge-currency-accountbased/pull/477
---
- https://app.asana.com/0/0/1203708973904748

Upgrade to edge-currency-accountbased v0.22.0

---

src/__tests__/__snapshots__/GuiPlugins.test.ts.snap
src/components/modals/WalletListModal.tsx
src/components/scenes/Loans/LoanCreateScene.tsx
src/components/scenes/Loans/LoanManageScene.tsx
src/constants/plugins/GuiPlugins.ts
src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json
src/controllers/action-queue/WyreClient.ts
src/controllers/action-queue/runtime/evaluateAction.ts
src/controllers/action-queue/runtime/mock/evaluateAction.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/ActionProgramUtils.ts

Disable Wyre

---

CHANGELOG.md
package.json

---
- https://app.asana.com/0/0/1203746481800610

v3.1.0 Changelog

---

src/__tests__/scenes/__snapshots__/RequestScene.test.tsx.snap
src/components/scenes/RequestScene.tsx

---
- https://app.asana.com/0/0/1203704965022950

Disable the launch explorer functionality and hide the chevron if the address explorer url is an empty string

---

src/__tests__/components/TransactionListRow.test.tsx
src/__tests__/components/TransactionRow.test.tsx
src/components/themed/TransactionRow.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

---
- https://app.asana.com/0/0/1203444039875736

Add rbf text option to transaction row

---

src/__tests__/components/BuyCrypto.test.tsx
src/__tests__/components/SelectFioAddress.test.tsx
src/__tests__/components/TransactionListRow.test.tsx
src/__tests__/components/TransactionRow.test.tsx
src/__tests__/components/WalletListHeader.test.tsx
src/__tests__/modals/PasswordReminderModal.test.tsx
src/actions/DeepLinkingActions.ts
src/components/Main.ui.tsx
src/components/modals/PasswordReminderModal.tsx
src/components/modals/PriceChangeBuySellSwapModal.tsx
src/components/navigation/GuiPluginBackButton.tsx
src/components/scenes/FioStakingOverviewScene.tsx
src/components/scenes/Loans/LoanCreateConfirmationScene.tsx
src/components/scenes/Loans/LoanManageScene.tsx
src/components/scenes/SendScene.tsx
src/components/scenes/SendScene2.tsx
src/components/scenes/TransactionDetailsScene.tsx
src/components/scenes/TransactionListScene.tsx
src/components/scenes/WalletListScene.tsx
src/components/services/AccountCallbackManager.tsx
src/components/themed/BuyCrypto.tsx
src/components/themed/ControlPanel.tsx
src/components/themed/SelectFioAddress.tsx
src/components/themed/SelectFioAddress2.tsx
src/components/themed/TransactionListRow.tsx
src/components/themed/TransactionListTop.tsx
src/components/themed/WalletListHeader.tsx

- Deprecate react-native-router-flux in most components
sam/navigation-actions
---
- https://app.asana.com/0/0/1203659728447756

Replace Actions with navigation in components

---

src/modules/UI/scenes/Plugins/EdgeProvider.tsx

none
https://github.com/EdgeApp/edge-react-gui/pull/3932
---
- https://app.asana.com/0/0/1203527749920572

Use SendScene2 for EdgeProvider 

---

src/types/routerTypes.tsx

none
none
---
- https://app.asana.com/0/0/1203787002444479

Fix broken `navigation.replace` poly-fill.

---

src/__tests__/components/__snapshots__/MenuTab.test.tsx.snap
src/components/themed/ControlPanel.tsx
src/components/themed/MenuTab.tsx
src/types/routerTypes.tsx
src/util/fake/fakeNavigation.ts

Compare our version with the version in the docs.
none
none

Make our navigation polyfill more realistic

---

src/plugins/gui/providers/banxaProvider.ts

Add Banxa GooglePay support
none
---
- https://app.asana.com/0/0/1203779760329170

Add Banxa GooglePay support

---

src/components/themed/TransactionListTop.tsx

-fix: staked funds display denomination
none
---
- https://app.asana.com/0/0/1203721784528155

Fix staked funds display denomination

---

ios/Podfile.lock
package.json
src/__tests__/components/__snapshots__/ClickableRow.test.tsx.snap
src/__tests__/components/__snapshots__/MenuTab.test.tsx.snap
src/__tests__/modals/__snapshots__/AutoLogoutModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CurrencyNotificationScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CurrencySettings.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/FioAddressListScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/components/scenes/FioAddressListScene.tsx
src/components/scenes/FioRequestListScene.tsx
src/components/themed/SwipeableRow.tsx
src/components/themed/TransactionListComponents.tsx
src/components/themed/WalletListSwipeableCurrencyRow.tsx
src/components/themed/WalletListSwipeableLoadingRow.tsx
src/modules/UI/components/Gradient/Gradient.ui.tsx
src/theme/variables/edgeDark.ts
src/theme/variables/edgeLight.ts
src/theme/variables/testDark.ts
src/theme/variables/testLight.ts
src/types/Theme.ts
yarn.lock

- Changed: Adjust background gradient to be vertical
none
---
- https://app.asana.com/0/0/1203761519516997

Vertical background gradient

---

src/modules/UI/scenes/Plugins/EdgeProvider.tsx

---
- https://app.asana.com/0/0/1203803380676717

Re-add currency icon paths to EdgeProvider getCurrentWalletInfo return value

---

src/components/scenes/SendScene2.tsx

Fix tagging transactions with payee name from URI label param
none
---
- https://app.asana.com/0/0/1203792073176254

Fix using label param in URI to tag transactions

---

src/components/data/row/CurrencyRow.tsx

Show exchange rate even if there is no tokenId
none
none
---
- https://app.asana.com/0/0/1203791209382666

Fix missing exchange rate on wallet row

---

src/__tests__/scenes/__snapshots__/FioAddressDetailsScene.test.tsx.snap
src/components/navigation/TransactionDropdown.tsx
src/components/scenes/FioAddressDetailsScene.tsx
src/components/scenes/FioAddressRegisterScene.tsx
src/modules/FioAddress/components/ConnectWallets.tsx
src/modules/FioAddress/components/DomainListModal.tsx
src/modules/UI/scenes/Plugins/EdgeProvider.tsx

none
none
---
- https://app.asana.com/0/0/1201388479070452

Clean up remaining actions uses

---

src/components/icons/PairIcons.tsx
src/components/scenes/DefaultFiatSettingScene.tsx
src/components/scenes/FioRequestListScene.tsx
src/components/themed/MaybeCustomServersSetting.tsx
src/modules/FioAddress/components/ConnectWallets.tsx
src/modules/FioAddress/components/DomainListModal.tsx

---
- https://app.asana.com/0/0/1203848674296948

Audit use of array indices as component keys

---

scripts/configure.ts
src/reducers/scenes/SettingsReducer.ts

- Removed BETA_FEATURES_DEV_MODE_ONLY developer env.json configuration
none
---
- https://app.asana.com/0/0/1203404797838780

Remove BETA_FEATURES_DEV_MODE_ONLY from env.json

---

src/__tests__/components/SelectFioAddress.test.tsx
src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/actions/CreateWalletActions.tsx
src/actions/SplitWalletModalActions.tsx
src/actions/WalletActions.tsx
src/actions/WalletListMenuActions.tsx
src/components/modals/WcSmartContractModal.tsx
src/components/navigation/HeaderTitle.tsx
src/components/scenes/CreateWalletAccountSelectScene.tsx
src/components/scenes/FioAddressRegisterSelectWalletScene.tsx
src/components/scenes/FioDomainRegisterSelectWalletScene.tsx
src/components/scenes/FioRequestListScene.tsx
src/components/scenes/FioSentRequestDetailsScene.tsx
src/components/scenes/FioStakingChangeScene.tsx
src/components/scenes/FioStakingOverviewScene.tsx
src/components/scenes/SendScene2.tsx
src/components/scenes/TransactionDetailsScene.tsx
src/components/scenes/WcConnectScene.tsx
src/components/services/AccountCallbackManager.tsx
src/components/services/WalletLifecycle.ts
src/components/themed/FioRequestRow.tsx
src/components/themed/SelectFioAddress.tsx
src/reducers/scenes/WalletsReducer.ts
src/selectors/WalletSelectors.ts
src/types/reduxActions.ts
src/types/types.ts

none
none
---
- https://app.asana.com/0/0/1203869381348558

No GuiWallet

---

src/__tests__/scenes/RequestScene.test.tsx
src/actions/WalletActions.tsx
src/components/modals/WalletListMenuModal.tsx
src/components/navigation/TransactionDropdown.tsx
src/components/scenes/RequestScene.tsx
src/components/scenes/SendScene.tsx
src/components/scenes/WcConnectScene.tsx
src/components/themed/ControlPanel.tsx
src/components/themed/TransactionListRow.tsx
src/components/themed/TransactionListTop.tsx
src/components/themed/WalletList.tsx
src/components/themed/WalletListSwipeable.tsx
src/components/themed/WalletListSwipeableCurrencyRow.tsx
src/constants/WalletAndCurrencyConstants.ts

Cleanup to facilitate XRP tokens
1. Allow for currency plugins that support tokens without custom tokens
2. Refactor selectWallet to allow for token activation
none
https://github.com/EdgeApp/edge-core-js/pull/501
---
- https://app.asana.com/0/0/1203860324833432

Token wallet cleanup

---

src/components/common/TextDropdown.tsx
src/components/scenes/SettingsScene.tsx

Show a dropdown indicating that account deletion succeeded. 
none
---
- https://app.asana.com/0/0/1203717474770600

Add TextDropdown component for confiming account deletion

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1203880380954153

v3.2.0 Changelog

---

src/components/scenes/SendScene2.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
none
---
- https://app.asana.com/0/0/1203880315889917

Fix make spend

---

src/__tests__/GuiPlugins.test.ts
src/__tests__/__snapshots__/GuiPlugins.test.ts.snap
src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/__tests__/scenes/CryptoExchangeScene.test.tsx
src/actions/CryptoExchangeActions.tsx
src/actions/ExchangeInfoActions.ts
src/components/scenes/CryptoExchangeScene.tsx
src/components/scenes/GuiPluginListScene.tsx
src/components/services/Services.tsx
src/modules/UI/reducer.ts
src/plugins/gui/creditCardPlugin.ts
src/plugins/gui/fiatPlugin.tsx
src/plugins/gui/fiatPluginTypes.ts
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
src/reducers/ExchangeInfoReducer.ts
src/types/reduxActions.ts
src/util/GuiPluginTools.ts
src/util/serverState.ts

---
- https://app.asana.com/0/0/1203666515493951

Add exchangeInfo to redux

---

src/actions/WalletActions.tsx

Select wallet before early exit

---

src/actions/ScanActions.tsx

none
none
---
- https://app.asana.com/0/0/1203927979295605

Use the correct wallet to sweep private keys

---

src/util/tracking.ts

none
none
---
- https://app.asana.com/0/0/1203949301248776

Add version info as a param to all tracked events

---

src/locales/en_US.ts
src/locales/strings/enUS.json

none
none
---
- https://app.asana.com/0/0/1203970478941580

Change default XRP wallet name

---

src/actions/LoginActions.tsx
src/components/scenes/CreateWalletSelectCryptoScene.tsx
src/types/routerTypes.tsx

none
none
---
- https://app.asana.com/0/0/1203995389966609

Fix routing during create account workflow

---

src/actions/SettingsActions.tsx
src/components/scenes/SwapSettingsScene.tsx
src/modules/Core/Account/settings.ts

Fix exchange settings not saving after logout
none
---
- https://app.asana.com/0/0/1203411283954272

Fix non-sticky exchange settings

---

src/envConfig.ts
src/util/corePlugins.ts

none
https://github.com/EdgeApp/edge-exchange-plugins/pull/263
---
- https://app.asana.com/0/0/1203980209263040

Enable Lifi swap plugin

---

src/components/Main.tsx

none
none
---
- https://app.asana.com/0/0/1204008571723883

Fix component re-mount issue caused by using HOC for scene components

---

src/components/themed/BuyCrypto.tsx

none
none
---
- https://app.asana.com/0/0/1204015929948740

Fix navigation to PluginListBuy from BuyCrypto component

---

src/components/scenes/LoginScene.tsx

---
- https://app.asana.com/0/0/1204093307855093

Fix recovery deeplink infinite loop

---

src/components/scenes/MigrateWalletCalculateFeeScene.tsx
src/components/scenes/MigrateWalletCompletionScene.tsx

---
- https://app.asana.com/0/0/1204100397034098

Migrate wallet fixes

---

src/locales/en_US.ts
src/locales/strings/enUS.json

Rebrand RSK to Rootstock
The https://github.com/EdgeApp/edge-currency-accountbased/pull/484 for edge-currency-accountbased repository. Pull requests can be merged in any order

Rebrand RSK to Rootstock - display name

---

src/components/cards/StakingReturnsCard.tsx
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
src/plugins/stake-plugins/types.ts

none
none
---
- https://app.asana.com/0/0/1204012354710167

Do not crash if apy == null

---

ios/Podfile.lock
package.json
src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap
src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap
src/components/modals/AddressModal.tsx
src/components/modals/CategoryModal.tsx
src/components/modals/ListModal.tsx
src/components/modals/WalletListModal.tsx
src/components/scenes/CoinRankingScene.tsx
src/components/scenes/CreateWalletCompletionScene.tsx
src/components/scenes/CreateWalletSelectCryptoScene.tsx
src/components/scenes/CreateWalletSelectFiatScene.tsx
src/components/scenes/DefaultFiatSettingScene.tsx
src/components/scenes/GuiPluginListScene.tsx
src/components/scenes/Loans/LoanDashboardScene.tsx
src/components/scenes/ManageTokensScene.tsx
src/components/scenes/Staking/StakeOptionsScene.tsx
src/components/scenes/Staking/StakeOverviewScene.tsx
src/components/themed/WalletList.tsx
src/components/themed/WalletListSwipeable.tsx
src/modules/FioAddress/components/ConnectWallets.tsx
src/modules/FioAddress/components/DomainListModal.tsx
yarn.lock

---
- https://app.asana.com/0/0/1204008899312552

Replace all `FlatList`s with `FlashList`

---

src/actions/SplitWalletModalActions.tsx
src/actions/WalletListMenuActions.tsx
src/components/modals/WalletListMenuModal.tsx

---
- https://app.asana.com/0/0/1204092193076810

Replace currency code with pluginId to identify splittable walletType

---

src/__tests__/modals/__snapshots__/AccelerateTxModal.test.tsx.snap
src/__tests__/modals/__snapshots__/AddressModal.test.tsx.snap
src/__tests__/modals/__snapshots__/AdvancedDetailsModal.test.tsx.snap
src/__tests__/modals/__snapshots__/HelpModal.test.tsx.snap
src/__tests__/modals/__snapshots__/PasswordReminderModal.test.tsx.snap
src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap
src/components/modals/AccelerateTxModal.tsx
src/components/modals/AddressModal.tsx
src/components/modals/AdvancedDetailsModal.tsx
src/components/modals/ButtonsModal.tsx
src/components/modals/ConfirmContinueModal.tsx
src/components/modals/FioExpiredModal.tsx
src/components/modals/GradientFadeout.tsx
src/components/modals/HelpModal.tsx
src/components/modals/ListModal.tsx
src/components/modals/PasswordReminderModal.tsx
src/components/modals/PermissionsSettingModal.tsx
src/components/modals/RawTextModal.tsx
src/components/modals/ScanModal.tsx
src/components/modals/TextInputModal.tsx
src/components/modals/UpdateModal.tsx
src/components/modals/WalletListMenuModal.tsx
src/components/modals/WalletListModal.tsx
src/components/modals/WcSmartContractModal.tsx
src/components/scenes/FioStakingChangeScene.tsx
src/components/themed/ModalParts.tsx
src/modules/FioAddress/components/DomainListModal.tsx

Add a gradient fadeout to the bottom of List modals
none
|                                                         ContactListModal                                                         |                                                         CountryListModal                                                         | FiatListModal                                                                                                                    |
|:--------------------------------------------------------------------------------------------------------------------------------:|:--------------------------------------------------------------------------------------------------------------------------------:|------------- …

Add bottom GradientFadeout to ListModals

---

src/actions/CreateWalletActions.tsx
src/actions/CryptoExchangeActions.tsx
src/actions/DeepLinkingActions.ts
src/actions/LoginActions.tsx
src/actions/ScanActions.tsx
src/actions/SettingsActions.tsx
src/components/Main.tsx
src/components/modals/InsufficientFeesModal.tsx
src/components/modals/PriceChangeBuySellSwapModal.tsx
src/components/scenes/CreateWalletCompletionScene.tsx
src/components/scenes/CreateWalletSelectCryptoScene.tsx
src/components/scenes/CreateWalletSelectFiatScene.tsx
src/components/scenes/CryptoExchangeSuccessScene.tsx
src/components/scenes/FioAddressRegisterSelectWalletScene.tsx
src/components/scenes/FioDomainRegisterSelectWalletScene.tsx
src/components/scenes/FioNameConfirmScene.tsx
src/components/scenes/GuiPluginListScene.tsx
src/components/themed/BuyCrypto.tsx
src/components/themed/MenuTabs.tsx
src/types/routerTypes.tsx

none
none
---
- https://app.asana.com/0/0/1204091777780323

Add nested navigators for menus tabs

---

src/__tests__/modals/__snapshots__/AdvancedDetailsModal.test.tsx.snap
src/components/modals/AdvancedDetailsModal.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
none
---
- https://app.asana.com/0/0/1204093647236013

Add ourReceiveAddresses to advanced tx details modal

---

src/actions/LoginActions.tsx
src/components/scenes/CreateWalletSelectFiatScene.tsx
src/components/themed/WalletListErrorRow.tsx
src/components/themed/WalletListSwipeableLoadingRow.tsx

1) Show errors when creating wallets fails in account creation and when creating a single wallet
2) Show an error row when loading wallet fails
---
- https://app.asana.com/0/0/1204119791048624

Tweak currency wallet error handling

---

src/components/Main.tsx

none
none
---
- https://app.asana.com/0/0/1204132743554688

Fix 2FA that won't get the screen to allow or deny access

---

src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/__tests__/reducers/createWalletReducer.test.ts
src/__tests__/reducers/scenesReducer.test.ts
src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap
src/actions/CreateWalletActions.tsx
src/components/scenes/CreateWalletAccountSelectScene.tsx
src/components/scenes/CreateWalletAccountSetupScene.tsx
src/reducers/scenes/CreateWalletReducer.ts
src/theme/variables/airbitz.ts

none
none
---
- https://app.asana.com/0/0/1204144607084259

Fix Hedera activation

---

CHANGELOG.md

none
none
---
- https://app.asana.com/0/0/1204157221656034

v3.5.0 Changelog

---

src/util/CurrencyInfoHelpers.ts

Check for undefined currencyConfig
none
none
---
- https://app.asana.com/0/0/1204169694656241

Fix getTokenId crash

---

android/app/src/main/java/co/edgesecure/app/MainActivity.java

Do not used savedInstanceState since it may be inconsistent
https://stackoverflow.com/questions/57709742/unable-to-instantiate-fragment-com-swmansion-rnscreens-screen
none
none
---
- https://app.asana.com/0/0/1204169694656247

Fix android crash

---

src/modules/UI/scenes/Plugins/EdgeProvider.tsx

- fixed: Do not crash when visiting a buy / sell partner with no selected wallet.
none
---
- https://app.asana.com/0/0/1201400342342412

Fix EdgeProvider crash

---

src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap
src/components/scenes/CreateWalletCompletionScene.tsx
src/components/scenes/CreateWalletSelectCryptoScene.tsx
src/components/scenes/CreateWalletSelectFiatScene.tsx
src/components/scenes/MigrateWalletCalculateFeeScene.tsx
src/components/scenes/MigrateWalletCompletionScene.tsx
src/components/scenes/MigrateWalletSelectCryptoScene.tsx

FlashList is like an upgraded FlatList, but more aggressive with optimization. Because of this, we need to pass in `extraData` so it will update correctly.
FlashList also doesn't take a CSS `style` prop, so we need to delete those or get yellow warning boxes.
Also, we need to apply `useHandler` correctly, or not at all.
none
none
---
- https://app.asana.com/0/0/1204122607311075

Fix list usage in create / migrate wallet scenes

---

src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/components/scenes/SendScene2.tsx

none
none
---
- https://app.asana.com/0/0/1204179431208704

Fix centering of slider on send scene

---

src/actions/WalletActions.tsx
src/components/services/Services.tsx

---
- https://app.asana.com/0/0/1204179974732489

Move notification registration to Services

---

src/components/scenes/CoinRankingScene.tsx

none
none
---
- https://app.asana.com/0/0/1204178091170009

Fix market view toggles

---

src/components/interactions/SwipeOffsetDetector.tsx
src/components/scenes/GettingStartedScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
none
---
- https://app.asana.com/0/0/1204190903539521

USP Getting Started Scene Fixes

---

src/util/tracking.ts

added- Add tracking event data to logs
none
---
- https://app.asana.com/0/0/1204207399694359

Add tracking event data to logs

---

src/components/scenes/GuiPluginViewScene.tsx
src/components/scenes/Loans/LoanDashboardScene.tsx

none
none
---
- https://app.asana.com/0/0/1204196564436860

Visual gap at bottom of GuiPluginViewScene

---

src/components/scenes/MigrateWalletCalculateFeeScene.tsx

---
- https://app.asana.com/0/0/1204225086637355

Fix walletId reference in migration flow

---

src/actions/PaymentProtoActions.tsx
src/components/Main.tsx
src/components/scenes/SendScene2.tsx
src/modules/UI/scenes/Plugins/EdgeProvider.tsx

none
none
---
- https://app.asana.com/0/0/1204220396495751

Always pop SendScene2

---

src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/components/scenes/CreateWalletSelectCryptoScene.tsx

none
none
---
- https://app.asana.com/0/0/1204283628952435

Fix the create-wallet layout glitch

---

src/components/scenes/Fio/FioNameConfirmScene.tsx

---
- https://app.asana.com/0/0/1204295865014335

Fix missing theme in FioNameConfirmScene

---

src/__tests__/components/SelectFioAddress.test.tsx
src/components/Main.tsx
src/components/scenes/Fio/FioAddressSettingsScene.tsx
src/components/scenes/Fio/FioNameConfirmScene.tsx
src/components/scenes/Fio/FioRequestConfirmationScene.tsx
src/components/scenes/Fio/FioRequestListScene.tsx
src/modules/FioAddress/util.ts
src/types/routerTypes.tsx
src/types/types.ts

---
- https://app.asana.com/0/0/1204112329611718
- https://app.asana.com/0/0/1204211925285852

Replace FIO Actions with makeSpend, signTx, broadcastTx flow

---

src/components/services/SortedWalletList.ts
src/reducers/RootReducer.ts

---
- https://app.asana.com/0/0/1204273436087024

Wipe out sortedWalletList on logout

---

src/envConfig.ts
src/util/corePlugins.ts

---
- https://app.asana.com/0/0/1204333453142142

Add AVAX evmscan keys

---

src/components/scenes/EdgeLoginScene.tsx

none
none
---
- https://app.asana.com/0/0/1204255811350308

Use the correct logo for Edge login

---

src/util/exchangeRates.ts

Resolve null rates to 0
none
none
---
- https://app.asana.com/0/0/1204293288180110

Fix unresolved getHistoricalRate promises

---

src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/components/scenes/CreateWalletSelectCryptoScene.tsx

none
none
---
- https://app.asana.com/0/0/1204323588900417

Drop the keyboard when scrolling the create-wallet list

---

src/components/tiles/SwapDetailsTiles.tsx

---
- https://app.asana.com/0/0/1204166429714718

Fix currencyCode case

---

src/components/Main.tsx

none
none
---
- https://app.asana.com/0/0/1204342627698616

Define a react-navigation Theme to fix white background behinds scenes

---

src/components/services/ContactsLoader.ts
src/util/corePlugins.ts

---
- https://app.asana.com/0/0/1204351102858687

Add Velodrome

---

CHANGELOG.md
ios/Podfile.lock
package.json
src/actions/LoginActions.tsx
src/components/Main.tsx
src/components/scenes/GettingStartedScene.tsx
src/components/scenes/LoginScene.tsx
yarn.lock

- changed: Allow routing to GettingStartedScene from LoginScene
none
---
- https://app.asana.com/0/0/1204222679938640

Allow routing to GettingStartedScene from LoginScene

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1204367782806056

v3.7.0 Changelog

---

src/actions/LoginActions.tsx

Ensure createCustomWallets() begins prior to starting the new user FIO handle flow, while also ensuring that createCustomWallets() still finishes before starting updateWalletsRequest().
This change preserves the original code flow in all scenarios while satisfying fioCreateHandle's dependency of the createCustomWallets() call.
- fix: Red error dropdown when quickly progressing through the new user FIO handle flow.
none
---
- https://app.asana.com/0/0/1204385705490826

Fix error dropdown when quickly creating a FIO handle

---

src/__tests__/components/__snapshots__/OutlinedTextInput.test.tsx.snap
src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/components/scenes/Fio/FioCreateHandleScene.tsx
src/components/themed/OutlinedTextInput.tsx

- fixed: FIO Create Handle: Unable to delete first two characters of the handle when using backspace.
- fixed: FIO Create Handle: Double tapping clear in the handle input box removes the domain.
none
---
- https://app.asana.com/0/0/1204385705490826
- https://app.asana.com/0/0/1204378156120794
- https://app.asana.com/0/0/1204366217589433

Fix New User Free Fio Handle Scene

---

android/app/src/main/AndroidManifest.xml
ios/edge/Info.plist
scripts/patchFiles.ts
src/envConfig.ts

---
- https://app.asana.com/0/0/1204407648172338

Fix placeholder Bugsnag api key

---

src/actions/TransactionListActions.ts
src/components/scenes/TransactionDetailsScene.tsx
src/components/scenes/TransactionListScene.tsx
src/components/services/AccountCallbackManager.tsx
src/components/themed/TransactionListRow.tsx
src/components/themed/TransactionRow.tsx
src/util/utils.ts

- Update all code that created EdgeTransaction objects to also include `isSend`
none
none
---
- https://app.asana.com/0/0/1204343038506603

Use tx.isSend from edge-core-js 0.20.1

---

src/components/modals/WcSmartContractModal.tsx
src/components/scenes/WcConnectScene.tsx

---
- https://app.asana.com/0/0/1204414162532213

Fix async method usage

---

package.json
yarn.lock

none
none
---
- https://app.asana.com/0/0/1204416640006843

Add `react-native-email-link` dependency

---

src/__tests__/amountQuotePlugin.test.ts
src/plugins/gui/amountQuotePlugin.ts
src/plugins/gui/fiatProviderTypes.ts
src/plugins/gui/pluginUtils.ts
src/plugins/gui/providers/banxaProvider.ts
src/plugins/gui/providers/bityProvider.ts
src/plugins/gui/providers/dummyProvider.ts
src/plugins/gui/providers/dummyProvider2.ts
src/plugins/gui/providers/moonpayProvider.ts
src/plugins/gui/providers/simplexProvider.ts

---
- https://app.asana.com/0/0/1204204341600313

Fix region restriction error message handling

---

src/actions/LoginActions.tsx
src/components/Main.tsx

none
none
---
- https://app.asana.com/0/0/1204425462572479

Use `navigate` method to logout by modifying useBackEvent conditions

---

src/components/themed/FlipInput2.tsx

- fixed: Stabilize the keyboard when toggling the flip input.
none
---
- https://app.asana.com/0/0/1204425626125206

Stabilize the keyboard in the flip input

---

src/components/Main.tsx
src/components/navigation/EdgeLogoHeader.tsx
src/components/scenes/GettingStartedScene.tsx
src/components/scenes/LoginScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json
src/types/Theme.ts
src/util/ThemeCache.ts

Fixed uncentered Edge header logo on Android devices
None
| Wallet 	| Markets 	|
|---	|---	|
| ![wallet](https://user-images.githubusercontent.com/4023066/232646204-6601ae42-b21c-4fb9-9bc5-853c7514d1e1.jpg) 	| ![markets](https://user-images.githubusercontent.com/4023066/232646209-a2551c81-b46b-4b9a-9100-c217bc42ef1e.jpg) 	|
---
- https://app.asana.com/0/0/1204206920053793

Fixed uncentered Edge header logo on Android devices

---

src/plugins/gui/providers/simplexProvider.ts

none
none
---
- https://app.asana.com/0/0/1204085523933642

Enable Simplex Google Pay

---

src/actions/ScanActions.tsx
src/components/scenes/SendScene2.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
https://github.com/EdgeApp/edge-core-js/pull/522
---
- https://app.asana.com/0/0/1204428771512399

Support minNativeAmount

---

src/components/modals/WcSmartContractModal.tsx

---
- https://app.asana.com/0/0/1204452616785615

Fix eth_signTypedData_v4 support

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1204464090400187

v3.8.0 Changelog

---

src/components/modals/WcSmartContractModal.tsx
src/components/scenes/WcConnectScene.tsx
src/components/scenes/WcDisconnectScene.tsx
src/components/services/AccountCallbackManager.tsx

---
- https://app.asana.com/0/0/1204335086711417

Add Algorand wallet connect v1 support

---

README.md

none
none
---
- https://app.asana.com/0/0/1204385117905380

Update readme with new image/text

---

src/components/scenes/TransactionListScene.tsx

none
none
---
- https://app.asana.com/0/0/1204482287410159

Do the spam filter earlier in the tx list

---

jestSetup.js
src/components/Main.tsx
src/components/common/SceneWrapper.tsx
src/components/legacy/AirshipModal.tsx
src/components/navigation/BackButton.tsx
src/components/navigation/CurrencySettingsTitle.tsx
src/components/navigation/EdgeLogoHeader.tsx
src/components/navigation/HeaderTextButton.tsx
src/components/navigation/HeaderTitle.tsx
src/components/navigation/NavigationButton.tsx
src/components/navigation/SideMenuButton.tsx
src/components/navigation/TransactionDetailsTitle.tsx
src/theme/variables/airbitz.ts

This makes the app look correct on tiny Android devices.
- fixed: Improve the header appearance, especially on small Android's.
none
---
- https://app.asana.com/0/0/1204480611754483

Clean up scene header components

---

src/components/modals/FioCreateHandleModal.tsx
src/components/services/Services.tsx
src/util/CleanStore.ts

- Add: Show FIO handle creation modal to existing accounts without any registered FIO names
none
---
- https://app.asana.com/0/0/1204252350267523

Show FIO popup to existing users who don't have FIO handles

---

src/__tests__/scenes/__snapshots__/RequestScene.test.tsx.snap
src/components/scenes/Fio/FioRequestConfirmationScene.tsx
src/components/scenes/RequestScene.tsx
src/components/themed/ExchangedFlipInput2.tsx
src/types/routerTypes.tsx

- Integrate ExchangedFlipInput2 into RequestScene
- Improve FIO Request button handling
- Improve the receive wallet button to persist fiat amount into the next asset
- changed: Improve FIO Request button handling
none
---
- https://app.asana.com/0/0/1203214384662227

Integrate ExchangedFlipInput2 into RequestScene

---

src/plugins/gui/providers/simplexProvider.ts

---
- https://app.asana.com/0/0/1204507651432685

Add Simplex assets ALGO, OP-ETH, and OP

---

scripts/secretFiles.ts

none
This PR needs a corresponding change to the build servers SECRET_FILES env var to point to a git repo
---
- https://app.asana.com/0/0/1204525114482693

Pull secret files from git

---

src/components/modals/WcSmartContractModal.tsx

none
none
---
- https://app.asana.com/0/0/1204535491670269

Fix bug in WalletConnect asEvmWcRpcPayload cleaner

---

src/components/scenes/Fio/FioRequestListScene.tsx

---
- https://app.asana.com/0/0/1204555778634128

Fix date display in FIO request list scene section headers

---

src/components/scenes/Staking/StakeOptionsScene.tsx
src/components/themed/TransactionListTop.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/stake-plugins/currency/tronStakePlugin.ts
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
src/plugins/stake-plugins/types.ts
src/plugins/stake-plugins/uniswapV2/uniV2Plugin.ts
src/util/stakeUtils.ts

---
- https://app.asana.com/0/0/1204436465323062

Add Tron Stake v2

---

src/components/scenes/GettingStartedScene.tsx

Add navigation to login or signup flow after swiping past the final USP
none
---
- https://app.asana.com/0/0/1204190904815166

Add functionality to navigate after swiping past the USPs

---

src/components/scenes/Fio/FioCreateHandleScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
none
---
- https://app.asana.com/0/0/1204337685097349

Add FIO Handle Creation Success Toast

---

src/components/scenes/CreateWalletImportOptionsScene.tsx
src/constants/WalletAndCurrencyConstants.ts

---
- https://app.asana.com/0/0/1204570888950378

Make import key option validation a function

---

src/components/scenes/Fio/FioStakingChangeScene.tsx

none
none
---
- https://app.asana.com/0/0/1204496974154673

Only send decimal amounts to flipinput

---

src/components/tiles/AddressTile2.tsx

- Use native Segwit address (if available) when self-transferring 
none
| Native Segwit Wallet                                                                                                                      	| Non-segwit (wrapped Segwit) Wallet                                                                                                   	|
|-------------------------------------------------------------------------------------------------------------------------------------------	|--------------------------------------------------------------------------------------------------------------------------------------	|
| <video loop controls width="300px" src="https://github.com/EdgeApp/edge-react-gui/assets/4023066 …

Use native Segwit address when self-transferring

---

src/__tests__/scenes/__snapshots__/RequestScene.test.tsx.snap
src/components/scenes/RequestScene.tsx
src/components/themed/ShareButtons.tsx

- Fix duplicated share modals popping up when rapidly tapping Share button (Android only).
none
---
- https://app.asana.com/0/0/1204353783542603

Fix duplicated Share modal popup glitch on Android

---

src/components/modals/WcSmartContractModal.tsx

---
- https://app.asana.com/0/0/1204615731108224

Fix personal_sign wallet connect method

---

src/envConfig.ts
src/plugins/gui/RewardsCardPlugin.tsx
src/plugins/gui/providers/ioniaProvider.ts

none
none
---
- https://app.asana.com/0/0/1204616458395372

Upgrade Ionia to staging account

---

src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/components/cards/VisaCardCard.tsx
src/components/scenes/GuiPluginListScene.tsx
src/components/themed/ControlPanel.tsx
src/components/themed/TransactionListTop.tsx
src/constants/WalletAndCurrencyConstants.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/types/routerTypes.tsx
src/util/tracking.ts

none
none
---
- https://app.asana.com/0/0/1204632857989440

Add links to Visa Card Program back into the Control Panel and Tx List

---

src/plugins/gui/RewardsCardPlugin.tsx
src/plugins/gui/providers/ioniaProvider.ts

none
none
---
- https://app.asana.com/0/0/1204638799117435

Round fiat amount before send

---

src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/gui/providers/ioniaProvider.ts

none
none
---
- https://app.asana.com/0/0/1204631757796383

Update min/max error messaging for RewardsCardPlugin

---

src/plugins/gui/scenes/FiatPluginEnterAmountScene.tsx

none
none
---
- https://app.asana.com/0/0/1204640258552610

Lock Next button while amounts are spinning
