docs/MAESTRO.md
maestro.sh

none
---
- https://app.asana.com/0/0/1204357017841273

Maestro bootstrap shell script & `docs/MAESTRO.md`

---

docs/MAESTRO.md

Fix README `maestro.sh` URL path causing 404 error

---

src/plugins/gui/RewardsCardPlugin.tsx

Fixes missing logos on txlist
none
none
---
- https://app.asana.com/0/0/1204640924918910

Change Visa purchase metadata to match Contacts List

---

src/constants/WalletAndCurrencyConstants.ts
src/plugins/gui/RewardsCardPlugin.tsx
src/plugins/gui/scenes/RewardsCardDashboardScene.tsx

Disable Dash due to network stall
Remove safe area offset on dashboard
none
none
---
- https://app.asana.com/0/0/1204654031017140

More visa fixes

---

src/components/scenes/LoginScene.tsx

none
none
---
- https://app.asana.com/0/0/1204637819439235

Supress push server errors on login

---

src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/components/themed/ControlPanel.tsx
src/components/themed/TransactionListTop.tsx
src/constants/plugins/GuiPlugins.ts

- Changed: Moved Visa® Card Program out of beta
none
---
- https://app.asana.com/0/0/1204651918588693

Enable Visa Card Program for production track (remove beta flag)

---

src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/gui/RewardsCardPlugin.tsx
src/plugins/gui/scenes/RewardsCardDashboardScene.tsx

Fixed: Issues with new card purchase loading handling for Visa® Card Program
none
---
- https://app.asana.com/0/0/1204661457435362

Redesigned Visa Card Program loading handling and messaging

---

src/components/Main.tsx
src/envConfig.ts

none
none
---
- https://app.asana.com/0/0/1204673583120191

Add USE_WELCOME_SCREENS to env.json

---

src/plugins/gui/RewardsCardPlugin.tsx

none
none
---
- https://app.asana.com/0/0/1204680514663055

Update Visa Card Program support URL

---

src/components/themed/ControlPanel.tsx

- Changed: Changed Visa Card Program icon for the side menu
none
---
- https://app.asana.com/0/0/1204661457435393

Changed Visa Card Program menu icon

---

src/plugins/gui/providers/ioniaProvider.ts

none
none
---
- https://app.asana.com/0/0/1204678710095775

Fix incorrect pluginId for DOGE

---

src/components/scenes/LoginScene.tsx
src/util/tracking.ts

none
none
---
- https://app.asana.com/0/0/1204654142906170

Track errors in onLogin to Bugsnag

---

src/components/scenes/CoinRankingScene.tsx

none
none
---
- https://app.asana.com/0/0/1204583159737521

Properly refresh markets view on fiat code change

---

src/actions/LogActions.tsx
src/actions/WalletActions.tsx
src/actions/WalletListMenuActions.tsx
src/components/scenes/Staking/StakeModifyScene.tsx
src/components/scenes/Staking/StakeOverviewScene.tsx
src/components/themed/TransactionListTop.tsx
src/components/themed/WalletListCreateRow.tsx
src/modules/FioAddress/util.ts
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
src/plugins/stake-plugins/types.ts
src/plugins/stake-plugins/uniswapV2/policies/cemeteryPolicy.ts
src/plugins/stake-plugins/uniswapV2/policies/masonryPolicy.ts
src/plugins/stake-plugins/util/getSeed.ts

- changed: Replace deprecated core methods with updated ones.
none
---
- https://app.asana.com/0/0/1204653190095873

No deprecations

---

.fastlane/Matchfile
scripts/deploy.ts

none
none
---
- https://app.asana.com/0/0/1204732629745391

Add fastlane to deploy.ts for provisioning profiles

---

src/actions/CryptoExchangeActions.tsx

none
none
---
- https://app.asana.com/0/0/1204541171459583

Fix undefined value after wallet creation

---

src/plugins/gui/RewardsCardPlugin.tsx

none
none
---
- https://app.asana.com/0/0/1204692480542421

Fix Visa Card Welcome Scene Condition

---

src/actions/WalletListMenuActions.tsx

none
none
---
- https://app.asana.com/0/0/1204767755019955

Fix viewing raw private keys

---

src/util/logger.ts

- Fixed: Fix logging of Error objects in production
none
---
- https://app.asana.com/0/0/1204773377845725

Fix logging of Error objects in production

---

src/__tests__/scenes/__snapshots__/CurrencyNotificationScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CurrencySettings.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap
src/components/scenes/SwapSettingsScene.tsx
src/components/themed/SettingsRow.tsx

- Fixed: Fix race condition for exchange settings switch
none
---
- https://app.asana.com/0/0/1204696624144919

Fix race condition for exchange settings switch

---

src/plugins/gui/RewardsCardPlugin.tsx
src/plugins/gui/providers/ioniaProvider.ts
src/plugins/gui/scenes/RewardsCardDashboardScene.tsx

none
none
---
- https://app.asana.com/0/0/1204787084987270

Support new Ionia API fields as optional (Currency and ActualAmount)

---

src/constants/plugins/GuiPlugins.ts

Enable using ERC20, Polygon, and Tron stablecoins with Bitrefill
none
---
- https://app.asana.com/0/0/1204800102940845

Enable Bitrefill with stablecoins

---

src/plugins/gui/RewardsCardPlugin.tsx
src/plugins/gui/amountQuotePlugin.ts
src/plugins/gui/fiatPluginTypes.ts
src/plugins/gui/hooks/useStateManager.ts
src/plugins/gui/scenes/FiatPluginEnterAmountScene.tsx

- Changed: Cleanup FiatPlugin refactor
none
---
- https://app.asana.com/0/0/1204616458395337

Cleanup FiatPlugin refactor

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1204810700582277

v3.11.0 Changelog

---

src/actions/PaymentProtoActions.tsx
src/plugins/gui/RewardsCardPlugin.tsx
src/plugins/gui/fiatPlugin.tsx
src/plugins/gui/fiatPluginTypes.ts
src/plugins/gui/providers/ioniaProvider.ts

- Changed: Improved performance of purchase of Visa® Card by being hasty and using debouncing techniques
none
---
- https://app.asana.com/0/0/1204616457260607

Performance improvements for card program

---

src/plugins/gui/RewardsCardPlugin.tsx

- Fixed: Improvements to error handling for in Visa® Card Program
none
---
- https://app.asana.com/0/0/1204780297657593

Fix error handling for getQuote in RewardsCardPlugin

---

src/components/modals/ScanModal.tsx
src/components/scenes/WcConnectionsScene.tsx

- Fixed: Removed logging of QRs scanned from album or from new WalletConnect connections 
none
---
- https://app.asana.com/0/0/1204750941761897
- https://app.asana.com/0/0/1204829809536934

Don't log QR scan values

---

src/components/scenes/GuiPluginListScene.tsx

none
none
---
- https://app.asana.com/0/0/1204836801484075
- https://app.asana.com/0/0/1204845932425745

Prevent crash if guiplugin doesn't exist

---

src/components/scenes/WcConnectScene.tsx
src/components/scenes/WcConnectionsScene.tsx
src/components/services/WalletConnectService.tsx
src/hooks/useWalletConnect.tsx

Some fixes for:
Inaccurate walletId identification from session
Error handling
Dapp spec non-compliance safety
---
- https://app.asana.com/0/0/1204868235343560

WalletConnectV2 cleanups

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1204876931255805

v3.12.0 Changelog

---

package.json
src/actions/SpendingLimitsActions.ts
src/components/modals/RadioListModal.tsx
src/components/scenes/CryptoExchangeScene.tsx
src/components/scenes/RequestScene.tsx
src/components/services/EdgeCoreManager.tsx
src/components/services/WalletConnectService.tsx
src/components/themed/MaybeCustomServersSetting.tsx
src/components/themed/TransactionListTop.tsx
src/modules/FioAddress/components/DomainListModal.tsx
src/plugins/gui/RewardsCardPlugin.tsx
yarn.lock

none
none
---
- https://app.asana.com/0/0/1204868426100921

Upgrade to ESLint 8

---

maestro/10-assets/C400-utxo-01.yaml

none
none
---
- https://app.asana.com/0/0/1204868932565786

Add wait to utxo test

---

src/hooks/useTransactionList.ts

none
none
---
- https://app.asana.com/0/0/1204884077340437

Fix transaction list resync issue

---

maestro/common/clear-app-data.yaml
maestro/common/close-modal-hack.yaml
maestro/common/launch-cleared.yaml
maestro/common/launch.yaml
maestro/common/login-password.yaml

none
none
---
- https://app.asana.com/0/0/1204894185178374

Use variable app_id in maestro

---

src/__tests__/actions/AccountReferralActions.test.ts
src/actions/AccountReferralActions.ts
src/types/TweakTypes.ts

Add app version and country exclusion to promo card filters
none
---
- https://app.asana.com/0/0/1204739577599913

Add more promo filters

---

maestro/10-assets/C400-utxo-01.yaml

none
none
---
- https://app.asana.com/0/0/1204896665421583

Remove UFO/VTC tests due to node unreliability

---

maestro/10-assets/C400-utxo-01.yaml
maestro/common/login-password.yaml

Add waits for amount checking
none
none
---
- https://app.asana.com/0/0/1204912200115497

Fix utxo test timing

---

scripts/runMaestro.ts

none
none
---
- https://app.asana.com/0/0/1204894802695431

Fix maestro exclude/include tags

---

maestro/03-login/C184036-ip2fa-01.yaml
maestro/10-assets/C184035-utxo-01.yaml

none
none
---
- https://app.asana.com/0/0/1204899023593075

Add ip2fa block tests

---

src/actions/AccountReferralActions.ts
src/actions/CreateWalletActions.tsx
src/actions/CryptoExchangeActions.tsx
src/actions/DeepLinkingActions.ts
src/actions/FioActions.tsx
src/actions/LoginActions.tsx
src/actions/RequestReviewActions.tsx
src/actions/ScanActions.tsx
src/actions/TrackingActions.ts
src/actions/WalletListActions.tsx
src/components/cards/PromoCard.tsx
src/components/modals/InsufficientFeesModal.tsx
src/components/scenes/CryptoExchangeScene.tsx
src/components/scenes/PromotionSettingsScene.tsx
src/components/scenes/SwapSettingsScene.tsx
src/components/services/AccountCallbackManager.tsx
src/components/services/AirshipInstance.tsx
src/components/services/DeepLinkingManager.ts
src/components/themed/SideMenu.tsx
src/util/logger.ts
src/util/tracking.ts

none
none
---
- https://app.asana.com/0/0/1204848238190307

Fix first 101 floating-promises

---

src/util/scaling.ts

none
none
---
- https://app.asana.com/0/0/1204849217481125

Log scaling dimensions

---

src/actions/PluginActions.tsx
src/components/Main.tsx
src/plugins/gui/fiatPlugin.tsx
src/util/routerUtils.ts

This PR includes two commits, with two different approaches to fixing this problem, which may be squashed/dropped depending on the outcome of the review.
Fixed: Fix broken deep-linking for some new fiat plugins
none

Fix broken deep-linking for some new fiat plugins

---

src/components/navigation/FlashNotification.tsx

- added: Close button on funds received modal
none
---
- https://app.asana.com/0/0/1204597702128339

Add close button to tx received dropdown

---

src/assets/.eslintrc.json
src/components/buttons/.eslintrc.json
src/components/common/.eslintrc.json
src/components/data/row/.eslintrc.json
src/components/hoc/.eslintrc.json
src/components/icons/.eslintrc.json
src/components/interactions/.eslintrc.json
src/components/layout/.eslintrc.json
src/components/legacy/.eslintrc.json
src/components/progress-indicators/.eslintrc.json
src/components/text/.eslintrc.json
src/constants/.eslintrc.json
src/locales/.eslintrc.json
src/reducers/.eslintrc.json
src/selectors/.eslintrc.json
src/styles/common/.eslintrc.json
src/theme/.eslintrc.json
src/types/.eslintrc.json

none
none
---
- https://app.asana.com/0/0/1204903079993961

Harden no-floating-promises rule within each directory

---

src/modules/FioAddress/util.ts

none
none
---
- https://app.asana.com/0/0/1204536097865439

Optimize fio

---

src/locales/intl.ts

Prevents crash in biggystring
none
none
---
- https://app.asana.com/0/0/1204827446797537

Check for non-decimal strings in toPercentString

---

src/components/services/Services.tsx
src/util/scaling.ts

none
none
---
- https://app.asana.com/0/0/1204966023534310

Log dimensions from Services.tsx

---

src/actions/NotificationActions.ts
src/controllers/action-queue/types/pushApiTypes.ts

Fixed: Improve error handling for push server responses
none
---
- https://app.asana.com/0/0/1204746746640718

Improve error handling for push server responses

---

deployPatches/edge/beta/buildGradle.patch
deployPatches/edge/beta/edgeXcsheme.patch
deployPatches/edge/beta/projectPbxproj.patch
deployPatches/edge/develop/buildGradle.patch
deployPatches/edge/develop/projectPbxproj.patch
ios/edge.xcodeproj/project.pbxproj
ios/edge.xcodeproj/xcshareddata/xcschemes/edge.xcscheme

Fix deploy patches

---

deployPatches/edge/beta/projectPbxproj.patch
deployPatches/edge/develop/projectPbxproj.patch
ios/edge.xcodeproj/project.pbxproj

Prevent the Swift header name from changing

---

src/components/scenes/CreateWalletImportOptionsScene.tsx
src/constants/WalletAndCurrencyConstants.ts
src/locales/en_US.ts
src/locales/strings/enUS.json

---
- https://app.asana.com/0/0/1204578209489966

Add input option description and knowledge base modal launcher

---

src/components/navigation/CurrencySettingsTitle.tsx

none
none
---
- https://app.asana.com/0/0/1204980607217827

Fix crypto settings header

---

src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap
src/components/scenes/CreateWalletAccountSetupScene.tsx

- Fixed: Fix background for legacy themed CreateWalletAccountSetupScene
none
---
- https://app.asana.com/0/0/1204846698579618

Fix background for legacy themed CreateWalletAccountSetupScene

---

src/plugins/gui/RewardsCardPlugin.tsx
src/plugins/gui/fiatPlugin.tsx
src/plugins/gui/fiatPluginTypes.ts
src/plugins/gui/scenes/RewardsCardDashboardScene.tsx

none
none
---
- https://app.asana.com/0/0/1204983967362040

Enable long tap to copy visa card url

---

src/components/icons/CryptoIcon.tsx

This fixes a visual issue in flashlists
---
- https://app.asana.com/0/0/1204622252075359

Add key to wallet sync circle in the cryptoIcon component

---

maestro/10-assets/C184035-utxo-01.yaml

none
none
---
- https://app.asana.com/0/0/1205004411207746

Disable BSV from UTXO test

---

src/components/scenes/SwapSettingsScene.tsx

none
none
---
- https://app.asana.com/0/0/1204949188125165

Fix the preferred swap modal

---

src/components/scenes/MigrateWalletCompletionScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

---
- https://app.asana.com/0/0/1204779772531294

Add metadata to migrate wallet transactions

---

src/components/common/QrPeephole.tsx

This fixes a regression caused by upgrading libraries.
none
none
---
- https://app.asana.com/0/0/1204990908487398

Make fill transparent for each corner of the QrPeephole

---

src/components/scenes/CreateWalletCompletionScene.tsx
src/components/scenes/MigrateWalletCompletionScene.tsx

---
- https://app.asana.com/0/0/1204541795276723

Allow user to scroll when all wallets are created

---

src/components/scenes/WcConnectScene.tsx

---
- https://app.asana.com/0/0/1205068047605422

Don't wait for flash notification to resolve before navigating

---

src/components/modals/AddressModal.tsx

none
none
---
- https://app.asana.com/0/0/1205002161278611

Update component state before awaiting async address checks

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1205078293555954

v3.13.0 Changelog

---

src/components/modals/WalletListMenuModal.tsx

none
none
---
- https://app.asana.com/0/0/1204938757648101

Center close button for WalletListMenuModal

---

deployPatches/edge/beta/projectPbxproj.patch
deployPatches/edge/develop/projectPbxproj.patch

Re-create patch files due to conflicts
none
none
---
- https://app.asana.com/0/0/1205079057049423

Fix develop/beta builds

---

src/components/themed/WalletListCreateRow.tsx

---
- https://app.asana.com/0/0/1204917828008847

Don't rely on currency code when adding token from create wallet row

---

src/__tests__/modals/__snapshots__/PasswordReminderModal.test.tsx.snap
src/components/modals/PasswordReminderModal.tsx

none
none
---
- https://app.asana.com/0/0/1205096296562430

Remove auto-focus from the password reminder modal

---

ios/Podfile.lock
package.json
src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/actions/DeepLinkingActions.ts
src/actions/LoginActions.tsx
src/components/Main.tsx
src/components/hoc/IfLoggedIn.tsx
src/components/scenes/LoginScene.tsx
src/components/services/AutoLogout.ts
src/components/services/PasswordReminderService.ts
src/components/themed/SideMenu.tsx
src/reducers/RootReducer.ts
src/reducers/scenes/SettingsReducer.ts
src/types/reduxActions.ts
src/util/fake/fakeRootState.ts
src/util/middleware/loginStatusChecker.ts
yarn.lock

- changed: Select users by loginId instead of username from the side menu.
https://github.com/EdgeApp/edge-login-ui-rn/pull/102
---
- https://app.asana.com/0/0/1205101277177518

Upgrade login UI

---

maestro/99-misc/C999001-receive.yaml

none
none
---
- https://app.asana.com/0/0/1205115603319884

Fix address swipe on some phones

---

src/components/scenes/GettingStartedScene.tsx

Create a light or full account based on if there are existing saved accounts
none
none
---
- https://app.asana.com/0/0/1205115382145980

Conditionalize "Create an Account" button behavior

---

src/components/Main.tsx

none
none
---
- https://app.asana.com/0/0/1205114773222807

Remove jarring animation for initial route navigation

---

src/components/Main.tsx

none
none
---
- https://app.asana.com/0/0/1205126541184958

Fix logout back gesture regression

---

src/actions/LoginActions.tsx

Re-enable free FIO handle modal for light accounts
none
none
---
- https://app.asana.com/0/0/1205126829052311

Re-enable free FIO handle modal for light accounts

---

src/components/scenes/SettingsScene.tsx

none
none
---
- https://app.asana.com/0/0/1205100255666907

Remove PIN and biometric settings for light accounts

---

src/components/scenes/Fio/FioAddressSettingsScene.tsx
src/components/scenes/Fio/FioDomainSettingsScene.tsx
src/components/scenes/Fio/FioNameConfirmScene.tsx
src/modules/FioAddress/components/FioActionSubmit.tsx

- fixed: Fio handle registration cancel button broken
none
---
- https://app.asana.com/0/0/1204894267771317

Populate cancelOperation prop

---

patches/@react-native-firebase+analytics+14.9.1.patch

Forcibly exclude play-services-ads-identifier

---

src/locales/strings.ts

Adds logic to handle special case Mexico Spanish file from Crowdin
---
- https://app.asana.com/0/0/1204876931255790

Add Spanish (Mexico)

---

src/components/modals/WalletListModal.tsx
src/components/scenes/MigrateWalletSelectCryptoScene.tsx
src/components/scenes/RequestScene.tsx
src/constants/WalletAndCurrencyConstants.ts
src/util/CurrencyInfoHelpers.ts

- removed: Do not support new EOS wallets
none
---
- https://app.asana.com/0/0/1205128556455686

Keys-only EOS

---

src/components/scenes/GettingStartedScene.tsx
src/util/tracking.ts

- added: Tracking event for "Already have an account? Sign-in" tapc
none
---
- https://app.asana.com/0/0/1205228352682139
- https://app.asana.com/0/0/1205259687790586

Add Welcome_Signin event

---

src/actions/LoginActions.tsx
src/components/scenes/CreateWalletSelectCryptoScene.tsx
src/util/tracking.ts

- added: Signup analytics events
- fixed: Improved error reporting for wallet creation failures
none
---
- https://app.asana.com/0/0/1205214041882459

Tracking: Add more signup granularity

---

src/plugins/gui/providers/moonpayProvider.ts

---
- https://app.asana.com/0/0/1205258886998706

Update Moonpay logo filename

---

src/components/scenes/LoginScene.tsx

none
none
---
- https://app.asana.com/0/0/1205273153982946

Disable legacy landing for maestro

---

src/components/Main.tsx
src/components/scenes/LoginScene.tsx

none
none
---
- https://app.asana.com/0/0/1205273153982946

Fully disable legacyLanding test for Maestro

---

src/constants/WalletAndCurrencyConstants.ts

- changed: Removed transaction list support for ETC
none
---
- https://app.asana.com/0/0/1205329868913335

Change Ethereum Classic transaction list support

---

src/components/services/ContactsLoader.ts

---
- https://app.asana.com/0/0/1205330401525182

Add XRP DEX contact info

---

src/components/tiles/SwapDetailsTiles.tsx

added: date to exchange details
none
---
- https://app.asana.com/0/0/1205185754010327

Show date/time in exchange details

---

src/components/scenes/EditTokenScene.tsx
src/components/scenes/ManageTokensScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

Matching contract address, different token name
Matching built-in token code, different contract address:
Old vs new ManageTokensScene:
- added: Warning message when adding a custom token that conflicts with a built-in token
- fixed: Component styling in token management scenes
none
---
- https://app.asana.com/0/0/1205214596907253

Custom Token Conflict Warning

---

src/constants/WalletAndCurrencyConstants.ts
src/locales/en_US.ts
src/util/corePlugins.ts

- added: Filecoin currency support
none
---
- https://app.asana.com/0/0/1205369367397591

Add enable filecoin plugin

---

src/components/themed/MenuTabs.tsx

none
none
---
- https://app.asana.com/0/0/1205380092832467

Fix menu tab crashes

---

src/constants/WalletAndCurrencyConstants.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/corePlugins.ts

---
- https://app.asana.com/0/0/1205347750618515

Add Liberland

---

src/plugins/gui/providers/simplexProvider.ts

added: Buy PEPE on Simplex
none
---
- https://app.asana.com/0/0/1204965836813924

Enable PEPE for Simplex

---

src/components/themed/MenuTabs.tsx

Properly map the activeTabIndex
none
none
---
- https://app.asana.com/0/0/1205376715599452

Fix crash from missing tab index

---

src/components/themed/CreateWalletSelectCryptoRow.tsx
src/components/themed/WalletListCreateRow.tsx

- added: Network name display on token row UI
none
---
- https://app.asana.com/0/0/1205308893333756

Display network name for token rows

---

src/components/scenes/EditTokenScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

- added: Warning message when entering a custom token with a matching built-in currency code and address
none
---
- https://app.asana.com/0/0/1205367674582029

Handle the case of entering a custom token that exists

---

src/plugins/gui/providers/banxaProvider.ts
src/plugins/gui/providers/simplexProvider.ts

---
- https://app.asana.com/0/0/1205389557237318

Add FIL to Simplex and Banxa fiat plugins

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1205412889550984

3.16.0 changelog

---

src/constants/WalletAndCurrencyConstants.ts
src/locales/en_US.ts
src/locales/strings/enUS.json

---
- https://app.asana.com/0/0/1205386965646594

Fix minimum balance message and disable custom token support for Liberland

---

src/locales/strings/enUS.json

Fix Translation File

---

src/components/navigation/FlashNotification.tsx

none
none
---
- https://app.asana.com/0/0/1205427405273593

Add bottom padding to FlashNotification

---

src/constants/WalletAndCurrencyConstants.ts

none
none
---
- https://app.asana.com/0/0/1205444115216359

Disable max spend for filecoin

---

src/__tests__/modals/__snapshots__/AutoLogoutModal.test.tsx.snap
src/components/modals/AutoLogoutModal.tsx

none
none
---
- https://app.asana.com/0/0/1205491838793840

Remove extra cancel button from the auto-logout modal

---

src/constants/WalletAndCurrencyConstants.ts

---
- https://app.asana.com/0/0/1205419517607636

Enable keysOnlyMode for Piratechain

---

src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/stake-plugins/types.ts
src/plugins/stake-plugins/uniswapV2/policyInfo/optimism.ts
src/plugins/stake-plugins/uniswapV2/stakePolicy.ts
src/util/stakeUtils.ts

---
- https://app.asana.com/0/0/1205479562783366

Show yield type in stake policy title

---

CHANGELOG.md
src/components/scenes/SpendingLimitsScene.tsx

none
none
---
- https://app.asana.com/0/0/1205504688139900

Prevent setting invalid spending limits

---

localization/AppStoreGraphics.json
localization/PlayStoreGraphics.json

Add files for App Store and Playstore graphics

---

CHANGELOG.md

---
- https://app.asana.com/0/0/1205511320045119

3.17 Changelog

---

localization/AppStoreGraphics.json

none
none
---
- https://app.asana.com/0/0/1205521596641295

Create App Store graphic Json file for translations

---

localization/PlayStoreGraphics.json

none
none
---
- https://app.asana.com/0/0/1205521596641321

Create Play Store graphic Json file for translations

---

CHANGELOG.md
android/app/src/main/res/values/colors.xml

- changed: Tweak the boot background color on Android.
none
---
- https://app.asana.com/0/0/1205522315371785

Change Android boot background color

---

CHANGELOG.md
src/components/themed/TransactionListTop.tsx
src/plugins/stake-plugins/types.ts
src/plugins/stake-plugins/uniswapV2/policyInfo/fantom.ts
src/plugins/stake-plugins/uniswapV2/stakePolicy.ts

---
- https://app.asana.com/0/0/1205551005470386

Include staking plugin display name in error message

---

localization/PlayStoreDescription.txt

none
none
---
- https://app.asana.com/0/0/1205549636680303

Update Play Store desctiptions

---

localization/AppStoreDescription.txt

none
none
---
- https://app.asana.com/0/0/1205549636680266

Update App Store Description

---

CHANGELOG.md
src/components/scenes/SendScene2.tsx
src/util/FioAddressUtils.ts

none
---
- https://app.asana.com/0/0/1205407507660110

Fix FIO OBT recording

---

CHANGELOG.md
src/components/services/AutoLogout.ts

- fixed: Error showing in some cases during auto logout
none
---
- https://app.asana.com/0/0/1205446621578582

Hide errors during Auto Logout

---

crowdin.yml

none
none
---
- https://app.asana.com/0/0/1205532906159304

Add app/playstore descriptions to crowdin

---

maestro/03-login/C190284-2fa-01.yaml
maestro/10-assets/C209290-xmr-01.yaml
maestro/11-markets/C202732-markets.yaml
maestro/12-side-menu/C202842-side-menu-no-crash.yaml
maestro/12-side-menu/C202842a-side-menu-no-crash.yaml
maestro/13-settings/C209308-settings-visuals.yaml
maestro/99-misc/C999000-tx-details.yaml
maestro/99-misc/C999003-help-logged-in.yaml
maestro/99-misc/C999003i-help-logged-in.yaml
maestro/99-misc/C999004-no-crash-max-xrp-dex.yaml
scripts/runMaestro.ts

markets
side menu
help
Settings
2FA backup
Exchange max xrp
XMR sync
none
none
---
- https://app.asana.com/0/0/1205502719228756

add maestro tests

---

CHANGELOG.md
src/actions/TokenTermsActions.tsx
src/components/themed/ManageTokensRow.tsx
src/components/themed/WalletListCreateRow.tsx
src/constants/constantSettings.ts
src/locales/en_US.ts
src/locales/strings/enUS.json

- changed: Always show gas warning when enabling tokens
none
---
- https://app.asana.com/0/0/1204878408649473

Always show gas warning when enabling tokens

---

src/util/tracking.ts

- changed: Login-UI Analytics implementation consolidated into GUI
https://github.com/EdgeApp/edge-login-ui-rn/pull/131
---
- https://app.asana.com/0/0/1205535454470917

GUI: Unify Tracking

---

src/constants/WalletAndCurrencyConstants.ts

---
- https://app.asana.com/0/0/1205446621578571

Disable Liberland max send

---

src/experimentConfig.ts

- changed: Increase 'light account' variant probability to 50%
none
---
- https://app.asana.com/0/0/1205321359129572

Increase light account probability to 50%

---

localization/AppStoreDescription.txt
localization/PlayStoreDescription.txt

none
none
---
- https://app.asana.com/0/0/1205587690056945

Update App and Playstore Description file typos

---

src/components/scenes/Staking/StakeModifyScene.tsx
src/components/scenes/Staking/StakeOverviewScene.tsx
src/plugins/stake-plugins/currency/tronStakePlugin.ts
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
src/plugins/stake-plugins/types.ts
src/plugins/stake-plugins/uniswapV2/policies/VelodromeV2StakePolicy.ts
src/plugins/stake-plugins/uniswapV2/policies/cemeteryPolicy.ts
src/plugins/stake-plugins/uniswapV2/policies/masonryPolicy.ts
src/plugins/stake-plugins/uniswapV2/stakePolicy.ts
src/util/stakeUtils.ts

---
- https://app.asana.com/0/0/1205058026708442

Add Claim support to Tron Stake v2

---

src/components/scenes/Staking/StakeOverviewScene.tsx

---
- https://app.asana.com/0/0/1205594230369625

Reverse the default disable option the the stake overview

---

src/plugins/stake-plugins/currency/tronStakePlugin.ts

---
- https://app.asana.com/0/0/1205605214636921

Return a default empty allocation to tron stake plugin

---

CHANGELOG.md
src/envConfig.ts
src/experimentConfig.ts

- added: env.json experiment config override
none
---
- https://app.asana.com/0/0/1205606823900093

ENV Experiment Config Override

---

src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts

---
- https://app.asana.com/0/0/1205593749634794

Restore Doge to TC Savers plugin

---

CHANGELOG.md
src/util/tracking.ts

none
none
---
- https://app.asana.com/0/0/1205627407427059

Fix tracking to send original values to logging servers

---

src/theme/edgeConfig.ts

none
none
---
- https://app.asana.com/0/0/1205663534255993

Change support domain for transition

---

src/components/scenes/Staking/StakeModifyScene.tsx

---
- https://app.asana.com/0/0/1205605357571931

Don't render a earned funds on the modify scene if they are locked

---

CHANGELOG.md
src/experimentConfig.ts

- changed: 'legacyLanding' experiment config set to 0% probability
none
---
- https://app.asana.com/0/0/1205627264409076

Set legacyLanding experiment distribution to 0%

---

src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts

Per request from ninerealms, do not use midgard for thorchain/inbound_addresses endpoint
none
none
---
- https://app.asana.com/0/0/1205663373785875

Use thornode for thorchain/inbound_addresses endpoint

---

src/__tests__/scenes/__snapshots__/CurrencyNotificationScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CurrencySettings.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap
src/components/scenes/GuiPluginListScene.tsx
src/components/settings/SettingsRow.tsx

none
none
---
- https://app.asana.com/0/0/1205574668919815

Fix maestro targettability

---

CHANGELOG.md
ios/Podfile.lock
package.json
yarn.lock

none
none
---
- https://app.asana.com/0/0/1205663510577187

Upgrade react-native-linear-gradient 2.8.3

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

---
- https://app.asana.com/0/0/1205469057051677

Re-enable Piratechain

---

src/constants/plugins/GuiPlugins.ts
src/plugins/gui/providers/banxaProvider.ts

none
none
---
- https://app.asana.com/0/0/1205671006756498

Fix banxa sell to GBP faster payments

---

maestro/12-side-menu/C202842-side-menu-no-crash.yaml

none
none
---
- https://app.asana.com/0/0/1205673496779247

maestro fix side menu ipad

---

maestro/99-misc/C999003-help-logged-in.yaml

none
---
- https://app.asana.com/0/0/1205703636340832

Fix Maestro help test on Android

---

src/components/scenes/LoginScene.tsx
src/experimentConfig.ts

Also update users with existing legacyLanding experiment config vals and force them to use uspLanding
none
---
- https://app.asana.com/0/0/1205719559116023

Fix legacyLanding for login scene back button

---

CHANGELOG.md
src/__tests__/components/__snapshots__/FlipInput.test.tsx.snap
src/components/themed/FlipInput.tsx
src/components/themed/FlipInput2.tsx

none
---
- https://app.asana.com/0/0/1205457893036964

FlipInput "Tap to Edit"

---

CHANGELOG.md
src/components/scenes/SendScene2.tsx

---
- https://app.asana.com/0/0/1205724850151850

Use EdgeMemos on SendScene2

---

maestro/11-markets/C202732-markets.yaml
maestro/12-side-menu/C202842-side-menu-no-crash.yaml
maestro/12-side-menu/C202842a-side-menu-no-crash.yaml
maestro/13-settings/C209308-settings-visuals.yaml
maestro/99-misc/C999004-no-crash-max-xrp-dex.yaml

none
---
- https://app.asana.com/0/0/1205741977627363

Fix maestro tests missing "waits"

---

src/components/scenes/SendScene2.tsx

---
- https://app.asana.com/0/0/1205747413725174

Fix entered memo display

---

package.json
src/components/scenes/TransactionListScene.tsx
yarn.lock

https://github.com/EdgeApp/edge-info-server/pull/104

Support version-specific targeting of AssetStatus messages

---

CHANGELOG.md
src/__tests__/scenes/__snapshots__/FioAddressListScene.test.tsx.snap
src/components/themed/WalletListCurrencyRow.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json
src/theme/variables/edgeDark.ts
src/theme/variables/edgeLight.ts
src/theme/variables/testDark.ts
src/types/Theme.ts

none
---
- https://app.asana.com/0/0/1205654034220682

Overlay styling for "Wallet Paused"

---

CHANGELOG.md
src/experimentConfig.ts

none
---
- https://app.asana.com/0/0/1205751906499633

Add signupCaptcha experiment

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

Enable max spend for filecoin

---

ios/Podfile.lock
package.json
scripts/hack-travis.mjs
src/components/services/EdgeCoreManager.tsx
src/declare-modules.d.ts
src/envConfig.ts
src/util/corePluginBundle.js
yarn.lock

- https://github.com/EdgeApp/edge-exchange-plugins/pull/297
- https://github.com/EdgeApp/edge-currency-accountbased/pull/651
---
- https://app.asana.com/0/0/1205428174790064

Upgrade exchange and currency plugins

---

CHANGELOG.md
src/components/modals/AccelerateTxModal.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1205800570387933

New 'Lower Send Amount' warning for transaction acceleration

---

CHANGELOG.md
src/constants/plugins/buyPluginList.json

none
---
- https://app.asana.com/0/0/1205856947388552

Re-enable faster payments w/banxa

---

CHANGELOG.md
src/actions/RecoveryReminderActions.tsx
src/components/scenes/LoginScene.tsx
src/components/scenes/WalletListScene.tsx

none
---
- https://app.asana.com/0/0/1205534362484139

Don't show recovery, password, or otp reminders in maestro

---

src/actions/CategoriesActions.ts
src/components/scenes/TransactionDetailsScene.tsx

Also prioritize EdgeTxAction-derived direction over the existing direction logic.
https://github.com/EdgeApp/edge-currency-accountbased/pull/657

Infer tx direction from EdgeTxAction

---

src/plugins/gui/providers/paybisProvider.ts

---
- https://app.asana.com/0/0/1205801609454274

Remove hardcoded dummy icon uri

---

jestSetup.js
src/actions/WalletActions.tsx
src/components/modals/WalletListMenuModal.tsx
src/components/scenes/RequestScene.tsx
src/components/services/WalletLifecycle.ts
src/components/themed/WalletListCurrencyRow.tsx
src/constants/WalletAndCurrencyConstants.ts

---
- https://app.asana.com/0/0/1205790736004846

Pause keysOnlyMode wallets

---

src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1205888764853614

Parse the OS version number more safely

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1205835807832262

Disable max-spend for Filecoin wallets

---

src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json

none
---
- https://app.asana.com/0/0/1205846869179404

Update text description for paybis payment methods

---

src/constants/plugins/GuiPlugins.ts
src/constants/plugins/sellPluginList.json
src/plugins/gui/fiatPluginTypes.ts
src/plugins/gui/providers/paybisProvider.ts

They changed them on us :(
none
---
- https://app.asana.com/0/0/1205803571727304

Update paybis paymentmethod ids

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/corePlugins.ts

---
- https://app.asana.com/0/0/1205890056259006

Add Thorchain (RUNE)

---

src/plugins/gui/providers/banxaProvider.ts

Fixes poor error message from min limit quote requests that succeed but fail on execution
none
---
- https://app.asana.com/0/0/1205910728832670

Show banxa errors.title value if order creation fails

---

maestro/02-launch-login/C310-launch-no-crash.yaml
maestro/02-launch-login/C311-relaunch-no-crash.yaml
maestro/11-markets/C202732-markets.yaml
maestro/12-side-menu/C202842-side-menu-no-crash.yaml
maestro/12-side-menu/C202842a-side-menu-no-crash.yaml
maestro/99-misc/C999003-help-logged-in.yaml
maestro/99-misc/C999003i-help-logged-in.yaml

none
---
- https://app.asana.com/0/0/1205930213604957

Fix test id mismatch with filename

---

src/components/modals/WebViewModal.tsx
src/components/scenes/ExtraTabScene.tsx
src/components/themed/EdgeProviderComponent.tsx
src/plugins/gui/scenes/FiatPluginWebView.tsx

Fixes any KYC widget that uses inline video capture
none
---
- https://app.asana.com/0/0/1205943571388326

Add allowsInlineMediaPlayback to WebViews

---

CHANGELOG.md
src/components/themed/WiredProgressBar.tsx

none
---
- https://app.asana.com/0/0/1205935097933131

Do not count paused wallets for progress ratio

---

src/util/corePlugins.ts

---
- https://app.asana.com/0/0/1205935849121921

Pass api keys to thorchainrune plugin

---

CHANGELOG.md
src/experimentConfig.ts

none
---
- https://app.asana.com/0/0/1205972524750445

Disabled signupCaptcha experiment

---

CHANGELOG.md
src/experimentConfig.ts

Re-enabling after more safety features are implemented to prevent loss of funds
none
---
- https://app.asana.com/0/0/1206012190138383

Temporarily disable light account

---

CHANGELOG.md
src/components/modals/WalletListModal.tsx

none
---
- https://app.asana.com/0/0/1205981561051523

Properly return tokenId from WalleListModal

---

CHANGELOG.md
src/plugins/stake-plugins/uniswapV2/policyInfo/fantom.ts

none
---
- https://app.asana.com/0/0/1205997135183169

Add use of Pokt RPCs for Fantom

---

CHANGELOG.md
src/experimentConfig.ts

none
---
- https://app.asana.com/0/0/1205972524750443

Update USP/Legacy Landing probability to 50/50

---

CHANGELOG.md
src/plugins/stake-plugins/currency/tronStakePlugin.ts

none
---
- https://app.asana.com/0/0/1206059826168496

Look specifically for withdrawable amounts

---

CHANGELOG.md
src/envConfig.ts
src/util/corePlugins.ts

none
---
- https://app.asana.com/0/0/1206053195040063

Add Solana apikeys

---

src/components/charts/SwipeChart.tsx
src/envConfig.ts

none
---
- https://app.asana.com/0/0/1206062091848322

Fix markets view rate limiting

---

src/envConfig.ts
src/util/corePlugins.ts

none
---
- https://app.asana.com/0/0/1206061682946551

Add GOERLI_INIT

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts

none
---
- https://app.asana.com/0/0/1205615584415946

Enable bsc staking on thorchain

---

CHANGELOG.md
src/components/scenes/WcConnectScene.tsx
src/components/scenes/WcConnectionsScene.tsx
src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1205801609455304

Add create wallet support to wallet connect wallet select modal

---

CHANGELOG.md
src/components/scenes/GuiPluginListScene.tsx
src/plugins/gui/amountQuotePlugin.ts
src/plugins/gui/fiatPlugin.tsx
src/plugins/gui/fiatPluginTypes.ts

This is a hidden troubleshooting feature and hence strings are not translated
none
---
- https://app.asana.com/0/0/1205982380152723

Allow clearing of fiat provider data store

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/corePlugins.ts

---
- https://app.asana.com/0/0/1205984485249138

Add Coreum and Osmosis

---

src/components/themed/CryptoExchangeFlipInputWrapperComponent.tsx

This prop was missing in the change to use FlipInput2 for the exchange scene
none
---
- https://app.asana.com/0/0/1206104132422756

Add tokenId prop to ExchangedFlipInput2

---

package.json
src/plugins/stake-plugins/generic/policyAdapters/GlifInfinityPoolAdapter.ts
yarn.lock

none
---
- https://app.asana.com/0/0/1206080142508697

Fail gracefully on balance queries reverted for no reason

---

CHANGELOG.md
src/components/scenes/Staking/StakeOverviewScene.tsx

---
- https://app.asana.com/0/0/1206098511911901

Give staking allocations unique keys

---

package.json
src/__tests__/scenes/__snapshots__/FioAddressListScene.test.tsx.snap
src/components/cards/AssetStatusCard.tsx
src/components/ui4/ButtonUi4.tsx
src/components/ui4/CardUi4.tsx
src/components/ui4/PromoCardUi4.tsx
src/locales/intl.ts
src/theme/variables/edgeDark.ts
src/theme/variables/edgeLight.ts
src/theme/variables/testDark.ts
src/types/Theme.ts
yarn.lock

none
---
- https://app.asana.com/0/0/1205826921045601

UI4: Promo Cards

---

CHANGELOG.md
src/components/scenes/GettingStartedScene.tsx
src/experimentConfig.ts

Results have been determined. Choosing "Get Started"
https://github.com/EdgeApp/edge-login-ui-rn/pull/145
---
- https://app.asana.com/0/0/1206097186771211

Remove createAccountText experiment config

---

src/plugins/stake-plugins/generic/policyAdapters/GlifInfinityPoolAdapter.ts

none
---
- https://app.asana.com/0/0/1206100466791698

Fix unstake gas limit to be above minimum for Filecoin FEVM currency

---

CHANGELOG.md
src/components/themed/FilledTextInput.tsx

* https://github.com/EdgeApp/edge-react-gui/pull/4604
---
- https://app.asana.com/0/0/1205826921045603

Add FilledTextInput

---

CHANGELOG.md
src/components/cards/StakingOptionCard.tsx

---
- https://app.asana.com/0/0/1206124977258100

Remove minWidth from stake option card

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1206100466791675

Enable transaction support for zkSync

---

src/plugins/stake-plugins/generic/GenericStakePlugin.ts
src/plugins/stake-plugins/generic/pluginInfo/filecoinCalibrationGlifpool.ts
src/plugins/stake-plugins/generic/pluginInfo/filecoinGlifpool.ts
src/plugins/stake-plugins/generic/types.ts

none
---
- https://app.asana.com/0/0/1206107188258394

Add disableMaxStake option to generic stake plugins

---

CHANGELOG.md
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/components/notification/NotificationCard.tsx
src/components/notification/NotificationView.tsx
src/components/scenes/ManageTokensScene.tsx

- Token management scene now always sorts enabled tokens on top
- Color styling and icon choice now determined by NotificationCard by default. 
none
---
- https://app.asana.com/0/0/1206097714609111

Auto token detection updates

---

CHANGELOG.md
src/components/Main.tsx
src/util/tracking.ts

Counts the number of accounts saved on the device
none
---
- https://app.asana.com/0/0/1206136413835689

Implement numAccounts tracking param

---

src/plugins/stake-plugins/generic/policyAdapters/GlifInfinityPoolAdapter.ts

none
---
- https://app.asana.com/0/0/1206163748970883

Fix unstake gas limit for Filecoin FEVM currency

---

CHANGELOG.md
src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/components/tiles/AddressTile2.tsx

none
---
- https://app.asana.com/0/0/1205724543635215

Fix clipboard usage in AddressTile2

---

src/plugins/stake-plugins/generic/policyAdapters/GlifInfinityPoolAdapter.ts

none
---
- https://app.asana.com/0/0/1206176677997908

Fix unstake gas limit for GLIF pool adapter

---

src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1206188729467958

Make transaction list unsupported for FEVM currencies

---

CHANGELOG.md
src/plugins/gui/providers/paybisProvider.ts

none
---
- https://app.asana.com/0/0/1206123485759230

Enable ETH support on Paybis

---

CHANGELOG.md
src/components/ui4/AdvancedDetailsCard.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1206200463734148

Add minerTip to feeRateUsed processing

---

src/components/themed/WalletListCurrencyRow.tsx
src/components/themed/WalletListSwipeableCurrencyRow.tsx
src/components/ui4/CurrencyViewUi4.tsx

none
---
- https://app.asana.com/0/0/1206232163924196

Always show the ticker in CurrencyViewUi4

---

src/__tests__/components/__snapshots__/ExchangeQuoteComponent.test.tsx.snap
src/__tests__/scenes/__snapshots__/CryptoExchangeQuoteScene.test.tsx.snap
src/components/data/row/CurrencyRow.tsx
src/components/text/CryptoText.tsx
src/components/text/FiatText.tsx
src/components/ui4/BalanceCardUi4.tsx
src/components/ui4/CurrencyViewUi4.tsx
src/hooks/useCryptoText.ts
src/hooks/useFiatText.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/cryptoTextUtils.ts

none
---
- https://app.asana.com/0/0/1206250127173797

UI4: Unify Hidden Balance Display

---

android/app/src/main/java/co/edgesecure/app/MainActivity.java
android/app/src/main/java/co/edgesecure/app/MainApplication.java
android/build.gradle
android/settings.gradle
ios/Podfile
ios/Podfile.lock
ios/edge.xcodeproj/project.pbxproj
ios/edge/AppDelegate.h
ios/edge/AppDelegate.mm
jestSetup.js
package.json
src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/components/scenes/TransactionListScene.tsx
src/components/themed/TransactionListTop.tsx
src/components/themed/WalletListCurrencyRow.tsx
src/components/ui4/CryptoIconUi4.tsx
src/components/ui4/CurrencyViewUi4.tsx
yarn.lock

none
---
- https://app.asana.com/0/0/1206061725717169

Currency Icon Color Gradients

---

deployPatches/edge/beta/projectPbxproj.patch
deployPatches/edge/develop/projectPbxproj.patch

none
---
- https://app.asana.com/0/0/1206259794861490

Update project.pbxproj patch files

---

src/components/Main.tsx
src/components/ui4/scenes/HomeSceneUi4.tsx

This will give the scene the same header as other first screens in a
tab.
none
---
- https://app.asana.com/0/0/1206252243597672
- https://app.asana.com/0/0/1206251043571550
- https://app.asana.com/0/0/1206251043571552

Fix Asset scene display and routine issues

---

CHANGELOG.md
src/__tests__/components/TransactionListTop.test.tsx
src/components/modals/BackupForTransferModal.tsx
src/components/modals/TransferModal.tsx
src/components/scenes/TransactionListScene.tsx
src/components/scenes/WcConnectionsScene.tsx
src/components/themed/TransactionListTop.tsx
src/components/themed/WalletListSwipeableCurrencyRow.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1205999316796691

Light Account: Block Buy/Sell/Receive

---

src/components/themed/MenuTabs.tsx

none
---
- https://app.asana.com/0/0/1206237514290758

UI4: Update home tab icon

---

src/components/scenes/TransactionListScene.tsx
src/components/themed/TransactionListComponents.tsx
src/theme/variables/edgeDark.ts

none
---
- https://app.asana.com/0/0/1206231893065800

Remove sticky headers in TransactionListScene

---

src/actions/BackupModalActions.tsx
src/components/modals/TransferModal.tsx
src/components/scenes/WcConnectionsScene.tsx
src/components/themed/MenuTabs.tsx

none
---
- https://app.asana.com/0/0/1206262048565622

Disable buy/sell tab buttons for Light Account

---

src/components/themed/SideMenu.tsx

none
---
- https://app.asana.com/0/0/1206284636076443

Fix sidemenu inverted spinner logic

---

src/components/ui4/CryptoIconUi4.tsx

none
---
- https://app.asana.com/0/0/1206268191258619

Use vibrant color for wallets on Android

---

src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/components/scenes/TransactionDetailsScene.tsx
src/components/ui4/SwapDetailsCard.tsx

none
---
- https://app.asana.com/0/0/1206232453539978

UI4: Fix Tx Details Text Styling

---

src/actions/LoginActions.tsx

none
---
- https://app.asana.com/0/0/1206265982662403

UI4: Fix initial routing for new accounts

---

src/components/Main.tsx
src/components/navigation/EdgeHeader.tsx
src/components/themed/SideMenu.tsx
src/components/ui4/scenes/HomeSceneUi4.tsx
src/types/routerTypes.tsx

https://github.com/EdgeApp/edge-react-gui/pull/4683
---
- https://app.asana.com/0/0/1206280885176692

Fix Markets scene's missing Edge logo in header

---

CHANGELOG.md
src/plugins/stake-plugins/generic/pluginInfo/filecoinCalibrationGlifpool.ts
src/plugins/stake-plugins/generic/pluginInfo/filecoinGlifpool.ts

none
---
- https://app.asana.com/0/0/1206301475862744

Update Glif Pool APY yield info endpoints

---

src/actions/CategoriesActions.ts

Need to check `metadata.name` for empty string then translate that into default text like "Sent Bitcoin"
none
---
- https://app.asana.com/0/0/1206314724644109

Fix missing default "Sent Bitcoin" payee data

---

CHANGELOG.md
src/components/cards/AssetStatusCard.tsx

none
---
- https://app.asana.com/0/0/1206305124073934

Fixed title and message handling in AssetStatusCard

---

src/components/modals/FioCreateHandleModal.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/CdnUris.ts

- Use ButtonsViewUi4
- Change green word highlight location
https://github.com/EdgeApp/edge-react-gui/pull/4673
---
- https://app.asana.com/0/0/1206262048565608

Update FIO handle modal

---

src/__tests__/scenes/__snapshots__/CryptoExchangeQuoteScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/theme/variables/edgeDark.ts
src/theme/variables/edgeLight.ts
src/theme/variables/testDark.ts
src/theme/variables/testLight.ts

Old colors:
Error:
Warning:
New colors:
Error:
Warning:
none
---
- https://app.asana.com/0/0/1205856665924215

UI4: AlertCardUi4 Color Update

---

src/components/scenes/SendScene2.tsx

none
---
- https://app.asana.com/0/0/1206321284960235

Prevent multiple scan modals on sendscene

---

src/__tests__/components/__snapshots__/BalanceCard.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/EdgeLoginScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/actions/AccountReferralActions.ts
src/components/ui4/ButtonUi4.tsx
src/components/ui4/CardUi4.tsx
src/components/ui4/CarouselUi4.tsx
src/components/ui4/PromoCardUi4.tsx
src/components/ui4/PromoCardsUi4.tsx
src/components/ui4/scenes/HomeSceneUi4.tsx

Pending close button functionality
none
---
- https://app.asana.com/0/0/1206075308977979

Add promo cards to HomeScene

---

src/actions/DeepLinkingActions.ts
src/actions/PluginActions.tsx
src/components/scenes/GuiPluginListScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/gui/fiatPlugin.tsx
src/plugins/gui/fiatPluginTypes.ts
src/plugins/gui/providers/banxaProvider.ts
src/plugins/gui/providers/paybisProvider.ts

none
---
- https://app.asana.com/0/0/1206237460730144

Get camera permission for paybis and banxa

---

src/components/themed/MenuTabs.tsx

none
---
- https://app.asana.com/0/0/1206346500344661

Fix DEV_TAB logic

---

src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/components/themed/SimpleTextInput.tsx
src/theme/variables/edgeDark.ts

none
---
- https://app.asana.com/0/0/1206338978028636

Fix SimpleTextInput placeholder

---

src/components/scenes/TransactionListScene.tsx
src/components/themed/TransactionListTop.tsx
src/components/themed/WalletListCurrencyRow.tsx
src/components/ui4/CryptoIconUi4.tsx
src/components/ui4/CurrencyViewUi4.tsx

none
---
- https://app.asana.com/0/0/1206346500732272

Fix wallet color

---

src/plugins/stake-plugins/generic/pluginInfo/optimismTarotPool.ts

none
---
- https://app.asana.com/0/0/1206375237510507

Replace Tarot plugin Optimism node

---

src/state/SceneFooterState.tsx

none
---
- https://app.asana.com/0/0/1206332497625336

Fix crash on production Android builds from scroll end event

---

src/components/themed/WalletListSwipeable.tsx

We no longer scroll down the content because we don't have to hide
search below the header.
none
---
- https://app.asana.com/0/0/1206379497162078

Remove contentOffset from wallet list

---

src/components/scenes/ChangeMiningFeeScene.tsx

none
---
- https://app.asana.com/0/0/1206379497162107

Add background accent colors to ChangeMiningFeeScene

---

src/components/themed/TransactionListRow.tsx
src/components/ui4/AlertCardUi4.tsx
src/components/ui4/CardUi4.tsx
src/components/ui4/ModalUi4.tsx
src/components/ui4/SupportCardUi4.tsx
src/components/ui4/scenes/HomeSceneUi4.tsx
src/theme/variables/edgeDark.ts
src/theme/variables/edgeLight.ts
src/theme/variables/testDark.ts
src/theme/variables/testLight.ts
src/types/Theme.ts

none
---
- https://app.asana.com/0/0/1206315466361658

Remove "Ui4" from theme keys

---

src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/components/scenes/InputTesterScene.tsx
src/components/themed/FilledTextInput.tsx

none
---
- https://app.asana.com/0/0/1206396226106825

Add more padding to FilledTextInput

---

src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/components/themed/TransactionListTop.tsx

none
---
- https://app.asana.com/0/0/1206379497162070

Re-add the gear icon in the tx list

---

src/components/ui4/scenes/HomeSceneUi4.tsx

none
---
- https://app.asana.com/0/0/1206394920217302

Add WiredProgressBar to HomeSceneUi4

---

src/components/scenes/WalletListScene.tsx
src/components/services/Services.tsx
src/components/ui4/scenes/HomeSceneUi4.tsx

---
- https://app.asana.com/0/0/1206377226801739

Prevent conflicts from password reminder and backup modals

---

src/components/scenes/ChangeMiningFeeScene.tsx

This makes it clear how to close the keyboard when the user finishes entering an amount.
none
---
- https://app.asana.com/0/0/1206346500732297

Add a "done" button to the mining fee keyboard

---

src/components/themed/FilledTextInput.tsx

none
---
- https://app.asana.com/0/0/1206414153577128

Fix pink X glitch in FilledTextInput

---

CHANGELOG.md
src/actions/ScanActions.tsx
src/actions/WalletListMenuActions.tsx
src/constants/WalletAndCurrencyConstants.ts
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1205857134898560

Show nice error message when attempting to sweep a private key that can't afford the transaction fee

---

src/components/Main.tsx
src/components/themed/MenuTabs.tsx
src/components/themed/SceneFooterWrapper.tsx
src/components/themed/SearchFooter.tsx
src/components/themed/SimpleTextInput.tsx
src/state/SceneFooterState.tsx
src/state/SceneScrollState.tsx

none
---
- https://app.asana.com/0/0/1206417368202773

Fix footer performance

---

src/components/scenes/Staking/StakeOverviewScene.tsx
src/components/ui4/ButtonsViewUi4.tsx

Need a 4 button UI design spec before using ButtonsViewUi4.
For now, just make it look right using the ButtonsViewUi4 column styling.
none
---
- https://app.asana.com/0/0/1206332190957135

Fix StakeOverviewScene styling

---

src/__tests__/scenes/__snapshots__/CryptoExchangeQuoteScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/components/common/SceneWrapper.tsx
src/components/notification/NotificationCard.tsx
src/components/notification/NotificationView.tsx

none
---
- https://app.asana.com/0/0/1206424271493509

Fix NotificationView positioning

---

src/envConfig.ts

---
- https://app.asana.com/0/0/1206425025094470

Add alchemy key to Solana init options

---

src/components/common/AirshipDropdown.tsx

Only make the drop-down itself swipeable, not the whole scene.
none
---
- https://app.asana.com/0/0/1206425713692382

Fix dropdown gesture handling

---

src/__tests__/scenes/SettingsScene.test.tsx
src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap
src/actions/DeviceSettingsActions.ts
src/app.ts
src/components/common/EdgeAnim.tsx
src/components/scenes/CoinRankingScene.tsx
src/components/scenes/SettingsScene.tsx
src/components/scenes/TransactionListScene.tsx
src/components/themed/WalletListSwipeable.tsx
src/components/ui4/ButtonsViewUi4.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json
src/types/types.ts

none
---
- https://app.asana.com/0/0/1206447894981394

Add setting to disable animations

---

src/components/themed/WalletListSwipeable.tsx

---
- https://app.asana.com/0/0/1206447345628834

Fix passing tokenId as currencyCode

---

src/components/modals/FioCreateHandleModal.tsx

- Reduce margins
- Allow the image to shrink
none
---
- https://app.asana.com/0/0/1206280885176731

Restyle FioCreateHandleModal

---

src/components/Main.tsx
src/util/tracking.ts

Add two new events in addition to the existing start_app event
---
- https://app.asana.com/0/0/1206294833608887

Add Start_App_No_Accounts and Start_App_With_Accounts events

---

src/components/ui4/CarouselUi4.tsx
src/components/ui4/PromoCardUi4.tsx
src/components/ui4/PromoCardsUi4.tsx
src/components/ui4/scenes/HomeSceneUi4.tsx

none
---
- https://app.asana.com/0/0/1206315466361645

Fix carousel

---

src/components/services/Providers.tsx

none
---
- https://app.asana.com/0/0/1206417270663123

No more white nav bar

---

src/__tests__/components/__snapshots__/CurrencyIcon.test.tsx.snap
src/__tests__/components/__snapshots__/ExchangeQuoteComponent.test.tsx.snap
src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/__tests__/scenes/__snapshots__/CryptoExchangeQuoteScene.test.tsx.snap
src/components/progress-indicators/WalletSyncCircle.tsx

none
---
- https://app.asana.com/0/0/1206425714003050

Transparent WalletSyncCircle

---

src/__tests__/modals/__snapshots__/HelpModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CryptoExchangeQuoteScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/components/modals/HelpModal.tsx
src/components/modals/ScanModal.tsx
src/components/scenes/SendScene2.tsx
src/theme/variables/edgeDark.ts

none
---
- https://app.asana.com/0/0/1206427924851776
- https://app.asana.com/0/0/1206454137580840

Small GUI Fixes 3

---

CHANGELOG.md
src/components/modals/AutoLogoutModal.tsx

none
---
- https://app.asana.com/0/0/1206353529009466

Fix Android dark-mode detection

---

src/components/scenes/GuiPluginListScene.tsx

none
---
- https://app.asana.com/0/0/1206346500344678
- https://app.asana.com/0/0/1206425714003037

Add padding to Buy/Sell Scene

---

src/plugins/gui/components/GuiFormField.tsx
src/plugins/gui/scenes/SepaFormScene.tsx

none
---
- https://app.asana.com/0/0/1206346500344678

Restyle SepaFormScene

---

src/__tests__/components/__snapshots__/BalanceCard.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/EdgeLoginScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/components/Main.tsx
src/components/scenes/DevTestScene.tsx
src/components/ui4/ButtonUi4.tsx

https://github.com/EdgeApp/edge-login-ui-rn/pull/157
---
- https://app.asana.com/0/0/1206455248718481

GUI: Sync ButtonUi4 Spinner Fixes from LoginUI

---

src/components/scenes/Staking/StakeModifyScene.tsx
src/plugins/stake-plugins/generic/util/stakeKitUtils.ts

---
- https://app.asana.com/0/0/1206398950862158

Add StakeKit insufficientFunds error handling to action endpoints

---

src/components/common/SceneWrapper.tsx
src/components/themed/MenuTabs.tsx
src/components/themed/SearchFooter.tsx

none
---
- https://app.asana.com/0/0/1206346500732358

Fix foot cramps

---

src/actions/DeviceSettingsActions.ts
src/actions/LoginActions.tsx
src/components/notification/NotificationView.tsx
src/components/services/Services.tsx
src/types/types.ts

Also, only allow it to be interacted with once and then hidden forever.
---
- https://app.asana.com/0/0/1206426372035219

Only show the backup notification card if FIO names are present

---

android/app/src/main/res/values/styles.xml
src/components/services/Providers.tsx

Make the OS navbar opaque on Android

---

src/components/scenes/RequestScene.tsx

Do not use Carousel for single item qr codes
none
---
- https://app.asana.com/0/0/1206312840532595

Fix broken qr code

---

src/__tests__/components/__snapshots__/MenuTabs.test.tsx.snap
src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CryptoExchangeQuoteScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/components/notification/NotificationView.tsx
src/components/themed/MenuTabs.tsx
src/components/themed/SceneFooterWrapper.tsx
src/components/themed/SimpleTextInput.tsx
src/state/SceneFooterState.tsx

none
---
- https://app.asana.com/0/0/1206481495752109

Do translate instead of layout rules for footer/menu

---

src/components/themed/SideMenu.tsx

---
- https://app.asana.com/0/0/1206499621543692

Toggle pressability of down chevron with disabled flag

---

src/experimentConfig.ts

none
---
- https://app.asana.com/0/0/1206501007765990

Fix enable light accounts

---

src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1206490395612743

Disable Piratechain on Android Oreo and below

---

src/__tests__/toPercentString.test.ts
src/locales/intl.ts
src/util/cleaners.ts

none
---
- https://app.asana.com/0/0/1206500529318664

Add better string validation to `toPercentString`

---

src/__tests__/components/__snapshots__/TransactionListRow.test.tsx.snap
src/components/themed/TransactionListRow.tsx

- Add ellipses
- Set flexShrink=1
none
---
- https://app.asana.com/0/0/1206501449332905

Fix overextended pending notice.

---

CHANGELOG.md
android/build.gradle

none
---
- https://app.asana.com/0/0/1206445397352971

Upgrade to Android NDK version 26

---

src/plugins/stake-plugins/stakePlugins.ts

Add catch after makeGenericStakePlugin
none
---
- https://app.asana.com/0/0/1206499002939634

Fix red error entering some assets

---

src/components/themed/WalletListCreateRow.tsx

Physical Android devices perform double taps in this specific situation, and core cannot handle concurrent wallet creation requests.
none
---
- https://app.asana.com/0/0/1206501773855682

Mutex wallet creation in WalletListCreateRow

---

src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CryptoExchangeQuoteScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CurrencyNotificationScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CurrencySettings.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/EdgeLoginScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/components/common/SceneWrapper.tsx

none
---
- https://app.asana.com/0/0/1206513324458918

Add back DotsBackground to SceneWrapper

---

src/components/ui4/PromoCardsUi4.tsx

none
---
- https://app.asana.com/0/0/1206513575338578

Fix missing promo cards

---

CHANGELOG.md
src/experimentConfig.ts

none
---
- https://app.asana.com/0/0/1206378838830226

Re-enable signupCaptcha

---

CHANGELOG.md
src/components/ui4/SwapDetailsCard.tsx
src/controllers/edgeProvider/EdgeProviderServer.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1206049584644619

Better error message when user doesn't have an email account

---

CHANGELOG.md
src/components/themed/SwipeableRow.tsx

none
---
- https://app.asana.com/0/0/1206539941365453

Update style for SwipeableRow to match UI4

---

CHANGELOG.md
src/components/scenes/TransactionDetailsScene.tsx
src/constants/WalletAndCurrencyConstants.ts
src/envConfig.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/CurrencyInfoHelpers.ts
src/util/corePlugins.ts

none
---
- https://app.asana.com/0/0/1206548993975475

Add Arbitrum and Base

---

CHANGELOG.md
android/app/src/main/AndroidManifest.xml

none
---
- https://app.asana.com/0/0/1206543639740175

Change Android softInputMode to adjustResize

---

CHANGELOG.md
src/actions/LoginActions.tsx
src/components/Main.tsx
src/components/scenes/GettingStartedScene.tsx
src/components/scenes/LoginScene.tsx
src/experimentConfig.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/types/routerTypes.tsx
src/util/tracking.ts

- Remove concluded swipeLastUsp
- Centralize experiment config getter to Main for initial scenes
- Fix pagination dot count
- Replace 'legacyLanding' with 'landingType,' with variants: 
'A_legacy' - Legacy Landing
'B_Usps' - Original USPs
'C_UspsMinusWGYC' - USPs, minus the first slide:
'D_UspsAltWGYC' - USPs with modified first slide copy:
none
---
- https://app.asana.com/0/0/1206488798092840

ABCD Landing Test

---

src/__tests__/components/__snapshots__/FilledTextInput.test.tsx.snap
src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap
src/__tests__/modals/__snapshots__/HelpModal.test.tsx.snap
src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/components/themed/FilledTextInput.tsx
src/components/themed/SimpleTextInput.tsx
src/components/ui4/BalanceCardUi4.tsx
src/components/ui4/ModalUi4.tsx
src/components/ui4/SectionHeaderUi4.tsx

none
---
- https://app.asana.com/0/0/1205615584415966

Increase tap areas

---

CHANGELOG.md
src/components/themed/SideMenu.tsx

none
---
- https://app.asana.com/0/0/1206501486890527

Attach a unique referral ID to share links

---

CHANGELOG.md
src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/components/themed/TransactionListComponents.tsx
src/components/themed/TransactionListTop.tsx

none
---
- https://app.asana.com/0/0/1205615584415977

TransactionList styling updates

---

CHANGELOG.md
src/__tests__/scenes/FioAddressSettingsScene.test.tsx
src/components/scenes/Fio/FioAddressRegisterSelectWalletScene.tsx
src/components/scenes/Fio/FioAddressSettingsScene.tsx
src/components/scenes/Fio/FioCreateHandleScene.tsx
src/components/scenes/Fio/FioDomainRegisterSelectWalletScene.tsx
src/components/scenes/Fio/FioDomainSettingsScene.tsx
src/components/scenes/Fio/FioNameConfirmScene.tsx
src/util/tracking.ts

none
---
- https://app.asana.com/0/0/1206488798092845

FIO Conversion Analytics

---

CHANGELOG.md
src/components/modals/ScanModal.tsx
src/components/scenes/WcConnectionsScene.tsx
src/components/themed/FilledTextInput.tsx
src/components/themed/SideMenu.tsx

See linked Asana task for detailed investigation.
none
---
- https://app.asana.com/0/0/1206594642752089

Fix: Samsung FilledTextInput Defocus

---

CHANGELOG.md
src/actions/LoginActions.tsx
src/theme/edgeConfig.ts
src/theme/testConfig.ts
src/types/types.ts
src/util/CurrencyInfoHelpers.ts

none
---
- https://app.asana.com/0/0/1206604513660356

Use EdgeAsset for defaultWallets in AppConfig

---

CHANGELOG.md
src/util/tracking.ts

none
---
- https://app.asana.com/0/0/1206531980632083

Analytics: Notification Status

---

src/components/scenes/MigrateWalletCalculateFeeScene.tsx

---
- https://app.asana.com/0/0/1206617916204755

Catch insufficient funds errors thrown from getMaxSpendable

---

src/actions/WalletActions.tsx

---
- https://app.asana.com/0/0/1206659938019236

Fix updateMostRecentWalletsSelected tokenId arg

---

src/util/FioAddressUtils.ts

Check and filter out null token objects
none
---
- https://app.asana.com/0/0/1206662647999769

Fix currencyCode red error

---

src/components/scenes/GettingStartedScene.tsx

---
- https://app.asana.com/0/0/1206651477772715

Remove footnote from slide1Alt

---

src/components/scenes/CreateWalletCompletionScene.tsx

none
---
- https://app.asana.com/0/0/1206662724761958

Fix token creation on new wallets

---

src/constants/plugins/sellPluginList.json

none
---
- https://app.asana.com/0/0/1206673025749273

Enable sell to debit for UK (GB)

---

src/components/scenes/OtpRepairScene.tsx
src/components/scenes/SecurityAlertsScene.tsx
src/components/scenes/UpgradeUsernameScreen.tsx

none
---
- https://app.asana.com/0/0/1206672583193529

Fix instances of SceneWrapper on scenes without headers

---

CHANGELOG.md
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts

Properly detect insufficient funds so we create a funding transaction for the primary address
none
---
- https://app.asana.com/0/0/1206669733974328

Fix InsufficientFundsError when unstaking

---

CHANGELOG.md
src/actions/LoginActions.tsx

none
---
- https://app.asana.com/0/0/1206689987490075

Only call loadAccountReferral on new accounts

---

CHANGELOG.md
src/actions/CategoriesActions.ts
src/components/services/ContactsLoader.ts
src/util/corePlugins.ts

https://github.com/EdgeApp/edge-currency-accountbased/pull/731
https://github.com/EdgeApp/edge-exchange-plugins/pull/314
---
- https://app.asana.com/0/0/1206659939139680

Enable cosmosibc swap plugin

---

CHANGELOG.md
src/components/notification/NotificationView.tsx
src/components/services/Services.tsx

none
---
- https://app.asana.com/0/0/1206584676528444

Add a pw reminder notification

---

src/components/scenes/CreateWalletCompletionScene.tsx
src/components/scenes/CreateWalletSelectFiatScene.tsx

none
---
- https://app.asana.com/0/0/1206727526970426

Correctly handle key options for wallet creation

---

src/actions/LoginActions.tsx
src/components/scenes/LoginScene.tsx
src/reducers/scenes/SettingsReducer.ts

https://github.com/EdgeApp/edge-login-ui-rn/pull/171
---
- https://app.asana.com/0/0/1206696302392513

Switch the login-ui into `fastLogin` mode

---

CHANGELOG.md
src/components/scenes/Fio/FioAddressSettingsScene.tsx

none
---
- https://app.asana.com/0/0/1206742525242422

Fix sendParams for FIO name transfer

---

src/plugins/gui/providers/kadoProvider.ts

none
---
- https://app.asana.com/0/0/1206790202336168

Limit kado to ach/wire only

---

CHANGELOG.md
src/components/scenes/DevTestScene.tsx
src/components/ui4/ButtonUi4.tsx

none
---
- https://app.asana.com/0/0/1206469369468356

Fixed button width regardless of content visiblity

---

src/actions/CreateWalletActions.tsx
src/actions/CryptoExchangeActions.tsx
src/components/scenes/Fio/FioAddressRegisterSelectWalletScene.tsx
src/components/scenes/Fio/FioAddressSettingsScene.tsx
src/components/scenes/Fio/FioCreateHandleScene.tsx
src/components/scenes/Fio/FioDomainRegisterSelectWalletScene.tsx
src/components/scenes/Fio/FioDomainSettingsScene.tsx
src/components/scenes/Fio/FioNameConfirmScene.tsx
src/controllers/edgeProvider/EdgeProviderServer.tsx
src/plugins/gui/fiatPlugin.tsx
src/plugins/gui/fiatPluginTypes.ts
src/plugins/gui/providers/banxaProvider.ts
src/plugins/gui/providers/kadoProvider.ts
src/plugins/gui/providers/mtpelerinProvider.ts
src/plugins/gui/providers/paybisProvider.ts
src/util/CryptoAmount.ts
src/util/tracking.ts

This PR fixes an erronous merge from PR https://github.com/EdgeApp/edge-react-gui/pull/4890
none

Refactor tracking props to be explicit, use CryptoAmount

---

src/__tests__/components/Buttons.test.tsx
src/__tests__/components/Card.test.tsx
src/__tests__/components/Row.test.tsx
src/__tests__/components/__snapshots__/Buttons.test.tsx.snap
src/__tests__/components/__snapshots__/Card.test.tsx.snap
src/__tests__/components/__snapshots__/Row.test.tsx.snap

none
---
- https://app.asana.com/0/0/1206177717415406

UI4: Unit Tests 1.0 - Card, Row, Buttons

---

src/components/modals/WalletListModal.tsx
src/components/services/SortedWalletList.ts
src/components/themed/WalletList.tsx
src/components/themed/WalletListSwipeable.tsx

Quicker Wallet Picker

---

CHANGELOG.md
src/components/scenes/Fio/FioAddressRegisterSelectWalletScene.tsx
src/components/scenes/Fio/FioDomainRegisterSelectWalletScene.tsx
src/constants/WalletAndCurrencyConstants.ts
src/util/FioAddressUtils.ts

This fixes incorrect mapping of FIO payment currency codes which do not match actual standard currency codes used in Edge.
none
---
- https://app.asana.com/0/0/1206779841848673

Fix FIO handle/domain registration to use tokenId

---

src/components/scenes/CryptoExchangeQuoteProcessingScene.tsx
src/components/scenes/CryptoExchangeScene.tsx
src/components/themed/CryptoExchangeFlipInput.tsx

none
---
- https://app.asana.com/0/0/1206837292251140

Exchange refactor fixes

---

ios/Podfile.lock
jestSetup.js
package.json
src/components/scenes/RequestScene.tsx
yarn.lock

none
---
- https://app.asana.com/0/0/1206840588533464

Fix clipboard crash

---

src/actions/PaymentProtoActions.tsx
src/components/scenes/CryptoExchangeQuoteScene.tsx
src/components/scenes/Loans/LoanCreateScene.tsx
src/components/themed/TransactionListTop.tsx
src/components/tiles/AddressTile2.tsx
src/hooks/useSelectedWallet.ts
src/locales/strings/enUS.json
src/plugins/gui/util/initializeProviders.ts
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
src/util/CryptoAmount.ts
src/util/CurrencyInfoHelpers.ts
src/util/tracking.ts
src/util/utils.ts

none
---
- https://app.asana.com/0/0/1206867236470048
- https://app.asana.com/0/0/1206867222862133

Fix exchange scene red error

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1206190300542474

Re-enabled Filecoin FEVM transactions

---

src/plugins/gui/scenes/FiatPluginEnterAmountScene.tsx

none
---
- https://app.asana.com/0/0/1206879219392485

Fix notifications on EnterAmount scene

---

CHANGELOG.md
src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap
src/components/modals/WalletListModal.tsx

An extra ScrollView was causing children not to
receive taps while the keyboard was open
none
---
- https://app.asana.com/0/0/1206859630507460

Fix WalletList children not receiving taps

---

CHANGELOG.md
src/actions/LogActions.tsx

none
---
- https://app.asana.com/0/0/1206859452306560

Successfully upload logs, even with core errors

---

CHANGELOG.md
ios/Podfile.lock
package.json
src/envConfig.ts
src/util/corePlugins.ts
yarn.lock

none
---
- https://app.asana.com/0/0/1206892270758886

Add FILECOIN_INIT for `glifApiKey`

---

src/components/scenes/CryptoExchangeScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1206891394057398

Fix crash error caused by triggering swap quote from keyboard

---

src/components/services/AirshipInstance.tsx

none
---
- https://app.asana.com/0/0/1206900920409631

Hide "WebView has been unmounted" errors

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts
src/envConfig.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/gui/providers/paybisProvider.ts
src/util/corePlugins.ts

---
- https://app.asana.com/0/0/1206683661257161

Add Cardano

---

CHANGELOG.md
ios/Podfile.lock
package.json
src/__tests__/components/__snapshots__/TransactionListRow.test.tsx.snap
src/components/themed/TransactionListRow.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json
yarn.lock

none
---
- https://app.asana.com/0/0/1206663127267137

Display new `'failed'` case for transaction confirmation status

---

CHANGELOG.md
src/util/CurrencyInfoHelpers.ts

none
---
- https://app.asana.com/0/0/1206566747586157

Add safety checks to currency code utility fns

---

src/actions/CategoriesActions.ts

none
---
- https://app.asana.com/0/0/1206566749463613

Work around BugSnag crash in `getTxActionDisplayInfo`

---

src/components/scenes/SwapCreateScene.tsx
src/components/themed/SwapInput.tsx

none
---
- https://app.asana.com/0/0/1206939425095268

Relocate max button on swap scene so it's touchable

---

src/components/scenes/SwapCreateScene.tsx

none
---
- https://app.asana.com/0/0/1206939571387513

Swap scene state fixes

---

.gitignore
package.json
src/__tests__/scenes/__snapshots__/SwapCreateScene.test.tsx.snap
src/components/scenes/SwapCreateScene.tsx

- Fix incorrect strings mismatch on the swap scene for the select wallet buttons
- Fix the typechain precommit script to be less obnoxious when generating new contracts directory
none
---
- https://app.asana.com/0/0/1206954922796851

Fix mistakes

---

src/components/themed/FlipInput2.tsx

none
---
- https://app.asana.com/0/0/1206934861246662

Propagate clear press event as a change event for FlipInput2

---

src/components/scenes/SwapCreateScene.tsx
src/components/themed/SwapInput.tsx

none
---
- https://app.asana.com/0/0/1206936104345267

Change secondary placeholder behavior for SwapInput

---

package.json
src/components/services/Providers.tsx
yarn.lock

none
---
- https://app.asana.com/0/0/1206963122180775

Remove redux-flipper

---

src/components/scenes/SwapCreateScene.tsx

none
---
- https://app.asana.com/0/0/1206962923767230

Show currency code for primary placeholder when input is empty

---

ios/Podfile
ios/Podfile.lock
package.json
yarn.lock

none
---
- https://app.asana.com/0/0/1206966606672158

Upgrade to react-native-permissions v4

---

CHANGELOG.md
src/components/scenes/SendScene2.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1204726661956279

Add a better '504' tx failure message

---

src/components/themed/WalletList.tsx

none
---
- https://app.asana.com/0/0/1206981844105028

Fix duplicate item keys in the wallet list

---

src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/components/themed/TransactionListTop.tsx

Edit: Top row changes:
- Reduce eye icon ~75% from original
- Adjust balance font scaling
- Reduce balance maximum font size to match smaller eye better
- (Edit) Change wallet picker to match `SwapInput`
none
---
- https://app.asana.com/0/0/1206981582225833

Adjust styling on TransactionListTop

---

src/__tests__/scenes/CreateWalletImportScene.test.tsx
src/__tests__/scenes/CreateWalletSelectFiatScene.test.tsx
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap
src/components/modals/WalletListModal.tsx
src/components/scenes/MigrateWalletSelectCryptoScene.tsx
src/components/services/SortedWalletList.ts
src/components/services/WalletLifecycle.ts
src/components/themed/WalletList.tsx
src/selectors/getCreateWalletList.ts
src/types/types.ts

none
---
- https://app.asana.com/0/0/1207031204951091

Add a type to wallet list items

---

CHANGELOG.md
src/components/modals/WalletListModal.tsx
src/components/themed/TransactionListTop.tsx
src/components/themed/WalletList.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1206779193613531

Add "Parent Wallet" Section to TxList Wallet Picker

---

src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json
src/plugins/gui/providers/bityProvider.ts

none
---
- https://app.asana.com/0/0/1207004050443359

Change supportEmail for bityProvider

---

CHANGELOG.md
src/components/Main.tsx
src/components/scenes/GettingStartedScene.tsx
src/components/scenes/LoginScene.tsx
src/experimentConfig.ts
src/locales/en_US.ts
src/locales/strings/enUS.json

Use the original USP flavor (B_Usps).
none
---
- https://app.asana.com/0/0/1206936863273882

Conclude USPs experiment

---

CHANGELOG.md
src/hooks/useTransactionList.ts

none
---
- https://app.asana.com/0/0/1206902425530802
https://github.com/EdgeApp/edge-react-gui/assets/517469/e7d12a20-727f-46a5-ab7e-047bf5b997ae

Fix glitchy load behavior when searching on TransactionListScene

---

src/plugins/gui/amountQuotePlugin.ts

none
---
- https://app.asana.com/0/0/1207030726311935

Show a better error in amountQuotePlugin if no provider is found

---

CHANGELOG.md
src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/components/icons/ThemedIcons.tsx
src/components/themed/SimpleTextInput.tsx

none
---
- https://app.asana.com/0/0/1207014593281421

Add Done button to search bar

---

CHANGELOG.md
src/components/scenes/SendScene2.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1206912420386184

Improve send insufficient funds error

---

CHANGELOG.md
src/plugins/gui/fiatPlugin.tsx
src/plugins/gui/providers/kadoProvider.ts

none
---
- https://app.asana.com/0/0/1207057109616480

Fix Kado Plain bank linking glitchiness

---

ios/edge.xcodeproj/project.pbxproj
ios/edge/PrivacyInfo.xcprivacy
patches/react-native-fs+2.20.0.patch

See https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api for context.
none
---
- https://app.asana.com/0/0/1207030029358666

Privacy manifest

---

CHANGELOG.md
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/components/modals/WalletListModal.tsx
src/components/scenes/CreateWalletSelectCryptoScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1206524978696205

Custom Token From CreateWalletSelectCryptoScene

---

src/components/Main.tsx

none
---
- https://app.asana.com/0/0/1207101857998754

Supress back button toast message

---

scripts/prepare.sh

Add comment to `npx jetify` in prepare.sh

---

src/components/scenes/CreateWalletSelectFiatScene.tsx

none
---
- https://app.asana.com/0/0/1207098717611525

Make the split operation sequential

---

CHANGELOG.md
src/__tests__/components/__snapshots__/Buttons.test.tsx.snap
src/__tests__/components/__snapshots__/ExchangeQuoteComponent.test.tsx.snap
src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectFiatScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SwapConfirmationScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/actions/CategoriesActions.ts
src/components/common/SceneButtons.tsx
src/components/data/row/CurrencyRow.tsx
src/components/scenes/GuiPluginListScene.tsx
src/components/themed/ExchangeQuoteComponent.tsx
src/components/themed/FilledTextInput.tsx
src/components/themed/TransactionListTop.tsx
src/components/ui4/ButtonsViewUi4.tsx
src/plugins/gui/amountQuotePlugin.ts
src/plugins/gui/fiatPlugin.tsx

none
---
- https://app.asana.com/0/0/1207014495418292

4.6 Small Gui Fixes

---

CHANGELOG.md
src/actions/WalletActions.tsx
src/constants/WalletAndCurrencyConstants.ts

---
- https://app.asana.com/0/0/1206801422762387

Remove Hedera activation

---

CHANGELOG.md
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/components/scenes/CreateWalletCompletionScene.tsx
src/components/scenes/CreateWalletImportScene.tsx
src/components/scenes/MigrateWalletCalculateFeeScene.tsx
src/components/ui4/MarginsUi4.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

NOTE: Was unable to route directly to MigrateWalletCalculateFeeScene. Doing so made it think that there was still 0 max spendable for the wallets, even after waiting for wallets to fully sync...
As a workaround, routed a step earlier in the migrate flow instead.
none
---
- https://app.asana.com/0/0/1205838484838736

Add Migrate to Import Flow

---

CHANGELOG.md
src/components/scenes/WcConnectionsScene.tsx
src/hooks/useWalletConnect.tsx

---
- https://app.asana.com/0/0/1206626674849693

Handle sessions with 0 required namespaces

---

patches/expo-file-system+16.0.8.patch

none
---
- https://app.asana.com/0/0/1207131951874646

Remove disk free space from expo-file-system

---

src/components/scenes/CreateWalletSelectCryptoScene.tsx
src/components/scenes/EditTokenScene.tsx
src/components/scenes/TransactionListScene.tsx
src/components/themed/TransactionListTop.tsx
src/components/themed/WalletList.tsx

---
- https://app.asana.com/0/0/1206698013777470

Fix staked amount display in transaction list scene

---

CHANGELOG.md
ios/Podfile.lock
package.json
src/__tests__/scenes/FioAddressSettingsScene.test.tsx
src/__tests__/scenes/FioConnectWalletConfirmScene.test.tsx
src/actions/FioActions.tsx
src/app.ts
src/components/FioAddress/ConnectWallets.tsx
src/components/modals/WalletListModal.tsx
src/components/scenes/Fio/FioAddressDetailsScene.tsx
src/components/scenes/Fio/FioAddressListScene.tsx
src/components/scenes/Fio/FioAddressRegisterScene.tsx
src/components/scenes/Fio/FioAddressRegisterSelectWalletScene.tsx
src/components/scenes/Fio/FioAddressSettingsScene.tsx
src/components/scenes/Fio/FioConnectWalletConfirmScene.tsx
src/components/scenes/Fio/FioDomainRegisterScene.tsx
src/components/scenes/Fio/FioDomainRegisterSelectWalletScene.tsx
src/components/scenes/Fio/FioDomainSettingsScene.tsx
src/components/scenes/Fio/FioNameConfirmScene.tsx
src/components/scenes/Fio/FioRequestConfirmationScene.tsx
src/components/scenes/Fio/FioRequestListScene.tsx
src/components/scenes/WalletListScene.tsx
src/components/themed/SceneFooterWrapper.tsx
src/components/themed/SearchFooter.tsx
src/components/themed/SelectFioAddress2.tsx
src/components/themed/TransactionListTop.tsx
src/types/routerTypes.tsx
src/util/CryptoAmount.ts
src/util/tracking.ts
yarn.lock

none
---
- https://app.asana.com/0/0/1206559859162449

Yellow RN Warning Fixes

---

CHANGELOG.md
src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/gui/amountQuotePlugin.ts

none
---
- https://app.asana.com/0/0/1207087700790825

Show toast message when no providers exist for region/payment method

---

src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/gui/fiatPlugin.tsx
src/plugins/gui/fiatPluginTypes.ts
src/plugins/gui/providers/paybisProvider.ts

none
---
- https://app.asana.com/0/0/1207214496338536

Add spinning toast when finalizing Paybis quote

---

android/app/build.gradle

none
---
- https://app.asana.com/0/0/1207207548888924

Restore animated GIF support on Android

---

CHANGELOG.md
src/components/ui4/PromoCardsUi4.tsx

none
---
- https://app.asana.com/0/0/1207094332957030

Add support to filter promo cards based on promoIds

---

CHANGELOG.md
src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/components/Main.tsx
src/components/scenes/TransactionListScene.tsx
src/components/themed/SwapInput.tsx
src/components/themed/TransactionListTop.tsx
src/components/themed/WalletListSwipeable.tsx
src/components/themed/WalletListSwipeableCurrencyRow.tsx

none
---
- https://app.asana.com/0/0/1207127789245039

Swap Flip Input Minor Redesign

---

scripts/hack-travis.mjs

none
---
- https://app.asana.com/0/0/1207317125247697

Fix Travis build issue caused by edge-currency-plugins upgrade

---

CHANGELOG.md
src/actions/LoginActions.tsx
src/actions/ScamWarningActions.tsx
src/actions/WalletListMenuActions.tsx
src/components/modals/ScamWarningModal.tsx
src/components/scenes/DevTestScene.tsx
src/components/scenes/SendScene2.tsx
src/components/scenes/WcConnectionsScene.tsx
src/constants/constantSettings.ts
src/locales/en_US.ts
src/locales/strings/enUS.json

Add the new warning to first login, key view, and WalletConnect
none
---
- https://app.asana.com/0/0/1205607977307501

Extend Scam Warning

---

CHANGELOG.md
src/plugins/gui/providers/paybisProvider.ts

none
---
- https://app.asana.com/0/0/1205615584416000

Enable Paybis buy

---

package.json
src/components/scenes/EditTokenScene.tsx
yarn.lock

https://github.com/EdgeApp/edge-currency-accountbased/pull/770
---
- https://app.asana.com/0/0/1207199560481485

Add Thorchain token support

---

src/components/scenes/SendScene2.tsx

---
- https://app.asana.com/0/0/1206616383733403

Fix InsufficientFeesModal logic

---

CHANGELOG.md
index.ts
ios/Podfile
ios/Podfile.lock
package.json
src/actions/LoginActions.tsx
src/components/scenes/LoginScene.tsx
src/perf.ts
yarn.lock

none
---
- https://app.asana.com/0/0/1206479125385477

Add performance metrics to logs

---

src/perf.ts

none
---
- https://app.asana.com/0/0/1207334862540596

Fix crash caused by missing performance mark

---

CHANGELOG.md
src/plugins/gui/providers/simplexProvider.ts

none
---
- https://app.asana.com/0/0/1207328129024979

Add Simplex euid value to quoting requests

---

src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/components/themed/TransactionListTop.tsx

none
---
- https://app.asana.com/0/0/1207318440457587

Add sync circle to crypto icon in TransactionListTop

---

CHANGELOG.md
src/__tests__/components/ui4/BlogCards.test.tsx
src/components/ui4/BlogCards.tsx
src/components/ui4/PromoCardsUi4.tsx
src/components/ui4/scenes/HomeSceneUi4.tsx

https://github.com/EdgeApp/edge-info-server/pull/121
---
- https://app.asana.com/0/0/1207153989175776

GUI: Geo-Filtered Blog Posts

---

CHANGELOG.md
src/components/scenes/Fio/FioDomainRegisterSelectWalletScene.tsx
src/util/FioAddressUtils.ts

Response no longer includes additional currency amounts and addresses. To be reevaluated when the FIO registration system switches away from Coinbase in the near future
---
- https://app.asana.com/0/0/1207383029886872

Revert fa3cd553a1747484adfa688d19b333aff0fc6c96

---

src/components/scenes/GettingStartedScene.tsx
src/theme/edgeConfig.ts
src/theme/testConfig.ts

none
---
- https://app.asana.com/0/0/1207407575219428

Small fixes

---

src/envConfig.ts
src/util/corePlugins.ts

none
---
- https://app.asana.com/0/0/1207416818156613

Add ZKSYNC_INIT

---

ios/edge.xcodeproj/project.pbxproj

This accidentally got lost in 4eae49e9b79e38e0834ecbab092d02027685f558.
none
---
- https://app.asana.com/0/0/1207446295106803

Add back missing iPad support

---

CHANGELOG.md
src/plugins/gui/providers/kadoProvider.ts

none
---
- https://app.asana.com/0/0/1207409592447621

Remove Florida from Kado support

---

CHANGELOG.md
ios/Podfile.lock
react-native.config.js
src/util/corePlugins.ts

none
---
- https://app.asana.com/0/0/1207448473220913

iOS - Disable Piratechain

---

src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json

none
---
- https://app.asana.com/0/0/1207455229830109

Remove florida from ach plugins

---

CHANGELOG.md
src/components/ui4/PromoCardsUi4.tsx

Pending info server fix and final spec/requirement refinements
none
---
- https://app.asana.com/0/0/1207295020388870

Temporarily disable promo card promoId filter

---

src/constants/WalletAndCurrencyConstants.ts
src/util/corePlugins.ts

---
- https://app.asana.com/0/0/1207457481301092

Pause iOS Piratechain wallets

---

CHANGELOG.md
src/components/scenes/GuiPluginListScene.tsx

none
---
- https://app.asana.com/0/0/1207150393925287

Delay the reset of the forced asset in GuiPluginListScene

---

CHANGELOG.md
src/plugins/stake-plugins/uniswapV2/policies/VelodromeV2StakePolicy.ts
src/plugins/stake-plugins/uniswapV2/policies/cemeteryPolicy.ts
src/plugins/stake-plugins/uniswapV2/policies/masonryPolicy.ts

none
---
- https://app.asana.com/0/0/1207489348498661

Reduce severity of insufficient balance to warning for Velodrome

---

src/constants/plugins/sellPluginList.json

none
---
- https://app.asana.com/0/0/1207457483167456

Remove FL from ach sell

---

src/constants/plugins/sellPluginList.json

Was accidentally disabled when trying to disable ACH
none
---
- https://app.asana.com/0/0/1207489060177502

Re-enable FL for sell to debit

---

src/components/scenes/SwapCreateScene.tsx

none
---
- https://app.asana.com/0/0/1207458923735120
- https://app.asana.com/0/0/1207497441419130

Fix error tracking

---

ios/Podfile.lock
package.json
src/components/common/SceneWrapper.tsx
yarn.lock

none
---
- https://app.asana.com/0/0/1207483368367849

Add hack to work around keyboard height bug during scene transitions

---

src/constants/plugins/sellPluginList.json

none
---
- https://app.asana.com/0/0/1207507911861926

Fix sell to debit to restrict only NY, HI

---

android/app/src/main/AndroidManifest.xml
patches/rn-id-blurview+1.2.1.patch

none
---
- https://app.asana.com/0/0/1207507679305842

Clear a blurview warning

---

src/components/scenes/LoginScene.tsx

Add missing change from #5070

---

src/components/scenes/GuiPluginListScene.tsx

none
---
- https://app.asana.com/0/0/1207518222773680

Fix flipped logic of country list modal blocking

---

src/constants/WalletAndCurrencyConstants.ts
src/envConfig.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/corePlugins.ts

none
---
- https://app.asana.com/0/0/1202824923939272

Add mumbai

---

CHANGELOG.md
src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/actions/DeviceSettingsActions.ts
src/actions/LocalSettingsActions.ts
src/actions/LoginActions.tsx
src/components/notification/NotificationView.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json
src/types/types.ts

none
---
- https://app.asana.com/0/0/1206859452306575

2FA/IP Validation Notification Card

---

CHANGELOG.md
src/components/notification/NotificationCard.tsx
src/components/notification/NotificationView.tsx
src/components/scenes/GuiPluginListScene.tsx
src/components/themed/TransactionListTop.tsx
src/components/ui4/IconButton.tsx
src/hooks/useAsyncNavigation.tsx
src/plugins/gui/fiatPlugin.tsx
src/theme/edgeConfig.ts
src/theme/testConfig.ts
src/types/types.ts

- Implement useAsyncNavigation
- Debounce notification cards
- Re-implement fix for debounced buy/sell/swapc tx list buttons
none
---
- https://app.asana.com/0/0/1207516764960120

Debounce buttons (cont)

---

CHANGELOG.md
src/components/notification/NotificationCard.tsx
src/components/notification/NotificationView.tsx
src/types/types.ts

none
---
- https://app.asana.com/0/0/1207393169205308

Re-Enable Light Account Backup Notification

---

patches/react-native-reanimated+3.12.0.patch

https://github.com/software-mansion/react-native-reanimated/issues/6119
none
---
- https://app.asana.com/0/0/1207485024420900

Fix `useDerivedValue` color glitches on iOS

---

CHANGELOG.md
src/__tests__/modals/__snapshots__/CountryListModal.test.tsx.snap
src/components/modals/CountryListModal.tsx

https://github.com/EdgeApp/edge-react-gui/assets/90650827/a053a104-31df-40f7-9578-ccde80c4c61d
none
---
- https://app.asana.com/0/0/1207556015394327

Fix CountryListModal Animation Stutter

---

CHANGELOG.md
src/__tests__/scenes/SwapConfirmationScene.test.tsx
src/components/scenes/SwapConfirmationScene.tsx

none
---
- https://app.asana.com/0/0/1207519749626404

Prefer DEX over CEX if rate is better

---

src/components/modals/WalletListMenuModal.tsx

none
---
- https://app.asana.com/0/0/1207563341311610

Fix duplicated "Split" wallet menu options

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1207435386673386

Fix Algorand WalletConnect reference

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

Also need to disable activation flow for EOS (similar to WAX)
---
- https://app.asana.com/0/0/1207438419460736

Enable keysOnlyMode for Telos

---

CHANGELOG.md
ios/Podfile
ios/edge.xcodeproj/project.pbxproj

none
---
- https://app.asana.com/0/0/1207533988179233

Increase ios minimum to 15.6

---

src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/SwapConfirmationScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SwapCreateScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/components/notification/NotificationView.tsx

none
---
- https://app.asana.com/0/0/1207615894294444

Flip the IP validation notification visibility condition

---

src/components/common/SceneWrapper.tsx
src/components/scenes/SwapCreateScene.tsx

none
---
- https://app.asana.com/0/0/1207510119361424

Forcefully close the keyboard before navigation to fix floating-nav bug

---

patches/react-native-reanimated+3.13.0-rc.2.patch

See https://github.com/software-mansion/react-native-reanimated/pull/6153 for details.
none
---
- https://app.asana.com/0/0/1207602355396701

Fix color interpolation not to crash

---

CHANGELOG.md
src/plugins/gui/providers/banxaProvider.ts

none
---
- https://app.asana.com/0/0/1207606246115520

Remove unused cleaner params that were removed from api

---

src/components/modals/SurveyModal.tsx

none
---
- https://app.asana.com/0/0/1207635550315591

Include the header in the scrolling area

---

CHANGELOG.md
package.json
src/__tests__/intl.test.ts
src/actions/RecoveryReminderActions.tsx
src/components/ui4/BalanceCardUi4.tsx
src/locales/intl.ts
src/util/utils.ts
yarn.lock

Use strings for the full path of total balance calculation
none
---
- https://app.asana.com/0/0/1207641525998409

Hopefully fix negative balance

---

CHANGELOG.md
android/app/src/debug/AndroidManifest.xml
android/app/src/main/AndroidManifest.xml
ios/edge/Info.plist

none
---
- https://app.asana.com/0/0/1207330698069842

Universal + App Link Support

---

src/__tests__/scenes/RequestScene.test.tsx
src/__tests__/scenes/__snapshots__/RequestScene.test.tsx.snap
src/components/scenes/Fio/FioRequestConfirmationScene.tsx
src/components/scenes/RequestScene.tsx
src/components/themed/FioRequestRow.tsx
src/types/routerTypes.tsx
src/types/types.ts

This cleans up the request scene and it's related Fio request confirmation scene.
none
---
- https://app.asana.com/0/0/1207622990313290

Request scene cleanup

---

src/components/common/EdgeAnim.tsx
src/components/data/row/CoinRankRow.tsx

---
- https://app.asana.com/0/0/1207699012295326

Limit EdgeAnim rerenders

---

src/__tests__/components/__snapshots__/WalletListSortableRow.test.tsx.snap
src/__tests__/scenes/__snapshots__/CurrencySettings.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/EdgeLoginScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SwapConfirmationScene.test.tsx.snap
src/components/cards/AssetStatusCard.tsx
src/components/cards/WarningCard.tsx
src/components/modals/RadioListModal.tsx
src/components/navigation/BackButton.tsx
src/components/scenes/Loans/LoanDashboardScene.tsx
src/components/scenes/SettingsScene.tsx
src/components/settings/SettingsRadioRow.tsx
src/components/themed/Alert.tsx
src/components/themed/WalletListHeader.tsx
src/components/themed/WalletListSortableRow.tsx
src/components/ui4/AlertCardUi4.tsx

---
- https://app.asana.com/0/0/1207692341555279

Restore missing IonIcons

---

CHANGELOG.md
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/co/edgesecure/app/MainApplication.kt
ios/edge/AppDelegate.mm
src/components/scenes/DevTestScene.tsx

none
---
- https://app.asana.com/0/0/1207729435310838

Disable Sentry automatic breadcrumbs

---

src/components/services/AccountCallbackManager.tsx

---
- https://app.asana.com/0/0/1207729435310843

Don't initiate exchange rates update on balanceMap changes

---

src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/components/services/Services.tsx
src/components/themed/TransactionListTop.tsx
src/plugins/stake-plugins/currency/tronStakePlugin.ts
src/plugins/stake-plugins/stakePlugins.ts
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts
src/plugins/stake-plugins/uniswapV2/uniV2Plugin.ts

---
- https://app.asana.com/0/0/1207721925742885

Load stake plugins as needed

---

src/util/utils.ts

none
---
- https://app.asana.com/0/0/1207722186783709

Fix receive scene NaN crash

---

src/__tests__/scenes/__snapshots__/FioAddressDetailsScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/FioAddressListScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/FioDomainRegisterScene.test.tsx.snap
src/components/scenes/Fio/FioAddressDetailsScene.tsx
src/components/scenes/Fio/FioAddressListScene.tsx
src/components/scenes/Fio/FioDomainRegisterScene.tsx
src/components/scenes/Fio/FioDomainRegisterSelectWalletScene.tsx
src/components/themed/ThemedButtons.tsx

---
- https://app.asana.com/0/0/1207729439812656

Fix missing Ion icons in survey modal and FIO names scenes

---

CHANGELOG.md
src/components/scenes/SwapConfirmationScene.tsx
src/components/themed/ExchangeQuoteComponent.tsx
src/envConfig.ts
src/util/corePlugins.ts

none
---
- https://app.asana.com/0/0/1207262641546820

Add 0xgasless plugin

---

src/actions/LoginActions.tsx

none
---
- https://app.asana.com/0/0/1207758998059491

Match the navigation method between new and existing accounts

---

CHANGELOG.md
src/__tests__/components/__snapshots__/BalanceCard.test.tsx.snap
src/components/ui4/BalanceCardUi4.tsx

none
---
- https://app.asana.com/0/0/1207740902961769

Remove spinner from balance card

---

src/actions/LoginActions.tsx

none
---
- https://app.asana.com/0/0/1207759658118461

Omit the survey modal from the first login

---

src/actions/SettingsActions.tsx
src/components/Main.tsx
src/components/scenes/CoinRankingScene.tsx
src/components/scenes/SettingsScene.tsx
src/components/scenes/SwapCreateScene.tsx

none
---
- https://app.asana.com/0/0/1207780186591855

Tiny fixes

---

CHANGELOG.md
src/actions/CreateWalletActions.tsx
src/actions/SettingsActions.tsx
src/actions/WalletListMenuActions.tsx
src/components/modals/BackupModal.tsx
src/components/scenes/DefaultFiatSettingScene.tsx
src/components/scenes/Fio/FioAddressDetailsScene.tsx
src/components/scenes/Fio/FioAddressRegisterSelectWalletScene.tsx
src/components/scenes/SendScene2.tsx
src/components/scenes/SpendingLimitsScene.tsx
src/components/services/EdgeCoreManager.tsx
src/plugins/gui/scenes/RewardsCardDashboardScene.tsx

none
---
- https://app.asana.com/0/0/1207761072563617

Replace native alerts with showToast and ButtonsModal

---

CHANGELOG.md
src/components/ui4/CryptoIconUi4.tsx
src/constants/WalletAndCurrencyConstants.ts
src/util/CdnUris.ts

none
---
- https://app.asana.com/0/0/1207749580046222

Use common chain icon for Ethereum L2s

---

CHANGELOG.md
src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/actions/FioActions.tsx
src/actions/LoginActions.tsx
src/actions/WalletActions.tsx
src/components/services/AccountCallbackManager.tsx
src/components/services/FioService.ts
src/components/services/Services.tsx
src/reducers/FioReducer.ts
src/selectors/WalletSelectors.ts
src/types/reduxActions.ts
src/util/FioAddressUtils.ts

none
---
- https://app.asana.com/0/0/1207692345505863

Create `FioServices` 

---

src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/components/common/SceneWrapper.tsx
src/components/themed/SideMenu.tsx
src/reducers/CoreReducer.ts

none
---
- https://app.asana.com/0/0/1207787615031264

Fix delete-account navigation

---

CHANGELOG.md
src/plugins/gui/providers/banxaProvider.ts
src/plugins/gui/providers/moonpayProvider.ts

none
---
- https://app.asana.com/0/0/1207162856822149

Add Solana on Banxa and Moonpay

---

CHANGELOG.md
src/components/modals/InsufficientFeesModal.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

Same rules as SendScene where it applies to
currencies whose mainnet currency is ETH but the
network is not Ethereum
none
---
- https://app.asana.com/0/0/1207613579517093

Update InsufficientFeesModal message

---

src/components/modals/AccelerateTxModal.tsx

none
---
- https://app.asana.com/0/0/1207847529652617

Fix broken fiat amounts in AccelerateTxModel

---

src/actions/CategoriesActions.ts
src/components/services/ContactsLoader.ts

none
---
- https://app.asana.com/0/0/1207849256427174

Add 0xgasless swaps to CategoriesActions and ContactsLoader

---

CHANGELOG.md
src/components/scenes/Staking/StakeModifyScene.tsx
src/plugins/abi/VELODROME_V2_VOTER.json
src/plugins/stake-plugins/uniswapV2/policies/VelodromeV2StakePolicy.ts

none
---
- https://app.asana.com/0/0/1207835911007499
- https://app.asana.com/0/0/1207808002877104

Velodrome staking fixes

---

src/actions/CategoriesActions.ts

---
- https://app.asana.com/0/0/1207868266698627

Add Rango icon path

---

CHANGELOG.md
src/components/layout/CurrencyView.tsx

none
---
- https://app.asana.com/0/0/1207749579877494

Add network name to wallet list cards

---

CHANGELOG.md
src/plugins/stake-plugins/generic/pluginInfo/filecoinCalibrationGlifpool.ts
src/plugins/stake-plugins/generic/pluginInfo/filecoinGlifpool.ts
src/plugins/stake-plugins/generic/policyAdapters/CoreumStakeKitAdaptor.ts
src/plugins/stake-plugins/generic/policyAdapters/GlifInfinityPoolAdapter.ts
src/plugins/stake-plugins/generic/util/stakeKitUtils.ts

https://github.com/EdgeApp/edge-info-server/pull/124
---
- https://app.asana.com/0/0/1207721444734377

Use info server rollup for GLif and Coreum StakeKit pools

---

src/__tests__/modals/AddressModal.test.tsx
src/__tests__/modals/PasswordReminderModal.test.tsx
src/components/FioAddress/DomainListModal.tsx
src/components/FioAddress/FioActionSubmit.tsx
src/components/modals/AccelerateTxModal.tsx
src/components/modals/AddressModal.tsx
src/components/modals/PasswordReminderModal.tsx
src/components/services/NetworkActivity.ts

This ports a bunch of connectors to hooks.
none
---
- https://app.asana.com/0/0/1207860741273221

Reduce Connectors

---

src/components/layout/CurrencyView.tsx

Show for any token or ETH mainnet currencies on non-ethereum networks.
none
---
- https://app.asana.com/0/0/1207879128931495

Change conditions for the visibility of a network bubble

---

src/components/scenes/GettingStartedScene.tsx

EdgeAnim is incompatible with the Section implementation somehow. 
none
---
- https://app.asana.com/0/0/1207898557159070

Fix the first swipe on the USPs

---

src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/actions/DeepLinkingActions.ts
src/actions/LoginActions.tsx
src/components/scenes/LoginScene.tsx
src/components/themed/SideMenu.tsx
src/reducers/RootReducer.ts
src/types/reduxActions.ts
src/util/fake/fakeRootState.ts

none
---
- https://app.asana.com/0/0/1207687355742784

Handle recovery links as route params

---

CHANGELOG.md
src/__tests__/__snapshots__/GuiPlugins.test.ts.snap
src/constants/plugins/GuiPlugins.ts
src/constants/plugins/buyPluginList.json
src/plugins/gui/fiatPluginTypes.ts
src/plugins/gui/providers/kadoProvider.ts

none
---
- https://app.asana.com/0/0/1207917267339203

Add Kado buy via wire transfer

---

CHANGELOG.md
src/components/notification/NotificationView.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1207946127272903

Change backup notification copy

---

CHANGELOG.md
src/components/notification/NotificationView.tsx

none
---
- https://app.asana.com/0/0/1207945490511096

Hide IP validation notification for light accounts

---

CHANGELOG.md
src/plugins/gui/fiatPlugin.tsx
src/plugins/gui/fiatPluginTypes.ts
src/plugins/gui/providers/bityProvider.ts
src/plugins/gui/scenes/AddressFormScene.tsx
src/plugins/gui/scenes/SepaFormScene.tsx

none
---
- https://app.asana.com/0/0/1206500978761526
- https://app.asana.com/0/0/1207807100473757

Misc Bity fixes

---

CHANGELOG.md
src/components/common/SectionHeader.tsx

none
---
- https://app.asana.com/0/0/1207960096146908

Fix SectionHeader on Android (Wallet List Add/Sort)

---

src/components/scenes/SweepPrivateKeyCalculateFeeScene.tsx

---
- https://app.asana.com/0/0/1207954989521497

Fix slider handling in sweep private key calculate fee scene

---

CHANGELOG.md
src/actions/ExchangeRateActions.ts

none
---
- https://app.asana.com/0/0/1207863694812196

Add 5 minute rate cache

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1207611176038990

Disable max spend for zkSync

---

src/components/scenes/SweepPrivateKeyCalculateFeeScene.tsx

---
- https://app.asana.com/0/0/1207957295481158

Update flatList when exchange rates update

---

CHANGELOG.md
scripts/deploy.ts

none
---
- https://app.asana.com/0/0/1207969087236113

Add zealot upload to deploy script

---

CHANGELOG.md
ios/Podfile.lock
package.json
src/components/scenes/TransactionListScene.tsx
src/hooks/useTransactionList.ts
yarn.lock

https://github.com/EdgeApp/edge-core-js/pull/611
---
- https://app.asana.com/0/0/1207983177888552

Core spam filter

---

src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/reducers/CoreReducer.ts

none
---
- https://app.asana.com/0/0/1207963247742448

Show a blank username when logged out

---

CHANGELOG.md
src/components/scenes/TransactionListScene.tsx
src/components/scenes/WalletListScene.tsx

none
---
- https://app.asana.com/0/0/1207604270480124

Remove pull down to refresh

---

CHANGELOG.md
src/actions/PaymentProtoActions.tsx
src/components/scenes/Fio/FioAddressRegisterSelectWalletScene.tsx
src/components/scenes/Fio/FioDomainRegisterSelectWalletScene.tsx
src/components/tiles/AddressTile2.tsx
src/constants/WalletAndCurrencyConstants.ts
src/controllers/edgeProvider/EdgeProviderServer.tsx
src/plugins/gui/providers/ioniaProvider.ts
src/util/FioAddressUtils.ts

none
---
- https://app.asana.com/0/0/1207426648754856

Switch to Bitpay payments for FIO names and domains

---

CHANGELOG.md
scripts/deploy.ts

none
---
- https://app.asana.com/0/0/1208057678750035

Add more zealot metadata

---

CHANGELOG.md
src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/gui/providers/bityProvider.ts

none
---
- https://app.asana.com/0/0/1208077257562665

Fix bity message signing

---

CHANGELOG.md
src/components/navigation/SideMenuButton.tsx

none
---
- https://app.asana.com/0/0/1207994364310639

Always dismiss the keyboard when opening the SideMenu

---

CHANGELOG.md
src/components/scenes/Fio/FioStakingChangeScene.tsx
src/components/scenes/Fio/FioStakingOverviewScene.tsx
src/constants/WalletAndCurrencyConstants.ts
src/types/routerTypes.tsx

Does NOT include fix for display issues after resync
none
---
- https://app.asana.com/0/0/1206787288256812

Fix FIO Stake/Unstake tx display

---

CHANGELOG.md
scripts/deploy.ts

none
---
- https://app.asana.com/0/0/1208097046069443

Properly add newlines in zealot changelog

---

CHANGELOG.md
src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json

No providers can support at this time
none
---
- https://app.asana.com/0/0/1208079639918182

Disable fasterpayments

---

CHANGELOG.md
src/components/common/EdgeCarousel.tsx

none
---
- https://app.asana.com/0/0/1208171921634845

Fix iOS not showing `Carousel` cards on first render if there's only one card in the `Carousel`

---

src/plugins/stake-plugins/generic/policyAdapters/CardanoKilnAdaptor.ts
src/plugins/stake-plugins/generic/util/kilnUtils.ts

none
---
- https://app.asana.com/0/0/1208229808315320

Disable staking when ADA is staked in any of the KILN pools

---

src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/stake-plugins/generic/policyAdapters/CardanoKilnAdaptor.ts

none
---
- https://app.asana.com/0/0/1208229808315339

Fix cardano staking 3

---

src/components/cards/StakingOptionCard.tsx
src/components/scenes/Staking/StakeOptionsScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1208229808315256

Add APR estimate text to StakingOptionCard on StakingOptionsScene

---

CHANGELOG.md
src/components/modals/SurveyModal.tsx

none
---
- https://app.asana.com/0/0/1208249605282401

Add Free Talk Live option to survey modal

---

CHANGELOG.md
src/actions/LogActions.tsx

none
---
- https://app.asana.com/0/0/1208056566426967

Add customTokens to WalletData in the log output

---

CHANGELOG.md
src/components/scenes/HomeScene.tsx

- Update filterContentPosts function to accept nullish input
- Add explicit return type for filterContentPosts
- Simplify usage of filterContentPosts in HomeScene component
- Improve null handling for infoServerData.rollup properties
none
---
- https://app.asana.com/0/0/1208288363210698

Fix crash from filterContentPosts nullish input and improve type safety

---

CHANGELOG.md
src/components/scenes/HomeScene.tsx

- Update filterContentPosts function to accept nullish input
- Add explicit return type for filterContentPosts
- Simplify usage of filterContentPosts in HomeScene component
- Improve null handling for infoServerData.rollup properties
none
---
- https://app.asana.com/0/0/1208288363210698

Followup: Fix crash from filterContentPosts nullish input and improve type safety

---

src/plugins/stake-plugins/generic/policyAdapters/CardanoKilnAdaptor.ts

none
---
- https://app.asana.com/0/0/1208296923323673

Change Cardano's minimum staking amount to 5 ADA

---

src/plugins/stake-plugins/generic/pluginInfo/filecoinGlifpool.ts

none
---
- https://app.asana.com/0/0/1208285420971625

Fix GLIF Infinity Pool staking

---

src/plugins/stake-plugins/generic/policyAdapters/GlifInfinityPoolAdapter.ts
src/plugins/stake-plugins/generic/policyAdapters/TarotPoolAdaptor.ts
src/plugins/stake-plugins/generic/util/EdgeWalletSigner.ts

Follup to PR: https://github.com/EdgeApp/edge-react-gui/pull/5245
none

Process metadata as its own entry in customData for EdgeWalletSigner

---

src/plugins/stake-plugins/generic/pluginInfo.ts

---
- https://app.asana.com/0/0/1208313389088308

Disable Kiln pools

---

CHANGELOG.md
src/components/navigation/FlashNotification.tsx
src/components/services/DeepLinkingManager.tsx

none
---
- https://app.asana.com/0/0/1208040714093837

Handle foreground push notifications

---

CHANGELOG.md
src/util/tracking.ts
src/util/utils.ts

none
---
- https://app.asana.com/0/0/1208200104527033

Add new tracking param: `accountAgeMonths`

---

CHANGELOG.md
src/components/rows/SwapProviderRow.tsx
src/components/themed/ExchangeQuoteComponent.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1208231167011433
- https://app.asana.com/0/0/1208162689994842

Add minimum receive amount to SwapConfirmationScene

---

CHANGELOG.md
src/components/modals/SurveyModal.tsx

none
---
- https://app.asana.com/0/0/1208299498601862

Add Cris Cyborg to SurveyModal

---

CHANGELOG.md
src/components/modals/WalletListModal.tsx
src/components/scenes/SwapCreateScene.tsx

none
---
- https://app.asana.com/0/0/1208286489879867

Add onSelectWallet to the fiatPlugin

---

src/components/themed/TransactionListTop.tsx

none
---
- https://app.asana.com/0/0/1207816000157564

Change trade menu order

---

CHANGELOG.md
src/__tests__/__snapshots__/GuiPlugins.test.ts.snap
src/constants/plugins/buyPluginList.json

Update Apple Pay branding

---

src/components/scenes/SwapCreateScene.tsx

none
---
- https://app.asana.com/0/0/1208381747052354

Fix clearing asset type swap errors

---

CHANGELOG.md
src/plugins/gui/providers/kadoProvider.ts

none
---
- https://app.asana.com/0/0/1208364027056323

Kado fixes

---

CHANGELOG.md
src/actions/CategoriesActions.ts

edge-rjqa2: ETH - My Arbitrum
none
---
- https://app.asana.com/0/0/1208366357239280

Correctly tag `tokenApproval` `actionType` in  `getTxActionDisplayInfo`

---

src/constants/plugins/buyPluginList.json

none
---
- https://app.asana.com/0/0/1208356725382607

Change US State for wire xfer

---

CHANGELOG.md
ios/Podfile.lock
patches/react-native-piratechain+0.5.1.patch
react-native.config.js
src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1207982832446869

Re-enable Piratechain on iOS

---

CHANGELOG.md
src/plugins/stake-plugins/generic/pluginInfo.ts

none
---
- https://app.asana.com/0/0/1208401387533235

Enable Cardano staking

---

CHANGELOG.md
src/components/services/DeepLinkingManager.tsx

none
---
- https://app.asana.com/0/0/1208440290442324

Add title handling to foreground push message UI

---

CHANGELOG.md
src/plugins/gui/fiatPlugin.tsx
src/plugins/gui/fiatPluginTypes.ts
src/plugins/gui/scenes/AddressFormScene.tsx
src/plugins/gui/scenes/InfoDisplayScene.tsx
src/plugins/gui/scenes/SepaFormScene.tsx
src/types/routerTypes.tsx

Redo of https://github.com/EdgeApp/edge-react-gui/pull/5287
none

Sam/sepa info done button overlap redo PR

---

src/plugins/gui/providers/moonpayProvider.ts

---
- https://app.asana.com/0/0/1208497129426346

Moonpay: Handle EVM burn address for native currencies

---

src/plugins/gui/providers/paybisProvider.ts
src/plugins/gui/providers/simplexProvider.ts

---
- https://app.asana.com/0/0/1208439738385362

Fix POL codes with Simplex and Paybis

---

CHANGELOG.md
src/actions/SettingsActions.tsx

none
---
- https://app.asana.com/0/0/1207767212901870

Navigate to wallet list after restoring wallets

---

src/components/scenes/Fio/FioCreateHandleScene.tsx
src/components/tiles/AddressTile2.tsx
src/plugins/gui/pluginUtils.ts
src/plugins/gui/providers/banxaProvider.ts
src/plugins/gui/providers/bityProvider.ts
src/plugins/gui/providers/kadoProvider.ts
src/plugins/gui/providers/moonpayProvider.ts
src/plugins/gui/providers/mtpelerinProvider.ts
src/plugins/gui/providers/paybisProvider.ts

---
- https://app.asana.com/0/0/1208105233891024

Small error handling fixes

---

CHANGELOG.md
src/plugins/stake-plugins/generic/pluginInfo.ts
src/plugins/stake-plugins/generic/pluginInfo/ethereumKilnPool.ts

none
---
- https://app.asana.com/0/0/1208462758417742

Enable Ethereum mainnet staking

---

CHANGELOG.md
src/actions/LogActions.tsx

none
---
- https://app.asana.com/0/0/1208401503487094

Add wallet creation date to log output

---

CHANGELOG.md
src/hooks/useTransactionList.ts

none
---
- https://app.asana.com/0/0/1208296004541894

Prevent exchange rate fluctuations from restarting transaction list stream

---

CHANGELOG.md
src/actions/LoginActions.tsx
src/actions/WalletListMenuActions.tsx
src/components/scenes/CreateWalletSelectCryptoScene.tsx

none
---
- https://app.asana.com/0/0/1207499791232301

Remove legacy non-segwit wallets from new account wallet selection scene

---

CHANGELOG.md
src/__tests__/components/__snapshots__/MenuTabs.test.tsx.snap
src/__tests__/modals/__snapshots__/CategoryModal.test.tsx.snap
src/__tests__/modals/__snapshots__/CountryListModal.test.tsx.snap
src/__tests__/modals/__snapshots__/HelpModal.test.tsx.snap
src/__tests__/modals/__snapshots__/LogsModal.test.tsx.snap
src/__tests__/modals/__snapshots__/TextInputModal.test.tsx.snap
src/__tests__/modals/__snapshots__/WalletListModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/SendScene2.ui.test.tsx.snap
src/__tests__/scenes/__snapshots__/SwapConfirmationScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SwapCreateScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SwapSuccessScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/components/common/BlurBackground.tsx
src/components/notification/NotificationCard.tsx
src/components/notification/NotificationView.tsx
src/theme/variables/edgeDark.ts
src/theme/variables/edgeLight.ts
src/theme/variables/testDark.ts
src/theme/variables/testLight.ts
src/types/Theme.ts

none
---
- https://app.asana.com/0/0/1207030814000439

Update `NotificationCard` to UI4 styling

---

CHANGELOG.md
src/components/scenes/GuiPluginListScene.tsx

none
---
- https://app.asana.com/0/0/1208354081062675

Fix undefined wallet access in `GuiPluginListScene`

---

CHANGELOG.md
src/constants/plugins/sellPluginList.json

none
---
- https://app.asana.com/0/0/1208544789913785

Disable Florida ACH sell

---

CHANGELOG.md
src/components/scenes/SpendingLimitsScene.tsx

none
---
- https://app.asana.com/0/0/1208524802495873

Allow 0 amount entry in `SpendingLimitsScene`

---

src/components/scenes/WalletRestoreScene.tsx

none
---
- https://app.asana.com/0/0/1208577919961355

Fix `WalletRestoreScene` `handlePressDone`

---

CHANGELOG.md
src/components/scenes/HomeScene.tsx
src/components/themed/WalletListSwipeable.tsx
src/components/themed/WalletListSwipeableCurrencyRow.tsx

none
---
- https://app.asana.com/0/0/1208602021372192

Only access `countryCode` from `getFirstOpenInfo()`

---

src/app.ts

none
---
- https://app.asana.com/0/0/1208628337942754

Remove console logs from Sentry breadcrumbs

---

CHANGELOG.md
src/plugins/stake-plugins/generic/policyAdapters/EthereumKilnAdaptor.ts

Add explicit gas limit for Kiln staking

---

src/components/modals/InsufficientFeesModal.tsx
src/components/scenes/GuiPluginListScene.tsx
src/components/scenes/Staking/StakeOverviewScene.tsx
src/components/scenes/TransactionListScene.tsx
src/components/themed/BuyCrypto.tsx
src/util/ukComplianceUtils.ts

none
---
- https://app.asana.com/0/0/1208638841968962
- https://app.asana.com/0/0/1208626301816227

Additional UK Compliance, Fix `InsufficientFeesModal` Crash

---

src/plugins/stake-plugins/generic/policyAdapters/EthereumKilnAdaptor.ts

none
---
- https://app.asana.com/0/0/1208642530820111

Add metadata to Kiln transactions

---

CHANGELOG.md
src/components/modals/SurveyModal.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1208710003625114

Add BTCTKVR Magazine option to post-install survey

---

CHANGELOG.md
src/components/scenes/TransactionsExportScene.tsx

none
---
- https://app.asana.com/0/0/1208707070209460

Android - allow multiple files export

---

CHANGELOG.md
package.json
src/app.ts
src/components/modals/AddressModal.tsx
src/constants/WalletAndCurrencyConstants.ts
src/envConfig.ts
yarn.lock

none
---
- https://app.asana.com/0/0/1208623680992506

Update Unstoppable domains support

---

CHANGELOG.md
src/actions/DeepLinkingActions.tsx

none
---
- https://app.asana.com/0/0/1208635507463521

Fix currencyWallets reference in create wallet paths

---

CHANGELOG.md
ios/Podfile.lock
jestSetup.js
src/__tests__/modals/__snapshots__/HelpModal.test.tsx.snap
src/components/modals/EdgeModal.tsx
src/components/modals/SurveyModal.tsx

none
---
- https://app.asana.com/0/0/1207341997973038

Re-enable modal close buttons for desktop

---

ios/Podfile.lock
package.json
src/actions/CategoriesActions.ts
src/envConfig.ts
src/util/corePlugins.ts
yarn.lock

https://github.com/EdgeApp/edge-info-server/pull/139
https://github.com/EdgeApp/edge-exchange-plugins/pull/349
---
- https://app.asana.com/0/0/1208308287641370

Rename Thorchain DEX Aggregator to SwapKit

---

CHANGELOG.md
src/components/scenes/SwapConfirmationScene.tsx
src/util/tracking.ts

none
---
- https://app.asana.com/0/0/1208711876005734

Add `isBuiltinAsset` to `Exchange_Shift_Success`

---

src/envConfig.ts

none
---
- https://app.asana.com/0/0/1208828332101210

Add SideShift private key to env config

---

CHANGELOG.md
src/components/modals/SurveyModal.tsx

none
---
- https://app.asana.com/0/0/1208791093549062

Use info server for some survey options

---

CHANGELOG.md
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/selectors/getCreateWalletList.ts

none
---
- https://app.asana.com/0/0/1208888687906399

Filter CreateWalletItem list by networkLocation instead of tokenId

---

src/envConfig.ts

https://github.com/EdgeApp/edge-currency-accountbased/pull/859
---
- https://app.asana.com/0/0/1208890120090151

Add Helius to Solana env config

---

src/__tests__/__snapshots__/GuiPlugins.test.ts.snap
src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json

none
---
- https://app.asana.com/0/0/1208889051351714

Sort Venmo plugin above Paypal

---

CHANGELOG.md
package.json
src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/stake-plugins/generic/GenericStakePlugin.ts
src/plugins/stake-plugins/generic/pluginInfo/coreumNativeStaking.ts
src/plugins/stake-plugins/generic/policyAdapters/CoreumStakeKitAdaptor.ts
src/plugins/stake-plugins/generic/policyAdapters/types.ts
src/plugins/stake-plugins/generic/util/stakeKitUtils.ts
yarn.lock

none
---
- https://app.asana.com/0/0/1208958905936263

Check for Coreum validator status before getting staking quote

---

CHANGELOG.md
src/plugins/gui/providers/banxaProvider.ts

none
---
- https://app.asana.com/0/0/1206334009226449

Remove payment types for Banxa

---

src/components/themed/SearchFooter.tsx

Otherwise clear and cancel do exactly the same thing.
none
---
- https://app.asana.com/0/0/1208980515380893

Do not blur on clear of search bar.

---

src/components/themed/SearchFooter.tsx
src/components/themed/SimpleTextInput.tsx

none
---
- https://app.asana.com/0/0/1208980515380905

Do not exit search on scroll

---

CHANGELOG.md
src/components/scenes/CreateWalletImportScene.tsx

none
---
- https://app.asana.com/0/0/1208483942472148

Only send successful import items to import options and completion scenes

---

CHANGELOG.md
src/components/modals/ContactListModal.tsx
src/components/modals/ListModal.tsx
src/components/themed/FilledTextInput.tsx

none
---
- https://app.asana.com/0/0/1208994566212051

Autoselect payee field when focused

---

CHANGELOG.md
src/components/modals/WcSmartContractModal.tsx

none
---
- https://app.asana.com/0/0/1207454495618646

Fix WalletConnect eth_sendRawTransaction handling

---

CHANGELOG.md
src/actions/LoginActions.tsx

none
---
- https://app.asana.com/0/0/1208898501892435

Add 'numAccounts' to 'Signup_Complete' event

---

src/components/themed/FilledTextInput.tsx

none
---
- https://app.asana.com/0/0/1209011986785098

Fix android auto select text

---

src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.ts

It's not clear what the problem is, so it's not clear if this PR will fix anything. What it *will* do is dramatically improve performance, since we fetch far less data now.
none
---
- https://app.asana.com/0/0/1209000958628643

Simplify Thorchain savers fetching

---

CHANGELOG.md
src/components/modals/SwapVerifyTermsModal.tsx

none
---
- https://app.asana.com/0/0/1209000447242768

Show KYC warning modal when trading with Swapuz

---

src/actions/DeepLinkingActions.tsx
src/components/tiles/AddressTile2.tsx
src/util/utils.ts

none
---
- https://app.asana.com/0/0/1209080263604100

Add confirmation modal to scanned email

---

CHANGELOG.md
package.json
src/components/modals/SurveyModal.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/tracking.ts
yarn.lock

Avoiding too much refactoring because this is soon subject to change.
none
---
- https://app.asana.com/0/0/1209065058519199

Survey Modal 2.0

---

src/state/SceneScrollState.tsx

none
---
- https://app.asana.com/0/0/1208887349854070

Avoid re-rendering from useIsFocused

---

src/envConfig.ts
src/plugins/gui/providers/mtpelerinProvider.ts

none
---
- https://app.asana.com/0/0/1209197620849928

Add rfr param to mtpelerin

---

CHANGELOG.md
src/components/scenes/Staking/EarnScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1208741686424086

Add search to `EarnScene`

---

src/envConfig.ts
src/util/corePlugins.ts

none
---
- https://app.asana.com/0/0/1209239393469718

Add TON_INIT

---

CHANGELOG.md
src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.tsx

none
---
- https://app.asana.com/0/0/1209233498796802

Replace TC Savers quoting with an error modal

---

src/components/themed/TransactionListTop.tsx

none
---
- https://app.asana.com/0/0/1209408043124610

Fix missing locked FIO amounts

---

CHANGELOG.md
src/plugins/gui/providers/simplexProvider.ts

none
---
- https://app.asana.com/0/0/1209401183293090

Enable TRUMP and MELANIA purchases through Simplex

---

src/__tests__/components/__snapshots__/ExchangeQuoteComponent.test.tsx.snap
src/__tests__/components/__snapshots__/TransactionListTop.test.tsx.snap
src/__tests__/scenes/__snapshots__/SwapConfirmationScene.test.tsx.snap
src/components/icons/WalletIcon.tsx
src/components/layout/CurrencyView.tsx
src/components/rows/CurrencyRow.tsx
src/components/themed/TransactionListTop.tsx

Broken in https://github.com/EdgeApp/edge-react-gui/pull/5439
none
---
- https://app.asana.com/0/0/1209419042399689

Fix missing sync circle

---

src/actions/ExchangeRateActions.ts

The cached asset pair list wasn't being used before:
- On the first update, we wouldn't fetch from the server.
- On subsequent updates, we wouldn't read the cached asset list.
This commit keeps the asset pairs in memory, so we can keep using them each time we fetch from the server. It also moves some of the high-level logic up into `updateExchangeRates` redux action, so it's more obvious when various things take place.
none
---
- https://app.asana.com/0/0/1209448657423335

Actually use the cached asset pair list

---

src/__tests__/components/PromoCards.test.tsx
src/components/cards/InfoCardCarousel.tsx
src/components/scenes/GuiPluginListScene.tsx
src/util/infoUtils.ts

none
---
- https://app.asana.com/0/0/1209467964854249

Fix `InfoCardCarousel`

---

CHANGELOG.md
src/components/cards/MarketsCard.tsx
src/components/rows/CoinRankRow.tsx
src/components/scenes/CoinRankingDetailsScene.tsx
src/components/scenes/CoinRankingScene.tsx
src/components/scenes/WalletDetailsScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

- **Always use the supported fiat currency**
- **Add warning card for fallback currency**
- **Add EUR to COINGECKO_SUPPORTED_FIATS**
none
---
- https://app.asana.com/0/0/1209378289256103

Fix Coin Ranking Details scene

---

src/components/themed/FilledTextInput.tsx
src/components/themed/SimpleTextInput.tsx

none
---
- https://app.asana.com/0/0/1209491590168136

Use a SharedValue for internal value state

---

src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1209529563320258

Fix Abstract chain Id

---

CHANGELOG.md
src/actions/WalletListMenuActions.tsx
src/components/buttons/ModalButtons.tsx
src/components/modals/ButtonsModal.tsx
src/components/modals/DateModal.tsx
src/components/modals/EdgeModal.tsx
src/components/modals/TextInputModal.tsx
src/components/scenes/Fio/FioConnectWalletConfirmScene.tsx
src/components/scenes/Fio/FioRequestConfirmationScene.tsx
src/components/scenes/Fio/FioRequestListScene.tsx
src/components/services/Providers.tsx
src/plugins/gui/scenes/RewardsCardDashboardScene.tsx

none
---
- https://app.asana.com/0/0/1209540014038679

Sync modals with loginUi

---

CHANGELOG.md
src/__tests__/scenes/__snapshots__/ChangePasswordScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/ChangePinScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/FioAddressDetailsScene.test.tsx.snap
src/actions/DeepLinkingActions.tsx
src/actions/ScanActions.tsx
src/components/Main.tsx
src/components/scenes/GuiPluginListScene.tsx
src/plugins/gui/fiatPlugin.tsx
src/types/routerTypes.tsx
src/util/fake/fakeSceneProps.ts

none
---
- https://app.asana.com/0/0/1208644065408258
- https://app.asana.com/0/0/1209101588771630

Address Scene Navigation Props PR Comments

---

CHANGELOG.md
src/components/themed/QrCode.tsx

none
---
- https://app.asana.com/0/0/1208439791846009

Update icon styling on `QrCode`

---

CHANGELOG.md
src/util/FioAddressUtils.ts

none
---
- https://app.asana.com/0/0/1209672435244147
- https://app.asana.com/0/0/1209321700791831

Support FIO registrations without fioRegApiToken

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1209633260484539

Use Ethereum chain icon for bobevm plugin

---

src/__tests__/__snapshots__/GuiPlugins.test.ts.snap
src/constants/plugins/buyPluginList.json
src/constants/plugins/sellPluginList.json

---
- https://app.asana.com/0/0/1208750421902822

Remove IL from Paypal list and JM from Bitrefill

---

src/constants/plugins/sellPluginList.json

none
---
- https://app.asana.com/0/0/1209704587273482

Re-enable Bitrefill in Jamaica

---

CHANGELOG.md
src/__tests__/exchangeRates.test.ts
src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/actions/ExchangeRateActions.ts
src/hooks/useTokenDisplayData.ts
src/reducers/RootReducer.ts
src/types/reduxActions.ts
src/types/types.ts
src/util/fake/fakeRootState.ts

none
---
- https://app.asana.com/0/0/1209696532407295

Add exchangeRatesMap to redux for current and 24 hour rates

---

CHANGELOG.md
src/components/themed/TransactionListTop.tsx

none
---
- https://app.asana.com/0/0/1209728963813433

Fix FIO special casing around transaction list top Earn button

---

src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.tsx

none
---
- https://app.asana.com/0/0/1209735537950568

Fix binance smart chain earn button infinite spinning

---

CHANGELOG.md
src/actions/LocalSettingsActions.ts
src/actions/TokenTermsActions.tsx
src/components/services/NotificationService.ts

none
---
- https://app.asana.com/0/0/1209719855993891

Fix race condition where we could write defaults over local data on disk

---

CHANGELOG.md
src/components/scenes/TransactionDetailsScene.tsx

none
---
- https://app.asana.com/0/0/1209571139914150

Prevent acceleration for swap transactions

---

CHANGELOG.md
src/actions/WalletListMenuActions.tsx
src/components/modals/WalletListMenuModal.tsx

none
---
- https://app.asana.com/0/0/1209526374689890

Add "Asset Settings" to `WalletListMenuModal`

---

CHANGELOG.md
src/components/scenes/TransactionListScene.tsx

none
---
- https://app.asana.com/0/0/1209740780578250

Filter spam transaction on TransactionListScene

---

CHANGELOG.md
src/app.ts
src/components/charts/SwipeChart.tsx

none
---
- https://app.asana.com/0/0/1209591004150768

Handle network failures in `SwipeChart`

---

CHANGELOG.md
src/actions/DeepLinkingActions.tsx
src/components/modals/WalletListModal.tsx
src/types/DeepLinkTypes.ts
src/util/DeepLinkParser.ts

none
---
- https://app.asana.com/0/0/1209611358696314

Implent rewards deeplink handling

---

CHANGELOG.md
ios/Podfile.lock
package.json
src/constants/WalletAndCurrencyConstants.ts
src/envConfig.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/util/corePlugins.ts
yarn.lock

GUI: Add Sonic Support

---

CHANGELOG.md
src/components/modals/WalletListMenuModal.tsx
src/constants/WalletAndCurrencyConstants.ts
src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/gui/providers/bityProvider.ts
src/util/corePlugins.ts
src/util/fake/fakeRootState.ts

https://github.com/EdgeApp/edge-currency-plugins/pull/426
---
- https://app.asana.com/0/0/1208736884796470

Add Bitcoin Testnet4 plugin

---

CHANGELOG.md
src/components/scenes/SpendingLimitsScene.tsx

Also fix changelog
none
---
- https://app.asana.com/0/0/1208029655794180

Fix keyboard tapthrough on `SpendingLimitsScene`

---

src/__tests__/__snapshots__/GuiPlugins.test.ts.snap
src/constants/plugins/buyPluginList.json
src/locales/en_US.ts
src/locales/strings/enUS.json
src/plugins/gui/providers/kadoOtcProvider.ts
src/plugins/gui/scenes/EmailFormScene.tsx

none
---
- https://app.asana.com/0/0/1209103114511475

Fix OTC maximum limit

---

CHANGELOG.md
src/components/modals/WalletListMenuModal.tsx

none
---
- https://app.asana.com/0/0/1209909396016742

Conditionally show "Asset Settings" in `WalletListMenuModal`

---

CHANGELOG.md
src/components/notification/NotificationCenterCard.tsx

none
---
- https://app.asana.com/0/0/1209708484999530

Increase date spacing in `NotificationCenterCard`

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1210018491455096

Add monero multioutput support

---

CHANGELOG.md
src/plugins/gui/providers/moonpayProvider.ts

none
---
- https://app.asana.com/0/0/1210025029944382

Enable ACH for moonpay

---

CHANGELOG.md
src/actions/ScanActions.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1209551697973955

Update scan sweep private key modal button copy

---

CHANGELOG.md
src/components/modals/SwapVerifyTermsModal.tsx

none
---
- https://app.asana.com/0/0/1209470814623003

Add KYC links for Changehero, Exolix, and Sideshift

---

src/actions/LocalSettingsActions.ts
src/components/notification/NotificationView.tsx
src/components/scenes/NotificationCenterScene.tsx

none
---
- https://app.asana.com/0/0/1210123418313957

Hide certain notifications while in duress mode

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

https://github.com/EdgeApp/edge-currency-accountbased/pull/926
---
- https://app.asana.com/0/0/1210138498285788

Fantom - Disable transaction list

---

CHANGELOG.md
android/app/build.gradle
android/gradle.properties
scripts/deploy.ts

No android x86

---

CHANGELOG.md
src/actions/LogActions.tsx

none
---
- https://app.asana.com/0/0/1210046020671083

Add os version to the "OS" line of logs

---

CHANGELOG.md
src/__tests__/modals/__snapshots__/CountryListModal.test.tsx.snap
src/constants/CountryConstants.ts

none
---
- https://app.asana.com/0/0/1209245957738328

Add DC to `STATE_PROVINCE_CODES`

---

CHANGELOG.md
src/components/scenes/SendScene2.tsx
src/util/memoUtils.ts

none
---
- https://app.asana.com/0/0/1210103743026175

Add multiple memo option support to send scene

---

src/actions/LoginActions.tsx

Include pineapple juice log

---

ios/Podfile.lock
ios/edge.xcodeproj/project.pbxproj
ios/edge/AppDelegate.mm
ios/edge/Info.plist
package.json
src/actions/FirstOpenActions.tsx
src/types/brigad-react-native-adservices.d.ts
src/types/react-native-apple-ads-attribution.d.ts
src/util/tracking.ts
yarn.lock

https://developer.apple.com/documentation/AdServices/AAAttribution/attributionToken()?changes=l_6_6_8_7_8_2
none
---
- https://app.asana.com/0/0/1210036875460976

Add Apple Ads Attribution

---

CHANGELOG.md
src/components/scenes/DuressModeSettingScene.tsx

none
---
- https://app.asana.com/0/0/1210231939720694

Fix re-enable duress regressions

---

CHANGELOG.md
src/components/themed/SideMenu.tsx

none
---
- https://app.asana.com/0/0/1209897578891092

Use the correct usename in the "Forget Account" modal

---

src/actions/CategoriesActions.ts
src/plugins/stake-plugins/thorchainSavers/tcSaversPlugin.tsx
src/plugins/stake-plugins/thorchainSavers/tcyPlugin.ts

none
---
- https://app.asana.com/0/0/1210205925042644

Fix claim bugs

---

CHANGELOG.md
src/components/scenes/CreateWalletImportOptionsScene.tsx

none
---
- https://app.asana.com/0/0/1210267471684192

Fix Required text on optional import options

---

CHANGELOG.md
src/components/scenes/Staking/StakeOverviewScene.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1209233498796808

Add warning card to `StakeOverviewScene`

---

src/__tests__/components/__snapshots__/TransactionListRow.test.tsx.snap
src/components/themed/TransactionListRow.tsx

none
---
- https://app.asana.com/0/0/1210269046179424

TX List: Always show time text

---

CHANGELOG.md
src/components/services/Services.tsx

none
---
- https://app.asana.com/0/0/1210189113733299

Don't show FIO modal while in duress mode

---

ios/Podfile.lock
package.json
src/constants/WalletAndCurrencyConstants.ts
yarn.lock

https://github.com/EdgeApp/edge-currency-accountbased/pull/937
https://github.com/EdgeApp/edge-currency-accountbased/pull/937
---
- https://app.asana.com/0/0/1210321169174436

Add multi-output spends for Zano

---

CHANGELOG.md
src/components/modals/ScanModal.tsx

none
---
- https://app.asana.com/0/0/1208143080006374

Add scam warning to camera access request modal

---

CHANGELOG.md
src/actions/CategoriesActions.ts
src/components/services/ContactsLoader.ts
src/util/corePlugins.ts

https://github.com/EdgeApp/edge-exchange-plugins/pull/383
---
- https://app.asana.com/0/0/1209518986413128

Enable Fantom to Sonic bridge

---

CHANGELOG.md
src/components/scenes/EditTokenScene.tsx

none
---
- https://app.asana.com/0/0/1210476899040379

Support custom token template fields autocompletion

---

CHANGELOG.md
src/__tests__/actions/RequestReviewActions.test.ts
src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/actions/DeepLinkingActions.tsx
src/actions/LocalSettingsActions.ts
src/actions/PluginActions.tsx
src/actions/RequestReviewActions.tsx
src/components/Main.tsx
src/components/scenes/DevTestScene.tsx
src/components/scenes/GuiPluginListScene.tsx
src/components/scenes/ReviewTriggerTestScene.tsx
src/components/scenes/UpgradeUsernameScreen.tsx
src/components/services/AccountCallbackManager.tsx
src/components/services/Services.tsx
src/plugins/gui/fiatPlugin.tsx
src/types/routerTypes.tsx
src/types/types.ts

none
---
- https://app.asana.com/0/0/1210131153156905

Add review triggers for user actions

---

src/components/modals/AddressModal.tsx

none
---
- https://app.asana.com/0/0/1210630213472460

Fix address modal key race bug

---

src/plugins/gui/amountQuotePlugin.ts

This file change was missing from PR #5634
none

Add coreWallet to quote params

---

CHANGELOG.md
src/components/notification/NotificationView.tsx
src/components/services/NotificationService.ts

none
---
- https://app.asana.com/0/0/1210616634217827

Modify `NotificationCard` visibility rules

---

scripts/deploy.ts

none
---
- https://app.asana.com/0/0/1210794563709564

Only update the test repo for maestro builds

---

CHANGELOG.md
src/constants/WalletAndCurrencyConstants.ts

none
---
- https://app.asana.com/0/0/1210754769992348

Add PIVX to CURRENCY_SETTINGS_KEYS

---

CHANGELOG.md
src/components/themed/MenuTabs.tsx

none
---
- https://app.asana.com/0/0/1210803010952345

Reinstate "Sell" in `MenuTabs` for UK

---

maestro/03-login/C184036-ip2fa-01.yaml
maestro/03-login/C190284-2fa-01.yaml
maestro/11-markets/C202732-markets.yaml
maestro/12-side-menu/C202842-side-menu-no-crash.yaml
maestro/12-side-menu/C202842a-side-menu-no-crash.yaml

- Dismiss survey modal
- Add ip2fa test to ios
none
---
- https://app.asana.com/0/0/1210803607950484

Fix some tests

---

CHANGELOG.md
src/components/modals/WalletListMenuModal.tsx

none
---
- https://app.asana.com/0/0/1210733162536432

Add loading state and prevent multiple actions in WalletListMenuModal

---

CHANGELOG.md
package.json
src/__tests__/fiatProviders/processRevolutConfig.test.ts
src/envConfig.ts
src/plugins/gui/amountQuotePlugin.ts
src/plugins/gui/providers/revolutProvider.ts
src/plugins/gui/util/fetchRevolut.ts

none
---
- https://app.asana.com/0/0/1209616327127637

Add Revolut fiat provider

---

src/__tests__/reducers/__snapshots__/RootReducer.test.ts.snap
src/components/scenes/WalletListScene.tsx
src/reducers/CoreReducer.ts

none
---
- https://app.asana.com/0/0/1210565152963531

Fix auto-logout crash on WalletListScene

---

CHANGELOG.md
src/components/hoc/styled.tsx
src/components/navigation/AlertDropdown.tsx
src/components/services/AirshipInstance.tsx
src/locales/en_US.ts
src/locales/strings/enUS.json

none
---
- https://app.asana.com/0/0/1210923028554124

Add Report Error action to error dropdowns

---

CHANGELOG.md
src/components/notification/NotificationCard.tsx

none
---
- https://app.asana.com/0/0/1210825250074101

Increase `NotificationCard` X tappable area

---

src/util/parseMarkdown.tsx

none
---
- https://app.asana.com/0/0/1210987828407242

Fix Marked import

---

src/__tests__/components/__snapshots__/BalanceCard.test.tsx.snap
src/__tests__/components/__snapshots__/Buttons.test.tsx.snap
src/__tests__/modals/__snapshots__/AddressModal.test.tsx.snap
src/__tests__/modals/__snapshots__/AutoLogoutModal.test.tsx.snap
src/__tests__/modals/__snapshots__/LogsModal.test.tsx.snap
src/__tests__/modals/__snapshots__/PasswordReminderModal.test.tsx.snap
src/__tests__/modals/__snapshots__/TextInputModal.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletAccountSetupScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletEditNameScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletImportScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/CreateWalletSelectCryptoScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/EdgeLoginScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/FioAddressDetailsScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/FioAddressListScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/FioAddressRegisterScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/FioAddressRegisterSelectWalletScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/FioAddressRegisteredScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/FioAddressSettingsScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/RequestScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SettingsScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/SwapCreateScene.test.tsx.snap
src/__tests__/scenes/__snapshots__/TransactionDetailsScene.test.tsx.snap
src/components/buttons/ButtonsView.tsx
src/components/buttons/EdgeButton.tsx
src/components/scenes/GettingStartedScene.tsx

none
---
- https://app.asana.com/0/0/1210978903213397

Fix button styling

---

src/components/themed/WalletListSwipeable.tsx

none
---
- https://app.asana.com/0/0/1211009938731546

Fix crash when creating wallet from search

---

src/plugins/gui/providers/banxaProvider.ts

none
---
- https://app.asana.com/0/0/1211028123520508

Enable Banxa Faster Payments

---

CHANGELOG.md
src/components/notification/NotificationCenterCard.tsx
src/components/services/NotificationService.ts
src/util/promoCardUtils.ts

none
---
- https://app.asana.com/0/0/1210803433019491

Removed expired notifs with promos from `NotificationCenter`

---

CHANGELOG.md
src/components/cards/AdvancedDetailsCard.tsx

none
---
- https://app.asana.com/0/0/1211165109172499

Fix crash potential in AdvancedDetailsCard.tsx

---

CHANGELOG.md
src/__tests__/__snapshots__/GuiPlugins.test.ts.snap
src/constants/plugins/buyPluginList.json

none
---
- https://app.asana.com/0/0/1211001719303453

Remove revolut from US buy

---

CHANGELOG.md
src/components/scenes/GettingStartedScene.tsx

Make progressing past the last slide behave the same as the skip button
none
---
- https://app.asana.com/0/0/1210547184817058

Make the end of the USP flow consistent

---

eslint.config.mjs
src/components/Main.tsx
src/components/interactions/SwipeOffsetDetector.tsx

none
---
- https://app.asana.com/0/0/1211212704711329

USP bounce

---

eslint.config.mjs
src/components/themed/Carousel.tsx

none
---
- https://app.asana.com/0/0/1211309764542432

Fix qr bounce

---

eslint.config.mjs
src/selectors/WalletSelectors.ts

none
---
- https://app.asana.com/0/0/1211376857401409

Fix NaN in exchange-rate selector

---

eslint.config.mjs
src/actions/ExchangeRateActions.ts

none
---
- https://app.asana.com/0/0/1211456106681061

Fetch all rates as USD
